inspirehep/inspire-next

inspire/modules/workflows/actions/core_approval.py, inspire/modules/workflows/tasks/submission.py, inspire/modules/workflows/templates/workflows/actions/core_approval_mini.html, inspire/modules/workflows/templates/workflows/actions/core_approval_side.html
* Improves the default layout of the rejection modal for the
core_approval action. Also pre-fills rejection text in the mini
action.
* Strips the content to the reply_ticket body when taken from the
rejection text.
=> workflows: core_approval rejection fix

Gruntfile.js, package.json
* Removes the copy task from the Gruntfile, since it's no longer
used, and makes `jshint` the default task.  (fixes #201)
Documentation was already fixed in #210, I think.
=> grunt: remove unused code

setup.py
* Downgrades mixer to 4.9.5 which doesn't cause problems with
knwKB table.
Signed-off-by: Mateusz Susik <mateusz.susik@cern.ch>
=> setup: mixer downgrade

.travis.yml, inspire/modules/workflows/actions/core_approval.py
* Updates the core_approval render functions to gracefully fail
should the BibWorkflowObject not be a Deposition.
=> workflows: core_approval fix

inspire/base/classifierext/taxonomies/HEPontCore.rdf
* Adds a trimmed ontology (HEPontCore.rdf) which focuses just on the
core keywords.
Signed-off-by: fschwenn <florian.schwennsen@desy.de>
=> classifierext: add HEPCore ontology

inspire/modules/workflows/tasks/matching.py, inspire/testsuite/test_holdingpen.py, inspire/testsuite/test_matching.py
* Refactors the matching tasks inside workflows to match DOI and
arXiv on remote systems.
* Adds tests.
=> workflows: arXiv/doi match refactoring

inspire/dojson/conferences/schemas/conferences-0.0.1.json, inspire/dojson/current_marcxml_usage/closed-jobs.txt, inspire/dojson/current_marcxml_usage/jobs.txt, inspire/dojson/jobs/schemas/jobs-0.0.1.json
* Introduces new jobs-0.0.1.json schema.
* Resorts inspire/dojson/conferences/schemas/conferences-0.0.1.json
schema.
* Provide closed-jobs.txt and jobs.txt statistics.
=> dojson: new jobs-0.0.1.json schema

inspire/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
* Fixes render_record_authors() macro to correctly handle records
with missing authors.
=> base: render_record_authors macro fix

inspire/modules/workflows/templates/workflows/styles/harvesting_record.html, inspire/modules/workflows/workflows/process_record_arxiv.py
* Temporarily removes some workflows from process_record_arxiv,
in order to be able to use the workflow.
* Adds an if clause to check for authors in
harvesting_record.html.
Signed-off-by: Ilias Koutsakis <ilias.koutsakis@cern.ch>
=> workflows: workflow fixes

inspire/modules/converter/tasks.py, inspire/modules/workflows/workflows/oaiharvest_production_sync.py
* Adds an encoding task for use in the INSPIRE production
synchronization workflow as the data coming from INSPIRE
is given as ISO-8859-1.
=> converter: add encoding task

inspire/modules/authors/testsuite/test_utils.py, inspire/modules/authors/utils.py
This PR adds a reimplementation of the BAI generation function. 
Note: it does not handle the numbered suffix to be added at the end of the BAI. I am not sure how to do that properly in fact, as this operation needs to have the exact number of profiles with the same BAI currently the db (i.e., you cannot rely on ES since it can be out of sync). 
CC: @kaplun @jacenkow
=> authors: BAI generation function

inspire/base/templates/search/search.html
* Loads MathJax from cdn and renders search results. (closes #283)
=> search: mathjax rendering

INSTALL.rst, inspire/dojson/experiments/fields/bd1xx.py, inspire/dojson/experiments/schemas/experiments-0.0.1.json, inspire/dojson/hep/fields/bd01x09x.py, inspire/dojson/hep/fields/bd25x28x.py, inspire/modules/citations/models.py, inspire/modules/citations/testsuite/test_citations.py, inspire/modules/migrator/manage.py, inspire/modules/records/__init__.py, inspire/modules/records/receivers.py, install.sh
* Introduces new demo records by using the new script:
inspirehep/inspire-scripts/utility/generate_demo_records.py.
* Contains the 10 most cited hep papers, 10 core books, theses,
proceedings, notes, corresponding cited papers, 10 citing papers
for each paper, 10 collaboration papers.
* Contains all the HepNames record referred across the papers.
* Expands the MARCXML of the publications, by adding 2 new subfields
in the 100 and 700 tags:
$x: containing the record ID of the author HepName
$y: containing 1 if the given ID is claimed/checked, 0 otherwise
=> demosite: brand new demo records

inspire/base/templates/format/record/Inspire_Default_HTML_detailed.tpl, inspire/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl, inspire/base/templates/search/search.html
* Loads MathJax from CDN in detailed HEP records. (closes #489)
=> format: detailed HEP record MathJax rendering

inspire/modules/formatter/output_formats/hd.yml
* Resolves an issue where the default template was incorrectly rendered, instead of the authors template. (adresses #507)
=> formatter: render the appropriate authors detailed template

inspire/modules/authors/receivers.py, inspire/modules/authors/testsuite/test_utils.py, inspire/modules/authors/utils.py
* Ports BibIndexAuthorTokenizer from old invenio.
* Enhances json record before indexing it to elasticsearch
with all the possible variations of the authors name.
(closes #529)
=> authors: authors names tokenizer

inspire/base/searchext/mappings/hep.json, inspire/dojson/hep/schemas/hep-0.0.1.json
* Adds configuration for author name variations field.
* This needs to be merged together with #529 and
inspirehep/invenio-search#2
=> elasticsearch: elastic configuration additions

inspire/base/searchext/mappings/hep.json, inspire/dojson/hep/schemas/hep-0.0.1.json, inspire/modules/authors/receivers.py
* Adds assign_signature_block in receivers.py resposible for
assigning phonetic names of authors (signatures) in HEP
collection. The blocks are assigned on before_record_index
signal.
* Renames HEP schema ml_block to signature_block.
* Cleans up assign_uuid in receivers.py. Removes
before_record_update signal.
* Extends HEP schema with regex pattern for uuid.
=> authors: phonetic name notation

inspire/ext/jinja_filters/record.py, inspire/utils/bibtex_booktitle.py
* NOTE: Invenio search API recids property should not be used with
ElasticSearch 2.0 as size cannot be bigger than 10000.
=> global: remove search API recids usage

inspirehep/modules/migrator/tasks.py, setup.py
* Introduces special continuos_migration() celery task that uses
Redis to synchronize with production.
* Amends migrate_chunk task with the acks_late=True flag in orde to
resume failed tasks automatically.
* Adds librabbitmq dependency.
=> prodsync: support for Redis continuos migration

inspirehep/base/static/js/notification.js, inspirehep/base/static/less/base/core.less
* Adds cookie to avoid seeing toast message more than once.
Expiration is set to 10 days. (closes #584)
* Changes toast position to not interfere with Login button.
=> global: toast message changes

inspirehep/base/static/js/dropdown-menu/dropdown-menu.js, inspirehep/base/static/less/base/header.less, inspirehep/base/templates/header.html
Updates the selectors used in the Resources dropdown menu so that the code does not affect other dropdown menus across the entire site. E.g. this was causing dropdowns in Holding Pen to malfunction.
PS: Be careful when using very generic selectors of bootstrap components that may be used elsewhere. Better always use id's to select with.
@ioannistsanaktsidis @nikpap
=> static: resources dropdown-menu fixes

inspirehep/base/searchext/mappings/hep.json
* Adds doi mapping as non-analyzed.
=> elasticsearch: doi mapping addition

inspirehep/dojson/hep/schemas/hep-0.0.1.json
* Removes two unintended commas from the json schema to make it valid.
=> dojson: valid schema

Procfile, base.requirements.txt
* Upgrades invenio-search dependency to include
inspirehep/invenio-search#9.
* Amends honcho's Procfile to enable Celery DEBUG by default, so that
it is possible to see on the log how queries are interpreted.
=> search: enable debug

inspirehep/base/templates/search/form/controls.html
* Tab in the main search bar sets focus to the search button. (closes #648)
=> search: tab index for main search bar

Procfile
* Reverts Celery DEBUG flag in Honcho's Procfile, since this is not
really necessary to see requests being performed online.
=> honcho: revert Celery DEBUG

inspirehep/config.py
* Fixes an issue when sorting on `relevance_score` would fail when
not defined in mappings.
=> config: override Holding Pen ES mapping

inspirehep/dojson/processors.py, inspirehep/dojson/utils.py, inspirehep/modules/migrator/tasks.py
* Introduces new step in dojson.processors, to remove any empty
value, i.e. anything corresponding to "", None, an empty list or
an empty dictionary. 0s and False are not considered empty values.
=> dojson: strip empty values

inspirehep/modules/migrator/manage.py, inspirehep/modules/migrator/tasks.py
* No longer schedules the parent migration task in Celery. Instead,
suspend Celery, so that the chunks are quickly loaded into
RabbitMQ and then processed as fast as possible.
=> migrator: migrate out of Celery

inspirehep/config.py
* Removes unneeded keywords from elasticsearch mapping.
=> config: keywords fix

inspirehep/manage.py, tests/test_reindexing.py
* Improves reindexing algorithm by really ensuring reindexing happens
on a given node and is checked on that very node.
* Deletes and swaps alias only after having ensured the number of
documents in the new index corresponds to the previous one.
* Introduces testsuite for reindexing.
=> inspirehep: reindexing testing

inspirehep/base/searchext/mappings/hep.json, inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl, inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/dojson/hep/fields/bd6xx.py, inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/dojson/hep/fields/bd76x78x.py, inspirehep/dojson/hep/model.py, inspirehep/dojson/hep/schemas/hep-0.0.1.json, inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/dojson/jobs/fields/bd1xx.py, inspirehep/utils/bibtex.py, inspirehep/utils/cv_latex.py, inspirehep/utils/cv_latex_html_text.py, inspirehep/utils/latex.py, tests/fixtures/test_hep_book.xml, tests/fixtures/test_hep_record.xml, tests/test_hep.py
* 100/700 $x with Record ID of linked HepName,
$y with True/False if the signature is claimed
$z with Record ID of institution
* 371/110 $z with Record ID of institution
* 502 $z with Record ID of institution
* 999C5 $0 with on the fly discovered Record IDs (not for books)
* 773 $0 with Record ID of corresponding Book or Proceeding
$1 with Record ID of corresponding Journal
$2 with Record ID of corresponding Conference
* 693/710 $0 with Record ID of corresponding experiment
* Closes #485.
=> dojson: support enhanced marcxml links

inspirehep/modules/workflows/workflows/process_record_arxiv.py, inspirehep/utils/arxiv.py
* Fixes an issue where old arXiv IDs generated bad filenames for
downloaded tarball and PDF.
* Adds top_words statistics to arXiv predictions.
=> workflows: safe arXiv file handling

inspirehep/base/searchext/mappings/hep.json, inspirehep/dojson/hep/fields/bd76x78x.py, inspirehep/dojson/hep/schemas/hep-0.0.1.json, tests/test_hep.py
* Takes into consideration all possible record ids that can be present
in the publication information.
* Amends json schema accordingly.
=> dojson: publication info record ids improvement

inspirehep/base/searchext/mappings/hep.json, inspirehep/modules/authors/utils.py, tests/test_bai.py
* Name tokenizer now includes the last name in the name variations.
* Adds a new analyzer that generates one token for every input.
* Adds a new filter that replaces multiple whitespaces with a single one.
* Adds the trim filter that trims the input for authors.
=> WIP authors: tokenizer additions

base.requirements.txt
* Changes requirements to use INSPIRE invenio-formatter fork.
=> global: invenio-formatter fork

inspirehep/utils/references.py
* Modifies query sent to ElasticSearch in order to remove limitation of
10 records. (closes #744)
=> references: remove size limit retrieving references

inspirehep/dojson/hep/fields/bd90x99x.py, tests/test_citation_counts.py
* Fixes case where a missing number in a citation would not add recids.
=> dojson: fix reference conversion

inspirehep/modules/authors/receivers.py, tests/test_authors.py
* Fixes an issue where exceptions could be raised upon bad
authornames. (closes #746)
=> authors: assign_signature_block fix

inspirehep/modules/workflows/tasks/upload.py, inspirehep/modules/workflows/workflows/oaiharvest_production_sync.py, inspirehep/modules/workflows/workflows/process_record_arxiv.py, tests/workflows/harvesting_fixture.py, tests/workflows/payload_fixture.py, tests/workflows/payload_model_fixture.py
* Ports the "legacy" convert_record_to_json workflow task from
invenio-oaiharvester as it will no longer be part of that module.
=> workflows: port legacy convert_record_to_json

inspirehep/base/templates/500.html, inspirehep/base/templates/header.html, inspirehep/base/templates/search/form/controls.html, inspirehep/config.py, inspirehep/ext/error_pages.py
* Adds a preliminary 500 error page.
* Fixes issues with collection name in templates when collection
object is not available.
We should improve the text/look, but this acts as a preliminary page at least instead of good ol white Internal Server Error page.
=> ext: error pages handler

inspirehep/base/views.py
* Shadows / view to directly render the Literature search page as
landing page.
=> base: landing page route change

base.requirements.txt
* Bumps invenio-ext version in order to force latest fix
on Sentry and Celery.
=> requirements: bump invenio-ext

setup.py
Wrong version listed, so `dbexec` fails. Fixed.
=> setup: remove duplicate invenio-formatter

inspirehep/modules/migrator/manage.py, inspirehep/modules/migrator/tasks.py, install.sh
* Don't schedule in Celery the global add_citation_counts().
* Workarounds references having more than one recid.
=> migrator: simpler add_citation_counts()

inspirehep/base/templates/search/form/controls.html
* Sets the collection name properly in landing pages.
=> templates: collection name fix on landing pages

inspirehep/ext/jinja_filters/record.py
* Modifies the query to report the correct total number of records
on each collection landing page.
=> filters: number of records per collection fix

inspirehep/modules/authors/receivers.py
* Skips assignation of uuid if a given signature has already one.
=> authors: skip uuid if already present

inspirehep/base/templates/header.html, inspirehep/base/templates/search/facets/conferences.html, inspirehep/base/templates/search/facets/experiments.html, inspirehep/base/templates/search/facets/hep.html, inspirehep/base/templates/search/facets/institutions.html, inspirehep/base/templates/search/facets/jobs.html, inspirehep/base/templates/search/facets/journals.html, inspirehep/base/templates/search/form/controls.html
* Optimizes facet templates in order to call _search only once.
* Small fix in search results search bar colour.
=> templates: facet template refactoring

base.requirements.txt
* Forces version 0.3.1.dev20160128 to be installed.
=> global: invenio-query-parser version bump

base.requirements.txt, inspirehep/modules/authors/tasks.py, setup.py, tests/test_utils.py
* Switches to INSPIRE invenio-utils fork.
* Fix on data model conversion.
* Test added for invenio-utils expected functionality.
=> authors: several fixes and invenio-utils fork usage

inspirehep/base/searchext/mappings/data.json, inspirehep/manage.py
Avoid exception in ElasticSearch when accessing Holding Pen due to missing mappings.
=> searchext: add missing data mapping

inspirehep/base/views.py
* /jobs now points to the search results of the Jobs collection.
=> base: change Jobs landing page

inspirehep/modules/deposit/workflows/literature.py
* If a title does not come from arXiv or Crossref, add the submitter as
a source.
=> deposit: add submitter as source for titles

inspirehep/dojson/hepnames/fields/bd1xx.py
* Properly deals with the case when a MARCXML field has two $$z
subfields, one for the recid and one for the status.
=> dojson: hepnames name fix

inspirehep/modules/migrator/tasks.py
* Disconnects signals from catch_citations_update receiver during migration.
=> migrator: disconnect signal from citations receiver

base.requirements.txt, inspirehep/base/templates/search/results.html, inspirehep/ext/jinja_filters/record.py
* Uses information about the query stored in session instead of performing
a query every time a facet is selected.
=> filters: number of records optimization

inspirehep/dojson/common/base.py, inspirehep/dojson/hep/schemas/hep-0.0.1.json, tests/fixtures/test_hep_record.xml, tests/test_hep.py
Adds missing handling + tests of 970__d and 981__a in dojson.
Significantly improves testing speed of `test_hep` from 23s to 2.3s by using pytest and fixtures. @kaplun @jacquerie @jmartinm
=> dojson: tests upgrade and deleted fields

inspirehep/base/templates/citations.html, inspirehep/base/templates/format/record/Cache_HTML_macros.tpl, inspirehep/base/templates/format/record/Inspire_Default_HTML_brief.tpl, inspirehep/base/templates/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/base/templates/references.html, inspirehep/base/views.py, inspirehep/config.py, inspirehep/ext/cache_manager/__init__.py, inspirehep/ext/cache_manager/cache.py, inspirehep/ext/cache_manager/manager.py, inspirehep/ext/cache_manager/proxy.py, inspirehep/ext/cache_manager/receivers.py, inspirehep/ext/cache_manager/tasks.py, inspirehep/ext/cache_manager/utils.py, inspirehep/ext/jinja_filters/record.py, inspirehep/manage.py, inspirehep/modules/citations/receivers.py, inspirehep/modules/citations/signals.py, inspirehep/modules/citations/tasks.py, inspirehep/utils/references.py, tests/test_cache_manager.py
* Adds caching and memoization to the following views:
single-reference, single-citation, references, citations
and brief search.
* Introduces InspireCache class which extends Flask Cache
(adding conditional caching and memoization:
e.g. cache/memoize when not in debug mode).
* Adds CacheManager extension which decides
which cached views should be invalidated on record insert/update.
* Adds 'invalidate_cache' command to inspirehep in order to
allow manual invalidation of certain views (references, citations etc.).
=> caching: add caching and cache management (invalidation)

INSTALL.rst, Procfile, inspirehep/base/templates/search/facets/hep.html, inspirehep/config.py, inspirehep/modules/records/receivers.py, inspirehep/utils/formulas.py, install.sh, mathoid.config.yaml, pytest.ini
* Fixes deployment of Mathoid to be compatible with Docker, Linux and
Mac OS.
* Provides default Mathoid configuration suitable to be run on
production. (closes #864)
* Fixes positioning of formulas facet and its correct ID, so that
closing it actually works. (closes #862 )
* Skips empty formulas. (closes #863 )
* Documents installation steps for Mathoid.
=> formulas: several fixes

inspirehep/base/templates/references.html, inspirehep/utils/references.py
* Wraps record JSON passed to reference template in invenio_records
Record object to allow for 'smart' access of keys in the template.
=> references: template fix

inspirehep/dojson/hep/fields/bd01x09x.py, inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd20x24x.py, inspirehep/dojson/hep/fields/bd6xx.py, inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/dojson/utils.py, tests/dojson/test_utils.py, tests/test_bibtex.py, tests/test_cvlatex_html_text.py, tests/test_export.py
Introduces two new utils, `remove_duplicates_from_list` and `remove_duplicates_from_list_of_dicts`. They do as it says on the tin, except they also preserve the original ordering, something which is useful to have during testing.
Not having that was causing failures such as https://travis-ci.org/inspirehep/inspire-next/jobs/108116178#L1952. Testing that this bug won't occur again is outside of the scope of this PR; maybe in a future PR?
=> dojson: guarantee order when removing duplicates

base.requirements.txt, inspirehep/base/templates/format/record/Inspire_Default_HTML_brief.tpl, inspirehep/base/templates/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/dojson/hep/receivers.py, inspirehep/ext/jinja_filters/record.py, inspirehep/utils/date.py, tests/test_date_utils.py, tests/test_dojson_receivers.py
* Displays dates in the same format as current production.
* Improves earliest_date recognition.
* Adds test for earliest_date and new utilities.
=> utils: legacy date formatting port

inspirehep/dojson/hep/fields/bd1xx.py
* Fixes porting 100/700 $y into curated_relation flag.
=> dojson: fix curated_relation

inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl, inspirehep/ext/jinja_filters/record.py
* Removes leading internal number in plot captions. (closes #870)
=> templates: strip plot caption

inspirehep/base/static/js/feedback/feedback.js, inspirehep/base/static/js/feedback/templates/email.mustache, inspirehep/base/static/js/feedback/templates/modal.mustache, inspirehep/base/static/less/feedback/button.less, inspirehep/base/static/less/feedback/modal.less, inspirehep/base/views.py, tests/test_views.py
As requested in #465, disallow anonymous feedback. Instead of implementing the solution proposed by @jmartinm I decided for another flow:
If the user is logged in, she can submit her feedback exactly like today. If the user is not logged in, when she tries to submit her feedback, a new field is added to the popup, requesting the email.
=> feedback: disallow anonymous feedback

inspirehep/modules/theme/bundles.py, inspirehep/modules/theme/ext.py
* Fixes hogan npm dependency to `hogan.js` instead of `hogan`.
* Adds JS bundles to be excluded from other bundles to config
variable `THEME_BASE_BUNDLES_EXCLUDE_JS`.
=> theme: hogan dependency fix

inspirehep/base/jsonschemas/hepnames-0.0.1.json, inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/modules/authors/views.py
* Sanity check for status field.
* Makes preferred name a string instead of an array.
=> authors: form fix

inspirehep/config.py, inspirehep/modules/theme/views.py, requirements.txt, tests/conftest.py, tests/test_views.py
Also adds the `app` fixture, which can be injected in the tests that need access to the application context.
Similar fixtures for DB, ES... will be ported from Zenodo (https://github.com/zenodo/zenodo/blob/ca7f630c45ff01ccf0cb84587407e23a060a7879/tests/unit/conftest.py) as soon as they are needed.
=> theme: add postfeedback handler

.gitignore
When I run
```shell
$ python setup.py test
```
on my machine I get an `.eggs` folder which then I have to avoid committing/delete. Since I got tired of doing that, I decided to update `.gitignore`: it pulls all the latest changes from the one recommended by GitHub (https://github.com/github/gitignore/blob/master/Python.gitignore), and retains all our modifications.
I only removed `bin/`, since we are not producing binaries anymore (we use the instance's CLI), `bower.json`, since we are not using Bower anymore, `**/static/vendors/**` and `**/static/gen/**`, since assets generation now happens in the instance folder.
Have a look if you want something added/removed, in case it conflicts with your development environment.
=> RFC git: gitignore update

inspirehep/config.py, inspirehep/modules/migrator/tasks.py, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_brief.tpl, inspirehep/modules/theme/templates/inspirehep_theme/header.html, requirements.txt
* Different record types now use different pid_types.
* NOTE: Each document type now has a specific endpoint for detailed
views. E.g. invenio_records_ui.literature.
=> records: use different pid_type for different record types

inspirehep/modules/search/static/js/search/app.js, inspirehep/modules/search/static/templates/search/literature/briefresults.html, inspirehep/modules/theme/bundles.py, inspirehep/modules/theme/static/js/inspire/filters/doi.js, inspirehep/modules/theme/static/js/inspire/filters/module.js, inspirehep/modules/theme/static/js/inspire/module.js, inspirehep/modules/theme/static/js/settings.js
* Creates inspire AngularJS module that can be reused across the site.
* Includes inspire AngularJS filters in search results page.
* Adds angular and angular-sanitize as dependencies.
=> theme: inspire AngularJS module and filters

inspirehep/modules/search/bundles.py, inspirehep/modules/search/static/js/search/app.js, inspirehep/modules/theme/bundles.py, inspirehep/modules/theme/static/js/settings.js, inspirehep/modules/theme/templates/inspirehep_theme/javascript.html, setup.py
* Allows usage of ASSETS_DEBUG by including requirejs in the page when
the setting is enabled.
* Bundle cleanup.
* NOTE: when switching to ASSETS_DEBUG=True the contents of the folder
static/.webassets-cache/ should be removed to have full effect.
=> theme: ASSETS_DEBUG fix

inspirehep/modules/theme/bundles.py, inspirehep/modules/theme/static/js/detailed_record_init.js, inspirehep/modules/theme/static/js/plots.js, inspirehep/modules/theme/static/scss/format/detailed-record.scss, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl, setup.py
* Desktop view
* Tablet view
* Mobile view
=> Invenio3 plots

inspirehep/dojson/bibfield/fields/bibfield.py, inspirehep/dojson/common/base.py, inspirehep/dojson/experiments/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/dojson/hep/fields/bd6xx.py, inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/dojson/hep/fields/bd76x78x.py, inspirehep/dojson/hep/fields/bd90x99x.py, inspirehep/dojson/hep/model.py, inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/dojson/jobs/fields/bd1xx.py, inspirehep/dojson/utils.py, inspirehep/modules/records/jsonschemas/records/acquisition_source.json, inspirehep/modules/records/jsonschemas/records/authors.json, inspirehep/modules/records/jsonschemas/records/conferences.json, inspirehep/modules/records/jsonschemas/records/experiments.json, inspirehep/modules/records/jsonschemas/records/hep.json, inspirehep/modules/records/jsonschemas/records/institutions.json, inspirehep/modules/records/jsonschemas/records/jobs.json, inspirehep/modules/records/jsonschemas/records/journals.json, inspirehep/modules/records/jsonschemas/records/json_reference.json, inspirehep/modules/records/receivers.py, inspirehep/modules/theme/jinja2filters.py, tests/test_hep.py, tests/unit/dojson/test_dojson_utils.py, tests/unit/records/test_records_receivers.py, tests/unit/theme/test_theme_jinja2filters.py
LE: Actually the base of any integration test will be reindexing everything and asserting that all the marc records were indexed as json correctly. So any integration testing framework will always use this code.
* Closes #958
=> Porting schemas to use JSONref

Procfile, scripts/recreate_records
* `scripts/recreate_records` did not cleanup any workers upon cancellation -> fix that using trap
* `scripts/recreate_records` started new workers even if others were started via `honcho start` -> fix using a common pidfile
* the first argument is the celery loglevel. Makes things easy to debug when breaking `recreate_records`
TODO
* ~~test `--autoreload` (having the server started with `honcho start` would not autoreload on code changes before, but the webapp did)~~ Does not work
* ~~make everything work with ES started as a service (`service elasticsearch start`)~~
LE:
`scripts/recreate_records` doesn't care about how ES is started so it might be left like this for now. On the other hand I am not sure on how `honcho start` works with ES installed as a service.
LE2:
Managing ES will …
=> Make scripts/recreate_records work with honcho start

inspirehep/config.py, requirements.txt
* Allows invenio-query-parser to accept case insesitive keywords.
* Should be merged with inspirehep/invenio-query-parser#16.
=> search: case insensitive keywords

inspirehep/config.py
* Changes config so that flask_security is not needed before being
loaded.
=> global: security loading workaround

inspirehep/modules/records/json_ref_loader.py, inspirehep/utils/record_getter.py, tests/unit/records/test_records_json_ref_loader.py, tests/unit/utils/test_utils_record_getter.py
* Adds JSON reference loaders that first try to resolve recird URIS
against the database or Elasticsearch before making HTTP requests.
usage example
```python
>>> from inspirehep.modules.records import json_ref_loader
>>> json_ref_loader.replace_refs({'$ref': 'http://localhost:5000/api/literature/1385669'})
{'samething': 'from db'}
>>> json_ref_loader.replace_refs({'$ref': 'http://localhost:5000/api/literature/1385669'}, 'es')
{'samething': 'from elastic'}
>>> json_ref_loader.replace_refs({'$ref': 'http://localhost:5000/api/literature/1385669'}, 'http')
{'samething': 'using GET'}
```
=> JSON Reference Resolver that bypasses HTTP requests for known resources.

inspirehep/config.py
* Configures term filters for non-HEP collections.
=> config: facet filtering configuration

inspirehep/dojson/utils.py, inspirehep/modules/records/json_ref_loader.py, tests/unit/dojson/test_dojson_utils.py, tests/unit/records/test_records_json_ref_loader.py
* Fixes double http:// prepending when SERVERN_NAME is
http://inspirehep.net
cc @kaplun Almost forgot to fix this :)
=> Fix for prod https:// SERVER_NAME in dojson and ref_loader

.travis.yml, docker-compose.deps.yml, docker-compose.test.yml, docker-compose.yml, dockerfiles/Dockerfile, dockerfiles/Dockerfile.elastic, dockerfiles/docker_entrypoint.sh, inspirehep/config.py, scripts/clear_pycache, scripts/recreate_records, services.yml
Get the latest Docker setup.
* If you are using Mac, please build a simple box with `docker-engine` above `1.10` and `docker-compose` above `1.6.0`.
Make sure you can run docker without sudo.
* `id $USER`
If you are not in the `docker` group, run the following command and then restart `docker`. If this doesn't work, just restart your machine :)
*  `sudo usermod -a -G docker $USER`
Get docker-compose:
```shell
sudo pip install docker-compose
```
* Add `DOCKER_DATA` env variable in your `.bashrc` or `.zshrc`. In this directory you will have all the persistent data between Docker runs.
```
export DOCKER_DATA=~/inspirehep_docker_data/
```
By default the virtualenv and everything else will be kept on `/tmp` and they will be available only until the next reboot.
* Install a host persistent venv …
=> Docker compose setup for dev and integration tests

tests/unit/search/test_search_query.py
From Piwik's logs I retrieved the set of the most common queries that users typed from 2012 to 2016. I recast a representative sample of these (I'm still missing a few) as tests.
Whenever the produced ES query is not satisfactory I xfailed the test. If you want to see the failures you just need to run `py.test tests --runxfail`.
In some cases the fix is clear: for example, we definitely need to add the BAI to the ES mapping, as people use them to search. It's less clear what we should do with _malformed_ queries, for example when the users forget to type `find` before `a`, or uses the abbreviation `ea` before a colon, instead of `exactauthor`. I'd argue that we should lean towards the user, and do what they meant, but maybe we already decided not to do this.
I also found two bugs, one …
=> tests: unsupported queries as xfailed tests

inspirehep/modules/search/walkers/elasticsearch.py, tests/unit/search/test_search_query.py
* When `refersto` is followed by `recid` the search will work as intended.
=> search: enables refersto:recid:xxx search

inspirehep/modules/search/templates/search/search.html, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl
* Extends JS dependencies in order to render mathematical notation
using MathJax. ~~NOTE: works only in ASSETS_DEBUG = True.~~
=> theme: add MathJax

inspirehep/config.py, inspirehep/modules/records/mappings/records/hep.json, tests/unit/search/test_search_query.py
* Enables Searching by Type-Code (tc).
* Closes #970 .
* Need to be merged with inspirehep/invenio-query-parser#17 .
=> search: type_code search

inspirehep/kbs/weblinks.kb, inspirehep/modules/theme/ext.py, inspirehep/modules/theme/jinja2filters.py, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl, tests/unit/theme/test_theme_jinja2filters.py
- Articles from SCOAP3: eg 1393760
- check 1280200, 1388555
- Check 1230937
=> format: HEP detailed record external links

.editorconfig
* NOTE: Use an extension for your favourite IDE in order to use
the .editorconfig.
=> global: .editorconfig addition

inspirehep/modules/theme/jinja2filters.py
* Sets literature as default collection when no collection parameters are
found in the URL. (closes #1033)
=> theme: collection color fix

inspirehep/config.py
* Prevents the "Remember Me" cookie from being accessed by client-side scripts.
=> config: REMEMBER_COOKIE_HTTPONLY set

inspirehep/modules/search/walkers/elasticsearch.py, inspirehep/modules/search/walkers/elasticsearch_no_keywords.py, tests/unit/search/test_search_query.py
* Enables searching with wildcards (only used in the end of a word).
* Should be merged with inspirehep/invenio-query-parser#14.
* Should be merged with  inspirehep/invenio-query-parser#18.
* Closes box no.10 of #817.
* Closes #831.
=> search: enables wildcards

inspirehep/config.py, inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/impactgraph_serializer.py, inspirehep/utils/record.py, tests/integration/test_impact_graphs.py, tests/unit/utils/test_utils_record.py
* Adds API to retrieve information regarding references and citations
for a given record. Needed by impact graph visualization. (closes #1044)
* Adds new record utils for record-related utilities.
* Adds get_title util.
* Adds appropriate tests for the added functionality.
=> records: impact graph API addition

inspirehep/modules/authors/tasks.py, inspirehep/modules/workflows/tasks/submission.py
* Sends robotupload requests by setting corresponding priority to 5,
so that literature suggestions and authors additions are treated
promptly.
=> deposit: robotupload with priority

inspirehep/dojson/current_marcxml_usage/README.rst, inspirehep/dojson/current_marcxml_usage/closed-jobs-repeatable.txt, inspirehep/dojson/current_marcxml_usage/conferences-repeatable.txt, inspirehep/dojson/current_marcxml_usage/experiments-repeatable.txt, inspirehep/dojson/current_marcxml_usage/hep-repeatable.txt, inspirehep/dojson/current_marcxml_usage/hepnames-repeatable.txt, inspirehep/dojson/current_marcxml_usage/institutions-repeatable.txt, inspirehep/dojson/current_marcxml_usage/jobs-repeatable.txt, inspirehep/dojson/current_marcxml_usage/journals-repeatable.txt
* Adds statistics files for every collection, to describe the current
usage on legacy for MARC fields and subfields.
=> dojson: repeatable statistics

inspirehep/dojson/hep/fields/bd5xx.py
Fix discovered while working with literature suggest and workflows.
cc @tomaszgy @bittirousku @jmartinm
=> dojson: hep `license` field regex fix

inspirehep/modules/workflows/models.py, inspirehep/modules/workflows/utils.py, setup.py, tests/integration/conftest.py, tests/integration/workflows/test_audit.py
* Adds back the Audit module for tracking actions in Holding Pen.
=> audit: initial Audit trail

inspirehep/utils/record.py, inspirehep/utils/record_getter.py, tests/unit/utils/test_utils_record.py
* Adds a utility function `get_smart_value` to allow for dotted
record key lookup. E.g. `get_smart_value(rec, "titles.title")`.
* Migrated from legacy `invenio_utils.datastructures` package.
=> utils: dotted record key lookup

inspirehep/modules/records/jsonschemas/records/hep.json
* Removes string type of items in collections field.
=> schemas: fix hep collections bug

inspirehep/modules/theme/templates/inspirehep_theme/header.html, inspirehep/modules/theme/templates/inspirehep_theme/search/collection_basic.html, inspirehep/modules/theme/templates/inspirehep_theme/search/form/form.html
* Correctly sets cc parameter in all top search bars.
=> theme: top search bar collection fix

inspirehep/modules/literaturesuggest/static/js/literaturesuggest/literature_submission_form.js, inspirehep/modules/theme/static/js/settings.js
* Conflicts can appear if jquery-ui is loaded after bootstrap.js as jQuery
plugins can be shadowed (such as button or tooltip). This commit ensures
that the correct order is used. (addresses #1119)
=> js: load jquery-ui before bootstrap.js

inspirehep/modules/theme/static/scss/base/footer.scss, inspirehep/modules/theme/templates/inspirehep_theme/footer.html, inspirehep/modules/theme/templates/inspirehep_theme/header.html
The CSS rule for `.error-pages h4` was leaking in the footer. I fixed it by making the footer CSS more specific and specifying the default values.
Also contains a commit to fix two HTML validity issues I found while investigating this tiny bug.
WDYT about tests that check the validity of HTML pages we generate? Spoiler alert: we fail.
=> theme: footer style fix in error pages

inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hep/receivers.py, inspirehep/dojson/utils.py, inspirehep/utils/dedupers.py, setup.py, tests/unit/dojson/test_dojson_hepnames.py
Preparatory work for #1093, which requires a recent DoJSON version, but is hitting a performance regression in the `authors` rule in `inspirehep/dojson/hep/fields/bd1xx.py`.
This PR fixes that, but discovers three new (unrelated) failures caused by updating DoJSON.
=> WIP dojson: update dojson to 1.2.1

inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/modules/deposit/dojson/fields/literature.py
* Fixes data format for collaboration field to match ES mapping.
=> dojson: collaboration fix

inspirehep/modules/authors/receivers.py, tests/unit/authors/test_authors_receivers.py
* Adds uuid to each signature on before_record_insert signal.
* Adds test to check if uuid field is not empty.
=> authors: add uuid generator

inspirehep/config.py, inspirehep/modules/fixtures/__init__.py, inspirehep/modules/fixtures/cli.py, inspirehep/modules/fixtures/ext.py, inspirehep/modules/fixtures/files.py, inspirehep/modules/workflows/ext.py, scripts/recreate_records, setup.py, tests/integration/conftest.py
* Adds new fixtures module used when setting up the INSPIRE instance
to pre-load database tables with content and setting up folders etc.
* NOTE There is a new CLI command you need to run to setup the site properly:
`inspirehep fixtures init`
E.g. we could potentially later hook up the collection loading here also from #1116 
@kaplun @jmartinm
=> fixtures: initial module

inspirehep/modules/authors/forms.py, inspirehep/modules/authors/templates/authors/forms/update_form.html, inspirehep/modules/authors/views.py, inspirehep/modules/deposit/validators/simple_fields.py
* Checks for ORCID duplicates in order to not allow new author information
to be submitted if an ORCID already exists in inspirehep.net.
=> authors: ORCID duplicate validation

inspirehep/config.py, inspirehep/modules/migrator/__init__.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/utils.py, inspirehep/modules/workflows/workflows/arxiv_ingestion.py, inspirehep/utils/arxiv.py, inspirehep/utils/helpers.py, tests/integration/workflows/test_arxiv_workflow.py
Integrates new file handling into arXiv ingestion.
E.g. in the workflow API to access files go to `/api/holdingpen/1/files`. You will see info about `bucket` and `key`.
@eamonnmag To download/use the file, go to `/api/files/{bucket}/{key}`
On top of #1168
=> update files handling

inspirehep/modules/authors/receivers.py, tests/unit/authors/test_authors_receivers.py, tests/unit/conftest.py
* Adds phonetic block to each signature on
before_record_insert and before_record_update signals.
=> authors: add phonetic blocks generator

Procfile, gunicorn.cfg, inspirehep/wsgi.py, setup.py
* Moves away from the standard development server to use
gunicorn in order to address the resource unavailable issue
which often occured during local development.
* NOTE You can edit the gunicorn settings locally in `gunicorn.cfg`
Co-authored-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
CC @Panos512
=> setup: gunicorn for development

inspirehep/modules/theme/templates/inspirehep_theme/format/record/authors/Author_HTML_detailed.html
* Removes biography directive. Once we allow for editing of profile we can
add it back to allow for personalized content.
=> authors: remove biography

gunicorn.cfg
* Sets bind address to correctly run outside of honcho.
* Increases timeout to make sure an ipdb session does not get killed.
=> setup: gunicorn.cfg update

inspirehep/modules/warnings/__init__.py, requirements.txt, setup.py
* Use flask-cli with iPython support.
* Adds warning extension to disable DeprecationWarnings unless `DEBUG_SHOW_DEPRECATION_WARNINGS` is `True`.
=> IPython shell and warnings adjustments

inspirehep/modules/theme/jinja2filters.py, tests/unit/theme/test_theme_jinja2filters.py
* Avoids crash when parent recid does not exist in ES.
* Adds testcase.
=> jinja2filters: pubinfo sanity check

.gitmodules
* NOTE: run `git submodule update --init --recursive` to fetch the contents of the
inspirehep-search-js repo.
Once that is done, working inside the folder inspirehep-search-js/
will be equivalent to working on the standalone repo and you can create
PRs on the inspirehep-search-js repo.
=> submodules: add inspirehep-search-js as submodule

inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/modules/authors/tasks.py, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/fixtures/test_hepnames_record.xml, tests/unit/dojson/test_dojson_hep.py, tests/unit/dojson/test_dojson_hepnames.py
I would like this to be a single item field. Then we can more easily filter/display this field for new Holding Pen, and keep our sanity. 
Thoughts?
=> dojson: fix acquisition_source

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Experiment_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/authors/Author_HTML_detailed.html, tests/integration/conftest.py, tests/unit/dojson/test_dojson_hep.py, tests/unit/dojson/test_dojson_hepnames.py
* First commit is unrelated, but while investigating this issue I wrote a few tests for the corresponding DoJSON rules to see if the bug is there.
* Second commit fixes the bugs currently present in templates after #1170.
* Third commit adds `DEBUG = True` to the integration `app` fixture, so that we can more easily discover the bugs fixed in the previous commit.
Closes #1178
=> theme: amend templates to pass tests

setup.py
`invenio-admin==1.0.0a3` and `Flask-Admin==1.4.1` are incompatible, causing this error: https://travis-ci.org/inspirehep/inspire-next/jobs/137282868#L1094
This PR works around that by requiring `Flask-Admin==1.4.0`, the last known working version.
=> setup: pin Flask-Admin

tests/unit/authors/test_authors_dojson.py
Pretty straightforward tests. Still missing a few, but this was a quick coverage win and will help refactoring after #1170.
A similar PR will come for `inspirehep/modules/literaturesuggest/dojson`.
=> tests: unit tests for authors DoJSON

inspirehep/dojson/hep/fields/bd01x09x.py, inspirehep/dojson/hep/fields/bd90x99x.py, setup.py
* Changes the ISBN parse error to match the isbnid new dependency in
idutils.
=> dojson: idutils version bump

inspirehep/config.py, inspirehep/dojson/hep/fields/bd76x78x.py, inspirehep/dojson/utils/__init__.py, inspirehep/modules/literaturesuggest/dojson/fields/literature.py, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/records/jsonschemas/records/hep.json, inspirehep/modules/records/receivers.py, inspirehep/modules/refextract/tasks.py, inspirehep/modules/theme/jinja2filters.py, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Conference_info_macros.tpl, inspirehep/utils/bibtex.py, inspirehep/utils/cv_latex.py, inspirehep/utils/cv_latex_html_text.py, inspirehep/utils/latex.py, inspirehep/utils/record.py, tests/unit/dojson/fixtures/test_hep_record.xml, tests/unit/dojson/test_dojson_hep.py, tests/unit/literaturesuggest/test_literaturesuggest_dojson.py, tests/unit/search/test_search_query.py, tests/unit/theme/test_theme_jinja2filters.py, tests/unit/utils/test_utils_bibtex.py, tests/unit/utils/test_utils_cv_latex.py, tests/unit/utils/test_utils_cv_latex_html_text.py, tests/unit/utils/test_utils_latex.py
* Amends JSONSchema, dojson, serializer, search, Jinja templates in
order to correctly capture the concepts of page_start, page_end,
and artid.
=> jsonschema: page_artid -> page_start/end + artid

inspirehep/dojson/institutions/fields/bd1xx.py, inspirehep/modules/records/jsonschemas/records/institutions.json, tests/unit/dojson/test_dojson_institutions.py
~~This PR adds more tests to the DoJSON conversions for the "minor" collections: Institutions, Conferences, Experiments, Jobs, and Journals.~~
~~The main purpose is to see what we actually have in the data and discover its quirks. Some will have to be solved in Legacy (like https://github.com/inspirehep/inspire/issues/170), others will have to be taken in account when building the DoJSON rules.~~
This was growing too much in scope, so in this PR I will only deal with Institutions. Other minor collections are tracked in #1240.
Only the assertions will have to be changed when we finalise the schemas, the test cases will stay the same (which is why this work will not be wasted).
Closes #1202
=> tests: unit tests for DoJSON institutions

inspirehep/modules/records/jsonschemas/records/hep.json
* Introduces supports for CRediT taxonomy of authorship roles.
=> jsonschema: CRediT support in hep.json

inspirehep/config.py, inspirehep/modules/orcid/__init__.py, inspirehep/modules/orcid/config.py, inspirehep/modules/orcid/ext.py, inspirehep/modules/orcid/models.py, inspirehep/modules/orcid/receivers.py, inspirehep/modules/orcid/schema.py, inspirehep/modules/orcid/tasks.py, inspirehep/modules/orcid/utils.py, inspirehep/modules/records/mappings/records/authors.json, inspirehep/modules/records/receivers.py, inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/orcid_serializer.py, inspirehep/modules/records/signals.py, inspirehep/modules/theme/templates/inspirehep_theme/accounts/login.html, inspirehep/utils/record.py, setup.py, tests/integration/test_orcid.py, tests/unit/orcid/test_orcid_converter.py, tests/unit/utils/test_utils_record.py
Adds the functionality to send updated/new records to orcid.
Signed-off-by: Panos Paparrigopoulos <panos.paparrigopoulos@cern
=> orcid: pushing records to orcid

inspirehep/modules/literaturesuggest/tasks.py, tests/unit/literaturesuggest/test_literaturesuggest_tasks.py
* First commit adds unit tests for most of `inspirehep/modules/literaturesuggest/tasks.py`. This also uncovered a few bugs, documented by xfailed tests.
* Second commit is taken (and slightly modified) from #1241, which fixes a mistake introduced in #1236.
The style of testing used in the first commit can probably be applied to testing the other tasks in the codebase.
Closes #1241
=> literaturesuggest: graceful page_nr

inspirehep/dojson/journals/fields/bd1xx.py, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Journal_HTML_detailed.tpl, tests/unit/dojson/test_dojson_journals.py
=> tests: unit tests for DoJSON journals

docker-compose.deps.yml
Last two merge builds were bad because PyPI went down while installing test dependencies: https://travis-ci.org/inspirehep/inspire-next/jobs/141055132#L1478 and https://travis-ci.org/inspirehep/inspire-next/jobs/140783712#L1602.
This PR should improve this by installing test dependencies as part of the development dependencies, whose installation is automatically retried on failure by Travis.
=> travis: improve build reliability

inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/test_dojson_hep.py
First commit reverts b3ab2fbb98edf5919ad002c6d6cc2d9509c6c045. Second commit xfails two tests that, consequently, had incorrect behaviour, while the third implements the correct one.
cc: @jmartinm
=> dojson: fix bug in HEP hidden_notes

inspirehep/modules/theme/templates/inspirehep_theme/accounts/login.html
* Shows flashed messages when using local account login in order to get
information if the user/password is wrong.
=> theme: login page show flashed messages

inspirehep/dojson/hep/fields/bd01x09x.py, inspirehep/dojson/hep/fields/bd90x99x.py
* Currently `dedupe_lists` is called on the full list, every time a record is appended. (Dedupe is n^2 or some heavy O(n)) Multiply this with the length of the list and we get to unnecessary n^3 or n^2. Would be cool to have the `freeze` + `set` logic but that would be some massive hack which sets function attributes.
=> dojson: faster dedupes

inspirehep/modules/theme/bundles.py, inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
Fix the current issue when using a new cleancss module that fails to
import the css file. Moved it to a bundle instead. (fixes #1296)
=> holdingpen: cleancss include error

setup.py
Build failed with: https://travis-ci.org/inspirehep/inspire-next/jobs/143751233#L1147. Commit 8f19cb9b added a pin on `aqmp` without an explanation (but it was probably fixing a build). This PR tries to fix the current build failure by removing this pin. If this fails I'll instead add a pin on `kombu`.
=> setup: add pin on celery

docker-compose.test.yml, docker-compose.yml, inspirehep/config.py
* Override ACCOUNTS_SESSION_REDIS_URL conf key with the env var if
available
* Update docker compose files to use it
=> config: missing env var override

inspirehep/dojson/common/base.py, inspirehep/dojson/hep/fields/bd01x09x.py, inspirehep/dojson/hep/fields/bd20x24x.py, inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/dojson/hep/fields/bd6xx.py, inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/dojson/hep/receivers.py, inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/dojson/processors.py, inspirehep/dojson/utils/__init__.py, inspirehep/modules/migrator/tasks.py, tests/unit/dojson/test_dojson_common_base.py, tests/unit/dojson/test_dojson_utils.py
* Adds `dedupe_all_lists` function
* Calls `dedupe_all_lists` for any `dojson` output
Signed-off-by: Mihai Bivol <mm.bivol@gmail.com>
=> dojson: dedupe and clean once per record

docs/building_the_docs.rst, docs/index.rst, setup.py
* Add also the requires.txt to the docs directory, with the
dependencies to build the docs themselves
=> docs: add how to build the docs

tests/integration/conftest.py
There's absolutely no point in deleting the records again after the integration tests have run: It just forces a costly `scripts/recreate_records` for no good reason. I have no idea what I was thinking when I wrote those lines.
=> tests: don't delete records when done testing

inspirehep/modules/workflows/tasks/beard.py, tests/unit/workflows/test_workflows_tasks_beard.py
First commit extracts the BEARD URL logic in a different method for testability and for similarity with how the Magpie tasks do it. Second commit adds tests. Third and fourth commit fix two bugs I found while writing these tests.
First bug was somewhat serious: we were not sending the abstract to BEARD to check for coreness. Where we getting good enough results with just the first title and the arXiv categories?
=> tests: unit tests for workflows beard tasks

setup.py
* Incorporates @jirikuncar's suggestion of trying to avoid `Flask-CLI`, which is still going to be installed because it's required by a lot of other Invenio packages.
* Incorporates @Panos512's suggestion of requiring at least version 0.2.2 to support IPython 5.0.0.
Closes #1305
=> setup: add flask-shell-ipython

inspirehep/dojson/jobs/fields/bd1xx.py, inspirehep/dojson/utils/__init__.py, inspirehep/modules/records/jsonschemas/records/jobs.json, tests/unit/dojson/test_dojson_jobs.py, tests/unit/dojson/test_dojson_utils.py
=> tests: unit tests for DoJSON jobs

inspirehep/dojson/common/base.py, inspirehep/dojson/conferences/fields/bd1xx.py, inspirehep/dojson/experiments/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd01x09x.py, inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd20x24x.py, inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/dojson/hep/fields/bd6xx.py, inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/dojson/hep/fields/bd76x78x.py, inspirehep/dojson/hep/fields/bd90x99x.py, inspirehep/dojson/hep/model.py, inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/dojson/institutions/fields/bd1xx.py, inspirehep/dojson/jobs/fields/bd1xx.py, inspirehep/dojson/processors.py, inspirehep/dojson/utils/__init__.py, inspirehep/dojson/utils/geo.py, inspirehep/modules/orcid/schema.py, inspirehep/utils/bibtex.py, tests/unit/dojson/test_dojson_institutions.py, tests/unit/dojson/test_dojson_utils.py, tests/unit/dojson/test_dojson_utils_geo.py
First commit adds a `force_force_list` util that **always** returns a `list`, unlike `force_list` from DoJSON that returns either a `tuple` or `None`. Second commit amends all uses of `force_list` to `force_force_list`.
=> global: force_list -> force_force_list

inspirehep/dojson/common/base.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/test_dojson_hep.py
* Removes OAI-PMH handling which should be better handled
natively via invenio-oaiserver. (closes #1339)
=> dojson: remove OAI-PMH handling

inspirehep/dojson/conferences/fields/bd1xx.py, tests/unit/dojson/test_dojson_conferences.py
=> tests: unit tests for DoJSON conferences

inspirehep/dojson/hep/fields/bd90x99x.py, inspirehep/modules/references/processors.py, tests/unit/dojson/test_dojson_hep.py, tests/unit/references/test_processors.py
* Adds method to parse out individual authors from legacy refextract
author strings containing multiple authors.
* Uses added method in dojson.
Closes #1344 
=> references: support for old refextract authors strings

inspirehep/modules/theme/views.py
Whoops. The actual collection name to pass is `hepnames`, not `authors`, otherwise we fall back on the HEP count.
=> theme: fix count shown on authors landing page

inspirehep/dojson/journals/fields/bd1xx.py, tests/unit/dojson/test_dojson_dois.py, tests/unit/dojson/test_dojson_hep.py, tests/unit/dojson/test_dojson_hepnames.py, tests/unit/dojson/test_dojson_institutions.py, tests/unit/dojson/test_dojson_journals.py, tests/unit/dojson/test_dojson_utils.py
We should be using `clean_record` instead of `strip_empty_values`, but the tests contain lots of examples of the latter. This PR removes most of these examples, except for a few legitimate uses.
=> dojson: almost remove strip_empty_values

inspirehep/dojson/common/__init__.py, inspirehep/dojson/conferences/fields/__init__.py, inspirehep/dojson/experiments/fields/__init__.py, inspirehep/dojson/hep/fields/__init__.py, inspirehep/dojson/hepnames/fields/__init__.py, inspirehep/dojson/institutions/fields/__init__.py, inspirehep/dojson/jobs/fields/__init__.py, inspirehep/dojson/journals/fields/__init__.py, inspirehep/modules/authors/ext.py, inspirehep/modules/authors/views/__init__.py, inspirehep/modules/authors/views/holdingpen.py, inspirehep/modules/authors/views/publications.py, inspirehep/modules/workflows/tasks/arxiv.py, tests/integration/test_author_views.py, tests/unit/authors/test_authors_views.py
Since #1353 is trying (but will not succeed) to introduce more uses of the `unicode_literals` import I took the occasion of removing all current uses in the codebase.
This might impact your PRs: please ping me if you need help rebasing after conflicts.
=> global: remove unicode_literals import

inspirehep/dojson/institutions/fields/bd1xx.py, inspirehep/modules/records/jsonschemas/records/institutions.json, tests/unit/dojson/test_dojson_institutions.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601661/
These are the values (and counts) of `372__a` in Institutions:
```
1 Laboratory
1 Natl., Inst., mat., phys., nat., ent., inst., nat., phys., mat., mater, reg., lab., ind., appl., pol., poly.
1 Research Center-microelectronics
1 Univesity
1 university
2 Research center/
46 Research Center
60 Company
662 Research center
4545 University
```
My solution classifies only the first two as `"Other"`, and normalizes the rest.
=> dojson: fix field_activity in institutions

inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/modules/literaturesuggest/dojson/fields/literature.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/test_dojson_hep.py, tests/unit/literaturesuggest/test_literaturesuggest_dojson.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601705/
Doesn't yet handle all cases present in the data, but I'm going to fix those when they arrive in Sentry.
=> schemas: thesis_supervisor -> thesis_supervisors

pytest.ini
* As we don't have any tests mixed in with the code, we can skip
crawling inside the inspirehep module and shave off a few seconds
and a bunch of useless logs from the test runs.
=> tests: ignore inspirehep module

.coveragerc, Procfile, gunicorn.cfg, inspirehep/__init__.py, inspirehep/celery.py, inspirehep/cli.py, inspirehep/config.py, inspirehep/factory.py, inspirehep/version.py, inspirehep/wsgi.py, pytest.ini, requirements.txt, setup.cfg
A simple PR full of nitpickery: see the branch name.
First commit fixes licenses, docstrings and imports of top level files. Second PR adds a `.coveragerc` file ignoring those app instantiation files which are never executed by the application itself (slightly improving coverage).
=> tests: add .coveragerc file

inspirehep/config.py
* Now you can override current crawler configuration variables using
environment variables, specifically:
- CRAWLER_HOST_URL
- CRAWLER_API_PIPELINE_URL
- CRAWLER_API_PIPELINE_TASK_ENDPOINT_DEFAULT
=> crawler: add override of config vars wih env vars

.travis.yml
After https://www.traviscistatus.com/incidents/2p40l49r3yxd the Travis people updated the Ubuntu Trusty images to a newer version:
> We've determined that an image cleanup process malfunctioned and deleted the stable build environment images. Due to various factors our only option at this point is roll forward with newer build environment images, for both Precise and Trusty.
1. This new Trusty image ships with the `1.12.0-0~trusty` version of `docker-engine`. Our Travis script was trying to downgrade it to `1.10.3-0~trusty`, which was failing: https://travis-ci.org/inspirehep/inspire-next/jobs/151099253#L422. The reason why escapes me, but I just decided to bump the `docker-engine` we require on Travis.
2. This new Trusty image ships *without* a `docker-compose` command. Our Travis script …
=> travis: fix build

inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/modules/records/jsonschemas/records/hep.json
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601706/
This is the partial status of the `502__b` field (I interrupted a query that had been running for a few hours...):
```
1 Dubna, JINR
1 Licencia
1 Maitrise Communication
1 PDF
1 Ph.D Thesis
1 master
2 Internship report
2 PHD
2 Rapport de stage
3 phD
3 thesis
4 Licentiate
4 Mainz U.
6 Licenciate
7 Phd
85 Habilitation
99 Laurea
160 Bachelor
412 Diploma
1063 Thesis
1159 Master
13047 PhD
```
This PR adds a little normalization to the DoJSON rule so that less values will result in invalid records. It's not a complete solution because I don't know if we should ignore the rest of the cases, or we want to have "Internship report"s and similar entries.
=> dojson: normalize degree_type

inspirehep/modules/search/static/js/search/app.js, inspirehep/modules/search/templates/search/search.html, inspirehep/modules/theme/static/scss/base/header.scss, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/header.html, inspirehep/modules/theme/templates/inspirehep_theme/search/form/controls.html, inspirehep/modules/theme/templates/inspirehep_theme/typeahead.html
* Changes search bar in search results to use Angular directive.
* Makes typeahead work with and without Angular.
* Shows search bar in all detailed pages.
=> theme: search bar improvements

inspirehep/dojson/hep/receivers.py, tests/unit/dojson/test_dojson_hep_receivers.py
* Amends earliest_date receiver to be triggered only at index time,
rather than before_record_* time, thus adding earliest_date bit
only in ES (it's not a property that is supposed to be touched
by humans).
=> dojson: earliest_date in ES only

inspirehep/config.py, inspirehep/dojson/common/base.py, inspirehep/dojson/hep/fields/bd5xx.py, inspirehep/modules/records/jsonschemas/records/hep.json, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/workflows/mappings/holdingpen/authors.json, inspirehep/modules/workflows/mappings/holdingpen/hep.json, tests/unit/dojson/test_dojson_hep.py
* Removes fields only used on ElasticSearch and not part of the record
data model.
=> jsonschemas: schema clean up

inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hepnames/fields/bd1xx.py, tests/unit/dojson/test_dojson_hep.py, tests/unit/dojson/test_dojson_hepnames.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/602865/ and https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/602870/. There's also https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/602869/, but I can't reproduce it locally...
Merging quickly so I can start again the nightly.
=> dojson: fix identifiers rules

inspirehep/modules/references/view_utils.py, inspirehep/modules/search/api.py, inspirehep/utils/record_getter.py
* Fixes issue were the generated query is too long which throws a
recursion depth error.
=> references: use mget instead of a parsed query

inspirehep/dojson/hep/fields/bd1xx.py, tests/unit/dojson/test_dojson_hep.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/602894/
=> dojson: ensure that x_value is an integer

inspirehep/dojson/hep/fields/bd5xx.py, tests/unit/dojson/test_dojson_hep.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/602792/events/130178183/
This bug might be the reason why the nightly migration stops at 834028 HEP records.
=> dojson: make thesis more robust

inspirehep/dojson/utils/geo.py, tests/unit/dojson/test_dojson_conferences.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601668/
This file isn't great code, but is useful, so I made the smallest possible modification to prevent the exception, because I anticipate that this will be entirely rewritten.
=> dojson: make parse_conference_address more robust

inspirehep/modules/records/jsonschemas/records/experiments.json
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601669/
The `accelerator` field is a slowly varying field, but still a varying
field, so not a good fit for an `enum`, since it would require a code
modification per data update.
=> schemas: remove accelerator enum

inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd5xx.py, tests/unit/dojson/test_dojson_hep.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601658/
=> dojson: use logger, not warnings

inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/utils/bibtex.py, tests/unit/dojson/test_dojson_hep.py, tests/unit/utils/test_utils_bibtex.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601938/
A `701` field can contain multiple `a` subfields. A reasonable
interpretation is that they all share the same affiliation(s)
contained in the `u` subfields of the field. This code assumes
this and creates a `thesis_supervisor` per `701__a` field it
finds.
By using the `contributor_roles` added in cf74d6 we can specify
the fact that an author contributed to some work as a supervisor.
This means that the `thesis_supervisor` key is redundant, and
can be merged inside of `authors`.  (Closes #1259)
Also adds some logic to the BibTeX exporter in order not to add
the thesis supervisors as authors. This addition required some
refactoring to the `get_author` method, which removed the support
for multiple `full_name`s, …
=> dojson: split multiple thesis supervisors

setup.py
`webassets==0.12.0` introduces an unknown regression whose exception can be found on Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/603057/.
Pinning it to the previous version should work around this issue.
=> setup: pin webassets

.travis.yml, docker-compose.test.yml, inspirehep/demosite/data/demo-records-small.xml, inspirehep/modules/disambiguation/__init__.py, inspirehep/modules/disambiguation/beard.py, inspirehep/modules/disambiguation/config.py, inspirehep/modules/disambiguation/ext.py, inspirehep/modules/disambiguation/logic.py, inspirehep/modules/disambiguation/models.py, inspirehep/modules/disambiguation/receivers.py, inspirehep/modules/disambiguation/records.py, inspirehep/modules/disambiguation/search.py, inspirehep/modules/disambiguation/tasks.py, setup.py, tests/integration/conftest.py, tests/integration/disambiguation/test_daemon.py, tests/integration/disambiguation/test_logic.py, tests/integration/disambiguation/test_receivers.py, tests/integration/disambiguation/test_records.py, tests/integration/disambiguation/test_workflows.py, tests/unit/disambiguation/test_logic.py, tests/unit/disambiguation/test_receivers.py
* Adds a method to communicate with Beard Celery instances
in order to delegate a clustering job.
* Adds methods to create a new author profile and update
signatures to point to new author profiles.
* Adds methods to keep track of new/updated records.
=> disambiguation: alpha release

inspirehep/modules/authors/bundles.py, inspirehep/modules/forms/bundles.py, inspirehep/modules/theme/bundles.py, setup.py
Removes the pin introduced in f00e62b, and consequently bumps the
`invenio-assets` dependency. This requires us to use the `node-scss`
filter everywhere instead of the `scss` filter.
=> setup: unpin webassets

inspirehep/config.py, inspirehep/modules/authors/rest/__init__.py, inspirehep/modules/authors/rest/citations.py, inspirehep/modules/authors/rest/coauthors.py, inspirehep/modules/authors/rest/publications.py, inspirehep/modules/authors/rest/stats.py, tests/integration/test_author_api.py
I rewrote the tests and found a weird bug: sometimes `null` is considered a keyword. For now I'm not raising an error by expanding the response schema to allow for `null` values there, but clearly something's off.
Closes #1463
=> api: extend /authors endpoint

inspirehep/dojson/hep/fields/bd01x09x.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/test_dojson_hep.py
* Normalizes languages using ISO 639-1.
=> dojson: language support

inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/modules/records/jsonschemas/records/elements/id.json, tests/unit/dojson/test_dojson_hepnames.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/602869/
~~Needs an answer to https://github.com/inspirehep/inspire/issues/211 in order to know which ID schemes we want to implement.~~
=> dojson: more fixes to ids

inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/modules/records/jsonschemas/records/authors.json, inspirehep/modules/theme/templates/inspirehep_theme/format/record/authors/Author_HTML_detailed.html, tests/unit/dojson/test_dojson_hepnames.py
* Unifies `email` and `old_email` in a single field called `emails`,
with the convention that the first emails are the most current.
* Consolidates the treatment of `status`/`current`, and moves
`curated_relation` where it belongs (near the institution).
Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
=> dojson: rewrite positions rule

inspirehep/dojson/institutions/fields/bd1xx.py, tests/unit/dojson/test_dojson_institutions.py
Now that https://github.com/inspirehep/inspire/issues/170 was properly solved on Legacy data we can start ignoring this error on Nightly.
=> dojson: ignore double longitudes

inspirehep/dojson/hep/fields/bd76x78x.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/fixtures/test_hep_record.xml, tests/unit/dojson/test_dojson_hep.py
* Model pulication info notes as a list with unique values (if not
unique, duplicates will be ignored on parsing)
=> schema: allow list as publication info notes

inspirehep/config.py, inspirehep/modules/pidstore/providers.py, tests/integration/conftest.py, tests/integration/test_pidstore.py
* Adds a method, which reserves a new pid from legacy instance,
so that when a new record arrives there won't be a conflict
between legacy systems and labs.
=> pidstore: request next pid from legacy

inspirehep/dojson/institutions/fields/bd1xx.py, inspirehep/modules/records/jsonschemas/records/institutions.json, tests/unit/dojson/test_dojson_institutions.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601660/
* Merges obsolete_institutions into related_institutes.
=> jsonschema: correct obsolete_institutions

inspirehep/dojson/hep/fields/bd76x78x.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/test_dojson_hep.py
* Ignores second instances of subfields for mashed up 773s.
(closes #1507)
=> dojson: mashed up 773s

inspirehep/modules/migrator/tasks.py
This was all that was needed to have citation counts on Nightly.
=> migrator: allow errors in count_citations

inspirehep/dojson/hep/fields/bd5xx.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601709/
=> dojson: ignore Open Access redundant license

inspirehep/dojson/hep/fields/bd01x09x.py, tests/unit/dojson/test_dojson_hep.py
Substantially rewritten, but same business logic.
Closes #1516
=> dojson: skip CURATOR source in DOI

inspirehep/dojson/hep/fields/bd20x24x.py, inspirehep/modules/records/jsonschemas/records/hep.json, inspirehep/utils/record.py, setup.py, tests/unit/dojson/test_dojson_hep.py, tests/unit/orcid/test_orcid_converter.py, tests/unit/utils/test_utils_record.py
* Merge title_variations (210) and titles_old(247) into titles with
the convention that the main title is the first in the list and all
the others are variations or previous versions. (closes #1257)
=> jsonschema: simple titles

inspirehep/config.py, inspirehep/dojson/hep/fields/bd1xx.py, inspirehep/dojson/hep/fields/bd70x75x.py, inspirehep/modules/disambiguation/search.py, inspirehep/modules/records/jsonschemas/records/hep.json, tests/unit/dojson/fixtures/test_hep_record.xml, tests/unit/dojson/test_dojson_hep.py, tests/unit/utils/test_utils_bibtex.py
* Deletes `roles` field.
* Stores normalized roles in `contributor_roles`.
(closes #1533)
=> dojson: roles fix

inspirehep/dojson/institutions/fields/bd1xx.py, inspirehep/modules/records/jsonschemas/records/institutions.json, tests/unit/dojson/test_dojson_institutions.py
* Ignores name variants coming from non valid sources.
(closes #1524)
=> dojson: invalid name variant sources

inspirehep/dojson/conferences/fields/bd1xx.py, inspirehep/modules/records/jsonschemas/records/conferences.json, inspirehep/modules/records/mappings/records/conferences.json, tests/unit/dojson/test_dojson_conferences.py
* Makes series and number back into one field in conferences, when
they are split in multiple.
(closes #1517)
=> dojson: series and number in one field

inspirehep/modules/oaiharvester/tasks/arxiv.py
Should fix: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/244919/ and https://sentry.cern.ch/inspire-sentry/inspire-labs/group/244943/
=> oaiharvester: ignore CorruptImageError

tests/integration/conftest.py, tests/unit/conftest.py
* Since py.test>2.10 the yield_fixture construct is deprecated, and
the request.addfinalizer mechanism was replaced by using just yield
instead of return in the fixture, see:
http://doc.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code
=> tests: remove deprecated yield_fixture uses

inspirehep/config.py, inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/wrappers.py, inspirehep/modules/theme/jinja2filters.py, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Publication_info.tpl, setup.py, tests/unit/theme/test_theme_jinja2filters.py
* Removes the theme extension that should not be present in the API app.
(closes #1508)
* Refactors publication_info jinja2 filter to separate the data generation
from the template rendering.
* Makes use of LiteratureRecord in search serializer instead of jinja2
filter to avoid dependency on templates. The dependency on the templates
is the reason why theme is loaded into API at the moment.
=> global: theme extension removal from API

inspirehep/modules/authors/receivers.py, inspirehep/modules/theme/templates/inspirehep_theme/typeahead.html
* Fixes receiver that populates payload used by typeahead to adapt to
data model change for ids.
* Fixes typeahead angular directive so that it works nicely with the jQuery
plugin. (closes #1432)
=> theme: typeahead fixes

tests/unit/dojson/test_dojson_hep.py
=> tests: stable langdetect in tests

inspirehep/modules/disambiguation/__init__.py, inspirehep/modules/disambiguation/beard.py, inspirehep/modules/disambiguation/config.py, inspirehep/modules/disambiguation/ext.py, inspirehep/modules/disambiguation/logic.py, inspirehep/modules/disambiguation/models.py, inspirehep/modules/disambiguation/receivers.py, inspirehep/modules/disambiguation/records.py, inspirehep/modules/disambiguation/search.py, inspirehep/modules/disambiguation/tasks.py, tests/integration/conftest.py, tests/integration/disambiguation/test_daemon.py, tests/integration/disambiguation/test_logic.py, tests/integration/disambiguation/test_receivers.py, tests/integration/disambiguation/test_records.py, tests/unit/disambiguation/test_disambiguation_logic.py, tests/unit/disambiguation/test_disambiguation_receivers.py
* First commit retouches some imports in the `disambiguation` module.
* Second commit detaches the receivers from the signals. The rationale is in the commit message:
> On record migration the `append_new_record_to_queue` receiver fires,
which adds the record to the `DisambiguationRecord` queue. Then, when
the same record is indexed, `append_updated_record_to_queue` fires,
which will try adding the same record to the queue. In doing so, it
will shoot back a query at ES to try to get a previous version of the
record, which will probably return a 404 because this is the first
time we're inserting the record. This generates undue pressure on ES
and achieves nothing, therefore this PR disable these signals.
=> disambiguation: detach receivers

inspirehep/dojson/hepnames/fields/bd1xx.py, tests/unit/dojson/fixtures/test_hepnames_record.xml, tests/unit/dojson/test_dojson_hepnames.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601676/
Some minor changes, like removing the (unrelated?) modifications in `tests/unit/conftest.py` and tweaking the docstrings as suggested in https://github.com/inspirehep/inspire-next/pull/1526#r77206250.
Closes #1526
=> dojson: allow multiple experiments in authors

inspirehep/modules/records/jsonschemas/records/elements/field.json, tests/unit/dojson/test_dojson_common_base.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601663/
=> schemas: add conference to field categories source

inspirehep/dojson/hep/fields/bd5xx.py, tests/unit/dojson/test_dojson_hep.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/603523/
=> dojson: output multiple public_notes

inspirehep/modules/forms/static/js/forms/affiliations_typeahead.js, inspirehep/modules/forms/static/js/forms/authors_typeahead.js, inspirehep/modules/forms/static/js/forms/experiments_typeahead.js, tests/acceptance/conftest.py, tests/acceptance/test_author_create_typehead.py
@rikirenz, some things changed from the integrated PR:
* I squashed the first two commits  because they implement the same idea: switching from using a `small_app` in the acceptance tests to a `full_app`, or, as we call it, `app`.
* I squashed together the three commits that fix the suggestions parsers and the three tests commit since they basically do the same thing, except for different fields. Note here that this signals a refactoring opportunity: the fact that you had to something three times means that the code is not DRY (https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
* I put the commit that implements the feature first, so that `git bisect` won't break when driven by the acceptance test suite.
Then, some style comments:
* People usually write commit titles in the …
=> forms: fix authors autocomplete

docs/building_the_docs.rst, docs/grobid.rst, docs/harvesting.rst, docs/index.rst, docs/installation.rst, docs/operations.rst, docs/tests.rst, docs/tools.rst
#1602 was missing the documentation commit from #1554. I also took the occasion to fix the licenses in that folder.
Closes #1604
=> docs: add documentation about selenium tests

inspirehep/modules/records/es_record.py, tests/integration/test_record.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/606029/
First commit fixes a license and rearranges some imports.
Second commit (by @spirosdelviniotis) is the meat of the PR:
> Requesting a record from Elasticsearch too soon after creation
might result in a missing `_updated` key, which raises an
uncaught exception in the `updated` property of the `ESRecord`
class. This commit ensures that this doesn't happen by returning
a fresh datetime.now() object instead (closes #1595).
Third commit (also by @spirosdelviniotis) does some minor refactoring in the same file, removing some duplicated code.
Closes #1603
=> records: fix crash in get_es_record

inspirehep/modules/theme/templates/inspirehep_theme/header.html
Removed a duplicate HTML attribute (ignored by the browser) and added a space betwen the URL attributes.
Signed-off-by: Liam Kirsh <liam.kirsh@cern.ch>
=> theme: fix invalid HTML in header

inspirehep/config.py, inspirehep/dojson/utils/__init__.py, inspirehep/modules/fixtures/cli.py, inspirehep/modules/fixtures/collections.py, inspirehep/modules/fixtures/users.py, inspirehep/modules/records/mappings/records/authors.json, inspirehep/modules/records/mappings/records/conferences.json, inspirehep/modules/records/mappings/records/data.json, inspirehep/modules/records/mappings/records/experiments.json, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/mappings/records/institutions.json, inspirehep/modules/records/mappings/records/jobs.json, inspirehep/modules/records/mappings/records/journals.json, inspirehep/modules/records/permissions.py, inspirehep/modules/search/api.py, inspirehep/modules/search/query_factory.py, inspirehep/modules/theme/ext.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/author.py, setup.py, tests/acceptance/conftest.py, tests/integration/conftest.py, tests/integration/test_permissions.py, tests/integration/test_record.py
=> global: add record/collection permissions

setup.py
* The fix for the issue we were seeing was already pushed upstream on
the latest version (1.0b10/0.99999999).
=> packaging: unpin html5lib

inspirehep/modules/migrator/legacy/audit.py
* Audit table dumping now only dumps data related to specific workflows types.
Signed-off-by: Panos Paparrigopoulos panos.paparrigopoulos@cern.ch
=> audit: dump only valid records.

INSTALL.rst
More recent versions of `node-sass` cause issue #1642, therefore
recommend developers to use this particular version (closes #1644).
Closes #1655 
@zzacharo: can you run
```
git config --local user.name "Zacharias Zacharodimos"
git config --local user.email <zacharias.zacharodimos@cern.ch>
```
so that your local `git` configuration matches what I put for you here?
=> docs: recommend node-sass@3.8.0

setup.py
Otherwise the build fails like this: https://travis-ci.org/inspirehep/inspire-next/jobs/168969097#L716
Remove this when `elasticsearch-dsl` is updated (build might start failing again).
=> setup: pin elasticsearch

setup.py
`Flask-Login==0.4.0` was [just released](https://github.com/maxcountryman/flask-login/releases/tag/0.4.0), but it is [incompatible](https://github.com/mattupstate/flask-security/blob/9e5865d9735b0b292360f63588ed4725c376757e/requirements.txt#L2) with `Flask-Security==1.7.5` (just spotted this on Nightly).
Failure: https://travis-ci.org/inspirehep/inspire-next/jobs/170856603#L709.
=> setup: pin Flask-Login

inspirehep/modules/authors/views/holdingpen.py
it should work as before but avoid the key error in the field _private_node
=> authors: fix key error in workflow comments field

inspirehep/config.py, inspirehep/modules/api/__init__.py, inspirehep/modules/api/utils.py, inspirehep/modules/api/v1/__init__.py, inspirehep/modules/api/v1/authors.py, inspirehep/modules/api/v1/experiments.py, inspirehep/modules/api/v1/institutions.py, inspirehep/modules/api/v1/journals.py, inspirehep/modules/api/v1/literature.py, tests/integration/api/v1/test_authors.py, tests/integration/api/v1/test_experiments.py, tests/integration/api/v1/test_institutions.py, tests/integration/api/v1/test_journals.py, tests/integration/api/v1/test_literature.py, tests/unit/api/test_api_utils.py
Introduces the new API module, were all things API should live. Note that the folder structure allows for multiple API versions: the same should be added to our `invenio-records-rest` configuration and possibly upstream (I'll expand on this later).
As a PoC for the API module, implements the `citesummary` endpoint for `literature`, `authors`, `institutions` using ES queries.
Addresses #1304
Closes #1572
=> api: add citesummary

inspirehep/dojson/hepnames/fields/bd1xx.py, inspirehep/modules/authors/dojson/fields/updateform.py, inspirehep/modules/authors/forms.py, inspirehep/modules/authors/static/scss/authors/authors-update-form.scss, inspirehep/modules/authors/views/holdingpen.py, inspirehep/modules/theme/templates/inspirehep_theme/format/record/authors/Author_HTML_detailed.html, tests/unit/authors/test_authors_dojson.py, tests/unit/authors/test_authors_views.py, tests/unit/dojson/test_dojson_hepnames.py
* To avoid losing information when converting from/to legacy marcxml
keep for the moment the old and new emails on different fields.
=> dojson: keep old_emails in positions

setup.py
It will be pulled in by hepcrawl if needed.
=> packaging: remove scrapyd dependency

setup.py, tests/integration/test_permissions.py
* Makes sure `transaction` table is cleaned properly.
=> tests: invenio-db==1.0.0b3 support

inspirehep/dojson/common/base.py, inspirehep/modules/api/utils.py, inspirehep/modules/authors/rest/citations.py, inspirehep/modules/authors/rest/stats.py, inspirehep/modules/migrator/tasks/records.py, inspirehep/modules/pidstore/minters.py, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/receivers.py, inspirehep/modules/records/serializers/impactgraph_serializer.py, inspirehep/modules/references/view_utils.py, inspirehep/modules/theme/views.py, inspirehep/utils/bibtex.py, inspirehep/utils/citations.py, inspirehep/utils/latex.py, setup.py, tests/integration/disambiguation/test_receivers.py, tests/integration/test_orcid.py, tests/integration/test_permissions.py, tests/unit/api/test_api_utils.py, tests/unit/orcid/test_orcid_converter.py, tests/unit/records/test_records_receivers.py, tests/unit/utils/test_utils_bibtex.py, tests/unit/utils/test_utils_cv_latex.py
* Updates inspire-schemas package to 2.0.0.
* Updates usage of control_number field to make sure it is always used
as an integer.
=> global: inspire-schemas 2.0.0 upgrade

tests/integration/workflows/test_arxiv_workflow.py
* Patches correctly download_file_to_record to avoid making requests
while testing.
=> tests: workflow mocking fix

inspirehep/modules/authors/dojson/fields/updateform.py, inspirehep/modules/authors/views/holdingpen.py, tests/unit/authors/test_authors_dojson.py
* Makes sure the output of the author creation form is compliant with
the json schema, to be able to save the author locally.
=> authors: form output schema compliant

inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/tasks/__init__.py, inspirehep/modules/migrator/tasks/workflows.py
* Adds a migrator command to load dumps of audit records.
=> migrator: import audit

inspirehep/modules/workflows/tasks/submission.py, tests/unit/workflows/test_workflows_tasks_submission.py
During the accepting phase for an harvest article, the worker raise an error for a duplicate dictionary. This fix should check if the dictionary that is going to be added is already present and avoid the error.
=> tasks: add control for duplicate notes

inspirehep/modules/migrator/legacy/user_roles.py, setup.py
* Can be applied to Invenio 2.x instance.
=> migrator: dump user roles

inspirehep/config.py
* For compatibility with passwords created with Invenio 2.x. (closes #1755)
=> config: add sha512_crypt to password schemes

inspirehep/utils/arxiv.py, tests/unit/utils/test_utils_arxiv.py
* Simplifies `get_clean_arXiv_id`
* Removes data-only fixtures in tests
* Cleans up licenses and imports
Spin off of #1748
=> utils: refactor arxiv utils

setup.py, tests/integration/conftest.py, tests/integration/test_pidstore.py, tests/unit/authors/test_authors_receivers.py, tests/unit/conftest.py
* Uses `pytest-httpretty` instead of `httpretty_mock` and `httppretty_mock`.
* Fixes some licenses and imports.
Spin off of #1748
=> setup: use pytest-httpretty

inspirehep/config.py
* Forces SQLALCHEMY_TRACK_MODIFICATIONS to False, since this feature
just adds overhead and we are not currently using it anywhere.
* Bonus point: remove the corresponding infamous warning.
=> config: disable SQLALCHEMY_TRACK_MODIFICATIONS

inspirehep/config.py, inspirehep/modules/fixtures/users.py, inspirehep/modules/records/permissions.py, setup.py, tests/integration/conftest.py, tests/integration/test_orcid.py, tests/integration/test_permissions.py
* Adds a new record update permission factory. Change update access from `allow_all`
to administrators and catalogers.
* Adds invenio_collections extension in api_apps entrypoints for using the
invenio-records-rest PUT request upon a single record.
* Adds a new integration test for checking user update permissions.
Signed-off-by: Zacharias Zacharodimos zacharias.zacharodimos@cern.ch
=> permissions: Creation of an update permission factory.

inspirehep/config.py, inspirehep/modules/disambiguation/records.py, inspirehep/modules/disambiguation/tasks.py, inspirehep/modules/migrator/cli.py, inspirehep/modules/records/receivers.py, inspirehep/modules/workflows/tasks/upload.py, tests/integration/test_model_receiver.py, tests/integration/test_permissions.py, tests/integration/test_record.py
* Adds models_committed receiver that sends to ElasticSearch the changes
made in the RecordsMetadata table.
=> records: sync modifications in database and ElasticSearch

.travis.yml
As you can see from the branch name, I started with the idea of removing [these lines](https://github.com/inspirehep/inspire-next/blob/9a9a4b4add6738d889251f8352510711a793eb9a/.travis.yml#L54-L57) and the variable above, but then I decided against it, because I believe there's value in specifying exactly which version of Docker/Docker-Compose we know are working.
=> travis: bump docker version

inspirehep/celery.py, requirements.txt
As explained in inveniosoftware/flask-celeryext#26, the parent of
a logger created by `get_task_logger` is `celery.task`, which does
not propagate exceptions, therefore preventing the handler sending
logging statements to Sentry from running.
The hack in inspirehep/celery.py was making so that the parent of
these tasks was `flask.logging.DebugLogger`, which does propagate
exceptions.
Since inveniosoftware/flask-celeryext#26 was merged we no longer
need this workaround, and we will start seeing again the validation
errors on Sentry (closes #1641).
Closes #1797
=> migrator: fix logging in celery tasks

inspirehep/modules/search/query.py, inspirehep/modules/search/query_factory.py, tests/integration/test_permissions.py, tests/integration/test_search_views.py
=> search: show correct debug output for search queries

inspirehep/dojson/institutions/fields/bd1xx.py, tests/unit/dojson/test_dojson_institutions.py
This bug was deviously hidden by a repeated test name, which was shadowing the broken test with a passing one.
=> dojson: fix bug in historical_data rule

inspirehep/dojson/institutions/fields/bd1xx.py, tests/unit/dojson/test_dojson_institutions.py
This is populating something which is not yet part of the schemas. Will send the associated PR against `inspire-schemas` later.
=> dojson: add institution ids

inspirehep/modules/authors/views/holdingpen.py, inspirehep/modules/literaturesuggest/views.py, inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_decision_authors.html, inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html, tests/acceptance/test_author_create_typehead.py
* Unifies URL naming to /literature/new, /author/new and
/author/<id>/update. (closes #1788)
=> global: suggestion forms URL change

inspirehep/modules/authors/dojson/fields/updateform.py, inspirehep/modules/authors/forms.py, inspirehep/modules/authors/tasks.py, inspirehep/modules/authors/views/holdingpen.py, tests/unit/authors/test_authors_tasks.py, tests/unit/authors/test_authors_views.py
* The emails generated doing an author workflow can access the control_number
to properly format the URLs (closes #1803).
=> authors: pass control_number to author tasks

inspirehep/config.py, inspirehep/modules/disambiguation/records.py, inspirehep/modules/disambiguation/tasks.py, inspirehep/modules/migrator/tasks/records.py, inspirehep/modules/records/api.py, inspirehep/modules/records/receivers.py, inspirehep/modules/records/wrappers.py, inspirehep/modules/workflows/tasks/upload.py, inspirehep/utils/record.py, inspirehep/utils/record_getter.py, tests/integration/disambiguation/test_receivers.py, tests/integration/disambiguation/test_records.py, tests/integration/disambiguation/test_workflows.py, tests/integration/test_model_receiver.py, tests/integration/test_permissions.py, tests/integration/test_record.py, tests/unit/authors/test_authors_views.py, tests/unit/dojson/test_dojson_hep_receivers.py, tests/unit/hal/test_tei.py, tests/unit/theme/test_theme_jinja2filters.py, tests/unit/utils/test_utils_bibtex.py, tests/unit/utils/test_utils_bibtex_booktitle.py, tests/unit/utils/test_utils_cv_latex.py, tests/unit/utils/test_utils_cv_latex_html_text.py, tests/unit/utils/test_utils_export.py, tests/unit/utils/test_utils_latex.py, tests/unit/utils/test_utils_record.py, tests/unit/workflows/test_workflows_tasks_beard.py, tests/unit/workflows/test_workflows_tasks_magpie.py
* Adds an inspire record class between invenio record and ESrecord.
Inheritance from invenio_records.api Record.
=> records: add Inspire record class

setup.py
Travis: https://travis-ci.org/inspirehep/inspire-next/jobs/189915754
This is a temporary workaround to a regression introduced by Jinja 2.9: `ASSET_URL` variables in `assets` block now appear to be undefined. Also see: https://github.com/miracle2k/flask-assets/issues/120
=> setup: pin Jinja2

setup.py
Reverts #1846
This was actually a bug in `webassets`: https://github.com/miracle2k/webassets/issues/477. A new release of `webassets` (0.12.1) fixed it.
=> setup: unpin Jinja2

inspirehep/modules/theme/ext.py, tests/unit/theme/test_theme_jinja2filters.py, tests/unit/utils/test_utils_conferences.py, tests/unit/utils/test_utils_experiments.py
Spin off of #1785.
Adds `lstrip_blocks` and `trim_blocks` to Jinja2's configuration, so
that most whitespace is deleted from the result.
See: http://jinja.pocoo.org/docs/dev/templates/#whitespace-control.
As @jmartinm remarked [here](https://github.com/inspirehep/inspire-next/pull/1785#discussion_r91735604), this means that all `{%-` and `-%}` are
now obsolete, and should be removed in a cleanup PR.
=> theme: configure Jinja2 to remove whitespace

tests/unit/utils/fixtures/foo-bar-baz, tests/unit/utils/test_utils_helpers.py
* Adds unit tests for methods in `inspirehep/utils/helpers.py`.
~~Depends on #1752~~
Spin off of #1748
=> tests: add unit tests for utils/helpers

inspirehep/dojson/common/base.py, inspirehep/modules/workflows/tasks/submission.py, tests/unit/dojson/test_dojson_common_base.py, tests/unit/workflows/test_workflows_tasks_submission.py
Closes #1769 
* First commit amends a DoJSON rule to also include a `filetype` subfield in `fft`.
* Second commit is just a preparatory commit for the next one.
* Third commit reimplements `prepare_files` from scratch, with complete test coverage.
=> workflows: rewrite prepare_files in tasks/submission

inspirehep/modules/literaturesuggest/static/js/literaturesuggest/literature_submission_form.js, inspirehep/modules/literaturesuggest/templates/literaturesuggest/forms/suggest.html
Closes #1867
Uses the `ARXIV_TO_INSPIRE_CATEGORY_MAPPING` configuration variable
to convert the categories imported from arXiv to INSPIRE categories
(closes #1823).
=> literaturesuggest: convert arxiv categories on import

docs/conf.py
Spin off of #1730
Since Sphinx 1.3 one does not need to use the `mock` library, but
can use a configuration variable inside of Sphinx.
=> docs: use autodoc_mock_imports

inspirehep/dojson/hep/fields/bd01x09x.py
=> dojson: fix missed double quote for docstring

inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/records/mappings/records/journals.json, tests/unit/authors/test_authors_receivers.py, tests/unit/authors/test_authors_tasks.py, tests/unit/conftest.py, tests/unit/dojson/test_dojson_utils.py, tests/unit/literaturesuggest/test_literaturesuggest_tasks.py, tests/unit/records/test_records_json_ref_loader.py, tests/unit/records/test_records_tasks.py, tests/unit/theme/test_theme_jinja2filters.py, tests/unit/theme/test_theme_views.py, tests/unit/utils/test_utils_robotupload.py, tests/unit/utils/test_utils_url.py
Closes #1868
I sketched a partial implementation of https://github.com/inspirehep/inspire-next/pull/1868#discussion_r97288690. Further uses of the `app` fixture can be found with:
```
$ ag "def test[^(]+\([^)]*app[^)]*\)" tests/unit
```
After that is done, the main commit of #1868 will be rebased on top.
=> literaturesuggest: normalize journal title names

inspirehep/modules/literaturesuggest/forms.py, inspirehep/modules/workflows/tasks/actions.py, tests/unit/workflows/test_workflows_tasks_actions.py
Fixes the key that the literaturesuggest form was using for imported
arXiv categories, which was preventing them from being sent to the
server.
Also fixes a bug in the `is_arxiv_paper` task, uncovered by the above
(closes #1893).
=> literaturesuggest: fix arXiv categories importing

tests/unit/dojson/test_dojson_hep_bd01x09x.py, tests/unit/dojson/test_dojson_hep_bd2xx.py, tests/unit/dojson/test_dojson_hep_bd6xx.py
=> tests: update/add tests for inspire-schemas v4.0

tests/unit/dojson/test_dojson_hep_bd01x09x.py, tests/unit/dojson/test_dojson_hep_bd90x99x.py
* Adds tests for fields that have been modified in a non-obvious way
between schemas versions 4 and 13: arxiv_eprints, citeable, core, document_type, publication_type, refereed, report_numbers, special_collections.
=> dojson: new tests for hep schema changes

inspirehep/modules/workflows/tasks/submission.py, tests/unit/workflows/test_workflows_tasks_submission.py
* FIX Uses the correct FFT doctype `arXiv` when sending to legacy
PDFs originated from arXiv. This is necessary in order to have
legacy hide them.
=> workflow: doctype for arXiv PDFs in FFT

tests/unit/dojson/test_dojson_hep_bd1xx.py
* Adds test for raw_affiliations.
* Also corrects wrong dojson direction in existing test.
=> dojson: test for raw_affiliations

inspirehep/config.py
* This is needed for the record editor to access the database version
of a record.
=> config: add endpoints for accessing DB records

INSTALL.rst
Version 4 of `clean-css` introduced several incompatible changes,
for which our asset pipeline is not yet ready. Meanwhile, we pin
it to version 3.
=> docs: pin clean-css version

inspirehep/modules/search/bundles.py
=> inspirehep-search-js bump version to 0.4.0

inspirehep/modules/authors/tasks.py
* Removes leftover code related to public_email which is not used anymore.
=> authors: unused public_email code removal

inspirehep/dojson/hep/rules/bd7xx.py, tests/unit/dojson/test_dojson_hep_bd7xx.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619224/
This function is severely undertested, so I expect more stuff to be incorrect.
=> dojson: notes -> material in publication_info

inspirehep/dojson/hep/rules/bd3xx.py, inspirehep/dojson/utils/__init__.py, tests/unit/dojson/test_dojson_hep_bd3xx.py, tests/unit/dojson/test_dojson_utils.py
https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619216
NB: this is discarding some data (in 133 records out of 1089353) in order to prevent exceptions that would discard 133 * 100 records. This seemed an acceptable tradeoff for this field (which doesn't look very useful anyway).
=> dojson: fix number of pages

inspirehep/modules/literaturesuggest/tasks.py
Closes #1986 
Categories that are part of the arXiv identifier are not necessarily
good categories to add: they might be outdated or no longer used.
=> literaturesuggest: remove _filter_arxiv_categories

tests/unit/conftest.py, tests/unit/dojson/test_dojson_hep_bd2xx.py
A build for https://github.com/inspirehep/inspire-next/pull/1992 failed because, after merging https://github.com/inspirehep/inspire-next/commit/b58c343efaaac237074c3df749401f6f0170ade6, the output of `langdetect` became non-deterministic because the fix in https://github.com/inspirehep/inspire-next/commit/1013b95cec26268983cb765618b52ef26c88bfb7 was no longer applied.
This PR adds it back in the form of a fixture, to be used wherever the output of `langdetect` needs to be deterministic.
=> tests: stable langdetect

setup.py
There appears to be absolutely no reason for this package to be pinned to a particular version.
=> packaging: unpin invenio-i18n

inspirehep/dojson/hepnames/rules.py, tests/unit/dojson/test_dojson_hepnames.py
Populates `ids` and `new_record` from `970__a` and `970__d`
respectively, and amends the `ids2marc` rule so that it also
populates `970` (closes #2004).
=> dojson: handle 970 in hepnames

inspirehep/modules/records/mappings/records/conferences.json, tests/acceptance/test_literature_suggestion_form.py
* Updates ElasticSearch mapping to fix conference autocompletion.
(closes #1941)
* Amends acceptance test with a more real scenario.
=> literaturesuggest: improve conference autocomplete

inspirehep/bat/pages/create_literature.py, inspirehep/modules/forms/static/js/forms/affiliations_typeahead.js, inspirehep/modules/records/mappings/records/institutions.json, tests/acceptance/test_literature_suggestion_form.py
* Adapt to data model change in institutions and use legacy_ICN instead of
ICN. (closes #1962)
=> literaturesuggest: use legacy_ICN for autocompletion

inspirehep/modules/forms/static/js/forms/inspire-form.js
Closes #2014 
Checks the status code in the fail handler because Firefox appears
to fire it anyway, even if the request was successful (closes #1947).
=> forms: prevent error message on Firefox

inspirehep/dojson/conferences/rules.py, inspirehep/dojson/hep/rules/bd1xx.py, inspirehep/dojson/hep/rules/bd2xx.py, inspirehep/dojson/hep/rules/bd4xx.py, inspirehep/dojson/hep/rules/bd6xx.py, inspirehep/dojson/hep/rules/bd7xx.py, inspirehep/dojson/hep/rules/bd8xx.py, inspirehep/dojson/hep/rules/bd9xx.py
I know that this sounds silly, but since with @michamos we were grepping the code base to find MARC fields we didn't cover I realized that we need a consistent way of expressing those, otherwise we waste time thinking we have no match...
=> dojson: use a consistent style in regexes

inspirehep/__init__.py, inspirehep/modules/arxiv/__init__.py, inspirehep/modules/arxiv/ext.py, inspirehep/modules/authors/__init__.py, inspirehep/modules/authors/dojson/__init__.py, inspirehep/modules/cache/__init__.py, inspirehep/modules/converter/__init__.py, inspirehep/modules/crossref/__init__.py, inspirehep/modules/crossref/ext.py, inspirehep/modules/disambiguation/__init__.py, inspirehep/modules/fixtures/__init__.py, inspirehep/modules/fixtures/ext.py, inspirehep/modules/forms/__init__.py, inspirehep/modules/forms/field_base.py, inspirehep/modules/literaturesuggest/__init__.py, inspirehep/modules/literaturesuggest/fields/arxiv_id.py, inspirehep/modules/migrator/__init__.py, inspirehep/modules/orcid/__init__.py, inspirehep/modules/search/__init__.py, inspirehep/modules/theme/__init__.py, inspirehep/modules/tools/__init__.py, inspirehep/modules/workflows/__init__.py, inspirehep/modules/workflows/actions/__init__.py, inspirehep/modules/workflows/proxies.py, inspirehep/modules/workflows/workflows/__init__.py
We use `__all__` when we expect users of our module to do
`from module import *`. Since this is almost always not the
case in INSPIRE, we can remove these definitions. The only
remaining uses are in `inspirehep/modules/forms/fields`,
where this assumption is true.
=> global: remove almost all definitions of __all__

inspirehep/modules/authors/forms.py, inspirehep/modules/authors/views/holdingpen.py, tests/unit/authors/test_authors_views.py
* Reads advisor degree type from correct field when importing data.
* Adds unit test for the functionality.
=> authors: advisor degree import fix

inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.controllers.js
Closes #2012
I'm not 100% sure that this works because I tested it on MacOS, where I had to remap the shortcut to Meta+A while testing, but I don't have a Linux desktop to try this right now...
=> holdingpen: prevent ctrl+a from selecting all

inspirehep/modules/forms/static/js/forms/conferences_typeahead.js
Closes #2011 
Not a satisfactory solution: we should rather be sorting at the ES level, but I couldn't figure out how to convince [`inspire_search_factory`](https://github.com/inspirehep/inspire-next/blob/454e73afb4b767f7701692ce4a1ac163f978681a/inspirehep/modules/search/query.py#L36-L69) to pass the `sort` parameter down to ES (through the API).
=> forms: sort conference suggestions by opening date

inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.directives.js, inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.services.js
* Saves changes done to the Holding Pen entry before executing an action.
(closes #1952) (closes #1953)
=> holdingpen: save changes before decision

inspirehep/modules/theme/views.py, tests/integration/test_theme_views.py
* Adds redirects to support legacy Labs URLs for author and literature
forms.
=> theme: add redirects for literature and author forms

inspirehep/modules/forms/static/js/forms/affiliations_typeahead.js
* Adds sanity check to prevent an error when a document does not have
an ICN key.
=> forms: affiliations autocomplete fix

inspirehep/modules/theme/views.py, tests/unit/theme/test_theme_views.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/820478/, https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/820479/
The email of the `current_user` is a property, not a key.
=> theme: fix feedback view

inspirehep/modules/authors/tasks.py
* Gets id from UserIdentity table instead of assigning directly the model.
Prevents a jsonschema validation error.
=> authors: formdata_to_model ORCID retrieval fix

inspirehep/config.py, inspirehep/dojson/common/rules.py, inspirehep/modules/authors/tasks.py, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/records/mappings/records/authors.json, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/workflows/mappings/holdingpen/authors.json, inspirehep/modules/workflows/mappings/holdingpen/hep.json, inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html, inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html, setup.py, tests/integration/fixtures/conference_article_expected.json, tests/integration/fixtures/journal_article_expected.json, tests/integration/fixtures/thesis_expected.json
Closes #2046 
Bumps `inspire-schemas` to version ~30.0 because they allow for the
`signature_block` field in `authors`, which is populated by Beard.
Also updates `acquisition_source` to use `datetime` instead of `date`.
=> setup: bump inspire-schemas to version ~30.0

inspirehep/modules/records/mappings/records/hep.json
Commit 1b62182 added `signature_block` to the `authors` key, but
forgot to amend the mapping correspondingly.
=> mappings: add signature_block to hep

docker-compose.test.yml
Closes #2061 
(@david-caro: please correct me if I said something wrong)
With this commit test runs from `docker-compose -f docker-compose.test.yml` will not reuse already running containers from a previous `docker-compose -d`, because the names are going to be different.
This will help preventing subtle bugs hidden by reusing configuration belonging to a previous container, and will hopefully reduce confusion when diagnosing these kind of issues.
On the other hand I expect that that is now going to fail while trying to bind two different containers (for example: `web` and `test-web`) on the same host port (for example: `5000`). So watch out for this kind of error when running the tests locally.
CC: @jmartinm @rikirenz @chris-asl @Glignos
=> docker: add test- prefix to test containers

inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py
Closes #2055 
The output of `guess_experiment` cannot currently be stored
inside of ElasticSearch because a field cannot contain both
strings and doubles.
=> workflows: comment the experiment guesser

inspirehep/modules/workflows/tasks/matching.py, setup.py, tests/integration/fixtures/journal_article_expected.json, tests/integration/workflows/test_arxiv_workflow.py
* Enabled checking even in non-production code.
* Parsing the standard format that we put on preprint_date.
=> workflows: improve earliest_date parsing and enable on devel

inspirehep/dojson/hep/rules/bd7xx.py, tests/unit/dojson/test_dojson_hep_bd7xx.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619224
=> dojson: isbn -> parent_isbn in publication_info

inspirehep/dojson/hep/rules/bd6xx.py, tests/unit/dojson/test_dojson_hep_bd6xx.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619228/
=> dojson: ensure required value in keywords

inspirehep/modules/workflows/tasks/arxiv.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820651/
Sadly without tests, because this task uses the `files` property of a `WorkflowObject`, which is very painful to mock.
=> workflows: make arxiv_plot_extract handle unicode

inspirehep/modules/authors/templates/authors/forms/new_review_accepted.html, inspirehep/modules/authors/templates/authors/forms/new_success.html, inspirehep/modules/authors/templates/authors/forms/update_success.html, inspirehep/modules/literaturesuggest/templates/literaturesuggest/forms/suggest_success.html
Removes dismiss button from suggest_success form which resulted in an empty page. 
This is the bootstrap alert with the dismiss button:
which if clicked, resulted to this:
=> literaturesuggest: remove dismiss btn from suggest_success

inspirehep/modules/workflows/actions/hep_approval.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/utils.py, tests/integration/workflows/test_arxiv_workflow.py, tests/integration/workflows/test_audit.py, tests/unit/workflows/test_workflows_tasks_actions.py
* Fixes a borked refactoring where not all variables had
been correctly renamed to relevance_prediction.
(closes #2115)
Co-authored-by: David Caro <david@dcaro.es>
=> workflows: rename to relevance_prediction

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html, setup.py
* Now the naming of the buttons better reflects what they will do
(though unfortunately, the names come from the workflows module).
* Show error stack only on error status.
=> Fixes to the workflows ui

inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
* Makes sure that what is used to derive the `earliest_date` is
actually present in the schema.
* The key `thesis` was replaced in the schema by `thesis_info`.
Fixes a bug spotted by @michamos on https://labs.inspirehep.net/api/literature/899962. Another bug that contributes to the wrong date is https://github.com/inspirehep/inspire/issues/287.
=> records: fix earliest_date receiver

inspirehep/modules/migrator/cli.py
We (luckily) don't need to deal with legacy tables anymore.
=> migrator: remove unused code in cli

inspirehep/modules/workflows/templates/inspire_workflows/index.html
* Now it's a bit less easy to confuse with new authors.
(closes #2147)
=> holdingpen: rename author updates card

inspirehep/modules/forms/validators/simple_fields.py, inspirehep/modules/literaturesuggest/forms.py, inspirehep/modules/literaturesuggest/tasks.py, tests/unit/literaturesuggest/test_literaturesuggest_tasks.py
* Do not allow a PDF to be inserted in the additional url field.
* Avoid adding two equal URLs to the record.
* Only add PDF as a link when no additional url is present. (closes #2066)
=> literaturesuggest: prevent duplicate URLs

tests/unit/theme/test_theme_jinja2filters.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_beard.py, tests/unit/workflows/test_workflows_tasks_magpie.py
The application configuration is a dictionary like object, so we can use [`patch.dict`](https://docs.python.org/3/library/unittest.mock.html#patch-dict) on it.
=> tests: refactor configuration mocking

inspirehep/modules/literaturesuggest/normalizers.py, tests/unit/literaturesuggest/test_literaturesuggest_normalizers.py
When the language is English we also don't want to have the
`title_translation` the user might have put in the form.
(As reported by @michamos)
=> literaturesuggest: also remove title_translation

setup.py
Something started failing with `selenium==3.3.2`.
Here's a passing build just before the release: https://travis-ci.org/inspirehep/inspire-next/jobs/218453576
Here's a failing build just after the release: https://travis-ci.org/inspirehep/inspire-next/jobs/218456386
=> setup: pin selenium to 3.3.1

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
* Sets a min-height to cards to allow for more content to fit inside
if needed.
=> holdingpen: remove fixed height from dashboard cards

inspirehep/dojson/hep/rules/bd3xx.py, inspirehep/dojson/hepnames/rules.py, inspirehep/dojson/utils/__init__.py, inspirehep/modules/refextract/tasks.py, inspirehep/utils/helpers.py, tests/unit/dojson/test_dojson_utils.py, tests/unit/refextract/test_refextract_tasks.py, tests/unit/utils/test_utils_helpers.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820882/
=> refextract: handle year an empty string

inspirehep/modules/workflows/tasks/actions.py, tests/unit/workflows/test_workflows_tasks_actions.py
Closes #2163 
Splits some logic into `is_auto_rejected` to improve readability
and testability, and documents its complete expected behavior with
tests.
=> workflows: refactor is_record_relevant

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/batch-actions.html
Commit 5ead604 clarified the labels that appear in the detailed
record view, but forgot to update correspondingly the labels of
the batch actions buttons.
=> workflows: fix batch actions buttons

inspirehep/config.py
* Upon authentication, defaults to login form instead of registration
form.
(closes #2196 )
=> orcid: default to login form

inspirehep/modules/theme/static/scss/base/core.scss, inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html, inspirehep/modules/theme/templates/inspirehep_theme/page.html
* Fixes template so that editor can take 100% height.
* Adds new Jinja2 variable hide_external_link_icons that will avoid
showing external link icons on a given page.
=> editor: index template amendments

inspirehep/modules/forms/validators/simple_fields.py, tests/unit/forms/test_forms_validators_simple_fields.py
Makes `pdf_validator` less strict by accepting not only links that
point to resources whose reported `Content-Type` is `application/pdf`
by checking whether the first few bytes of the pointed resource are
`%PDF` (closes #1057).
=> forms: make pdf validators less strict

inspirehep/dojson/hep/rules/bd6xx.py, tests/unit/dojson/test_dojson_hep_bd6xx.py
This is a stopgap solution requested by @ksachs during standup yesterday before we properly implement https://github.com/inspirehep/inspire-next/issues/2216.
=> dojson: don't export magpie keywords

.travis.yml, docker-compose.test.yml, docs/tests.rst
Closes #2045 
Adds the `visible_acceptance` test suite, and makes the
`acceptance` test suite the default on Travis.
=> tests: add visible_acceptance test suite

pytest.ini, setup.py
Uses `flake8-future-import` to make sure that all Python files
import exactly `absolute_import`, `division`, `print_function`
from `__future__`, preventing a regression on #1838.
=> tests: enforce future imports through flake8

requirements.txt, setup.py
Spin off of #2138. Reducing packages installed through `git` makes sense independently of bumping Celery (which looks like it might take some time).
=> packaging: use released Flask_CeleryExt

inspirehep/config.py
=> orcid: use non-deprecated OAuth scopes

inspirehep/modules/authors/__init__.py, inspirehep/modules/forms/fields/__init__.py, inspirehep/modules/forms/validators/__init__.py, inspirehep/modules/orcid/__init__.py, inspirehep/modules/records/__init__.py, inspirehep/modules/search/parser.py, inspirehep/modules/theme/__init__.py, inspirehep/modules/workflows/__init__.py, pytest.ini, tests/unit/theme/test_theme_jinja2filters.py
Fixes the PyFlakes errors about star imports. Some are still there,
because they actually serve as a primitive implementation of entry
points (closes #1835).
=> global: fix F403 and F405

inspirehep/modules/migrator/tasks/records.py, setup.py
* Introduces a redis-based lock to continuous_migration() so that
no two continuous_migration() tasks are executed at the same time.
=> migrator: lock continuous_migration

inspirehep/modules/records/mappings/records/hep.json
Commit 330e90e forgot to update the mappings to stay in sync with
the corresponding schema changes. This resulted in an incompatible
type for `persistent_identifiers` in `references`: formerly a list
of strings, now a list of objects.
=> records: amend mappings for inspire-schemas~=31.0

inspirehep/config.py, inspirehep/modules/records/mappings/records/authors.json, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/receivers.py, inspirehep/modules/search/bundles.py, tests/unit/records/test_records_receivers.py
* Create mapping fields especially for search-facets (with 'no_analyzed',
stemmed versions aren't useful for user-facing text) and ensure naming
consistency for fields used in 'config.py' (i.e. 'facet_X').
=> records: fix hep & authors search facets

inspirehep/dojson/conferences/rules.py, inspirehep/dojson/hep/rules/bd7xx.py, inspirehep/modules/references/processors.py, tests/unit/dojson/test_dojson_conferences.py, tests/unit/dojson/test_dojson_hep_bd9xx.py, tests/unit/references/test_references_processors.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/821839, https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/618717
First commit simplifies some convoluted code that had so far escaped refactoring.
Second commit implements a small thing I need for HAL.
Third commit fixes a long-standing bug in `conferences`.
=> references: remove version from arxiv_eprint 

inspirehep/modules/search/api.py, tests/integration/test_records.py
Closes #2302 
Catch `RequestError` from ES to prevent the application from crashing
when no documents are found in an `mget` request, but log this
exception when it happens (addresses #2300).
=> search: prevent error when no documents found in mget

setup.py
#2238 was fixed by inveniosoftware-contrib/invenio-workflows#40,
but the latest version of `invenio-workflows` must be installed
in order to fix the problem in production as well.
CC: @jmartinm
=> setup: bump invenio-workflows

inspirehep/modules/forms/validators/simple_fields.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/classifier.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/utils.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/utils/helpers.py, inspirehep/utils/url.py, tests/integration/workflows/test_arxiv_workflow.py
Closes #2283 
Uniformizes the handling of PDFs within workflows between user
submissions and arXiv harvesting (closes #2255).
Consistently checks if PDFs are PDFs by centralizing the usage
of `is_pdf_link` (and basing the check only on the file's magic
number rather than on the mimetype reported by the server).
=> workflows: refactor file handling

tests/unit/helpers/mocks.py, tests/unit/workflows/test_workflows_tasks_arxiv.py, tests/unit/workflows/test_workflows_tasks_submission.py, tests/unit/workflows/test_workflows_tasks_upload.py
Addresses #1773 
It makes little sense to unit test [`store_record`](https://github.com/inspirehep/inspire-next/blob/5fdbd8bf4ac6bd984406719b6a3d0c91b0b4cf77/inspirehep/modules/workflows/tasks/upload.py#L39-L62), so I skipped that.
=> tests: unit tests for workflows/tasks/upload

setup.py
Closes #2319 
As detailed in inspirehep/inspire-next#2319, we can now remove
this pin as it was a workaround to avoid a bad wheel that we
were caching in the Docker image.
=> setup: remove pin on coverage

INSTALL.rst
Closes #1911 
Remove `pip` from the package list as it is installed
automatically within `virtualenv` and should not be
required globally.
Add alternatives for installing `npm` globally inside the
`virtualenv` and setting up the `virtualenv` independently
from the `git` repository. One use case where this comes in
handy is when switching from Python 2.7 to Python 3, since
you can set up two environments and switch between them as
you need while working on the same code.
=> docs: update install guide

inspirehep/modules/migrator/tasks/records.py
Closes #2262 
Sentry 6 has trouble clustering log messages that are too long.
Now that the schema contains descriptions we hit this limit, so
we need to shorten the string we log when encountering an error.
=> migrator: shorten the validation errors for Sentry

inspirehep/config.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Closes #2338 
We have a verbal agreement with arXiv that we should use the
former instead of the latter to avoid throttling.
=> config: use export.arxiv.org instead of arxiv.org

inspirehep/utils/url.py
Uses the first line instead of the first four bytes because,
sometimes, the server might reply with fewer bytes than four.
In particular this happens for the following PDF: http://edok01.tib.uni-hannover.de/edoks/e01dh15/815761511.pdf, as reported by one of our users: https://rt.inspirehep.net/Ticket/Display.html?id=717918
We have the following curious behavior:
```python
>>> from requests import get
>>> response = get('http://edok01.tib.uni-hannover.de/edoks/e01dh15/815761511.pdf', stream=True)
>>> next(response.iter_content(4))
'%PD'
```
Note also, quite perplexingly, that:
```python
>>> from requests import get
>>> response = get('http://edok01.tib.uni-hannover.de/edoks/e01dh15/815761511.pdf', stream=True)
>>> iter = response.iter_content(1)
>>> next(iter)
'%'
>>> next(iter)
'P'
>>> …
```
=> utils: use first line to get magic number

inspirehep/modules/workflows/utils.py, tests/unit/workflows/test_workflows_utils.py
Addresses #2337 
The `requests` library rewraps all `urllib3` exceptions with their own classes.
=> workflows: catch the right exception

inspirehep/modules/workflows/tasks/arxiv.py
Closes #2371 
Closes #2372 
Makes so that actual files are attached as plots, and not the
string representations of their file descriptors.
=> workflows: fix arxiv_plot_extract

docker-compose.deps.yml, docker-compose.test.yml, docker-compose.yml, services.yml
* The venv dir must be created before mounting to avoid the docker
daemon from creating it, as it does as root no matter what.
=> docker: adapt to non-root user

setup.py
This build broke because `requests==2.15.0` was a bad version: https://travis-ci.org/inspirehep/inspire-next/builds/236661038
The [current build](https://travis-ci.org/inspirehep/inspire-next/builds/236879618) instead breaks because `requests~=2.16.5` has changed significantly how exception handling happens in `requests`.
=> setup: pin requests and docutils

inspirehep/config.py, inspirehep/modules/forms/static/js/forms/journals_typeahead.js, inspirehep/modules/records/mappings/records/journals.json, inspirehep/modules/records/receivers.py, tests/acceptance/test_literature_suggestion_form.py, tests/unit/records/test_records_receivers.py
* Add suggester for journal title in journal-records. Input is the full
title, title variants and short titles. Output is the first short
title and payload is full journal title. (closes #2120)
Co-authored-by: George Lignos <glignos93@gmail.com>
=> records-journals: add journal title suggester

inspirehep/modules/records/mappings/records/hep.json
Fields that contain external identifiers need to have a raw variant
to support aggregations and exact searches. This commit adds it to
`arxiv_eprints` and `dois`, but not to other fields (notably, `isbns`
and `report_numbers`) because the data contained in them contains
small typos and irregularities that we need to account for.
=> mappings: add raw fields to some external ids

inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.filters.js
Prevents an error that happens when `ng-repeat` is passed the same
category multiple times (closes #2383).
Closes #2383 
Closes #2399
=> holdingpen: pass unique categories to ng-repeat

inspirehep/modules/records/mappings/records/authors.json, inspirehep/modules/records/mappings/records/conferences.json, inspirehep/modules/records/mappings/records/experiments.json, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/mappings/records/institutions.json, inspirehep/modules/records/mappings/records/jobs.json, inspirehep/modules/records/mappings/records/journals.json
Since commit 8b0ecbe, when sending records to Elasticsearch we enrich
their JSON refs with the recid they are pointing to. This commit adds
those recids explicitly to the mappings. In fact, Elasticsearch could
easily generate their mappings from the data, but we prefer to state
this constraint explicitly so that in the future we may disallow the
automatic inference of mappings.
The only exception is the `conferences` key in the Authors collection:
this key is currently unused and might be removed in a future version
of the schema.
=> mappings: add recids from refs to mappings

inspirehep/modules/workflows/tasks/submission.py, tests/unit/helpers/mocks.py, tests/unit/workflows/test_workflows_tasks_submission.py
=> tests: unit tests for workflows/tasks/submission

scripts/clear_pycache
Since commit 386d150 we should no longer need to be root to remove
files cached by Python.
=> scripts: remove sudo from clear_pycache

inspirehep/dojson/hep/rules/bd7xx.py, tests/unit/dojson/test_dojson_hep_bd7xx.py
https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822408/
=> dojson: make publication_info2marc handle unicode

inspirehep/modules/workflows/utils.py, tests/unit/workflows/test_workflows_utils.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822046/
Closes #2355
=> workflows: make json_api_request fault-tolerant

services.yml
Currently on production we are using this particular version, offered
by CERN's DB on Demand service. To ensure that we don't introduce code
that depends on future features of PostgreSQL, which would break on
production, this commit pins its Docker image to that specific version.
=> docker: pin postgres to 9.4.5

inspirehep/modules/xrootd/__init__.py, inspirehep/modules/xrootd/ext.py, setup.py
Copies from Zenodo the XRootD integration. Unfortunately this is not testable on Travis. However by default, mocking XRootD is equivalent to having it disabled. So the real test will happen hopefully on QA.
Closes #1086
Currently we are using Fuse-mounted EOS on production and this has many stability and performance issues. Hopefully by switching to XRootD (which is the
native interface of EOS) will allow INSPIRE to use EOS following its original design, i.e. a blob-store, rather than a POSIX filesystem. This should, hopefully improve performance issue (if not also stability issues), at least within the workflow files.
* Copies from Zenodo the integration with XRootD, to be used as
storage, instead of Fuse-mounted EOS.
(closes #1086)
=> xrootd: first commit

setup.py
* This uses the format `~=[major].0,>=[major[.feat[.minor]]]` to all
the major version pins, as we were using the bad
`~=[major].[feat].[minor]` in some places, actually pinning to the
feature version.
Closes #2420
=> setup: harmonize the major version pins

.gitignore, docs/Makefile, docs/conf.py, docs/index.rst
Moves the generation of the api rst files to the conf.py file, as
readthedocs.io does not run the makefile.
Closes #2438
The api docs were not being generated.
=> docs: generate the api docs at conf.py

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py, setup.py
Worksaround inspirehep/refextract#26 by interrupting the running away
refextract process.
=> workflows: timeouts refextract

setup.py
We need to exclude the `xrootd` extra from `all` otherwise the build of
`inspire-docker` will try to install it, but `xrootdpyfs` requires a
dependency which is not available on PyPI.
https://travis-ci.org/inspirehep/inspire-docker/builds/243212256
=> setup: fix inspire-docker build

inspirehep/config.py, inspirehep/dojson/hep/rules/bd6xx.py, inspirehep/dojson/hep/rules/bd9xx.py, inspirehep/modules/records/mappings/records/experiments.json, inspirehep/modules/records/mappings/records/hep.json, setup.py, tests/unit/dojson/test_dojson_hep_bd6xx.py, tests/unit/dojson/test_dojson_hep_bd9xx.py
INCOMPATIBLE `energy_ranges` changes mapping type from `integer`
to `string`, so this commit will require a reindex.
CC: @ammirate @david-caro @jmartinm @kaplun 
Closes https://github.com/inspirehep/inspire-next/issues/2429
=> global: bump inspire-schemas to version ~36.0

inspirehep/dojson/institutions/rules.py, tests/unit/dojson/test_dojson_institutions.py
=> dojson: ignore name_variants with DESY source

.travis.yml, docker-compose.test.yml, docker-compose.yml, tests/acceptance/conftest.py, tests/integration/conftest.py
* This requires getting docker-compose > 1.10
* This makes the dependent containers wait for the dependencies to be
in a healthy state before starting.
* As we are sure now that ES is already healthy before running the
tests, there's no point on doing a sleep to wait for it to be up.
=> tests: get rid of es waits by adding health checks

docker-compose.test.yml, docker-compose.yml
Since version 9.3, PostgreSQL ships with a utility to check the
connection status of a database. For more information, please see
https://www.postgresql.org/docs/9.3/static/app-pg-isready.html
=> docker: simplify database health check

inspirehep/modules/authors/receivers.py, tests/unit/authors/test_authors_receivers.py
The function `assign_phonetic_block` is handling the case missing phonetic blocks putting `None`. This kind of behavior is not schema compatible
Closes https://github.com/inspirehep/inspire-next/issues/2462
=> authors: fix the signature_block assignment 

.travis.yml
Currently we are leaving the code directory as owned by id 1000,
though the travis runners use uid 2000. That prevents coverage from
reading the coverage file.
* This should fix the current coverage issues where the report does
not show up.
=> travis: restore the permissions to the correct uid

inspirehep/config.py, inspirehep/modules/records/mappings/records/experiments.json, inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
This receiver was briefly needed for a demo, but now is causing trouble
during migration because some experiments don't have a `long_name`.
=> records: remove experiment_suggest receiver

docker-compose.test.yml, docker-compose.yml
Sometimes the docker container for the indexer does not go fully to
the green state, and remains in yellow state, but that's good enough
for us.
It was being too strict in the health check, and not allowing the
indexer to be in yellow status.
=> docker: allow yellow status indexer

inspirehep/dojson/conferences/rules.py, tests/unit/dojson/test_dojson_conferences.py
First commit fixes a bug in `alternative_titles`, second commit fixes a bug in `contact_details`. All the remaining problems in this collection are tracked in https://github.com/inspirehep/inspire/issues/304.
=> dojson: fix conferences

inspirehep/modules/migrator/tasks/records.py
* Adds expiration time to the redis lock to avoid a situation where
the process crashes and the lock will remain.
* Sets auto_renewal=True so that while a process has the lock acquired
and is executing code, the lock will not expire.
=> migrator: avoid indefinite locking of continuous migration

inspirehep/dojson/common/rules.py, inspirehep/dojson/experiments/rules.py, tests/unit/dojson/test_dojson_experiments.py
DoJSON doesn't allow to have two rules defined on the same regular
expression, so the rule for `core` was hiding the rule for `deleted`.
=> dojson: fix deleted in experiments

docs/conf.py, docs/dev_flow.rst, setup.py
Napoleon is a Sphinx extension since Sphinx 1.3, so that can be used
instead of the `sphinxcontrib-napoleon` external dependency.
=> docs: use Sphinx-bundled Napoleon

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html
* Fixes off-by-one error when styling the number of core keywords.
=> holdingpen: number of classifier results display fix

inspirehep/modules/workflows/tasks/arxiv.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Downloaded pdf files from arxiv, sometimes were wrong recognized by
`invenio-files-rest` as mimetype 'application/pdf' but the content
was html. Therefore, `refextract` was correctly raising an exception.
For this reason, the check of mimetype was made more strict before
downloading the file.
(Closes #2523)
#2523
=> arxiv: Fix wrong mimetype for arxiv pdfs

inspirehep/bat/EC.py, inspirehep/bat/pages/create_author.py, inspirehep/bat/pages/holding_panel_author_detail.py, inspirehep/bat/pages/holding_panel_author_list.py, inspirehep/bat/pages/holding_panel_literature_detail.py, inspirehep/bat/pages/holding_panel_literature_list.py
* Add a new EC (expected condition) that's more stable to wait for the
text of an element.
* Use it in the author tests to get rid of the flakiness.
=> acceptance: use a more stable EC for authors

inspirehep/celery.py, inspirehep/cli.py, inspirehep/wsgi.py
* Disable backoff log propagation up to Sentry, not to pollute
Sentry log aggregation.
=> logging: backoff not in Sentry

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/fixtures/1707.02785.html, tests/unit/workflows/test_workflows_tasks_arxiv.py
* Checks whether the PDF actually exists on arXiv before trying
more and more to download it.
=> arxiv: check PDF actually exists

inspirehep/config.py
* Sets a good default for where to look an already built
journal-titles.kb needed by refextract.
NOTE: the REFEXTRACT_JOURNAL_KB_PATH configuration variable should
be changed on production.
=> config: default journal-titles.kb path

inspirehep/bat/pages/create_author.py
Fixing problem with acceptance tests, when some of the tests were getting stuck because it was trying to execute `show_title_bar()` in `submit_author()` when the page was not fully loaded
Closes #2518 
To avoid acceptance tests getting stuck.
=> tests: wait until page load in author submission

inspirehep/modules/workflows/tasks/actions.py
We don't need the `max_score` to be positive when rejecting a record:
it's enough that we couldn't find any CORE keywords in it and the ML
algorithm thinks it should be rejected.
Closes #2414 and Closes #2566
=> workflows: ignore max_score when rejecting

inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html
* Removes super() call in css block to avoid conflicts between
record-editor css and global INSPIRE css.
* Adds invenio-record-editor css bundle.
=> editor: index page changes

inspirehep/utils/url.py, tests/unit/utils/test_utils_url.py
* Avoid raising Stopiteration when response is empty. (closes #2589)
=> utils: is_pdf_link sanity check

setup.py
Reverts 81d5b1e because `requests==2.18.3` now allows `urllib==1.22`.
=> setup: unpin urllib3

inspirehep/modules/workflows/tasks/actions.py
* This adds a nice docs (including the params they were called with)
to the mark workflow step and other similar ones.
=> workflow: use nicer docstrings for mark and others

inspirehep/modules/workflows/ext.py, inspirehep/modules/workflows/views/callback.py
Now the errors from the callback results from legacy are properly
handled (at least, more usefully).
*NOTE*: The tests will come after the workflow tests refactor.
See #2466
When we receive an error from legacy, now the workflow is set to
'ERROR' status and the callback error message is added to the
`_error_message` so it gets shown in the holdingpen.
Closes #2083 and closes #2397.
Now it will set the workflow in error state and put the message of the
robotupload error on it so it can be viewed from the ui and restarted
if needed.
Also avoids using the recid `-1` completely, leaving the pending
records table coherent.
=> workflows.callbacks: handle robotupload errors

inspirehep/modules/forms/validators/simple_fields.py, inspirehep/modules/literaturesuggest/forms.py, tests/unit/forms/test_forms_validators_simple_fields.py
I introduced some validation for the "year" field in the Article/Conference paper submission form.
I implementing a validator for the "year" field. So, right now the UI complains when the introduced year is invalid and displays a warning field asking the user for a valid year instead.
Closes https://github.com/inspirehep/inspire-next/issues/2591
When submitting an Article/Conference paper with an invalid year (i.e. not 1000 - 2050),
the user was redirected to an error message that did not specify the cause.  The user found it hard to understand what was wrong and has to go back and complete the form again.
=> literaturesuggest: add year validation

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_tasks_submission.py
This reverts commit 25501fba66bdffbdb72e338591f7467b263944e7.
We need to properly handle the journal letter issue and be able to match
references before we can export reliable reference lists to legacy.
=> workflows: remove references before legacy export

inspirehep/modules/authors/tasks.py, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/refextract.py, inspirehep/modules/workflows/tasks/submission.py
As I said a little while ago to @david-caro, some of our workflow tasks where missing the `@with_debug_logging` decorator.
=> global: add missing with_debug_logging decorator

inspirehep/bat/pages/create_author.py, tests/acceptance/test_author_creation.py
Commit 1e571aa is already testing this logic and is much faster.
Addresses https://github.com/inspirehep/inspire-next/issues/1987.
=> tests: remove year validation tests

inspirehep/modules/workflows/workflows/article.py
Changed the workflow for harvested arXiv records to generate a RT curation ticket
when selected as 'core'.
Previously, a RT curation ticket was generated only for 'core' submissions.
Closes https://github.com/inspirehep/inspire-next/issues/2584
=> workflows: create ticket for core arXiv records

inspirehep/modules/workflows/views/callback.py
* Instead of checking if the record id returned is already in the
pending list first thing when getting the robotupload results, check
first if there were any errors, as on some errors the id returned is
invalid.
Just saw on labs a record that had the error 'record already exists
in the pending list', when the underlying error was that the record
already exists on inspire itself (returning id -1), so it should not
be masked.
=> robotupload: treat the errors before checking dups

tests/integration/api/v1/test_authors.py, tests/integration/api/v1/test_experiments.py, tests/integration/api/v1/test_institutions.py, tests/integration/api/v1/test_journals.py, tests/integration/api/v1/test_literature.py, tests/integration/test_author_api.py, tests/integration/test_citation_counts.py, tests/integration/test_datatable_citations.py, tests/integration/test_datatable_references.py, tests/integration/test_detailed_records.py, tests/integration/test_impact_graphs.py, tests/integration/test_other_conferences.py, tests/integration/test_pidstore.py, tests/integration/test_records.py, tests/integration/test_search_views.py, tests/integration/test_serializers.py, tests/integration/test_theme_views.py
The `app`, `app_client`, and `api_client` fixtures already provide the
right contexts, so there's no need to explicitly instantiate one.
This is done everywhere except in `orcid`, where the app fixtures are
defined in an obsolete fashion, and `workflows`, where it's possible
they might conflict too much with in-flight PRs.
=> tests: use the right fixtures almost everywhere

inspirehep/modules/workflows/tasks/matching.py
* We were doing a query that never returned any results, so we thought
the records were new when checking for their existance in the legacy
system.
We were seeing duplicated records being submitted to legacy, this is
the first guess towards answering why.
=> workflows.matching: fix legacy existance check

inspirehep/modules/workflows/tasks/actions.py
Commit b4e496a didn't achieve its stated purpose as it was populating
the wrong attribute, and the message is anyway better suited for it.
=> holdingpen: nicer halt message

docs/conf.py, inspirehep/modules/refextract/tasks.py, setup.py, tests/integration/refextract/test_refextract_tasks.py
Expands the task that populates the Knowledge Base used by refextract
to also use the `short_title` and the `journal_title`.
Adds the `celery.contrib.sphinx` extension to Sphinx in order to also
generate docs for Celery tasks.
This requires to pin the version of Sphinx to a lower version as there
is currently an API incompatibility with this extension and the latest
version of Sphinx.
Closes #2612 and closes #2613
=> refextract: also use journal_title and short_title

inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/tasks.py
The solution attempted in 16e9cb9 didn't work as that receiver was
detached by the Python interpreter executing the CLI command, not
the one executing the task code in the worker.
Fixes the performance issue caused by invenio-collections by detaching
its receiver during migration. Its work, in fact, is already handled
by inspire-dojson since inspirehep/inspire-dojson#62.
Closes https://github.com/inspirehep/inspire-next/issues/1640
=> migrator: detach receivers during migration

inspirehep/modules/authors/permissions.py, inspirehep/modules/editor/permissions.py, inspirehep/modules/records/permissions.py
* Since DynamicPermission is deprecated in invenio-access, moves
usages to the recommended Permission class.
=> permissions: move DynamicPermission to Permission

inspirehep/modules/hal/core/tei.py, inspirehep/modules/hal/templates/hal/art.xml, inspirehep/modules/hal/templates/hal/comm.xml
The `org` tags must appear, according the the XML schema, inside
of a `particDesc` tag.
Because of a runaway comma `conference_start_date` resulted in a tuple,
whose string serialization in the template resulted in an invalid date
for all comm records.
=> hal: fix issues during second push

setup.py, tests/integration/test_pidstore.py, tests/unit/authors/test_authors_receivers.py, tests/unit/forms/test_forms_validators_simple_fields.py, tests/unit/utils/test_utils_robotupload.py, tests/unit/workflows/test_workflows_tasks_arxiv.py, tests/unit/workflows/test_workflows_tasks_submission.py
Replaces all uses of `httpretty` with `requests_mock`, since the
former has bugs that the author has declared he's not going to
fix and it probably won't ever support Python 3 (closes #2354).
=> tests: httpretty -> requests_mock

inspirehep/modules/refextract/tasks.py, tests/integration/refextract/test_refextract_tasks.py
Avoids generating lines like `---DESTINATION`, and makes the code a
little bit more robust.
Closes #2732.
=> refextract: fix create_journal_kb_file

inspirehep/modules/workflows/tasks/arxiv.py, setup.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Rather than using local .tar directory (currently on a networked
filesystem) as a scratch space for extracting plots and author.xml
file, uses a temporary local directory that is cleaned up at the end.
=> workflows: use local scratch space

setup.py
There are no longer tasks in `inspirehep.modules.authors`, but there
were undeclared tasks in `inspirehep.modules.migrator`.
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822729/
=> setup: fix celery entrypoint

setup.py
Fixes the build by pinning `simplekv` since a new version of it
appears to be incompatible with Python 2.
=> setup: pin simplekv

inspirehep/modules/editor/views.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py, inspirehep/utils/references.py, tests/unit/editor/test_editor_views.py
`refextract` was sometimes being called without the right arguments (by
the editor and `extract_journal_info` in the workflows) resulting in the
static journal KB shipped with refextract being used instead of the
dynamic one and/or the publication info being produced in an incorrect
format.
=> refextract: pass correct options everywhere

setup.py
We can remove this pin as `simplekv` is already pinned by the latest
version of `invenio-accounts`
Closes #2749.
=> setup: unpin simplekv

inspirehep/config.py, inspirehep/modules/migrator/tasks.py, inspirehep/modules/theme/ext.py
Because we are instantiating `invenio-collection` two times, we can't
have it register its signals on instantiation, as we end up with the
same signal registered twice and no way of unregistering one of them.
Therefore, we don't need to unregister them during migration, as they
were never registered in the first place.
Closes https://github.com/inspirehep/inspire-next/issues/2770
=> config: don't register invenio-collection signals 

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_submission.py
* After inspirehep/inspire-schemas#231 and inspirehep/inspire-dojson#94, the information about whether the record has been curated can be completely handled by means of the `curated` flag.
=> workflows: don't add curation status notes

setup.py
We can remove this pin as `node-semver` is already pinned by the
latest version of `invenio-assets` (closes #2750).
Closes #2750
=> setup: unpin node-semver

inspirehep/modules/editor/views.py, inspirehep/modules/tools/__init__.py, inspirehep/modules/tools/templates/authorlist_form.html, inspirehep/modules/tools/utils.py, inspirehep/modules/tools/views.py, setup.py, tests/unit/editor/test_editor_views.py, tests/unit/tools/test_tools_utils.py
The authorlist tool is used by catalogers to parse author lists from PDFs (similar to refextract, but for authors instead of references). It used to produce MARC directly that could be pasted into bibedit.
Now it produces an inspire 3 record instead, that is seralized into MARC for legacy use but can also be used directly by the editor (@harunurhan, could you check that the editor API is OK for you?).
=> editor: add /authorlist/text view

inspirehep/modules/workflows/actions/hep_approval.py, tests/integration/workflows/test_hep_approval.py
* When handling the user action from the Holding Pen page, the
checkbox to remove the user PDF was not being handled. (closes #2725)
=> workflows: handle client request to remove PDF

inspirehep/modules/converter/stylesheets/authorlist2marcxml.xsl
This fixes a bug where non-ORCID IDs were put in the wrong field.
Same as https://github.com/inspirehep/invenio/pull/425
=> converter: update authorlist2marcxml stylesheet

docker-compose.deps.yml
Commit 0ffd8c0 forgot to add the ``--upgrade`` flag, which is essential
to use ``docker-compose -f docker-compose.deps.yml run --rm pip``as the
only command to deal with dependencies during development.
=> docker: also upgrade dependencies in pip command

inspirehep/modules/editor/permissions.py, inspirehep/modules/editor/views.py, inspirehep/modules/fixtures/users.py, setup.py, tests/integration/editor/test_editor_views.py
Adds permission to access editor API endpoints that do not require checking the record collections.
=> editor: add general API permission

tests/acceptance/conftest.py
Commit a863384 introduced Flake8 checks on indentation, but missed the
one fixed in this commit because `acceptance/conftest.py` is no longer
part of either ``acceptance-authors`` or ``acceptance-literature``.
=> tests: fix flake8 error in acceptance/conftest.py

inspirehep/modules/records/serializers/impactgraph_serializer.py, inspirehep/utils/citations.py
inspirehep/inspire-query-parser#30 removed support for ``refersto:``,
so we will have to rewrite these queries using ``references__recid``.
=> global: don't use refersto in queries

inspirehep/modules/editor/permissions.py, tests/integration/editor/test_editor_views.py
* When a permission is cached, return a response object instead of
a boolean.
=> editor: permission decorator cache fix

inspirehep/modules/authors/views.py, inspirehep/modules/forms/fields/language.py, inspirehep/modules/forms/fields/title.py, inspirehep/modules/workflows/tasks/classifier.py, inspirehep/wsgi.py
Imports inside of functions make static code analysis impossible, as you must be running the code to know which names are defined when a certain line is running.
This PR doesn't remove all of them, as some are still happening in the `workflows` module, but I avoided touching those to not cause merge conflicts with @ammirate's PR.
=> global: remove internal imports

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_refextract.py
Runs ``refextract`` on both the PDF in the workflow and the references
provided by the submitter, if any, then chooses the one that generated
the most and attaches them to the workflow object.
https://github.com/inspirehep/inspire-next/issues/2587
Previously references in the textbox were ignored and the curator had to copy/paste the references again in bibedit on legacy which is not efficient in terms of time.
=> workflows: also run refextract on the textbox refs

inspirehep/modules/records/mappings/records/hep.json
I set 'include_in_all' for the 'references' field of Literature collection records to false. I concluded that this was the right thing to do as follows:
1. I ran the search and noticed the high number of results
2. I copied the query which was available in the console in DEBUG mode
3. I opened Sentry and accessed the _explain endpoint in ES with the query
4. I investigated and noticed that most hits/matches occured in the '_all' which also contains the values from the  'references' field, specifically from 'full_name' in our case
5. I concluded that this is not what we need to happen as these matches are rather spurious, thus I configurated ES so that it shall not add the 'references' to '_all' by setting the 'include_in_all' field to false (by default it is true) int the Literature …
=> mappings: exclude references from _all in hep

inspirehep/config.py, inspirehep/modules/fixtures/files.py, inspirehep/modules/records/api.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/tasks/upload.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/test_records.py, tests/unit/helpers/mocks.py, tests/unit/workflows/test_workflows_tasks_arxiv.py, tests/unit/workflows/test_workflows_tasks_submission.py
Adds the ``files`` property to ``InspireRecord`` by inheriting from the
``Record`` of ``invenio_records_files``. This allows us to attach plots
and documents to records (closes #2551 and closes #2552).
Also modifies those workflows tasks that deal with records so that they
use builder methods to populate the ``documents`` and ``figures`` keys,
and those will then be converted by DoJSON to the ``FFT`` fields that
Legacy understands.
Closes #2551 and closes #2552.
=> global: handle files between records and workflows

inspirehep/modules/workflows/actions/hep_approval.py, tests/integration/workflows/test_hep_approval.py
Deletes from workflow data the corresponding document
that was marked as not attached. Currently the file was
deleted from `obj.files` but the `documents` metadata were
not cleaned. This was leading to creating `FFT` for a file
that was already deleted.
https://github.com/inspirehep/inspire-next/issues/2873
=> submission: Handle correctly the files in hep approval

inspirehep/modules/workflows/mappings/holdingpen/hep.json
Fixes: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/931989/
* Disables indexing of record_matches, which is not needed and has
changed type in a 6e8432a thus making impossible to index
both entries before the commit and after it.
=> holdingpen: do not index record_matches

inspirehep/modules/authors/utils.py, inspirehep/modules/theme/views.py, inspirehep/utils/bibtex.py, inspirehep/utils/latex.py, setup.py
Removes the pin introduced in 71c01de as the latest version of
``pytest-flake8`` is again compatible with the latest version
of ``flake8``.
=> setup: unpin flake8

inspirehep/modules/theme/jinja2filters.py, tests/unit/theme/test_theme_jinja2filters.py
Ensure jinja2filters:back_to_search_link handles unicode titles
(addresses #2133).
=> jinja2filters: back_to_search_link handle unicode

.travis.yml
Pulls the Docker images in parallel as local testing has shown that it
speeds up the process by 40%. Also deletes the build step as it's not
needed, since we only pull pre-built images.
=> travis: pull Docker images in parallel

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Some arXiv records just don't have a tarball, as they are allowed to
have anything there, so we shouldn't log an error whenever we don't
see one.
Note also that logging an error eats rapidly into our ``sentry.io``
quota, as we see roughly a thousand such events per day per instance.
https://sentry.io/inspirehep/inspire-prod/issues/388912388/
https://sentry.io/inspirehep/inspire-qa/issues/388908905/
=> workflows: decrease log level for invalid tarball

inspirehep/config.py, inspirehep/modules/api/__init__.py, inspirehep/modules/api/v1/__init__.py, inspirehep/modules/api/v1/common_serializers.py, inspirehep/modules/records/mappings/records/jobs.json, tests/integration/api/v1/test_common_serializers.py
* Add api and v1 packages.
* Add recids serializer for all main collection endpoints (addresses
#2840).
Provides a way to request record ids by using the search for main collections. 
Currently required by the editor.
=> api: add v1 recids serializer

inspirehep/modules/migrator/cli.py
Ensure response status code is checked before proceeding with a
migration. The problem was that if a request fails, the error was
undetected as the `response.content` contained an HTML page describing
the error.
When requesting a migration for one record, if the request failed for some reason you couldn't see the failure. 
For example, when requesting for a record from legacy, response.content was
```
'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html>  
<head>\n<title>502 Proxy Error</title>\n</head>  
<body>\n<h1>Proxy Error</h1>\n  
<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />  
\r\nThe proxy server could not handle the request <em>  
<a …
```
=> migrator: use raise_for_status in one command

inspirehep/config.py, inspirehep/modules/authors/rest/stats.py, inspirehep/modules/records/mappings/records/hep.json
Rename facet_inspire_subjects so it follows the field it takes its
value from, i.e. facet_inspire_categories.
The goal is to ensure uniformity in naming several mappings fields.
As we discussed with @jacquerie IRL, mappings naming can be improved (e.g. has inconsistencies). 
The goal is to gather (in time) some naming schemes/guidelines for anyone editing the mappings to follow.
For example, this PR is fixing the inconsistency of `facet_inspire_subjects` which got its values from `inspire_categories`.
=> mappings: rename facet_inspire_subjects

inspirehep/modules/records/api.py, tests/integration/records/test_records_api.py
This ensures that we have a single implementation of schema
validation (for constraints that do not require a DB) and
that we validate ``format``s.
=> records: use validate from inspire_schemas

tests/integration/workflows/helpers/calls.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/helpers/mocks.py, tests/unit/workflows/test_workflows_tasks_matching.py
Provide explicitly  ARXIV categories to tests by mocking the flask application.
This change is required in order for the tests to be independent of the current app configuration.
=> tests: better environment for already harvested

inspirehep/modules/forms/validators/simple_fields.py, inspirehep/modules/literaturesuggest/forms.py, tests/unit/forms/test_forms_validators_simple_fields.py
Adds some extra checks to the form when passing an arxiv id or doi:
* Check if is already ni the holdingpen with the same source.
* Check locally (in the DB) if there's a record that matches.
In those cases, it will not allow to pass it.
=> Add new arxiv/doi validators to the literature form.

inspirehep/modules/workflows/tasks/refextract.py, tests/unit/workflows/test_workflows_tasks_refextract.py
Ensures that ``extract_journal_info`` is correctly populating the
``journal_title`` and ``journal_volume`` keys after the journal
split.
Closes #2936.
=> workflows: fix the extract_journal_info task

inspirehep/modules/workflows/workflows/article.py
Some workflows are getting discarded without actually closing the
tickets or notifying anyone, this solves that case.
=> workflows: stop the workflow after closing tickets

inspirehep/utils/ext.py
Added new CFG_BIBCATALOG_SYSTEM_RT_VERIFY_SSL config option to allow
disabling ssl verification for the rt server (useful for tests and
qa).
=> utils.InspireRT: allow set the ssl verification in config

inspirehep/modules/pidstore/providers.py, tests/integration/conftest.py, tests/integration/editor/test_editor_views.py, tests/integration/helpers/utils.py, tests/integration/test_migrator.py, tests/integration/test_records.py, tests/integration/workflows/conftest.py, tests/unit/conftest.py
When inserting a new record having already a ``pid``, this is not added to the table ``pidstore_recid``, making the identifiers out of synch.
=> minter: increase record's pid properly when migrating records from legacy

inspirehep/celery.py, inspirehep/config.py
While testing on QA, for actually getting the log entries in Sentry, we have to enable this flag. 
Additionally, we don't need the `LOGGING_SENTRY_CLASS` anymore.
https://github.com/inspirehep/inspire-next/issues/1371
=> celery: enable LOGGING_SENTRY_CELERY

inspirehep/modules/records/mappings/records/hep.json
Add raw, search fields for providing exact and match support for BAIs.
The search field uses the `lowercase_analyzer` which does only
lowercasing in identifiers, which is usefull for searches like
`a a.einstein.1` to be equivalent with `a A.Einstein.1`.
For supporting BAI search in `inspire-query-parser`.
=> mappings: add raw and search fields to authors.ids

inspirehep/modules/hal/core/tei.py, inspirehep/modules/hal/utils.py, inspirehep/utils/record.py, tests/unit/hal/test_hal_utils.py, tests/unit/utils/test_utils_record.py
The convoluted logic is not needed anymore, as the data now reflect what
the preferred abstract is and it doesn't have to be computed at display
time.
inspirehep/inspire-dojson/pull/148
=> utils: always get first abstract in get_abstract

tests/unit/authors/test_authors_views.py, tests/unit/theme/test_theme_jinja2filters.py, tests/unit/utils/test_utils_bibtex.py, tests/unit/utils/test_utils_bibtex_booktitle.py, tests/unit/utils/test_utils_cv_latex.py, tests/unit/utils/test_utils_cv_latex_html_text.py, tests/unit/utils/test_utils_export.py, tests/unit/utils/test_utils_latex.py, tests/unit/workflows/test_workflows_tasks_beard.py, tests/unit/workflows/test_workflows_tasks_magpie.py
Commit b8e03967 replaced all instances of ``Record`` in unit tests
with ``InspireRecord``, but instead should have replaced them with
simple dictionaries, since we don't need its API in those tests.
=> tests: remove InspireRecord from unit tests

.gitmodules
The submodule for ``inspirehep-search-js`` is no longer needed. Please
follow the instructions in its repository to develop locally.
=>  git: remove submodules

inspirehep/utils/bibtex.py, inspirehep/utils/cv_latex_html_text.py, inspirehep/utils/record.py, tests/unit/utils/test_utils_bibtex.py, tests/unit/utils/test_utils_cv_latex_html_text.py, tests/unit/utils/test_utils_record.py
Since inspirehep/inspire-dojson#127 and inspirehep/inspire-schemas#272,
incomplete `publication_info`s having only a `journal_title`, which
represent articles submitted to a journal but not published, have been
moved to `public_notes`, so this function is no longer needed.
The failing tests for the cv_latex and bibtex serializers have been
removed, as they will be rewritten completely by #2839 anyway.
=> utils: remove is_submitted_but_not_published

inspirehep/config.py, inspirehep/modules/records/api.py, tests/integration/helpers/utils.py, tests/integration/test_records.py
Adds two ways to skip downloading the files:
* Setting the configuration variable ``RECORDS_SKIP_FILES``.
* Passing the ``skip_files`` parameter to the ``create`` and
``update`` methods in ``InspireRecord``.
Note that the latter has precedence, and that by default the
previous behavior (downloading the files) is preserved.
Supersedes https://github.com/inspirehep/inspire-next/pull/2948.
=> records: allow to skip downloading the files

inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
When populating the "bookautocomplete" field of Literature records, retrieving the values supposedly stored in "bookautocomplete" was done as if ES stores JSON objecs, i.e. using `json.get("bookautocomplete", [])`. This always returns `None`, therefore I had to remove `"copy-to":
"bookautocomplete"` from the hep.json mapping. Instead, I retrieve the required values that are assumed to be stored there manually and then appropriately update "bookautocomplete".
=> receivers: populate bookautocomplete in Python

inspirehep/config.py
The journal title suggester only displayed 5 results, and not
necessary the most relevant ones. This is due to the fact that
ES completion suggesters are implemented in such way that
it does not support relevance ordering for the suggesters.
Therefore, the current solution is to simply display more
results, i.e. 10 instead of 5.
Closes https://github.com/inspirehep/inspire-next/issues/2866.
=>  config: make journal suggester return 10 hits

inspirehep/alembic/cb5153afd839_create_workflow_record_sources_table.py, inspirehep/modules/editor/views.py, inspirehep/modules/workflows/errors.py, inspirehep/modules/workflows/models.py, inspirehep/modules/workflows/tasks/manual_merging.py, inspirehep/modules/workflows/tasks/merging.py, inspirehep/modules/workflows/utils/__init__.py, inspirehep/modules/workflows/workflows/__init__.py, inspirehep/modules/workflows/workflows/manual_merge.py, inspirehep/utils/record.py, setup.py, tests/integration/editor/test_editor_views.py, tests/integration/tasks/test_merging.py, tests/integration/test_alembic.py, tests/integration/workflows/helpers/calls.py, tests/integration/workflows/test_workflow_utils.py, tests/integration/workflows/test_workflows_manual_merge.py, tests/unit/utils/test_utils_record.py
=> workflows: add manual_merge workflow

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
* Ensures that no duplicate figures will be added to the workflow
data if a workflow is restarted.
=> workflows: make arxiv_plot_extract safe to rerun

inspirehep/modules/crossref/config.py, inspirehep/modules/crossref/core.py, inspirehep/modules/crossref/views.py, inspirehep/modules/forms/validation_utils.py, inspirehep/modules/literaturesuggest/normalizers.py, tests/integration/crossref/test_crossref_views.py
- I relaxed the form validator on DOI input in order to allow for ` (https?://)?(dx\.)?doi.org/ `.
- I added a new normalizer that cleans up the DOI value to make it conform with the schema.
Closes https://github.com/inspirehep/inspire-next/issues/2712.
The DOI input box should be less strict and attempt to normalize the DOI.
It should:
- strip whitespace
- strip leading doi:
- strip leading ` (https?://)?(dx\.)?doi.org/ `
=> forms: normalize DOIs at ingestion time

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
* In some cases, the same plot name can be found in different
directories of an arXiv tarball. This change ensures that all
plots get attached with unique names.
=> workflows: handle duplicate plot names in arXiv tarball

inspirehep/modules/forms/validators/simple_fields.py, tests/integration/forms/test_forms_validators_simple_fields.py, tests/integration/helpers/utils.py
We are currently blocking submissions of records that were deleted,
we should let them go to the holding pen.
This depends on https://github.com/inspirehep/inspire-matcher/pull/31
=> forms: filter out deleted records when checking dupes

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/helpers/mocks.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Make sure to remove the already existing added document if there.
=> workflows: allow rerunning the download document steps

inspirehep/modules/workflows/tasks/manual_merging.py, tests/integration/workflows/test_workflows_manual_merge.py
After the ``inspire-json-merger`` api change, we missed the change of the returned conflicts.
This closes #3018.
=> manual_merge: fix conflicts assignment in ``extra_data``

inspirehep/modules/migrator/tasks.py
Previously, this was put into the record JSON in `legacy_creation_date`, but the migrator should put this into the `created` field of the InspireRecord object instead. Thus, the 'legacy_creation_date' field
is now removed altogether from the record.
Closes https://github.com/inspirehep/inspire-next/issues/1922.
inspirehep/inspire-schemas#92 introduces a field to host the `creation_date` from legacy (which is exported in the XME format). The corresponding database column should be populated.
=> migrator: propagate legacy_creation_date to the DB

inspirehep/factory.py, inspirehep/modules/theme/views.py, setup.py, tests/unit/theme/test_theme_views.py
Inspire-theme added to API entry point
In setup.py inspire-theme added to api_apps.
Changes made to not render HTML error pages when
in the API application.
N/A
Enables to use jinja2 templates in the API.
=> setup: add theme extension to the API application

inspirehep/modules/theme/views.py
`error_render_response` takes a template name and a Flask exception, which is an unusual combination. IMO a decorator would be better here, since it would also preserve the original Flask-like error handler declaration.
=> theme: add api_friendly_error_handler decorator

inspirehep/modules/workflows/tasks/manual_merging.py, inspirehep/modules/workflows/utils/__init__.py, setup.py, tests/integration/workflows/test_workflow_utils.py, tests/integration/workflows/test_workflows_manual_merge.py
1. Bump ``inspire-json-merger``
2. After merging, saves as root the union of the merged records' roots
After the manual merge is performed, the roots of both records head and update are
retrieved and merged in according to their source.
If two roots with the same source exist, then the update's one is skipped.
Bump ``inspire-json-merger`` allows merging records with empty source.
Saving the union of the roots is the right operation to do, instead of saving the ``head`` and the ``update`` as root like we were doing before.
=> manual_merge: save the correct roots after merging

inspirehep/config.py, inspirehep/modules/migrator/tasks.py
We need a way to disable the creation of the files only at migration
time, so the rest of creation flows still add files (harvesting,
submission) while the migration does not try to pull them in.
This allows to skip the files creation only on migration while still
creating them on record ingestion and other record creation flows.
=> migrate: allow skipping files creation

inspirehep/utils/robotupload.py, tests/unit/utils/test_utils_robotupload.py
https://sentry.inspirehep.net/inspire-sentry/prod/issues/663/
When passing an xml string that is encoded with utf-8, it was trying
to reencode it twice.
=> make_robotupload_xml: handle utf-8 encoded strings

services.yml
=> docker: fix wrong env var name

docker-compose.test.yml, docker-compose.yml, inspirehep/modules/literaturesuggest/static/js/literaturesuggest/literature_submission_form.js
Closes #1997 
There appears to have been an error while publishing the image for
rabbitmq 3.7.0, so I added a commit to pin the previous version until
a fix is released.
=> forms: collapse links when importing from arXiv

docker-compose.test.yml, docker-compose.yml
Reverts b2bbcff as the upstream problem has now been solved.
See: https://github.com/docker-library/rabbitmq/issues/217
=> docker: unpin rabbitmq image

inspirehep/modules/theme/static/scss/format/brief-results.scss
closes #3041
Currently some panels in the search results have a lot of empty space (shown below) when a record does not contain some fields.
The screenshot below shows how they will look after the changes
=> theme: make results height scale with content

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/tasks/test_matching.py, tests/integration/workflows/conftest.py, tests/integration/workflows/helpers/utils.py, tests/integration/workflows/test_arxiv_workflow.py, tests/integration/workflows/test_audit.py, tests/integration/workflows/test_hep_approval.py, tests/unit/workflows/test_workflows_tasks_matching.py
Change the workflow's logic for handling matches in the holdingpen
This pull request changes the workflow's logic for rejecting, stopping or continuing workflows when the payload matches an existing workflow in the holdingpen.
The new business logic is:
* if matches in holdingpen but have different sources then continue.
* if matches in holdingpen but different sources, reject if the matched was previously rejected.
* if matches in holdingpen but different sources, stop the matched workflow if it wasn't rejected and continue. 
This PR also refactors some workflow's parts, adding marks in the main decisional points. Such marks are used in integration tests to check that the right control flow has been executed. 
Closes #1800, closes #1799, closes #1724.
Signed-off-by: Antonio Cesarano …
=> workflow: change logic of matches in holdingpen

inspirehep/modules/workflows/tasks/upload.py, inspirehep/modules/workflows/views.py, inspirehep/modules/workflows/workflows/article.py
Until we use labs as master, we need the recid to be minted on legacy
first, and then store the record locally.
=> workflows: store the record only when we have recid

docker-compose.test.yml, docker-compose.yml, inspirehep/modules/migrator/tasks.py
This will help in order to avoid starving the regular workflows.
Requires changes in the celery config in puppet.
=> migrator: use a special queue for the one-off migrations

inspirehep/modules/migrator/tasks.py
That way when there's a migration error, we don't fail before
handling the error.
=> migrator: don't try to load record on error

inspirehep/modules/workflows/workflows/article.py
This will not be needed once we have the revival of workflows
mechanism, but for now, we have to ignore the rejected ones if
there's a match in the db.
=> workflows: don't check previously rejected on updates

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl
PR #3057 was adding a `Show authors and collaborations` label for records that had an authors field. However, the PR resulted in some records showing this label twice (such as [this](https://labs.inspirehep.net/literature/1603990) one). This PR removes the duplicate labels.
Properly fixes #3053
=> theme: add "show authors and affs" label only once

inspirehep/modules/workflows/tasks/arxiv.py
That way we avoid the unlikely coincidence where the record id matches
the generated number in the figure name, and `add_figure` mistakes it
for a duplicate.
=> workflows: use non-numeric prefix when generating figure names

Procfile
Update Procfile so that it matches our Docker configuration as per
inspirehep/inspire-next#3077.
This was the issue that caused the migration of records hanging in macOS. Records were being inserted into the default `celery` named queue, but in #3077 they were inserted into a `migrator` named queue.
@david-caro @jacquerie
Since the commands that are executed in the Procfile are the same (or _should be_ the same) in each Docker Compose service, we could have them centralized in a configuration file, from which our `docker-compose.yml` and `Procfile` are either _reading_ or _being generated from_.
=> procfile: add queue celery,migrator option

inspirehep/modules/authors/tasks.py, inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/tasks.py, inspirehep/modules/workflows/tasks/upload.py, inspirehep/utils/schema.py, tests/unit/utils/test_utils_schema.py
As the `$schema` key of records is now required by the schemas to be a
valid `uri` but inspire-dojson only puts the schema name there, the
`reporterrors` CLI command has to fix this. Otherwise, the invalid
`$schema` format masks the real validation error.
=> migrator: ensure $schema is uri in reporterrors

inspirehep/modules/hal/core/tei.py, inspirehep/modules/hal/templates/hal/preprint.xml, tests/integration/hal/test_hal_core_tei.py
Adds the possibility of sending preprints to HAL, that is articles that have not been published (yet).
=> hal: also send preprints

inspirehep/modules/records/serializers/fields_export.py, tests/unit/records/test_records_serializers_fields_export.py
This fixes an issue where BibTeX generation fails if a thesis record contains no `thesis_info` field.
Example records displaying this issue:
- https://labs.inspirehep.net/api/literature/1646337
- https://labs.inspirehep.net/api/literature/754840
https://sentry.inspirehep.net/inspire-sentry/prod/issues/1773/
=> serializers: handle theses without thesis_info

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_tasks_actions.py
After the workflow step that normalizes journal titles has run, set
the ``refereed`` and fix the ``document_type`` keys if needed. This
is required to properly handle HEPCrawl harvests.
Closes #2863 and closes #2951
=> workflows: set refereed and fix the document_type

inspirehep/config.py
The option selected in the 'sort by' menu ('most recent' by default) is displayed in the box.
closes #3047
=> show selected option in the 'Sort By' menu

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl
closes #2703
Displays link to the pdf when records have a `documents` key.
=> theme: display links to pdf for literature records in detailed view

inspirehep/modules/theme/templates/inspirehep_theme/typeahead.html
Allows typeahead.js to autocomplete only when the `allowAutocomplete` attribute is set to true.
fixes #2979
=> theme: remove auto-complete by default from the search bar

inspirehep/modules/migrator/tasks.py
=> migrator: only set prod record as failed when it's there

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_tasks_actions.py
This PR removes the window time in which articles are automatically rejected since we can recognize them now as updates, using the matcher.
Such updates are now being sent back to legacy, potentially overwriting human work.
Thus, updates in this PR are not sent to legacy at all.
https://github.com/inspirehep/inspire-next/issues/3124
=> workflow: don't send updates to legacy and approve them on labs

inspirehep/modules/records/mappings/records/hep.json
For being able to support range queries with ES date rounding, while
also having all date fields, with date type (see
inspirehep/inspire-query-parser#75).
https://github.com/inspirehep/inspire-query-parser/pull/75
=> mappings: make publication_info.year a date

tests/integration/conftest.py, tests/integration/test_db_isolation.py
The existent `app` fixture does not provide db isolation between single (integration) tests: this means that if a test adds an object to the db, the same obj is found in the next tests.
The new `isolated_app` fixture instead provides db isolation between single tests.
=> test: add isolated_app fixture with db isolation

inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_tasks_matching.py
=> workflow: don't set `core` field if record is auto-approved

inspirehep/modules/migrator/tasks.py, inspirehep/modules/pidstore/utils.py, tests/integration/migrator/test_migrator_tasks.py, tests/unit/pidstore/test_pidstore_utils.py
Fix add_citation_counts task for PID with non numeric values.
We are about to introduce PID with string values (like ISBN, URN, ArXiv ID, ...) and the add_citation_counts task assumes that the PID value is always numeric.
=> migrator: fix add_citation_counts for PID with non numeric values

inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/receivers.py, setup.py, tests/unit/records/test_records_receivers.py
Add `author.full_name_normalized` not analysed field to hep.json. This field is populated by the receivers with the `NFKC` unicode normalized and lowercased `full_name` value. This value is already normalized by `inspire_utils.normalize_name`.
https://github.com/inspirehep/inspire-query-parser/issues/63
https://github.com/inspirehep/inspire-query-parser/pull/64
This field is needed in order to  support `exact-author` queries that perform
diacritic expansion and lowercase normalization.
=> records: populate full_name_unicode_normalized

Procfile
Add harvests queue in Procfile so that our Docker configuration is in
sync with the native one (following what #3137 introduced).
Keep in mind that although this PR introduces the `harvests` queue, it doesn't set the [`APP_LUST_RUNS_PATH`](https://github.com/david-caro/inspire-next/blob/2ffd1faf37d837911ce29bb5935f000f374dff66/docker-compose.yml#L41) env variable.  
I thought of moving the env-vars from docker-compose to a `.env` file, which is [supported already by Docker-Compose](https://docs.docker.com/compose/environment-variables/#the-env-file). 
This will also allow us to use the same `.env` file from `honcho` which [already supports](http://honcho.readthedocs.io/en/latest/using_procfiles.html#environment-files) that, as …
=> procfile: adapt to new harvests queue

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_tasks_actions.py
The ``submission_number`` key in ``acquisition_source`` is currently
being populated differently between HEPCrawl and form submissions.
In fact, HEPCrawl puts there the Scrapy job id as it can't possibly
know the workflow object id since it will be generated later. This
workflow step makes sure that they will both contain the workflow id
as we'd might want to link from the record to the Holding Pen entry
from which it came from.
Closes https://github.com/inspirehep/inspire-next/issues/2687.
=> workflows: fix submission number for harvests

inspirehep/modules/migrator/tasks.py
Integrates the ``StackTraceLogger`` from ``inspire-utils``, so that we see its behaviour, during the migration. If all goes well, then we can integrate it throughout the project.
#1371
=> migrator: use logger from inspire-utils

docker-compose.test.yml, setup.cfg, setup.py
Remove ``pytest-flake8`` and replace it with just ``flake8`` as the
former is sometimes not finding style violations present in the code.
=> global: don't use pytest-flake8

inspirehep/modules/orcid/__init__.py, inspirehep/modules/orcid/ext.py, inspirehep/modules/orcid/tasks.py, setup.py, tests/integration/test_orcid_import_legacy_tokens.py
Celery task pulls ORCID token data from legacy through redis, as described in issue #2894, and adds the data to inspire-next.
Will try to match an existing user to add the token to, upon failing will silently create a new user for that token. If the user already has a token assigned, this will leave it untouched.
implements #2894
ORCID API ver. 1.2 used in legacy will be switched off. In the meantime, until inspire-next is fully functional we could use inspire-next to push records from legacy using API ver. 2.0. To do this we need to copy over users' OAUTH tokens. See: #2894.
=> orcid: sync OAUTH tokens from legacy

inspirehep/modules/orcid/__init__.py, inspirehep/modules/orcid/builder.py, inspirehep/modules/orcid/converter.py, tests/integration/orcid/fixtures/common_2.0/common-2.0.xsd, tests/integration/orcid/fixtures/record_2.0/error-2.0.xsd, tests/integration/orcid/fixtures/record_2.0/work-2.0.xsd, tests/integration/orcid/test_orcid_export.py, tests/unit/orcid/test_orcid_builder.py
Works on top of two classes. The converter takes out fields
from INSPIRE record and passes them to a builder which
is responsible for building a correct ORCID record based
on the information given.
#2798 
Previous implementation was deleted due to being outdated in relation to schemas.
=> orcid: INSPIRE record to ORCID converter

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Workflow goes like this.
1. Populate `documents` based on type (submission or arxiv)
2. Download populate documents and replace url with internal url
3. Refaxtract
This also downloads documents for records coming from DESY by default,
in a more clean way.
Signed-off-by: harunurhan <harunurhan17@gmail.com>
=> workflows: refactor fulltext download

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/classifier.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_classifier.py
* Avoids auto-rejecting records in the workflows in case the keyword extraction has not run on the fulltext, but only on the metadata present in the record.
* Also runs the keyword extraction on subtitles and author keywords.
=> Fix auto reject

inspirehep/modules/records/mappings/records/hep.json
Add new `publication_info.artid_and_page_start` field to enable easier queries based on `publication_info.artid` and `publication_info.page_start`. Because the data is ambiguous, the 2 fields are sometimes populated with the same value, different values or one of them is not populated at all.
By using `copy_to` to copy the *values* stored in each one of the 2 fields to `publication_info.artid_and_page_start`, we can now query a single field instead of all the possible combinations of the other 2 fields. This is needed for more accurate number ( keeping track of citations, references etc).
=> mappings: add page_artid to publication_info

inspirehep/modules/records/serializers/schemas/base.py, tests/integration/test_bibtex_exporting.py
Do not pass an empty texkey to the library, instead fail early if that happens.
https://sentry.inspirehep.net/inspire-sentry/prod/issues/2606/
=> serializers: BibTeX: fail early if no texkey

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/classifier.py, inspirehep/modules/workflows/utils/__init__.py, inspirehep/utils/references.py, inspirehep/utils/url.py, tests/unit/utils/test_utils_url.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_classifier.py, tests/unit/workflows/test_workflows_utils.py
* The selection of the document used for further metadata extraction
(references, keywords) is now based on the `documents` metadata instead
of the file extension.
* Also refactors the `retrieve_uri` into a context manager, and does the minor refactor suggested in https://github.com/inspirehep/inspire-next/pull/3167/files#r166949783.
=> workflows: Better document selection

inspirehep/modules/theme/templates/inspirehep_theme/errors/500.html
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
the html error page (500+ statuses) currently shows an email address that does not exist/bounces
Adjusting this to a working and monitored email address as discussed on gitter/inspire-next
> > feedback@inspirehep.net ? Or perhaps @StellaCh knows...
> I'd suggest to keep it simple and use feedback for the time being and soon, when we'll launch the public beta, we can revisit the issue of the emails
simple text replacement, no functional changes
=> error_pages: adjust feedback email address

inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/workflows/tasks/submission.py, tests/integration/workflows/conftest.py
This fix this issue: https://sentry.inspirehep.net/inspire-sentry/prod/issues/12/
=> rt: fix rt ticket creation for harvests

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, setup.py, tests/unit/workflows/test_workflows_tasks_submission.py
Production is currently dropping a large number of harvests because
of validation errors of duplicated references.
This reverts commit e4043b3a8fba698e0d3c0b54e042635f4e8f965f.
We are getting duplicated references and failing validation after,
will investigate.
=> Revert "workflows: don't remove references at the end"

inspirehep/modules/authors/tasks.py, tests/unit/authors/test_authors_tasks.py
Current implementation proceeds silently if no control_number appears in the record.
This forces the control_number to be there.
For https://github.com/inspirehep/inspire-next/pull/3204, it would require accommodating for this 'feature', while it does not seem necessary/right.
=> authors.tasks.update_ticket_context: require recid

inspirehep/modules/workflows/templates/inspire_workflows/index.html
Added a card on holdingpen dashboard for all harvests that are not arXiv
=> workflows: add hp card for all publisher harvests

inspirehep/modules/authors/tasks.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/author.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_authors_workflow.py, tests/unit/workflows/test_workflows_tasks_actions.py
I removed the validation from the submission form and added it to the beginning of the authors workflow. If the record is not valid, a `ValidationaError` is raised, its message is stored in `obj.extra_data['_error_msg']` in order to help with identifying which part of the record is not schema compliant, the workflow is stopped, put in `ERROR` state. 
This is required because so far, if a record was not valid either in hepcrawl or submission form, a `ValidationError` would be raised before the workflow started and the actual record was lost. Moreover, it was hard to identify such errors because they were rather silent and required some investigation on Sentry to be brought to light.
=> authors: validate at the beginning of the workflow

inspirehep/modules/refextract/utils.py, tests/unit/refextract/test_refextract_utils.py
* Previously, the journal knowledge base file was opened in write mode
instead of append, which resulted in new writes overwriting previous
ones instead of being appended to them.
=> refextract: correctly generate journal KB

inspirehep/modules/records/ext.py, setup.py
Reintroduce registering receivers in records in `ext.py`
Discussion @ https://github.com/inspirehep/inspire-next/commit/2cbd46168268e86781c72e86176326d6a6b0647d#commitcomment-27696311
=> records.receivers: re-add receivers registration

inspirehep/config.py, inspirehep/modules/authors/tasks.py, inspirehep/modules/authors/views.py, inspirehep/modules/orcid/api.py, inspirehep/modules/orcid/converter.py, inspirehep/modules/orcid/utils.py, inspirehep/modules/records/json_ref_loader.py, inspirehep/modules/workflows/views.py, inspirehep/utils/url.py, setup.py, tests/integration/orcid/test_orcid_export.py, tests/unit/utils/test_utils_url.py
- This introduces a `get_prod_url_for_recid` util to make record URLs from recids.
- In addition to this, API of OrcidConverter is changed to keep it flask-less and seperate from the rest of the application. We cannot use the util in there directly, so this proposes to instead pass a URL pattern and uses inspire_utils, which will allow us to seperate it from the main app in the future.
=> Abstract legacy URL building

requirements.txt, setup.py
* Adds the option to select queue when ``run`` command is running. This
commit should be removed as soon as the
https://github.com/inveniosoftware/invenio-indexer/pull/78 is merged.
=> setup: temporary replace ``invenio-indexer``

inspirehep/modules/orcid/api.py, inspirehep/modules/orcid/tasks.py, tests/integration/orcid/conftest.py, tests/integration/orcid/test_orcid_push.py
Signed-off-by: Szymon Łopaciuk <szymon.lopaciuk@cern.ch>
=> orcid: bugfix: last cached record is always pushed

docker-compose.yml
Same as https://github.com/inspirehep/inspire-next/pull/3191.
=> docker: clean up pidfile when starting scrapyd

inspirehep/modules/orcid/converter.py
Don't use `self_recid` as it is not part of the schema, hence shouldn't be relied on. Instead use the `control_number` field.
=> orcid: don't rely on self_recid in record in OrcidConverter

inspirehep/modules/workflows/templates/inspire_workflows/index.html
This reverts commit 1d24d5276457dfe8d05c0562e82cc689fb1625aa in order to hide it from both QA and Prod.
This is needed due to the fact that the behaviour introduced by the commit is not the intended one and should not be allowed to confuse users until it is fixed.
=> Revert "workflows: add hp card for all publisher harvests"

inspirehep/config.py, inspirehep/modules/orcid/tasks.py, inspirehep/modules/records/receivers.py, tests/integration/orcid/test_orcid_push.py, tests/integration/records/test_records_receivers.py
- fix the receiver which called a wrong argument of `orcid_push`, i.e. `token` -> `oauth_token`
- change the name of the ORCID push task to align it with the RabbitMQ queue name, i.e. `push_orcid` -> `orcid_push`
=> orcid tasks & recv: fix argument, unify naming

inspirehep/config.py, inspirehep/modules/orcid/utils.py
This is done in order to store the default `allow_push` flag for the
token.
=> orcid: override oauth setup signup handler

inspirehep/utils/record_getter.py, tests/integration/test_records.py, tests/integration/utils/test_record_getter.py
* Adds a `get_db_records` util to get several records at once given a PID type and a list of recids.
* Also refactors the tests for `get_es_records`
This is useful for #3223.
=> utils: add get_db_records util

inspirehep/modules/orcid/builder.py, tests/integration/orcid/test_orcid_export.py, tests/unit/orcid/test_orcid_builder.py
- Order fields in the contributor in the correct order so that the record validates
- This version of the builder was manually tested on 10k records migrated from legacy
Records created by the previous version of the builder would fail validation if the author contained an ORCID.
=> orcid.builder: order contributor fields correctly

inspirehep/modules/forms/validation_utils.py, tests/unit/forms/test_forms_validation_utils.py
Resubmits https://github.com/inspirehep/inspire-next/pull/3220 against the `prod` branch so that we can hotfix this error on production: https://sentry.inspirehep.net/inspire-sentry/prod/issues/50311/.
Closes https://github.com/inspirehep/inspire-next/pull/3220.
=> forms: fix orcid validation after API update

inspirehep/config.py, inspirehep/modules/workflows/actions/match_approval.py, inspirehep/modules/workflows/mappings/holdingpen/hep.json, inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/tasks/upload.py, inspirehep/modules/workflows/workflows/article.py, setup.py, tests/acceptance/conftest.py, tests/integration/workflows/conftest.py, tests/integration/workflows/helpers/calls.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/helpers/mocks.py, tests/unit/workflows/test_workflows_actions.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_matching.py
Changed the step in the workflow that checks if the ingested article is an update, by
performing a fuzzy match. If there is at least a match, the workflow halts, waiting
for human matching confirmation.
All the matches are now stored in `obj.extra_data.matches`, which is a dictionary containing
`exact` matches, `fuzzy` matches, and eventually the `approved` fuzzy match.
A new action called `MatchApproval` has been added to resume the workflow when is halted for
matching approval.
Solves #2527.
=> workflow: integrate fuzzy matcher in the `article` workflow

inspirehep/modules/authors/forms.py
Add, populate and validate ORDCID field in "authors/recid/update" form.
The field behaves precisely like the one in the "authos/new" form.
The addition of the field was done by removing a simple check of the `is-update` field that hid the ORCID field in the case of an update form.
The validation - which was previously broken - has already been fixed by @szymonlopaciuk [here](https://github.com/inspirehep/inspire-next/pull/3236).
The implementation for the field population was already in place as one can see [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/authors/views.py#L235) where the `try ... except ...` statement is importing the record's xml from **legacy** and converting the data to the appropriate format to then populate the form fields (hint: check …
=> forms: add, populate and validate ORCID field

inspirehep/modules/workflows/tasks/matching.py, tests/integration/workflows/test_arxiv_workflow.py
Also, refactors the integration test for fuzzy matching mocking the Elastic Search query, since its result depends on the environment.
=> workflows: get first five recid when fuzzy match

setup.py
This commit pins the new versions of `inspire-crawler` and `hepcrawl` to start workflows in ERROR state.
=> setup: pin new versions of inspire-crawler and hepcrawl

setup.py
Fix an issue in our CI that makes the build of the Docker image used by
the other tests fail.
=> setup: add explicitly the pyOpenSSL dependency

setup.py, tests/unit/workflows/test_workflows_tasks_classifier.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/6/
~~This doesn't yet contain a fix, just a reproduction (this PR is expected to fail).~~
Fix happened here: https://github.com/inveniosoftware-contrib/invenio-classifier/pull/38
=> workflows: fix issue with unprintable keywords

setup.py
This pin was introduced in 7f18874 to avoid fetching a beta release.
As there's no longer a beta release to protect from, this pin is no
longer needed.
=> setup: unpin SQLAlchemy

inspirehep/modules/migrator/tasks.py, inspirehep/modules/orcid/tasks.py, tests/integration/migrator/fixtures/dummy.xml, tests/integration/migrator/test_migrator_tasks.py
Disables ORCID push during migration (however, not continuous migration) by the means of temporarily changing the ORCID push feature flag. This does not interfere with other tasks as they are run in separate processes. The flag is reset in case of errors as well.
=> migrator.tasks: disable migration on ORCID push

inspirehep/config.py, inspirehep/modules/workflows/tasks/matching.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_tasks_matching.py
Add a feature flag for enabling the fuzzy matcher.
=> matching: add feature flag for the fuzzy matcher

.gitignore
Add `.pytest_cache` dir to the `.gitignore`.
=> gitignore: add .pytest_cache

inspirehep/modules/workflows/errors.py, inspirehep/modules/workflows/loaders.py, inspirehep/modules/workflows/search.py, inspirehep/modules/workflows/serializers/__init__.py, inspirehep/modules/workflows/serializers/schemas/__init__.py, inspirehep/modules/workflows/serializers/schemas/json.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/utils/__init__.py, inspirehep/modules/workflows/views.py, tests/integration/workflows/helpers/calls.py, tests/integration/workflows/test_arxiv_workflow.py
* Adds a callback endpoint for the UI, this will allow the UI to run
validation and continue the workflow if the record is valid.
* Adds in ``extra_data`` ``callback_url`` and
``validation_errors`` fields on callback request and when validation
task runs.
Co-authored-by: Harris Tzovanakis <me@drjova.com>
=> workflows: add validation errors callback

inspirehep/modules/workflows/tasks/actions.py, inspirehep/utils/record.py, tests/unit/utils/test_utils_record.py, tests/unit/workflows/test_workflows_tasks_actions.py
Prevent it from throwing an exception when an incoming record has
``arxiv_eprints`` but no ``categories`` inside.
Sentry: https://sentry.inspirehep.net/inspire-sentry/inspire-qa/issues/59393/
=> workflows: fix and refactor is_experimental_paper

inspirehep/modules/workflows/workflows/article.py
Undo a change made in commit 211fb16 to take the automatic decision
before halting, so that we don't show things to curators needlessly.
=> workflows: do the automatic decision before halt

setup.py
Fix the build by avoiding getting a Celery which is incompatible
with Flask-CeleryExt. See: inveniosoftware/flask-celeryext#31.
=> setup: pin Celery

inspirehep/modules/authors/rest/citations.py, inspirehep/modules/authors/rest/coauthors.py, inspirehep/modules/authors/rest/publications.py, inspirehep/modules/authors/rest/stats.py, inspirehep/modules/orcid/utils.py, inspirehep/modules/records/mappings/records/hep.json, tests/integration/conftest.py, tests/integration/orcid/test_orcid_utils.py, tests/integration/test_db_isolation.py
We record that an author of recid X has claimed a paper of recid Y by
setting ``curated_relation`` to ``True`` in the author signature of Y
that also contains a record reference to X.
In order to later retrieve this information we need to nest this field,
otherwise we would get spurious matches across different signatures.
See also c20f672 for a similar argument for ``publication_info``s.
https://its.cern.ch/jira/browse/INSPIR-343
=> orcid: add get_literature_recids_by_orcid util

inspirehep/modules/records/mappings/records/data.json
Added mappings for the data records in Elasticsearch. This would add DOIs to the data records in the desired format, making us able to make ES queries on those.
This would help in accounting for citations to data, improving citation counts.
=> mappings: add mappings for data

inspirehep/config.py
Change fuzzy matcher configuration to use the Jaccard Index based validator for the authors and titles of the resulting possible matches against the given record.
https://github.com/inspirehep/inspire-matcher/pull/43
The current config does not specify a validator, thus the default one will be used which approves of any possible match. Due to the fact that the current ES query that is generated by the fuzzy matcher is too general and returns many irrelevant results, we have to filter out as much as possible the wrong matches.
=> Change fuzzy matcher config to use Jaccard Index based validator

inspirehep/modules/records/api.py
The recent refactor of #3290 omitted to pass the `skip_files` argument to the `update` path in `InspireRecord.create_or_update`. This fixes it.
https://sentry.inspirehep.net/inspire-sentry/inspire-qa/issues/71442/
=> records: correctly skip files in create_or_update

setup.py
Since inveniosoftware/flask-celeryext#31 was merged we can undo
commit 109bf7c and bump the version of Flask-CeleryExt.
=> setup: unpin Celery

docker-compose.test.yml, docker-compose.yml
This prevents the worker from starting up after the tests started
and cleaning up any pending jobs.
=> docker: add health check for the worker node

inspirehep/modules/workflows/tasks/beard.py, inspirehep/modules/workflows/tasks/classifier.py, inspirehep/modules/workflows/tasks/magpie.py, inspirehep/modules/workflows/tasks/matching.py
The ``with_debug_logging`` decorator should only be used when the
decorated function is a workflow step, so that we can trace the
workflow execution from the logs.
=> workflows: remove extra with_debug_logging

inspirehep/modules/orcid/utils.py
Previously the query was returning only the first 10 results, per
ES' defaults. It's ok to use ``size=9999`` because we don't expect
any author to have signed that many papers; if this in the future
becomes a problem we should start using the Scroll API.
=> orcid: return all results in get_literature_recids

inspirehep/modules/authors/forms.py
* Removes the validation for duplicate ORCIDs.
=> forms: remove validation for duplicate ORCIDs

inspirehep/config.py, inspirehep/modules/orcid/api.py, inspirehep/modules/orcid/tasks.py, inspirehep/modules/orcid/utils.py, tests/integration/orcid/test_orcid_api.py
**OUTDATED, left for historical reasons:**
*We are currently losing logs for ORCID pushes, for an unknown reason. I tried to troubleshoot but after over a day of coming up blank and discussing with @puntonim we decided that this may be a good opportunity to introduce explicit logging to a file, for now for the `orcid` module. Having the logs for ORCID can enable us to learn about the statistics such as ratio of updates to creations.*
**EDIT:**
This now successfully logs to stderr for the orcid module.
Turns out our problem comes from somewhere in raven/invenio-logging where the loggers are patched. For some reason, when enabling sentry all logs below `LOGGING_SENTRY_LEVEL` are lost. Investigation shows that the propagation on the `inspirehep` logger is disabled which causes messages to …
=> orcid: create a separate logger for orcid

inspirehep/config.py, inspirehep/modules/workflows/errors.py, inspirehep/modules/workflows/tasks/merging.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/tasks/upload.py, inspirehep/modules/workflows/utils/__init__.py, inspirehep/modules/workflows/views.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_arxiv_merge.py, tests/integration/workflows/test_arxiv_workflow.py
* Accepts ``is-update`` workflows and passes through the merge step. If
there are not conflicts the workflow will continue otherwise it'll
change the status to HALTED and wait for manual merge through the
editor.
* Adds an endpoint to resolve merge conflicts from the editor.
* Introduces two feature flags ``FEATURE_FLAG_ENABLE_MERGER``
to allow merges on update  and
``FEATURE_FLAG_ENABLE_UPDATE_TO_LEGACY`` to send a replace
on legacy on update.
* Removes obsolete step ``STOP_IF_TOO_OLD``.
* closes INSPIR-304
=> workflows: addition of rootless merge

docker-compose.test.yml, inspirehep/celery_tests.py, inspirehep/config.py, inspirehep/modules/workflows/tasks/classifier.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/conftest.py, tests/unit/workflows/test_workflows_tasks_classifier.py
This decreases the time of the workflow (unit and integration), and acceptance tests in **~3min**, as the first parsing of the HEPont.rdf is not needed anymore.
=> tests.classifier: use a small minimal taxonomy

inspirehep/alembic/402af3fbf68b_rename_inspire_prod_records_table.py, inspirehep/alembic/d99c70308006_merge_two_alembic_branches.py, inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/models.py, inspirehep/modules/migrator/tasks.py, tests/integration/conftest.py, tests/integration/migrator/test_migrator_cli.py, tests/integration/migrator/test_migrator_models.py, tests/integration/migrator/test_migrator_tasks.py, tests/integration/test_alembic.py, tests/integration/test_detailed_records.py, tests/integration/test_migrator.py
The previous implementation of the Alembic tests was lacking in several
regards, most notably test isolation. The approach in this PR side steps
the problem by creating two tests for `upgrade` and `downgrade`, which,
as https://github.com/inspirehep/inspire-next/commit/d578ca6b878fb66caf9e775408b4dbbd56eb3f72 shows, make writing these tests much easier.
Since commit 99aeb65 Alembic's INSPIRE branch has had two heads. This
commit fixes this situation by adding an empty merge migration.
Finally, https://github.com/inspirehep/inspire-next/pull/3267 was missing that SQLAlchemy's ``rename_table`` does not work
out of the box for PostgreSQL tables, and requires the fixes outlined in
http://petegraham.co.uk/rename-postgres-table-with-alembic/.
=> tests: rewrite the alembic tests

inspirehep/modules/migrator/tasks.py
Fixes a few issues in the migration:
- correctly disables the ORCID push
- `migrate_from_mirror` explicitly passes the `recid`, instead of relying on magic
=> migrator: fix two bugs

inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py
If the current workflow matches another workflow which state is
ERROR or INITIAL, then the current workflow raises a WorkflowsError
and goes in ERROR state.
This prevents some race conditions happening in Inspire.
=> workflow: raise if match a wf in error or initial state

inspirehep/modules/authors/forms.py
25 author submissions are failing because of not valid urls, this will prevent users to add wrong formatted urls in the future.
=> authors: addition of url validation

docs/operations.rst
=> update operations doc for remigrating in QA

inspirehep/config.py, inspirehep/modules/workflows/tasks/submission.py, tests/unit/workflows/test_workflows_tasks_submission.py
Unlike #3377, the optional removal of references is now done in `send_robotupload` in order not to delete references from the holdingpen and allow their inspection.
=> workflows: feature flag for sending refs to legacy

inspirehep/modules/orcid/api.py, inspirehep/modules/orcid/utils.py, tests/integration/orcid/cassettes/test_push_record_with_orcid_new.yaml, tests/integration/orcid/cassettes/test_push_record_with_orcid_update.yaml, tests/integration/orcid/cassettes/test_push_to_orcid_same_with_cache.yaml, tests/integration/orcid/cassettes/test_push_to_orcid_update_no_cache.yaml, tests/integration/orcid/cassettes/test_push_to_orcid_update_with_cache.yaml, tests/integration/orcid/cassettes/test_push_to_orcid_with_putcode_but_without_hash.yaml, tests/integration/orcid/test_orcid_utils.py
Similarly to df17def, this commit computes the BibTeX representation
of a record directly instead of through the API. Unlike that commit,
this is done for consistency rather than performance.
Jira: https://its.cern.ch/jira/browse/INSPIR-548
=> 548 orcid: don't get the BibTeX through the API

inspirehep/utils/url.py
The fix introduced in 7ac57d7 worked for the Holdingpen case, but
does not work when we are in the context of an HTTP request, such
as when we are validating a form submission.
This has been tested manually locally.
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/78022/
=> utils: fix (again) is_pdf_url

inspirehep/modules/migrator/tasks.py, tests/integration/migrator/test_migrator_tasks.py
This module used to have the `@shared_task` decorator applied very
liberally, even for functions that were always called as regular
functions and never scheduled through celery. Now, only functions that
are actually used as tasks have the decorator. This incidentally removes
all tasks synchronously calling other tasks, which is bad practice and
forbidden in Celery 4.*.
=> 668 migrator: remove unneeded tasks

inspirehep/modules/workflows/config.py, inspirehep/modules/workflows/tasks/refextract.py, tests/integration/helpers/factories/db/invenio_records.py, tests/integration/workflows/test_arxiv_merge.py, tests/integration/workflows/test_workflows_tasks_actions.py, tests/integration/workflows/test_workflows_tasks_refextract.py
This adds the capability to match references to data records in the current reference matcher.
https://its.cern.ch/jira/browse/INSPIR-472
This would improve citation counts.
Signed-off-by: Salman Maqbool <salman.maqbool@cern.ch>
=> workflows: add data references matcher

inspirehep/modules/workflows/tasks/upload.py, inspirehep/modules/workflows/utils/__init__.py, tests/integration/workflows/test_workflow_utils.py, tests/unit/workflows/test_workflows_utils.py
* Translates the sources to ``arxiv``, ``publisher`` and ``submitter``.
=> workflows: source translation for the roots

inspirehep/modules/disambiguation/__init__.py, inspirehep/modules/disambiguation/config.py, inspirehep/modules/disambiguation/ext.py, inspirehep/modules/migrator/tasks.py, setup.py, tests/unit/disambiguation/test_disambiguation_ext.py
The attempt to spin this module out as an independent blueprint (https://github.com/inspirehep/inspire-disambiguation) ran into the core issue of how to read/write the records independently of `inspire-next`, and the related issue of how to test code that interacts with the database.
One solution could have been to set up an independent Docker environment, similar to how `hepcrawl` does it. A problem with that approach is the undesirable repetition; the US to bump Celery to version 4 required modifying the same configuration variables in 4 different repositories. One could use the `docker-compose.yml` and `docker-compose.override.yml` pattern documented in https://docs.docker.com/compose/extends/#multiple-compose-files, which instead has the issue of having developers deal with git …
=> disambiguation: first commit

inspirehep/modules/theme/views.py, setup.py, tests/unit/theme/test_theme_views.py
This was added by the commit
https://github.com/inspirehep/inspire-next/pull/2816/files#diff-2eeaed663bd0d25b7e608891384b7298R198
And was not needed, as actually it also makes sure that the api app
never tries to render a template on error by using jsonify.
=> api: remove inspire theme extension

inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/workflows/config.py, tests/integration/workflows/test_workflows_tasks_refextract.py
=> 801 workflows: use texkeys in reference matcher

inspirehep/modules/literaturesuggest/tasks.py
This is no longer needed because refextract now also runs on the
references in the form.
=> 800 literaturesuggest: no refs in private notes

inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
Fixes this problem reported in chat: https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/subject/names.20are.20not.20foreign.20keys
=> records: fix assign_phonetic_block receiver

inspirehep/modules/disambiguation/core/db/readers.py, tests/integration/disambiguation/fixtures/1662077.json, tests/integration/disambiguation/test_disambiguation_core_db_readers.py
Given that, as documented by https://github.com/inspirehep/inspire-next/blob/c7e0862cd5d2052de767eed5c7a9943d9467cc81/tests/unit/records/test_records_receivers.py#L396-L416 not every author signature is required to have a `signature_block`, the `disambiguation` module shouldn't expect that to be true.
=> disambiguation: don't expect a signature_block

inspirehep/utils/url.py
The previous (i.e. third) iteration of `is_pdf_link` didn't work when
all the content was on a single line, as it was then reading too much
resulting in the connection being killed.
This is avoided by reading a fixed number of bytes, instead of a fixed
number of lines.
https://sentry.inspirehep.net/inspire-sentry/prod/issues/115184/
=> utils: make is_pdf_link accept long lines

setup.py
Build fails as installed version of urllib3 (1.23) fails the requirements of python-requests.
See: https://travis-ci.org/inspirehep/inspire-next/jobs/388221675
https://its.cern.ch/jira/browse/INSPIR-841
=> 841 requirements: pin urllib3==1.22

inspirehep/alembic/eaab22c59b89_insert_migrator_use_api_action_role.py, inspirehep/alembic/f9ea5752e7a5_update_legacy_records_mirror_table.py, inspirehep/modules/fixtures/users.py, inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/dumper.py, inspirehep/modules/migrator/models.py, inspirehep/modules/migrator/permissions.py, inspirehep/modules/migrator/serializers/__init__.py, inspirehep/modules/migrator/serializers/schemas/__init__.py, inspirehep/modules/migrator/serializers/schemas/json.py, inspirehep/modules/migrator/utils.py, inspirehep/modules/migrator/views.py, setup.py, tests/integration/conftest.py, tests/integration/helpers/factories/db/inspire_migrator.py, tests/integration/migrator/fixtures/1674987.xml, tests/integration/migrator/fixtures/1674989.xml, tests/integration/migrator/fixtures/1674997.xml, tests/integration/migrator/test_migrator_models.py, tests/integration/migrator/test_migrator_view.py
- Add `collection` column and db event listener for `last_updated` column for the LegacyRecordsMirror model. Also, create alembic recipe for these changes.
- Store the collection of each record with errors in the new `collection` column.
- Add marshmallow serializer and dumper for invalid records from the mirror.
- Add `GET` view for listing the records with errors (valid=False) from the mirror -> most recent first. (Pagination might be needed in the future.)
- Create new `migrator-use-api` permission for `cataloger` and use it to decorate the migrator view.
- Add integration tests for the view.
https://its.cern.ch/jira/browse/INSPIR-695
The backend is needed for the Exception Dashboard.
=> migrator: REST-ful API for Legacy Mirror

inspirehep/modules/disambiguation/ext.py
=> disambiguation: fix typo in configuration key

inspirehep/modules/disambiguation/core/db/readers.py, tests/integration/disambiguation/test_disambiguation_core_db_readers.py
We use `get_all_curated_signatures` to build the training set, while we use `get_all_signatures` to build the running set.
=> disambiguation: add get_all_signatures

inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
Another fix for a small bug in the `assign_phonetic_block` receiver.
=> records: don't assign an empty signature_block

inspirehep/modules/disambiguation/api.py, inspirehep/modules/disambiguation/ext.py, tests/integration/disambiguation/test_disambiguation_api.py
The main benefit of this refactor is that now `author_id` and `cluster_id` are independent, which means that we can represent in a uniform way
1. An input cluster that refers to an author.
2. An input cluster that does not refer to an author.
3. An output cluster.
This also prevents some needless copies that happen in the various disambiguation steps (for example: https://github.com/inspirehep/beard/blob/87b37a3028825b5199616b195663fee526c26be3/examples/applications/author-disambiguation/sampling.py#L177-L179).
=> disambiguation: refactor to use JSON Lines

inspirehep/testlib/api/mitm_client.py, tests/e2e/test_arxiv_harvest.py
Adds a client function for recording new interactions and a helper in the form of a decorator to abstract E2E test scenario management.
Makes it easier to use the mitmproxy for E2E tests in inspire-next. To record interactions during a test:
```python
from inspirehep.testlib.api.mitm_client import with_mitmproxy
@with_mitmproxy(should_record=True)
def test_get_record_from_legacy():
response = requests.get('http://inspirehep.net/record/123456')
response.raise_for_status()
```
Bear in mind that the service has to still be registered in the mitmproxy to allow for recording (functionality to do it dynamically is coming soon, for now we have Arxiv, Legacy and RT). After the interactions are recorded you can run your test like so, to avoid recording (`should_record` is `False` by default). …
=> 792 testlib: add mitmproxy scenario recording client

inspirehep/modules/disambiguation/api.py, inspirehep/modules/disambiguation/config.py, inspirehep/modules/disambiguation/core/ml/sampling.py, inspirehep/modules/disambiguation/ext.py, tests/integration/disambiguation/fixtures/765515.json, tests/integration/disambiguation/fixtures/765975.json, tests/integration/disambiguation/test_disambiguation_api.py
One test depended implicitly on the presence of an application
context, but didn't explicitly require an application fixture.
This meant that the test was failing when run in isolation.
Since INSPIRE has ~3M curated signatures it would take too much time
to train on all possible pairs, so we sample 1M pairs in such a way
that they are representative of the known clusters structure.
=> disambiguation: add signature pairs sampling

docs/e2e_tutorial.rst, docs/index.rst
Create an E2E test writing tutorial page in docs with a walk through how to write an E2E which harvests a non-core record from ArXiV and checks if it ends up in holdingpen as HALTED.
Everyone can learn how to write E2E tests for INSPIRE.
=> docs: add a tutorial on how to write E2E tests

inspirehep/alembic/2f5368ff6d20_update_indices_on_legacy_records_mirror_table.py, inspirehep/modules/migrator/models.py, inspirehep/modules/migrator/views.py, tests/integration/migrator/test_migrator_view.py
Do not return invalid records with collection 'DELETED' to the view.
Also, add a composite index on `valid` and `collection` columns of the
LegacyRecordsMirror table model and create an alembic recipe for it.
https://its.cern.ch/jira/browse/INSPIR-867
https://its.cern.ch/jira/browse/INSPIR-868
- We are not interested in checking errors for records that have been deleted.
- Indexing on 'collection' and 'valid' will increase the performance of the query.
=> migrator view: filter out 'DELETED' invalid records

inspirehep/modules/workflows/tasks/actions.py
Currently, we have records with lots of references where we hit the
refextract timeout, even if refextract is not stuck. That shouldn't
happen, so this commit increases the timeout.
=> workflows: increase refextract timeout to 10 min

inspirehep/modules/records/api.py, tests/integration/records/test_records_api.py
Encapsulate the record creation and minting statements found in `InspireRecord.create()` in a `with db.session.negin_nested():` SAVEPOINT. In case of an exception, the state of the DB will be rolled back to the savepoint, regardless of whether a PID or a record has already been created. Thus, now a PID cannot be created without an associated record. The opposite is also true.
https://its.cern.ch/jira/browse/INSPIR-732
At the moment, if the record creation fails because of errors like `ValidationError` , a PID is still created and stored for that record. Similarly, we had the opposite problem in the past: inspire records were saved with no associated PIDs when the minting process would fail because of errors like `PIDAlreadyExists`.
Signed-off-by: Iuliana Voinea …
=> records: fix transaction issue causing zomie pids

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py
Increasing the timeout to 10 min in
92d3166d84652520cf294aef430ae9c8296ea9de didn't solve the problem. This
might be because when there are lots of references, also reference
matching takes a long time, exceeding the allowed time. As we really
want to protect from refextract going wild and never finishing, rather
than ensuring the task runs in a fixed amount of time, it makes sense
not to include reference matching in the timeout.
=> workflows: put the refextract timeout on subtasks

inspirehep/modules/workflows/mappings/holdingpen/hep.json
**See: https://its.cern.ch/jira/browse/INSPIR-907**
This fixes:
- 'Filter by action' facet
Some facets in holdingpen don't have explicit mapping.
=> holdingpen: fix holdingpen-hep mapping for facets

inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/refextract.py, inspirehep/modules/workflows/utils/__init__.py, tests/unit/workflows/test_workflows_utils.py
=> workflows: no error when refextract times out

inspirehep/modules/workflows/workflows/edit_article.py, tests/integration/workflows/test_edit_article.py
When clicking on an outdated RT JLab ticket, the workflow's payload was showing old data. Now It will always load the latest info from the DB.
=> edit_article: use always latest data from db as payload

scripts/modify_record.py
Adds a snippet that can be used to modify metadata of an existing record. This is trickier than it seems, bceause if one modifies the data in-place, the changes don't get written to the database.
=> scripts: add modify_record

inspirehep/modules/workflows/search.py
User-story: [INSPIR-192](https://its.cern.ch/jira/browse/INSPIR-192)
Required for [PR 85](https://github.com/inspirehep/inspirehep-search-js/pull/85) in inspirehep-search-js to display the number of core and matched references for a given record.
=> workflows: make reference information available to the templates

inspirehep/modules/workflows/tasks/refextract.py, tests/integration/workflows/test_workflows_tasks_refextract.py
This fix causes the list of matched references to be deduped on control numbers rather than on the
raw Inspire Matcher match results.
Fixes: https://its.cern.ch/jira/browse/INSPIR-1029
Signed-off-by: Salman Maqbool <salman.maqbool@cern.ch>
=> 1029 Dedupe matched references on control number

inspirehep/modules/workflows/tasks/merging.py, tests/integration/workflows/test_arxiv_merge.py
Save the root used in the three-way-merge in order to facilitate debug/content checking afterwards
=> workflow: preserve original merging root

inspirehep/modules/workflows/views.py, tests/integration/workflows/test_views.py, tests/integration/workflows/test_workflows_tasks_actions.py
Add the endpoint `/workflows/inspect_merge/<holdingpen_id>` to get the `root`, `head`, `update`, and `merged` records in a given workflow - if it's an update.
=> workflows: add endpoint to inspect merge operations

inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_merge.py
=> INSPIR-1087: do relevance check only for new articles

inspirehep/modules/records/wrappers.py, tests/unit/records/test_records_wrappers.py
Change the LiteratureWrapper's `publication_information` property to no longer return objects containing empty string values.
=> records: fix publication_info wrapping

inspirehep/config.py, inspirehep/modules/migrator/tasks.py, inspirehep/modules/records/cli.py, inspirehep/modules/records/ext.py, inspirehep/modules/records/tasks.py, inspirehep/utils/record.py
Introduce a `simpleindex` cli to replace `invenio_indexer` for re-indexing record. This has an advantage of:
- actual parametrised bulk indexing (`invenio_indexer` bulk size is constant, and equal to one)
- better error reporting
- use one celery queue for indexing, without the intermediate RabbitMQ step
- easier to tell what breaks, if it does
- better
- faster
- stronger
=> records: add a cli for parallel bulk reindex

setup.py, tests/integration/workflows/test_views.py
* Due to the limitation of ``invenio-workflows-ui`` test suite, we're
adding the tests here to make sure the ``ETag`` is properly set.
=> tests: addition of workflow etag tests

.gitignore, inspirehep/modules/authors/views.py, inspirehep/modules/literaturesuggest/views.py, inspirehep/testlib/api/__init__.py, inspirehep/testlib/api/author_form.py, inspirehep/testlib/api/holdingpen.py, inspirehep/testlib/api/literature_form.py, tests/e2e/scenarios/author_submission_has_source_data/RTService/authenticate.yaml, tests/e2e/scenarios/author_submission_has_source_data/RTService/ticket_comment.yaml, tests/e2e/scenarios/author_submission_has_source_data/RTService/ticket_edit.yaml, tests/e2e/scenarios/author_submission_has_source_data/RTService/ticket_new.yaml, tests/e2e/scenarios/literature_submission_has_source_data/RTService/authenticate.yaml, tests/e2e/scenarios/literature_submission_has_source_data/RTService/ticket_comment.yaml, tests/e2e/scenarios/literature_submission_has_source_data/RTService/ticket_edit.yaml, tests/e2e/scenarios/literature_submission_has_source_data/RTService/ticket_new.yaml, tests/e2e/test_submissions.py
Initialise `source_data` (with `formdata`) for workflows created with submission forms for literature and authors.
Restartable Workflows: https://its.cern.ch/jira/browse/INSPIR-1026
=> 1026 literaturesuggest, authors: add source_data

inspirehep/modules/records/serializers/fields/__init__.py, inspirehep/modules/records/serializers/fields/list_with_limit.py, inspirehep/modules/records/serializers/schemas/common/author.py, inspirehep/modules/records/serializers/schemas/common/conference_info_item.py, inspirehep/modules/records/serializers/schemas/common/supervisor.py, inspirehep/modules/records/serializers/schemas/json.py, tests/integration/records/serializers/test_schemas_json.py, tests/integration/records/test_records_serializers_json.py, tests/unit/records/serializers/test_schemas_json.py
Add `authors` and `supervisors` properties to LiteratureRecord wrapper. Two new fields are added in order to be used by the UI: first_name, last_name.
https://its.cern.ch/jira/browse/INSPIR-1044
=> records: add authors prop to literature wrapper

tests/integration/workflows/conftest.py, tests/integration/workflows/test_arxiv_workflow.py, tests/integration/workflows/test_edit_article.py
Workflow tests go down from ~23 min to ~13 min on Travis with this little improvement.
=> Improve wf test speed

inspirehep/modules/records/wrappers.py, inspirehep/modules/theme/jinja2filters.py, tests/unit/records/test_records_wrappers.py
Make the LiteratureWrapper property `publication_information` return `None` in case the `publication_info` key does not exist in the record or it does not contain objects that are relevant for the UI. This is necessary because otherwise the UI will render the`Published in` label without any content.
https://its.cern.ch/jira/browse/INSPIR-1092
=> records: wrapper handles empty publication_info

Procfile
* Removing honcho elasticsearch start up. Installing ES5 locally works
out-of-the-box.
=> honcho: removal of elasticsearch

services.yml
When starting elasticsearch, if the docker data dir was cleaned up,
when creating the new dirs for elasticsearch they will be created as
root, and the instance will not have privileges to write anything
there.
=> docker: fix the ES privileges on start

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
* Fixes a bug with ``author_list`` when the tarball is not part of the
``files``.
=> workflows: fix for ``author_list``

inspirehep/alembic/0bc0a6ee1bc0_create_index_on_referenced_records.py, inspirehep/modules/records/api.py, inspirehep/modules/records/mappings/v5/records/data.json, inspirehep/modules/records/receivers.py, inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/serializers/schemas/json.py, tests/integration/records/test_records_api.py, tests/integration/records/test_records_serializers_json.py, tests/integration/test_alembic.py
INSPIR-1126 alembic: Allow querying for citing records
INSPIR-1149 serializers: Extend the json sent to elasticsearch to include the citation count
Also fixes problem with testing alembic migrations added after "eaab22c59b89".
Elastic search now will receive citation counts
Also Serializer for search page will receive citation count
Also Serializer for single Literature entry will now receive citation count
Also fixed few Indentation to be consistent with PEP8
- [] All new and existing tests passed.
=> INSPIR-1126 and INSPIR-1149

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/fixtures/multiple_matches_arxiv.json, tests/integration/workflows/fixtures/multiple_matches_arxiv_update.json, tests/integration/workflows/fixtures/multiple_matches_publisher.json, tests/integration/workflows/test_arxiv_workflow.py
When a workflow matches exactly more than one record in inspire, halt it with an appropriate message, to review by a curator.
Supersedes #3587 and supersedes #3592 
#3586 and [INSPIR-1223](https://its.cern.ch/jira/browse/INSPIR-1223)
=> workflows: halt on multiple exact matches

inspirehep/modules/records/mappings/v5/records/authors.json, inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
Added name_variation field to author records mappings as they are needed in in order to support the current minimal author search.
=> receivers: populate name_variations for author records

inspirehep/alembic/53e8594bc789_fix_the_production_db.py, inspirehep/alembic/cb9f81e8251c_add_record_metadata_indices.py, inspirehep/alembic/eaab22c59b89_insert_migrator_use_api_action_role.py, inspirehep/alembic/fddb3cfe7a9c_create_inspirehep_tables.py, inspirehep/config.py, inspirehep/modules/records/indexer.py, inspirehep/modules/records/receivers.py, inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/serializers/schemas/json/literature/__init__.py, inspirehep/wsgi_with_coverage.py, tests/integration/conftest.py, tests/integration/migrator/test_migrator_cli.py, tests/integration/records/test_records_api.py, tests/integration/records/test_records_serializers_json.py, tests/integration/test_alembic.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_arxiv_merge.py, tests/ui/conftest.py, tests/unit/conftest.py
updated tests. Fixing issue with missing citation_count on ES
InvenioRecordIndexer assumes that all records are (Invenio) Records, so when record is passed to ES it cannot check its own citations count as the method for it is a part of InspireRecord
Thanks to this change ES will be now populated with proper data about citations
INSPIR-1126
=> Replace InvenioRecordIndexer with InspireRecordIndexer

inspirehep/modules/records/serializers/schemas/json/literature/__init__.py, inspirehep/modules/records/serializers/schemas/json/literature/common/collaboration.py, inspirehep/modules/records/serializers/schemas/json/literature/common/collaboration_with_suffix.py, tests/unit/records/serializers/literature/common/test_collaboration.py
Moved the collaboration logic from frontend to the serializers. Split collaborations into 2 lists : collaborations and collaborations_with_suffix.
=> Move collaboration logic to serializer

inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/serializers/response.py, inspirehep/modules/records/views.py, inspirehep/modules/search/search_factory.py, tests/integration/test_search_views.py
Aggregations for facets are now splitted from main query
url for aggregations: api/literature/facets
=> Split aggregation and query in two queries

inspirehep/modules/search/search_factory.py, tests/integration/test_search_views.py
number_of_references were inconsistent in search and detail page,
because search_factory was only getting reference that have reference.title.
=> search: fix inconsistent number of references

tests/integration/conftest.py, tests/integration/helpers/factories/db/invenio_records.py, tests/integration/workflows/conftest.py
This gets rid of the instability we were seeing in the workflow tests
when creating multiple fake inspire records.
=> isolated_app: avoid control_number collisions

inspirehep/factory.py
This saves an extra request as the UI always uses the url without
the trailing slash, and gets a 301
=> global: don't redirect with trailing slashes

inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/serializers/schemas/json/literature/common/citation_item.py, inspirehep/modules/records/utils.py, inspirehep/modules/records/views.py, tests/integration/records/test_records_serializers_json.py, tests/integration/records/test_records_views.py
Replaced the db query with an elastic search query which contains pagination and sorting. Added earliest_date to the serializer.
Removed citations_count from the literature endpoint as it was not used.
=> Sort citations by earliest_date

inspirehep/modules/orcid/tasks.py, tests/integration/orcid/fixtures/test_orcid_tasks_import_legacy_tokens_TestImportLegacyOrcidTokens_author.json, tests/integration/orcid/fixtures/test_orcid_tasks_import_legacy_tokens_TestImportLegacyOrcidTokens_literature.json, tests/integration/orcid/test_orcid_tasks_import_legacy_tokens.py
Legacy might send (orcid, token, email, name) with an empty string as email or name (because this info was not found in the PERSON table nor in HepNames, yet there is a valid orcid token).
Labs creates a User and email is a mandatory and unique field.
To solve this issue, we generate a random string as email (in case the email is empty) according to a pattern.
=> 1313 orcid: generate random email when email is blank in import_legacy_orcid_tokens

inspirehep/modules/records/mappings/v5/records/hep.json, inspirehep/modules/records/receivers.py, inspirehep/modules/records/serializers/schemas/json/literature/__init__.py, inspirehep/modules/records/utils.py, inspirehep/modules/search/search_factory.py, tests/integration/test_search_views.py, tests/unit/records/serializers/literature/test_schemas_json.py, tests/unit/records/test_records_utils.py
* Puts number of references into another field in order to avoid
returning all references just for counting later.
=> remove references from hep search results

Procfile, docker-compose.yml, inspirehep/modules/records/api.py, inspirehep/modules/records/receivers.py, inspirehep/modules/records/tasks.py, tests/integration/conftest.py, tests/integration/records/test_records_receivers.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_workflows_tasks_actions.py
Changes in the current receiver `models_committed` to trigger a celery task, which computes the references diff between the current and previous version of the record and indexes the cited records.
However, before computing the references diff, the task checks that the current version of the record in the DB is the one it expects to find (passed before by the receiver). If it is not, it retries itself with exponential time.
A new celery queue called `bulk_index` is used for reindexing the cited records.
=> citation count: index new citation's records - INSPIR-1127

inspirehep/modules/orcid/tasks.py, setup.py, tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_already_existent.yaml, tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_happy_flow.yaml, tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_invalid_data_orcid.yaml, tests/integration/orcid/fixtures/test_orcid_tasks_orcid_push_TestOrcidPush.json, tests/integration/orcid/test_orcid_domain_models.py, tests/integration/orcid/test_orcid_tasks_orcid_push.py
And requirements bump for inspire-service-orcid>=3.2.0 with new exceptions ExternalIdentifierRequiredException and Generic400Exception
=> 1539 orcid: add TestOrcidPushTask tests

setup.py
inspire-service-orcid>=3.2.1 with fixed utils.smartget()
=> 1539 orcid: requirement bump

tests/unit/theme/test_theme_views.py
* ``/feedback`` is not working correctly, and the tests are
part of ``unit`` tests. We'll create a proper feedback with the
new UI.
=> tests: remove wrongly integration tests inside unit tests

tests/integration/orcid/test_orcid_domain_models.py
The test fails because it tries to cache a Mock object, now replaced
with the real string.
=> 1638 orcid tests: redis==3.0.0.post1 only allows accept basic data types

inspirehep/modules/migrator/utils.py, inspirehep/modules/migrator/views.py
The previous query was filtering out `DELETED` records in a naive way
that doesn't benefit from the DB index. This is fixed by providing the
explicit list of collections that we do want to return.
=> migrator: make exceptions dashboard fast

inspirehep/modules/records/serializers/schemas/json/literature/common/conference_info_item.py, tests/integration/records/serializers/literature/test_schemas_json.py
* Returns empty if conference_record.$ref is present but refereced
record is not on the DB.
=> serializers: handle missing conference_record

setup.py
As mentioned in the comment on the code, ``flask-shell-ipython`` requires a ``flask>=1.0`` which is incompatible with our code, as we use ``flask>=0.12.4`` . Pinning the version of ``flask-shell-ipython`` to the last one that works with the same ``flask`` version as ours.
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
=> pin flask-shell-ipython version

inspirehep/utils/ext.py, requirements.txt, setup.py
Temporarily until https://github.com/kpn-digital/py-timeexecution/pull/38 gets merged
=> 1850 metrics: use timeexecution fork

setup.py
as version 0.22.1 has broken formating and is not possible to import pybtex library from version 0.22.1 in python 2.7
=> Stick to pybtex 0.22.0 

inspirehep/config.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/author.py, inspirehep/modules/workflows/workflows/edit_article.py, tests/unit/workflows/test_workflows_tasks_submission.py
No tests for this as it's hard to test: requests in the workflow unit tests are tested with `request-mock`, which doesn't provide a simple way to match on POST request arguments. So it would require either implementing custom matching logic or using vcr instead.
=> workflows: make robotupload priority configurable INSPIR-1899

inspirehep/modules/migrator/tasks.py, tests/integration/migrator/test_migrator_tasks.py
Previously, when the record was invalid, `record.commit` triggered an
exception which was handled and hence didn't roll back the transaction.
By adding a nested transaction, it is correctly rolled back. This is
similar to #3828.
JIRA: INSPIR-2113
=> migrator: fix wrong transaction handling

inspirehep/modules/records/serializers/schemas/json/literature/common/conference_info_item.py, inspirehep/modules/records/serializers/schemas/json/literature/common/publication_info_item.py, tests/integration/records/serializers/literature/test_schemas_json.py, tests/unit/records/test_records_receivers.py
* Added acronyms, page_start and page_end to conference info because we need it in the ui_display field
* INSPIR-2069
=> serializer: add data to conference_info_item

inspirehep/modules/records/cli.py, tests/integration_async/test_records_cli.py
This commit removes from the query for reindexing the check for deleted record. This is possible because the `batch_reindex` task already filters out deleted record when the metadata is loaded to be enhanced before reindexing.
* INSPIR-2353
=> cli: decrease query time for simpleindex command

setup.py
Newer versions of scikit-learn are Python 3 only.
=> setup: pin scikit-learn to v0.20.*

inspirehep/__init__.py, inspirehep/version.py, setup.py
* We don't need the version check anymore, we'll
use inspire-next on kb8s.
=> global: remove the version check

inspirehep/config.py, inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_arxiv_workflow.py, tests/integration/workflows/test_workflows_tasks_upload.py
* add: Feature flag: ENABLE_INSPIREHEP_REMOTE_RECORD_MANAGEMENT - when set to true will save records through inspirehep records API
* INSPIR-2311
=> workflows: Allow workflows to create records via HTTP with inspirehep

Dockerfile
This also installs the `requirements.txt` in the same step as all other requirements.
As a result, the docker image is now 200 MB smaller (1.51 GB instead of 1.71 GB).
=> Dockerfile: disable pip cache

inspirehep/modules/refextract/utils.py, tests/unit/refextract/test_refextract_utils.py
Punctuation handling was incorrect, resulting in wrong journal normalizations. See https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/topic/wrong.20refextract.20normalization/near/166211712 for details.
=> refextract: correct punctuation in journal kb

inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_edit_article.py, tests/integration/workflows/test_workflows_tasks_upload.py
* Receive uuid instead of _id in store record because Inspirehep no longer send id_, it now sends uuid 
* INSPIR-2572
=> workflows: rename id_ to uuid

setup.py
* This was skipped due to a missing comma in setup.py and didn't fail
when installing deps due to lax parsing of versions in pip:
https://travis-ci.org/inspirehep/inspire-next/jobs/593223691#L549
=> setup: add babel dependency back

inspirehep/modules/editor/bundles.py
* This shouldn't be needed but there is no way to force deployment of
new inspire-next image with new record-editor without pushing to this
repo.
=> editor: bump editor patch version

setup.py
Collecting the coverage metrics on Coveralls has been broken since
September 2018 due to a change in the format of the .coverage file
that happened in coverage==5.0a2. So we can restore it by pinning
the previous and current stable version.
Last build that passed: https://coveralls.io/builds/18814566
Offending release of `coverage`: https://pypi.org/project/coverage/5.0a2/
This build passes: https://coveralls.io/builds/27541479
=> setup: pin coverage.py

inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_article_workflow.py
If workflow is CORE, create a ticket in hep_publisher queue if the workflow is coming from the publisher. Otherwise create a ticket in hep_curation queue.
Ref: https://github.com/inspirehep/inspirehep/issues/1511
=> workflows: create rt ticket in hep_curation/hep_publisher queues for core records

inspirehep/modules/search/bundles.py, inspirehep/modules/workflows/tasks/matching.py
* changed ids from plain strings to urls in error messages
* ref: cern-sis/issues-inspire#20
=> holdingpen: link workflow ids

inspirehep/modules/search/bundles.py, inspirehep/modules/workflows/tasks/matching.py
* use html tags inside string for proper render of links
* ref: cern-sis/issues-inspire#20
=> holdingpen: link workflow ids - use html tags

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_arxiv_workflow.py, tests/integration/workflows/test_workflows_tasks_actions.py, tests/integration_async/test_workflows.py, tests/unit/workflows/test_workflows_tasks_actions.py
* ref: cern-sis/issues-inspire#347
=> workflows: enable matcher on hep

inspirehep/config.py, inspirehep/modules/workflows/tasks/actions.py
Add feature flag to disable the workflow save to db inside the document download function.
ref: https://github.com/cern-sis/issues-inspire/issues/417
=> doc download: add save workflow feature flag

inspirehep/modules/workflows/tasks/actions.py
* ref: cern-sis/issues-inspire#462
=> matcher: request explicitly XML format in grobid

CentOS-Base.repo, Dockerfile, Dockerfile.dev
Centos 7 reached its end of life: https://www.redhat.com/en/blog/centos-linux-has-reached-its-end-life-eol
with that the repositories were moved to the archive at vault.centos.org.
This PR is a workaround, changing the default repository url.
=> docker: add workaround for centos7 version

inspirehep/modules/workflows/utils/__init__.py
The python 3.11 upgrade of inspirehep will require the requests to be passed with the content type json header.
=> headers: add content-type json

inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/core_selection.py, tests/integration/workflows/test_article_workflow.py
kept the actual function in case we need it again at some later stage
ref: https://github.com/cern-sis/issues-inspire/issues/554
=> workflows: remove prepare_keywords step

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_actions.py
ref: https://github.com/cern-sis/issues-inspire/issues/576
=> workflows: check published papers for uk queue

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_article_workflow.py, tests/unit/workflows/test_workflows_actions.py
ref: https://github.com/cern-sis/issues-inspire/issues/623
=> workflows: add core requirement to uk and ger queue

.github/workflows/backend-tests-on-docker.yml
We need to bump actions/cache as its getting deprecated: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
Also bumped the checkout action, because why not.
=> gh-actions: bump cache and checkout action
