inspire/modules/workflows/tasks/submission.py

Fixes RT creation on non-production mode.

deposit: fix non production mode RT creation

---

fabfile.py
inspire/config.py
inspire/modules/harvester/config.py
inspire/modules/harvester/definitions.py
inspire/modules/harvester/manage.py
inspire/modules/harvester/tasks/__init__.py
inspire/modules/harvester/tasks/world_scientific.py
inspire/modules/harvester/templates/harvester/ftp_upload_notification.html
inspire/modules/harvester/utils.py
inspire/modules/harvester/views.py
inspire/modules/harvester/workflows/world_scientific.py
inspire/modules/harvester/workflows/world_scientific_harvesting.py
setup.py

harvester: new module for harvesting

---

inspire/modules/deposit/workflows/literature.py
inspire/modules/workflows/tasks/submission.py

* Automatically closes the submission ticket upon finished workflow.
* Sets the ticket status back to "new" after replying to it the first
time.

deposit: automatic ticket status handling

---

inspire/testsuite/test_text.py
inspire/utils/robotupload.py
inspire/utils/text.py

Based on an issue faced when trying to ship xml with bad characters on Labs.

Clean XML before shipping to robotupload

---

README.rst

base: update README

---

inspire/modules/workflows/actions/core_approval.py

workflows: add title to rejected submission text

---

inspire/testsuite/test_text.py
inspire/utils/text.py

* Correct handling of utf-8 characters.
* Adds test case.

utils: clean_xml fix

---

inspire/base/bundles.py
inspire/base/static/js/feedback/feedback.js
inspire/base/static/js/feedback/templates/button.mustache
inspire/base/static/js/feedback/templates/error.mustache
inspire/base/static/js/feedback/templates/modal.mustache
inspire/base/static/js/feedback_inspire.js
inspire/base/static/js/settings.js
inspire/base/static/less/feedback/button.less
inspire/base/static/less/feedback/modal.less
inspire/base/testsuite/__init__.py
inspire/base/testsuite/js/feedback.spec.js
inspire/base/views.py
inspire/config.py

* Rewrites the feature without inspirehep/feedback.js. Builds the
modal using Bootstrap classes, making it responsive.  (closes #199)
* Adds some validation to avoid submitting an empty form.
(CC: @kaplun @jalavik @jmartinm)

feedback: rewrite without feedback.js

---

requirements.txt
setup.py

* Reorganizes requirements and setup.py dependencies.

base: requirements cleanup

---

inspire/modules/workflows/templates/workflows/results/classifier.html
inspire/testsuite/test_holdingpen.py

* Improves the ordering of classification keywords based on its
frequency.
* Adds a new test file to check output of Holding Pen templates.
Co-authored-by: Ilias Koutsakis <ilias.koutsakis@cern.ch>
Co-authored-by: Florian Schwennsen <florian.schwennsen@desy.de>

workflows: ordered classification results

---

inspire/modules/classifier/core.py

CC @jalavik  @Lilykos 
This requires Numpy, Scipy, Scikit-Learn and Beard as additional dependencies.

classifier: automatic tagging of CORE records

---

README.rst

README: add recommended developer config

---

inspire/modules/workflows/static/js/workflows/actions/arxiv_approval.js
inspire/modules/workflows/static/js/workflows/actions/batch_action_hotkeys.js

* Implements the batch action POST request.
* Cleans up the code.
Signed-off-by: Ilias Koutsakis <ilias.koutsakis@cern.ch>

workflows: hotkeys implementation

---

inspire/modules/workflows/tasks/matching.py

workflows: update the way arXiv ID matching is done

---

inspire/dojson/conferences/schemas/conferences-0.0.1.json

dojson: new conferences-0.0.1.json

---

inspire/modules/deposit/workflows/literature.py
inspire/modules/predicter/tasks.py
inspire/modules/predicter/utils.py
inspire/modules/workflows/actions/core_approval.py

deposit: prediction in literature submission

---

inspire/utils/bibtex_booktitle.py

utils: fixes bibtex_booktitle problem

---

inspire/modules/deposit/dojson/fields/literature.py
inspire/modules/deposit/workflows/literature.py

@Lilykos @jmartinm 
This makes sure there is always arxiv_category if it's an arXiv import.

deposit: add arxiv_category for literature submissions

---

inspire/base/templates/format/record/Inspire_Default_HTML_brief_macros.tpl

* Show more abstract displays the rest of the abstract

format: HEP brief format fixes

---

inspire/base/searchext/mappings/institutions.json
inspire/dojson/institutions/fields/bd1xx.py
inspire/dojson/institutions/schemas/insitutions-0.0.1.json
inspire/modules/converter/tasks.py
inspire/modules/workflows/workflows/oaiharvest_production_sync.py

* Updates the dojson conversion, schema and index mappings.

dojson: institutions data model update

---

inspire/modules/workflows/templates/workflows/details.html

Depends on https://github.com/inveniosoftware/invenio-workflows/pull/11

workflows: use available data and extra_data

---

inspire/base/searchext/mappings/conferences.json
inspire/base/searchext/mappings/experiments.json
inspire/base/searchext/mappings/hep.json
inspire/base/searchext/mappings/institutions.json
inspire/base/searchext/mappings/jobs.json
inspire/base/searchext/mappings/journals.json
inspire/config.py

Depends on https://github.com/inveniosoftware/invenio/pull/3450

WIP base: elasticsearch index configuration

---

inspire/base/static/js/search/search_results.js

search: removes unused code from search_results.js

---

inspire/dojson/hep/fields/bd1xx.py
inspire/dojson/hep/schemas/hep-0.0.1.json
inspire/dojson/hepnames/fields/bd1xx.py
inspire/dojson/utils.py

* Changed hep schema to handle new fields: author's profile and claimed
status.
* Added method to create hep authors' profiles links based on profile_id.
* Hepnames' start_year and end_year handle ValueErroe error exception.
* Removed controlfields from sample XML file.

dojson: profile and claimed fields

---

.travis.yml

travis: demo records being loaded

---

.travis.yml
README.rst

travis: coveralls support

---

.coveragerc
pytest.ini

travis: add missing .coveragerc

---

inspire/modules/citations/__init__.py
inspire/modules/citations/config.py
inspire/modules/citations/models.py
inspire/modules/citations/tasks.py
inspire/modules/citations/testsuite/__init__.py
inspire/modules/citations/testsuite/test_citations.py

* Adds citations functionality on labs.
* Adds models for Citations and Citation Log.
* Pulls log from production and populates rnkCITATIONDICT and rnkCITATIONLOG tables.
* Updates records with a new field (references_id) containing the ids of the references.
* Adds test cases for database insertions and record updates.

citations: production citation syncronization

---

inspire/dojson/hep/__init__.py
inspire/dojson/hep/receivers.py
inspire/dojson/hep/schemas/hep-0.0.1.json
inspire/dojson/utils.py

* Adds earliest_date field to HEP schema.
* New method for generating earliest_date on before_record_insert and
before_record_update signals.
* New methods for formating dates in utils.py

dojson: earliest_date field

---

base.requirements.txt
requirements.production.txt
requirements.qa.txt
requirements.txt
setup.py

* Sets up temporary dependencies inside base.requirements.txt so
that `qa` and `production` branches can re-use it.
* Adds `invenio-query-parser>=0.3.0` to general dependencies.

setup: refactor deployment requirements

---

inspire/base/searchext/mappings/hep.json
inspire/config.py
inspire/dojson/hep/fields/bd01x09x.py
inspire/dojson/hep/fields/bd1xx.py
inspire/dojson/hep/fields/bd20x24x.py
inspire/dojson/hep/fields/bd5xx.py
inspire/dojson/hep/fields/bd6xx.py
inspire/dojson/hep/fields/bd70x75x.py
inspire/dojson/hep/fields/bd76x78x.py
inspire/dojson/hep/fields/bd84188x.py
inspire/dojson/hep/schemas/hep-0.0.1.json
inspire/dojson/utils.py
inspire/modules/authors/utils.py
inspire/modules/oaiharvester/tasks/arxiv.py
inspire/modules/workflows/tasks/matching.py
inspire/testsuite/fixtures/test_hep_record.xml
inspire/testsuite/test_hep.py
inspire/testsuite/test_matching.py

dojson: fixes from validation

---

.travis.yml

travis: coveralls fix

---

inspire/dojson/hep/receivers.py
inspire/modules/deposit/dojson/fields/literature.py
inspire/modules/deposit/workflows/literature.py

Had to make some fixes for `earliest_date` field. @jacenkow

dojson: fix earliest date parsing

---

base.requirements.txt
inspire/base/mixer/sources/oaiHARVEST.json
inspire/base/static/js/settings.js
inspire/config.py
inspire/modules/citations/upgrades/citations_2015_09_29_initial.py
inspire/modules/deposit/bundles.py
inspire/modules/deposit/static/js/deposit/inspire_init.js
inspire/modules/deposit/templates/deposit/run.html
inspire/modules/migrator/config.py
inspire/modules/migrator/manage.py
inspire/modules/migrator/tasks.py
inspire/modules/workflows/upgrades/inspire_2015_09_30_oaiharvest_update.py
setup.py

Adds a migrator manager which helps with database/index migrations.
Also adds some new temporary forks of invenio packages required.
Adds upgrade recipe for citations modules.

WIP Migration and dependencies

---

inspire/dojson/hep/fields/bd01x09x.py
inspire/dojson/hep/fields/bd20x24x.py
inspire/dojson/hep/fields/bd5xx.py
inspire/dojson/hep/fields/bd6xx.py
inspire/dojson/hep/fields/bd70x75x.py
inspire/dojson/hep/fields/bd76x78x.py
inspire/testsuite/fixtures/test_hep_record.xml
inspire/testsuite/test_hep.py

* Implements complete test for hep record.

dojson: fixes mistakes in hep fields

---

inspire/base/templates/format/record/Journal_HTML_brief.tpl
inspire/dojson/journals/fields/bd1xx.py

journals: fixes problems in brief

---

inspire/base/searchext/mappings/experiments.json
inspire/base/templates/format/record/Experiment_HTML_brief.tpl
inspire/config.py
inspire/dojson/experiments/fields/bd1xx.py

experiments: fixes problems in brief

---

inspire/base/templates/format/record/Author_HTML_brief.tpl

authors: fixes problems in brief

---

inspire/base/templates/format/record/Job_HTML_brief.tpl
inspire/dojson/jobs/fields/bd1xx.py
inspire/ext/formatter_jinja_filters/record.py

* Adds link to find the institution the job belongs.
* Adds link to find the experiment the job belongs.

template: jobs brief institution search

---

inspire/base/templates/format/record/Conference_HTML_detailed.tpl
inspire/base/templates/format/record/Experiment_HTML_detailed.tpl

templates: removes leftovers from detailed results

---

inspire/modules/deposit/static/js/deposit/affiliations_typeahead.js
inspire/modules/deposit/static/js/deposit/conferences_typeahead.js
inspire/modules/deposit/static/js/deposit/data_sources/arxiv.js
inspire/modules/deposit/static/js/deposit/data_sources/data_source.js
inspire/modules/deposit/static/js/deposit/extended_typeahead.js
inspire/modules/deposit/static/js/deposit/fields_group.js
inspire/modules/deposit/static/js/deposit/inspire_init.js
inspire/modules/deposit/static/js/deposit/literature_submission_form.js
inspire/modules/deposit/static/js/deposit/mapper.js
inspire/modules/deposit/static/js/deposit/message_box.js
inspire/modules/deposit/static/js/deposit/stats/deposition_charts.js
inspire/modules/deposit/static/js/deposit/stats/init.js
inspire/modules/forms/static/js/forms/authors_typeahead.js
inspire/modules/forms/static/js/forms/experiments_typeahead.js
inspire/modules/forms/static/js/forms/inspire-form.js
inspire/modules/styleguide/static/js/dropdown.js
inspire/modules/styleguide/static/js/scrollspy.js
inspire/modules/styleguide/static/js/sg-plugins.js
inspire/modules/styleguide/static/js/sg-scripts.js
inspire/modules/workflows/static/js/workflows/actions/arxiv_approval.js
inspire/modules/workflows/static/js/workflows/actions/batch_action_hotkeys.js
inspire/modules/workflows/static/js/workflows/actions/core_approval.js
inspire/modules/workflows/static/js/workflows/actions/core_approval_modal.js
inspire/modules/workflows/static/js/workflows/actions/editable_subjects.js
inspire/modules/workflows/static/js/workflows/actions/editable_title.js
inspire/modules/workflows/static/js/workflows/actions/editable_urls.js

* Uses js-beautifier in all JavaScript in the overlay to keep
consistency.

global: JS beautification

---

Gruntfile.js
inspire/base/static/js/build.js
inspire/base/static/js/feedback/feedback.js
inspire/base/static/js/feedback_inspire.js
inspire/base/static/js/header/header.js
inspire/base/static/js/inspire_base_init.js
inspire/base/static/js/jquery_plugin.js
inspire/base/static/js/notification.js
inspire/base/static/js/search/invenio_with_spires_typeahead_configuration.js
inspire/base/static/js/search/search_box.js
inspire/base/static/js/search/search_results.js
inspire/base/static/js/settings.js

* Adds beautifier for base path.

jsbeautifier: beautifies all js files

---

inspire/base/templates/format/record/Inspire_Default_HTML_brief.tpl
inspire/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl

* Removes unneccesary check of duplicate values.

format: brief removal of duplicate check

---

inspire/dojson/hepnames/fields/bd1xx.py
inspire/dojson/hepnames/schemas/hepnames-0.0.1.json

hepnames: fixes bug in field_categories

---

inspire/base/classifierext/taxonomies/HEPontCore.rdf

* Updates the DESY maintained HEP ontologies.
Signed-off-by: fschwenn <florian.schwennsen@desy.de>

classifierext: update HEP ontologies

---

base.requirements.txt
setup.py

installation: use invenio-grobid from PyPi

---

docs/grobid.rst
docs/index.rst

This probably needs to be expanded a little more.
CC: @jalavik

WIP docs: GROBID documentation

---

inspire/base/templates/format/record/Inspire_Default_HTML_brief.tpl

brief: fixes duplication title problem

---

inspire/dojson/hep/fields/bd3xx.py
inspire/modules/deposit/dojson/fields/literature.py
inspire/modules/deposit/testsuite/fixtures/hep_submission_form.json
inspire/modules/deposit/testsuite/test_hep_submission.py
inspire/modules/deposit/workflows/literature.py
inspire/testsuite/test_hep.py

* Alters submission data conversion to comply with latest data
model.
* Adds tests for the data conversion.

deposit: data model related fixes

---

inspire/dojson/hep/fields/bd5xx.py
inspire/dojson/hep/schemas/hep-0.0.1.json
inspire/modules/workflows/dojson/__init__.py
inspire/modules/workflows/dojson/fields/__init__.py
inspire/modules/workflows/dojson/fields/bibfield.py
inspire/testsuite/fixtures/test_bibfield_record.json
inspire/testsuite/test_bibfield.py

* Improves the conversion of BibField (old data model) to the
new data model.
* Adds tests for the conversion.

dojson: BibField->HEP data model conversion

---

inspire/base/templates/format/record/Holding_Pen_HTML_detailed.tpl
inspire/dojson/hep/fields/bd84188x.py
inspire/dojson/hep/schemas/hep-0.0.1.json
inspire/modules/deposit/dojson/fields/literature.py
inspire/modules/deposit/testsuite/test_hep_submission.py
inspire/testsuite/test_hep.py
inspire/utils/bibtex.py

dojson: changes url to urls

---

inspire/base/templates/format/record/Author_HTML_brief.tpl
inspire/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspire/ext/formatter_jinja_filters/record.py

brief: fixes mistakes after introducing new model

---

inspire/dojson/hep/fields/bd01x09x.py
inspire/modules/oaiharvester/tasks/arxiv.py
inspire/testsuite/fixtures/test_hep_formats.xml
inspire/testsuite/test_bibtex.py
inspire/testsuite/test_cvlatex.py
inspire/testsuite/test_cvlatex_html_text.py
inspire/testsuite/test_export.py
inspire/testsuite/test_latex.py
inspire/testsuite/test_matching.py
inspire/utils/bibtex.py
inspire/utils/cv_latex.py
inspire/utils/cv_latex_html_text.py
inspire/utils/export.py
inspire/utils/latex.py

* Creates test for bibtex article.
* Creates test for latex(EU, US).
* Creates test for Cv Latex(html,text).
* Creates test for Cv Latex.
* Creates test for export.
* (addresses #403)

formats: fixes errors caused by new model

---

inspire/modules/audit/api.py
inspire/modules/predicter/arxiv.py
inspire/modules/workflows/actions/arxiv_approval.py
inspire/modules/workflows/tasks/actions.py
inspire/modules/workflows/workflows/ingestion_arxiv_math.py
inspire/modules/workflows/workflows/process_record_arxiv.py

Adds an automatic reject filter for arXiv workflow on current Labs production.

Rejection filter for current labs production

---

docs/conf.py

docs: mock certain modules when building

---

inspire/base/bundles.py
inspire/testsuite/test_cvlatex_html_text.py

* Amends tests to reflect API changes in 835286c94.
* Improves kwalitee.

testsuite: test fixes

---

inspire/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl

* Increases font size of authors and affiliations in modal window (closes #473).

format: detailed record affiliations

---

inspire/base/templates/format/record/Inspire_HTML_detailed_macros.tpl

* Resolves an issue with keyword search (closes #469).

format: detailed HEP record keywords

---

inspire/base/templates/format/record/Inspire_Default_HTML_detailed.tpl
inspire/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspire/base/templates/references.html
inspire/utils/references.py

* Updates display of references in detailed record (closes #468).

format: HEP detailed record references

---

inspire/base/static/js/dropdown-menu/dropdown-menu.js

header: fixes mega dropdown dependencies for firefox

---

inspire/testsuite/test_workflows.py

testsuite: improve workflows ES mock

---

inspire/base/templates/format/record/Inspire_Default_HTML_brief.tpl
inspire/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspire/base/templates/format/record/Inspire_HTML_detailed_macros.tpl
inspire/ext/formatter_jinja_filters/record.py

* Displays PDF's correctly
* Removes popover affiliations from modal window
* Displays external links correctly

format: bug fixes on HEP detailed record

---

inspire/base/templates/format/record/Job_HTML_brief.tpl

templates: adds creation date to jobs collection

---

inspire/base/static/js/search/search_results.js
inspire/base/static/less/format/brief-results.less
inspire/base/templates/search/form/form.html
inspire/base/templates/search/results.html
inspire/config.py

* Adds sort dropdown to search control panel.
* Introduces SEARCH_ELASTIC_SORT_FIELDS config variable that
lists allowed sort fields.

search: sorting addition

---

inspire/base/searchext/mappings/journals.json
inspire/modules/deposit/forms.py
inspire/modules/deposit/static/js/deposit/journals_typeahead.js
inspire/modules/forms/static/js/forms/inspire-form.js

deposit: fix autocompletion of the journals

---

inspire/base/static/less/format/brief-results.less
inspire/base/static/less/format/detailed-record.less

* Updates the copyright of LESS files in brief and detailed record.

format: LESS files copyright update

---

inspire/testsuite/test_ICU.py

* Adds a test that checks if ICU is installed.

elasticsearch: ICU plugin test

---

inspire/base/static/js/search/search_results.js
inspire/base/templates/search/results.html

export: adds disable class to download button

---

inspire/modules/migrator/tasks.py

migrator: functional implementation

---

inspire/base/static/js/search/form.js

facets: fixes search bug

---

inspire/base/static/js/search/search_results.js

export: fixes select all records problem

---

inspirehep/version.py
tests/helpers.py
tests/test_version.py

I really don't like files with 0% test coverage, even when trivial. Other tests will follow in other PRs.

Test version.py

---

inspirehep/dojson/conferences/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd76x78x.py
inspirehep/dojson/hep/fields/bd84188x.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/processors.py
inspirehep/modules/migrator/manage.py
inspirehep/modules/migrator/models.py
inspirehep/modules/migrator/tasks.py
inspirehep/modules/migrator/upgrades/inspire_2015_11_30_prod_records_add_indexes.py

Just latest works, including dojson fixes. I need to also rebase this branch.

Migrator fixes

---

inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl

* Displays the collaboration, if it's available.

format: display collaboration

---

INSTALL.rst
inspirehep/base/searchext/mappings/hep.json
inspirehep/config.py
inspirehep/modules/migrator/manage.py
inspirehep/modules/migrator/tasks.py
install.sh
tests/test_citation_count.py

citations: add migrator command to count citations count for all records added during migration

citations: add migrator command

---

inspirehep/base/templates/search/facets/hep.html
inspirehep/modules/records/receivers.py

facets: adds missing parts 

---

INSTALL.rst

install: fixes typo in migrator

---

inspirehep/modules/migrator/tasks.py

* add citation_count to all records, not only those that have references

citations: citation_count fix

---

inspirehep/config.py
inspirehep/ext/redis/__init__.py
inspirehep/ext/redis/client.py
inspirehep/ext/redis/proxy.py

* added extension for redis client

ext: redis client

---

tests/test_citation_count.py

tests: fix usage of Query().search().recids

---

base.requirements.txt
inspirehep/base/static/less/workflows/workflows.less
inspirehep/base/templates/format/record/Holding_Pen_HTML_detailed.tpl
inspirehep/base/templates/format/record/Holding_Pen_HTML_detailed_macros.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspirehep/config.py
inspirehep/modules/deposit/workflows/literature.py
inspirehep/modules/migrator/tasks.py
inspirehep/modules/migrator/upgrades/inspire_2015_11_24_prod_records.py
inspirehep/modules/migrator/utils.py
inspirehep/modules/workflows/dojson/fields/bibfield.py
inspirehep/modules/workflows/models.py
inspirehep/modules/workflows/tasks/matching.py
inspirehep/modules/workflows/tasks/submission.py
inspirehep/modules/workflows/templates/workflows/list.html
inspirehep/modules/workflows/templates/workflows/macros.html
inspirehep/modules/workflows/upgrades/inspire_2015_10_01_update_workflow_data.py
inspirehep/modules/workflows/views/holdingpen_edit.py
inspirehep/modules/workflows/workflows/hep_ingestion.py
setup.py
tests/test_bibfield.py
tests/test_workflows.py

Fixes for upgrading script for updating the data model in Holding Pen.

Updates to Holding Pen migration

---

base.requirements.txt

Following the comment from https://github.com/inspirehep/invenio-records/pull/7#issuecomment-162937029

global: update invenio-records

---

inspirehep/modules/deposit/workflows/literature.py
inspirehep/modules/workflows/models.py

* Rearranges the workflow tasks to optimize user request time by
moving tasks from request processing to post-request processing.
* Fixes and issue with missing user comments in submission data.
@jmartinm

deposit: literature workflow improvement

---

inspirehep/dojson/hep/fields/bd01x09x.py

dojson: fix HEP language parsing

---

inspirehep/base/static/js/search/form.js
inspirehep/base/static/less/search/collection.less
inspirehep/base/templates/search/collection_basic.html
inspirehep/base/templates/search/results.html

base: typeahead searchbar fix

---

base.requirements.txt
setup.py

This contains the new code from @Panos512 in inspirehep/invenio-query-parser#1 to work around when querying for things that look like nested keywords.

travis: forcing new invenio-query-parser

---

inspirehep/modules/deposit/forms.py
inspirehep/modules/deposit/workflows/literature.py

* Fixes the literature submission extra data handling such as
user comments, references and url to PDF.

deposit: extra submission data fix

---

inspirehep/modules/migrator/tasks.py
tests/test_records.py

Co-authored-by: Samuele Kaplun <samuele.kaplun@cern.ch>

migrator: fix record update during migration

---

inspirehep/modules/migrator/tasks.py
inspirehep/modules/workflows/dojson/__init__.py
inspirehep/modules/workflows/dojson/fields/author_bibfield.py
inspirehep/modules/workflows/dojson/model.py
tests/fixtures/test_author_bibfield.json
tests/test_author_bibfield.py

* Migrates data inside author workflow objects in order to be
compatible with new data model.

authors: workflow data migration

---

inspirehep/modules/migrator/manage.py

migrator: recreate index fix

---

base.requirements.txt

requirements: use new invenio-workflows version

---

inspirehep/base/static/less/format/brief-results.less
inspirehep/base/static/less/search/collection.less

* Resolves an issue where search bar width was not 100% in Firefox.

search: search bar width in Firefox

---

base.requirements.txt
setup.py

base: use invenio-oauthclient fork

---

inspirehep/modules/migrator/manage.py

* Introduces support for reindexing by using the plugin available at
https://github.com/codelibs/elasticsearch-reindexing.

migrator: reindexing support

---

inspirehep/base/templates/search/facets/hep.html
inspirehep/config.py

Depends on https://github.com/inspirehep/invenio-search/pull/12

Author facet fix

---

inspirehep/modules/migrator/manage.py

migrator: reindex specific index

---

inspirehep/dojson/hep/model.py

* Allows for record post-processing in order to modify the record
after it has been generated by dojson.

dojson: custom do function for hep records

---

base.requirements.txt

requirements: oauthclient version bump

---

base.requirements.txt

global: new release of local invenio-query-parser

---

inspirehep/modules/migrator/tasks.py

citations: fix counting twice same reference

---

inspirehep/utils/bibtex.py
inspirehep/utils/export.py

bibtex: metadata sanity check

---

inspirehep/base/templates/format/record/Job_HTML_brief.tpl
inspirehep/dojson/jobs/fields/bd1xx.py

dojson: fixes jobs continent issue

---

inspirehep/base/searchext/mappings/journals.json
inspirehep/dojson/journals/fields/bd1xx.py

dojson: fixes journal issn issue

---

inspirehep/base/static/js/search/search_results.js
inspirehep/base/static/less/format/brief-results.less
inspirehep/base/templates/search/results.html

facets: adds clear filters button

---

inspirehep/config.py

* Adds the paths of Inspire installation and json schema file
to inspire's configuration file.
* Adds some keywords to elastic mapping.
* Changes the way parsers are referenced in the config file.

configuration: config additions

---

INSTALL.rst
inspirehep/base/templates/format/record/Job_HTML_detailed.tpl
inspirehep/dojson/hep/fields/bd1xx.py
inspirehep/modules/records/testsuite/test_records.py
install.sh

* New set of demo-records, this time with working claims.
* NOTE The new input file to be installed has been compressed
with gzip, in order to comply with GitHub size limitations.

demosite: demo-records.xml with claims

---

inspirehep/manage.py

* Amends the usage of Elasticsearch reindexing plugin by first
temporary allowing only a single Elasticsearch client host, before
using the plugin. In this way we can then correctly poll the same
client to check for the plugin status.

manage: reindexing on single client

---

inspirehep/config.py

facets: remove 0 results from year

---

inspirehep/modules/records/receivers.py

dojson: fixes document type problem

---

inspirehep/base/static/js/citation_modal.js
inspirehep/base/static/js/detailed_record_init.js
inspirehep/base/static/js/search/search_results.js
inspirehep/base/static/less/format/brief-results.less
inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl
inspirehep/base/templates/search/results.html
inspirehep/modules/formatter/views.py

* Changes download functionality to modal box.

search: implements cite all functionality

---

inspirehep/modules/records/receivers.py

Avoids `TypeError` when making a submission.

records: optional index argument in receivers

---

inspirehep/manage.py

inspirehep: flush after reindexing

---

inspirehep/base/static/js/settings.js

settings: use proper buckets JS path

---

base.requirements.txt
inspirehep/base/searchext/mappings/hep.json
inspirehep/config.py
inspirehep/modules/workflows/tasks/matching.py
inspirehep/modules/workflows/workflows/hep_ingestion.py
inspirehep/modules/workflows/workflows/process_record_arxiv.py
tests/test_matching.py
tests/test_workflows.py
tests/workflows/payload_fixture.py
tests/workflows/payload_model_fixture.py

Adds basic invenio-matcher integration to start building upon.
Supersedes #559

Matcher integration

---

inspirehep/modules/harvester/config.py
inspirehep/modules/harvester/utils.py

harvester: storage location fix

---

inspirehep/dojson/hep/fields/bd5xx.py

dojson: double abstract fix

---

inspirehep/config.py
inspirehep/modules/oaiharvester/tasks/arxiv.py
inspirehep/modules/refextract/tasks.py
inspirehep/modules/workflows/workflows/hep_ingestion.py
inspirehep/modules/workflows/workflows/process_record_arxiv.py
inspirehep/utils/arxiv.py
inspirehep/utils/knowledge.py
setup.py
tests/workflows/harvesting_fixture.py

Refextract integration

---

inspirehep/base/static/js/settings.js
inspirehep/modules/deposit/bundles.py
inspirehep/modules/deposit/static/js/deposit/fields_group.js

Co-authored-by: Samuele Kaplun <samuele.kaplun@cern.ch>
Tested with `ASSETS_DEBUG=False` and `True`
cc @kaplun @jmartinm

deposit: use bundlejs from bower

---

base.requirements.txt

requirements: bump OPS packages version

---

base.requirements.txt

sentry: enforce OPS raven version

---

inspirehep/dojson/utils.py
tests/test_dojson_utils.py

dojson: fix for dates < 1900

---

inspirehep/base/bundles.py
inspirehep/base/static/js/citation_modal.js
inspirehep/base/static/js/detailed_record_init.js
inspirehep/base/static/js/search/search_results.js
inspirehep/base/static/js/settings.js
inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspirehep/base/templates/search/results.html

cite: selects automatically bibtex

---

inspirehep/utils/cv_latex.py
inspirehep/utils/cv_latex_html_text.py
inspirehep/utils/latex.py
tests/fixtures/test_hep_publi_info.xml
tests/test_cvlatex.py
tests/test_cvlatex_html_text.py
tests/test_latex.py

utils: fixes publi_info in output formats

---

inspirehep/modules/workflows/dojson/fields/bibfield.py
tests/test_bibfield.py

bibfield: update collaboration field

---

inspirehep/modules/migrator/utils.py

workflows: upgrade script update

---

inspirehep/modules/migrator/tasks.py

* Improves add_citation_counts() by making it more verbose, using
the largest chunk size when gathering information and exploiting
native streaming capability of es_bulk.
* No longer stops at the first error in case of exception in es_bulk.

migrator: add_citation_counts improvements

---

inspirehep/base/static/less/base/header.less

* Resolves header display issues.

WIP header: display fixes

---

inspirehep/modules/records/receivers.py

records: experiments fix

---

base.requirements.txt
inspirehep/modules/citations/receivers.py

Co-authored-by: Samuele Kaplun <samuele.kaplun@cern.ch>

records: citations update receiver update

---

base.requirements.txt
inspirehep/config.py

requirements: bumps invenio-query-parser/search

---

base.requirements.txt

requirements: update invenio-ext version

---

inspirehep/base/static/less/base/header.less
inspirehep/base/static/less/search/collection.less
inspirehep/base/templates/header.html
inspirehep/base/templates/search/collection_authors.html
inspirehep/base/templates/search/collection_data.html
inspirehep/config.py

* Adds data collection to collection bar.
* Creates basic landing page.

global: Data collection addition

---

base.requirements.txt

global: invenio-records version bump

---

inspirehep/base/static/less/base/core.less
inspirehep/base/static/less/format/abstract.less
inspirehep/base/static/less/format/brief-results.less
inspirehep/base/static/less/format/detailed-record.less
inspirehep/base/static/less/search/collection.less
inspirehep/base/templates/format/record/Author_HTML_brief.tpl
inspirehep/base/templates/format/record/Conference_HTML_brief.tpl
inspirehep/base/templates/format/record/Experiment_HTML_brief.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_brief.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspirehep/base/templates/format/record/Institution_HTML_brief.tpl
inspirehep/base/templates/format/record/Job_HTML_brief.tpl
inspirehep/base/templates/format/record/Journal_HTML_brief.tpl
inspirehep/base/templates/page.html
inspirehep/base/templates/search/results.html

* Changes font from Lato to Helvetica Neue.
* Adapts font weights accordingly.
* Proper alignment of facet checkboxes.

templates: font family and weight changes

---

base.requirements.txt

requirements: bump invenio-search/ext

---

inspirehep/base/searchext/mappings/hep.json

searchext: remove nested author mapping

---

inspirehep/manage.py

inspirehep: no refreshing upon reindexing

---

base.requirements.txt
inspirehep/dojson/hep/fields/bd20x24x.py
inspirehep/modules/deposit/forms.py
inspirehep/modules/deposit/static/js/deposit/data_sources/arxiv.js
inspirehep/modules/deposit/static/js/deposit/data_sources/doi.js
inspirehep/modules/deposit/static/js/deposit/literature_submission_form.js
inspirehep/modules/deposit/utils.py
inspirehep/modules/deposit/workflows/literature.py
tests/fixtures/hep_submission_form.json
tests/test_hep.py

* Correct handling of titles based on source.
* Fix on Knowledge base limit.
* Fix Citeable collection addition.

deposit: multiple improvements

---

inspirehep/config.py

* Adds the path to elastic search mapping file in the config file.

configuration: elastic mapping path

---

inspirehep/base/static/less/base/header.less
inspirehep/base/static/less/format/detailed-record.less
inspirehep/base/static/less/search/collection.less
inspirehep/base/templates/header.html
inspirehep/base/templates/search/form/controls.html

header: fixes

---

inspirehep/utils/bibtex.py
inspirehep/utils/cv_latex.py
inspirehep/utils/cv_latex_html_text.py
inspirehep/utils/export.py
inspirehep/utils/latex.py
tests/fixtures/test_citation_line.xml
tests/test_export.py

utils: fixes citation number in formats

---

inspirehep/modules/migrator/tasks.py

* Fixes continuos_migration() implementation by properly
decompressing the retrieved record and providing a bit more of
information in the log.

migrator: fix continuos_migration()

---

inspirehep/base/templates/format/record/Inspire_Default_HTML_brief.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_brief_macros.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_detailed.tpl
inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl
inspirehep/base/templates/format/record/Institution_HTML_detailed.tpl
inspirehep/dojson/hep/fields/bd01x09x.py
inspirehep/dojson/hep/fields/bd84188x.py
inspirehep/dojson/hep/model.py
inspirehep/ext/jinja_filters/record.py
tests/test_bibtex.py
tests/test_cvlatex_html_text.py
tests/test_export.py

templates: fixes errors caused in brief and detailed records

---

base.requirements.txt

requirements: bump invenio-oaiharvester

---

setup.py

Flower allows nodes to expose tasks API needed for the upcoming hepcrawl integration.

setup: add flower requirement

---

tests/fixtures/test_author_form.json
tests/fixtures/test_author_form_converted.json
tests/test_author_workflow.py

* Adds test to check that the form data gets properly converted to dojson.

authors: author form data conversion test

---

inspirehep/dojson/hepnames/fields/bd1xx.py
tests/fixtures/test_author_form_converted.json
tests/fixtures/test_hepnames_record.xml
tests/test_author_workflow.py
tests/test_hepnames.py

* Adds test to make sure conversion from and to MARCXML are consistent.

dojson: hepnames dojson test

---

inspirehep/base/templates/format/record/Conference_HTML_brief.tpl
inspirehep/base/templates/format/record/Institution_HTML_brief.tpl
inspirehep/base/templates/format/record/Institution_HTML_detailed.tpl
inspirehep/base/templates/format/record/Journal_HTML_brief.tpl
inspirehep/base/templates/format/record/Journal_HTML_detailed.tpl
inspirehep/base/templates/page.html
inspirehep/dojson/conferences/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd01x09x.py
inspirehep/dojson/hep/fields/bd6xx.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/institutions/fields/bd1xx.py
inspirehep/dojson/journals/fields/bd1xx.py
inspirehep/ext/jinja_filters/record.py

dojson: fixes records with issues

---

inspirehep/base/searchext/mappings/institutions.json
inspirehep/base/static/less/format/brief-results.less
inspirehep/base/templates/search/facets/conferences.html
inspirehep/base/templates/search/results.html
inspirehep/config.py
inspirehep/ext/jinja_filters/record.py

facets: fix 0 results problem in all collections

---

inspirehep/modules/records/receivers.py

receivers: adds report document_type

---

base.requirements.txt

* Updates invenio-query-parser to 0.3.1.dev20160202.
* Updates invenio-search to 0.1.6.dev20160202.

global: dependencies version update

---

inspirehep/modules/harvester/manage.py
inspirehep/modules/migrator/tasks.py

HP migration fix and useful harvester CLI update.

migrator: fix error setting issue

---

inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl

detailed: fix issue with datatables

---

inspirehep/modules/authors/views.py

* Correctly imports the public email from a HepNames record.

authors: author import email fix

---

tests/fixtures/test_citation_counts.xml

* Removes unresloved references from tested record.

citations: update sample XML file

---

setup.py

requirements: forcing dojson 0.4.0

---

inspirehep/base/searchext/mappings/hep.json
tests/test_records.py

* Adds a new filter to elasticsearch that is used to ignore special
characters on author searching.
* Ticks the author bullet (no.7) of inspirehep/inspire-next#817.

WIP elasticsearch: new filter

---

base.requirements.txt
inspirehep/modules/workflows/templates/workflows/details.html

* Fixes an issue in Holding Pen detailed templates that
could cause an exception to be raised.
* Improves the layout a bit more.

workflows: detailed template update

---

inspirehep/base/templates/search/facets/hep.html
inspirehep/config.py

* Fixes subject facet to use the correct JSON field.

facets: subjects facet fix

---

inspirehep/modules/formatter/views.py
inspirehep/utils/bibtex.py
inspirehep/utils/export.py

* Gets the record from  elasticsearch.
* Closes #825.

utils: fixes bibtex indexing issue

---

inspirehep/modules/migrator/tasks.py

migrato: continuos migration fix

---

inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/utils.py
tests/fixtures/test_hepnames_record.xml
tests/test_hepnames.py

* Fixes error when outputting the note field.

dojson: hepnames2marc fix

---

inspirehep/dojson/hep/schemas/hep-0.0.1.json

dojson: updates json schema

---

Procfile
inspirehep/base/searchext/mappings/hep.json
inspirehep/base/templates/search/facets/hep.html
inspirehep/config.py
inspirehep/modules/records/receivers.py
inspirehep/utils/formulas.py
install.sh
package.json
tests/test_formulas.py

* Introduces new LaTeX/MathML formula utilities, based on a MathJax
server running on NodeJS.

utils: new formula utils

---

.travis.yml

travis: parallel testing

---

inspirehep/base/searchext/mappings/conferences.json
inspirehep/base/searchext/mappings/hep.json
inspirehep/base/searchext/mappings/jobs.json
inspirehep/dojson/hep/receivers.py
inspirehep/dojson/utils.py
inspirehep/modules/citations/receivers.py
inspirehep/modules/records/receivers.py
inspirehep/utils/date.py
tests/test_date_utils.py

* Improves the date validation functions that is used e.g. in
earliest_date receiver. (Taken from INSPIRE PROD.)
* Moves the date functions from DoJSON utilities to a general
utility.
Fixes date issues upon ES indexing for multiple records.

utils: date utils addition

---

inspirehep/base/static/less/base/variables.less
inspirehep/base/static/less/format/brief-results.less
inspirehep/base/static/less/format/detailed-record.less
inspirehep/base/templates/format/record/Inspire_Default_HTML_detailed.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl
inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl
inspirehep/base/templates/references.html

* Minor changes in detail display of references and citations.
* Changes link style for Showing more authors and affiliations.
* Do not display all authors in references.

templates: css general adjustments

---

inspirehep/base/static/js/datatables.js
inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl
inspirehep/base/templates/records/base.html
inspirehep/utils/citations.py

datatables: display max 10 citations

---

inspirehep/base/templates/format/record/Conference_info_macros.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_brief.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_brief_macros.tpl
inspirehep/base/templates/format/record/Inspire_Default_HTML_detailed.tpl
inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl
inspirehep/ext/jinja_filters/record.py
tests/test_publication_info.py

* Adds conference information according to cases.
* Closes #541.

templates: displays conference info

---

install.sh
tests/test_views.py

tests: completes test views

---

inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl

* Capitalizes the title when it's all in uppercase. (closes #847)

Capitalize titles when all uppercase

---

base.requirements.txt
inspirehep/base/mixer/sources/oaiHARVEST.json
inspirehep/base/templates/format/record/Holding_Pen_HTML_detailed.tpl
inspirehep/config.py
inspirehep/modules/harvester/manage.py
inspirehep/modules/harvester/tasks/__init__.py
inspirehep/modules/oaiharvester/__init__.py
inspirehep/modules/workflows/receivers.py
inspirehep/modules/workflows/tasks/matching.py
inspirehep/modules/workflows/workflows/hep_ingestion.py
tests/test_workflows.py

Adjustments and bug fixes after new versions of workflows and oaiharvester.

Workflows and OAI harvester adjustments

---

tests/test_matching.py

* Also improve imports in tests with a lazy_import.
Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@gmail.com>

tests: update MatchResult mocking

---

inspirehep/base/jsonschemas/hep-0.0.1.json

dojson: removes claimed from jsonschema

---

base.requirements.txt
setup.py

Cleans up requirements. Only beard is the remaining non-invenio fork special dependency.

setup: requirements cleanup

---

inspirehep/base/jsonschemas/conferences-0.0.1.json
inspirehep/base/jsonschemas/experiments-0.0.1.json
inspirehep/base/jsonschemas/hep-0.0.1.json
inspirehep/base/jsonschemas/hepnames-0.0.1.json
inspirehep/base/jsonschemas/institutions-0.0.1.json
inspirehep/base/jsonschemas/jobs-0.0.1.json
inspirehep/base/jsonschemas/journals-0.0.1.json
inspirehep/dojson/common/base.py
inspirehep/dojson/conferences/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd01x09x.py
inspirehep/dojson/hep/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd20x24x.py
inspirehep/dojson/hep/fields/bd5xx.py
inspirehep/dojson/hep/fields/bd6xx.py
inspirehep/dojson/hep/fields/bd70x75x.py
inspirehep/dojson/hep/fields/bd76x78x.py
inspirehep/dojson/hep/fields/bd84188x.py
inspirehep/dojson/hep/fields/bd90x99x.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/institutions/fields/bd1xx.py
inspirehep/dojson/jobs/fields/bd1xx.py
tests/test_citation_counts.py

dojson: fixes data model validation errors

---

inspirehep/base/jsonschemas/hep-0.0.1.json
inspirehep/base/jsonschemas/hepnames-0.0.1.json
inspirehep/dojson/common/base.py
inspirehep/dojson/hep/fields/bd01x09x.py
inspirehep/dojson/hep/fields/bd6xx.py
inspirehep/dojson/hep/model.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/modules/records/receivers.py
tests/test_dois.py

dojson: fix dojson broken records

---

inspirehep/modules/records/receivers.py

receivers: fixes document type bug

---

inspirehep/ext/jinja_filters/record.py

filters: catches exceptions in publication info

---

inspirehep/config.py
inspirehep/modules/search/walkers/elasticsearch.py
inspirehep/modules/theme/jinja2filters.py

* Adds full ES walker from invenio-query-parser for finer grained
control on final ES queries.

search: walker update

---

base.requirements.txt
inspirehep/modules/workflows/actions/author_approval.py
inspirehep/modules/workflows/actions/hep_approval.py

Fixes for new oaiharvester and workflows updates.

workflows: align actions with new resolve API

---

inspirehep/base/templates/header.html
inspirehep/base/templates/search/index.html
inspirehep/base/views.py

Restore of homepage design

---

inspirehep/utils/url.py
setup.py
tests/conftest.py
tests/test_url.py

* Adds conftest.py with app fixture.

utils: make_user_agent_string addition

---

inspirehep/modules/records/jsonschemas/records/authors.json
inspirehep/modules/records/jsonschemas/records/hep.json

* Alters schema to make records importable.

schema: schema fix

---

inspirehep/modules/theme/ext.py

theme: adds Jinja2's do extension

---

inspirehep/config.py
inspirehep/modules/authors/dojson/__init__.py
inspirehep/modules/authors/dojson/fields/updateform.py
inspirehep/modules/authors/dojson/model.py
inspirehep/modules/authors/tasks.py
inspirehep/modules/authors/templates/authors/forms/new_form.html
inspirehep/modules/authors/templates/authors/forms/new_review_accepted.html
inspirehep/modules/authors/templates/authors/forms/new_success.html
inspirehep/modules/authors/templates/authors/forms/review_form.html
inspirehep/modules/authors/templates/authors/forms/update_success.html
inspirehep/modules/authors/views.py
inspirehep/modules/authors/workflows/__init__.py
inspirehep/modules/authors/workflows/authorupdate.py
inspirehep/modules/workflows/tasks/submission.py
inspirehep/utils/robotupload.py
inspirehep/utils/text.py
inspirehep/utils/tickets.py
setup.py
tests/test_robotupload.py
tests/test_text.py

authors: workflows porting

---

inspirehep/config.py

* Adds topcite and cited keyword support.
* Should be merged with inspirehep/invenio-query-parser#13.
* Closes box no.9 of #817.

search: topcite keyword

---

inspirehep/modules/authors/templates/authors/forms/new_success.html
inspirehep/modules/authors/templates/authors/forms/review_form.html
inspirehep/modules/authors/templates/authors/tickets/curation_needed.html
inspirehep/modules/authors/templates/authors/tickets/curator_new.html
inspirehep/modules/authors/templates/authors/tickets/user_accepted.html
inspirehep/modules/authors/templates/authors/tickets/user_new.html
inspirehep/modules/authors/templates/authors/workflows/actions/author_approval_main.html
inspirehep/modules/authors/templates/authors/workflows/authorupdate.html
inspirehep/modules/authors/views.py
inspirehep/modules/authors/workflows/__init__.py
inspirehep/modules/authors/workflows/actions/author_approval.py
inspirehep/modules/authors/workflows/authornew.py
inspirehep/modules/authors/workflows/authorupdate.py
inspirehep/modules/theme/jinja2filters.py
inspirehep/modules/workflows/tasks/actions.py
inspirehep/modules/workflows/tasks/submission.py
inspirehep/utils/helpers.py
setup.py

authors: ports author new to invenio3

---

inspirehep/modules/theme/jinja2filters.py

filters: ports publication info filter in invenio3

---

tests/test_hep.py
tests/test_hepnames.py

* Fixes porting from assertEqual to bare assert

Replace assert (x, y) with assert x == y

---

inspirehep/config.py
inspirehep/modules/search/templates/search/search.html

* Fixes sorting configuration.

search: sorting configuration

---

inspirehep/config.py
setup.py

* Config file clean up. Removes unneeded variables and adds some new
useful configuration options.

global: config cleanup

---

.travis.yml
setup.py

* Adds mock dependency in setup.py

global: mock in tests_require

---

inspirehep/modules/records/serializers/json.py
inspirehep/modules/theme/bundles.py
inspirehep/modules/theme/static/js/settings.js
setup.py

records: adds display fields

---

inspirehep/modules/theme/jinja2filters.py
tests/unit/theme/test_theme_jinja2filters.py

* Uses replace_refs in publication_info filter.

theme: jsonref in jinja2filters

---

inspirehep/modules/theme/jinja2filters.py
inspirehep/utils/date.py
tests/unit/theme/test_theme_jinja2filters.py
tests/unit/theme/test_theme_views.py

Not yet fulfilling the promise in https://github.com/inspirehep/inspire-next/pull/932#issuecomment-189243461.

theme: implement or fix xfailed tests

---

inspirehep/dojson/common/base.py
inspirehep/modules/records/jsonschemas/records/authors.json
inspirehep/modules/records/jsonschemas/records/conferences.json
inspirehep/modules/records/jsonschemas/records/experiments.json
inspirehep/modules/records/jsonschemas/records/hep.json
inspirehep/modules/records/jsonschemas/records/institutions.json
inspirehep/modules/records/jsonschemas/records/jobs.json
inspirehep/modules/records/jsonschemas/records/journals.json
tests/unit/dojson/test_dojson_hep.py

dojson: add self url to every record

---

inspirehep/config.py
inspirehep/modules/records/mappings/records/hep.json
tests/unit/search/test_search_query.py

* Need to be merged with inspirehep/invenio-query-parser#15 .

search: enables fc keyword

---

inspirehep/modules/search/bundles.py
inspirehep/modules/search/static/js/search/app.js
inspirehep/modules/search/views.py
tests/unit/search/test_search_views.py

Assets building has been producing an error for quite a while: https://travis-ci.org/inspirehep/inspire-next/builds/116986936#L780. This PR contains a reproducible test case for triggering failures that appears related to it: https://travis-ci.org/inspirehep/inspire-next/builds/116986936#L1434 (but I also see it locally). If someone manages to fix it I will cherry-pick their commit and add it as first commit of this PR.

tests: test search views

---

inspirehep/modules/theme/static/scss/format/abstract.scss
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl

* Resolves abstract truncation error. (closes #866)

format: HEP detailed abstract

---

README.rst

This pull request fixed the installation link.

Fixed installation link

---

inspirehep/modules/search/views.py

views: fixes template rendering error in brief results

---

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_brief.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_brief_macros.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl

* Correctly displays DOI in search results and detailed records.
* Consolidates the two macros in one generic macro.

format: HEP record DOI

---

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl

* Loads the config of MathJax iff the external source was loaded.

theme: MathJax fix

---

inspirehep/modules/migrator/tasks.py
scripts/recreate_records

migrator: restore citation_count from Invenio2

---

inspirehep/modules/authors/views.py

* Takes into account that native name is a list when importing data.

authors: native name import fix

---

tests/unit/theme/test_theme_jinja2filters.py

Due to a small C-c C-v mistake we were skipping a test, which actually masked an error in one of them. I also fixed the style of a few neighboring tests, just for the sake of it.

tests: small test fixes

---

.travis.yml
docker-compose.test.yml
inspirehep/modules/migrator/tasks.py
run-tests.sh
tests/integration/conftest.py
tests/integration/test_citation_counts.py

First example of an integration test.

tests: test add_citation_counts

---

requirements.txt
setup.py

Hopefully fixes the build failure in https://travis-ci.org/inspirehep/inspire-next/jobs/123996582#L1004

requirements: pin records-rest and search

---

inspirehep/modules/search/templates/search/search.html

cite: removes cite all directive

---

inspirehep/modules/theme/static/js/settings.js

cc @jmartinm @tomaszgy @bittirousku

theme: settings.js update for Holding Pen

---

inspirehep/modules/theme/templates/inspirehep_theme/header.html

* Fixes `Submit` link in the navigation bar and simplifies
the navigation menu to be more direct.
@jmartinm

theme: simplify navigation header

---

inspirehep/modules/authors/receivers.py
inspirehep/modules/authors/utils.py
inspirehep/modules/migrator/tasks.py
run-tests.sh
setup.cfg
setup.py
tests/integration/conftest.py
tests/integration/test_detailed_records.py
tests/integration/test_proper_configuration.py
tests/integration/test_search_views.py
tests/integration/test_theme_views.py
tests/unit/authors/test_authors_receivers.py
tests/unit/authors/test_authors_utils.py
tests/unit/authors/test_authors_views.py
tests/unit/dojson/test_dojson_hep_receivers.py
tests/unit/search/test_search_views.py
tests/unit/theme/test_theme_views.py

Includes #934 by @Panos512 and #1053 by me.

tests: more tests

---

.dockerignore
dockerfiles/Dockerfile

Thanks to @mihaibivol and @jacquerie

docker: add ignore and update lib

---

inspirehep/modules/records/serializers/__init__.py
inspirehep/modules/records/serializers/response.py
inspirehep/modules/search/templates/search/search.html

Co-authored-by: Javier Martin Montull <montull@gmail.com>

cite: fixes checkbox for selecting all records

---

inspirehep/modules/search/bundles.py
inspirehep/modules/search/static/js/search/app.js
inspirehep/modules/search/templates/search/search.html
inspirehep/modules/theme/static/js/settings.js
inspirehep/modules/theme/static/scss/base/core.scss
inspirehep/modules/theme/static/scss/inspirehep.scss

theme: add angular-loading-bar

---

inspirehep/modules/authors/ext.py
inspirehep/modules/authors/views/__init__.py
inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/authors/views/publications.py
inspirehep/modules/theme/jinja2filters.py
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl
tests/integration/conftest.py
tests/integration/test_author_views.py
tests/unit/authors/test_authors_views.py

Supersedes #1106 because @jacenkow had to run away and I really really wanted to merge his stuff today.

authors: split blueprints + misc. fixes

---

inspirehep/modules/literaturesuggest/forms.py
setup.py

Required to make the submission workflow run correctly. @jmartinm

setup: literature workflow fix

---

inspirehep/modules/theme/static/scss/format/brief-results.scss

format: HEP brief search results fixes

---

inspirehep/modules/theme/jinja2filters.py
inspirehep/modules/theme/static/scss/format/detailed-record.scss
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Job_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/similar_jobs.html
inspirehep/utils/jinja2.py

format: Job detailed record

---

inspirehep/modules/theme/bundles.py
inspirehep/modules/theme/static/js/d3-wrapper.js
inspirehep/modules/theme/static/js/settings.js
inspirehep/modules/theme/static/scss/format/detailed-record.scss
inspirehep/modules/theme/static/scss/inspirehep.scss
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl

* Adds impact-graphs to detailed record pages.

theme: impact-graphs visualization JS

---

inspirehep/modules/literaturesuggest/static/js/literaturesuggest/literature_submission_form.js
inspirehep/modules/literaturesuggest/templates/literaturesuggest/forms/suggest.html
inspirehep/modules/theme/bundles.py
inspirehep/modules/theme/static/scss/inspirehep.scss

literaturesuggest: tooltip fix

---

inspirehep/modules/theme/static/scss/base/footer.scss
inspirehep/modules/theme/static/scss/base/variables.scss
inspirehep/modules/theme/templates/inspirehep_theme/footer.html

theme: footer style change

---

inspirehep/modules/theme/bundles.py
inspirehep/modules/theme/static/js/datatables.js
inspirehep/modules/theme/static/js/detailed_record_init.js
inspirehep/modules/theme/static/scss/format/detailed-record.scss
inspirehep/modules/theme/templates/inspirehep_theme/citations.html
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Cache_HTML_macros.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/records/base.html
inspirehep/modules/theme/templates/inspirehep_theme/references.html
inspirehep/modules/theme/views.py
inspirehep/utils/citations.py
inspirehep/utils/references.py
tests/integration/test_datatable_citations.py
tests/integration/test_datatable_references.py

format: port datatables to Invenio3

---

inspirehep/modules/authors/static/js/authors/publications.js

* Fixes the links of profile keywords pointing to search.

authors: keywords search fix

---

inspirehep/modules/theme/static/scss/authors/profiles.scss
inspirehep/modules/theme/templates/inspirehep_theme/format/record/authors/Author_HTML_detailed.html

* Small cosmetics applied to gravatar image.

profiles: gravatar styling

---

inspirehep/config.py
inspirehep/dojson/utils.py
inspirehep/modules/theme/templates/inspirehep_theme/errors/404.html
setup.py

Assortement of minor fixes that was needed to properly run QA.

Fixes from QA

---

inspirehep/config.py
inspirehep/modules/workflows/tasks/matching.py

Initial REST workflow config

---

inspirehep/config.py
inspirehep/modules/literaturesuggest/workflows/literature.py
inspirehep/modules/workflows/actions/hep_approval.py
inspirehep/modules/workflows/tasks/actions.py
inspirehep/modules/workflows/tasks/beard.py
inspirehep/modules/workflows/workflows/arxiv_ingestion.py
inspirehep/modules/workflows/workflows/hep_ingestion.py
tests/integration/workflows/test_arxiv_workflow.py

workflows: beard API integration

---

inspirehep/modules/workflows/tasks/matching.py
inspirehep/utils/search.py
setup.py
tests/integration/workflows/test_audit.py

* Fixes outdated import in exists_in_holding_pen().
(Closes #1156)

workflows: fix exists_in_holding_pen()

---

inspirehep/config.py
inspirehep/modules/workflows/search.py
inspirehep/modules/workflows/tasks/matching.py
setup.py
tests/integration/conftest.py

This is the custom searcher for the new angular based Holding Pen list view filtering out some of the JSON for performance reasons.

workflows: custom search factory

---

inspirehep/modules/authors/tasks.py
inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/authors/workflows/authornew.py
inspirehep/modules/authors/workflows/authorupdate.py
inspirehep/modules/literaturesuggest/tasks.py
inspirehep/modules/literaturesuggest/views.py
inspirehep/modules/literaturesuggest/workflows/literature.py
inspirehep/modules/workflows/search.py

* Fixes an issue with the workflows in submissions after recent API updates.
* Updates workflows API query factory to include the correct fields. @eamonnmag

submission fixes

---

inspirehep/modules/workflows/tasks/actions.py

* Adds more categories of records to do experimental guessing
for.
CC @annetteholtkamp @kaplun

workflows: improve experimental guessing

---

dockerfiles/docker_entrypoint.sh

docker: race condition on *.pyc removal fix

---

tests/integration/test_detailed_records.py

tests: ensure that all records are valid

---

inspirehep/modules/migrator/tasks.py

migrator: add citations with progress bar

---

inspirehep/config.py
inspirehep/modules/search/templates/search/search_jobs.html

search: jobs search sorting addition

---

README.rst

README: update to Invenio 3.0

---

inspirehep/modules/theme/views.py
tests/integration/test_theme_views.py

Uses HTTP 301 code, because redirection is permanent.
Closes #1076

theme: permanent redirect for /record/N

---

inspirehep/dojson/hep/fields/bd90x99x.py
inspirehep/modules/migrator/tasks.py
inspirehep/modules/records/jsonschemas/records/hep.json
tests/integration/test_detailed_records.py
tests/unit/dojson/test_dojson_hep.py

jsonschema: array-related fixes

---

inspirehep/config.py

config: update ORCID configuration

---

inspirehep/modules/migrator/tasks.py

* Removes putting Celery to sleep upon migration. This had been
introduced in order to solve some memory leaks in Celery which are
nowadays solved on production via memmon.
(Closes #1230)

migrator: no longer put Celery to sleep

---

inspirehep/modules/literaturesuggest/dojson/fields/literature.py
tests/unit/literaturesuggest/test_literaturesuggest_dojson.py

tests: unit tests for literaturesuggest DoJSON

---

inspirehep/config.py
inspirehep/modules/authors/receivers.py
inspirehep/modules/migrator/tasks.py
inspirehep/modules/records/mappings/records/hep.json
inspirehep/modules/search/templates/search/search.html
inspirehep/modules/search/views.py
inspirehep/modules/theme/bundles.py
inspirehep/modules/theme/static/js/inspire_base_init.js
inspirehep/modules/theme/static/js/settings.js
inspirehep/modules/theme/static/scss/base/header.scss
inspirehep/modules/theme/static/scss/format/brief-results.scss
inspirehep/modules/theme/static/scss/inspirehep.scss
inspirehep/modules/theme/static/scss/search/collection.scss
inspirehep/modules/theme/static/scss/search/typeahead.scss
inspirehep/modules/theme/templates/inspirehep_theme/search/collection_literature.html
inspirehep/modules/theme/templates/inspirehep_theme/typeahead.html
tests/integration/conftest.py

* Initial typeahead usage.
* Invenio and Spires syntax keywords to show are configurable.
* Introduces first suggester example with author field.

theme: adds typeahead to search bar

---

inspirehep/modules/search/views.py

* Fixes case were there are multiple names for a given bai.

search: author suggest fix

---

inspirehep/dojson/institutions/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/institutions.json
tests/unit/dojson/test_dojson_institutions.py

~~It's missing a few tests.~~
Closes #1239

schemas: populate related_institutes

---

inspirehep/config.py
inspirehep/modules/search/walkers/elasticsearch.py
tests/unit/search/test_search_query.py

* Adds support for matching author search by BAI. (closes #1242)

search: BAI search support

---

inspirehep/modules/theme/jinja2filters.py
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl
tests/unit/theme/test_theme_jinja2filters.py

Doesn't yet do what the title says, but the first two commits refactor the somewhat messy Jinja2 filters and add a few missing tests. There will be a third commit implementing what @eamonnmag suggested.
(I would also like to move ES logic into the controller from the template, but this PR will not yet do that.)

theme: use count instead of hits total

---

inspirehep/modules/records/mappings/records/hep.json

* Adds a new analyzer for the authors.full_name field.

mappings: authors full_name analyzer

---

inspirehep/modules/search/walkers/elasticsearch.py
tests/unit/search/test_search_query.py

* AMENDS 98a634797f8d996ee1540f71df4dc02fcce5543a

search: elasticsearch dsl fix for author queries

---

inspirehep/dojson/hep/fields/bd5xx.py
inspirehep/dojson/hep/receivers.py
inspirehep/modules/literaturesuggest/dojson/fields/literature.py
inspirehep/modules/records/jsonschemas/records/hep.json
inspirehep/utils/bibtex.py
inspirehep/utils/cv_latex.py
tests/unit/dojson/test_dojson_hep.py
tests/unit/dojson/test_dojson_hep_receivers.py
tests/unit/literaturesuggest/test_literaturesuggest_dojson.py
tests/unit/utils/test_utils_bibtex.py
tests/unit/utils/test_utils_cv_latex.py

schema: better thesis field for HEP

---

inspirehep/modules/forms/field_widgets.py
inspirehep/modules/forms/validation_utils.py
inspirehep/modules/forms/validators/simple_fields.py

Instead of writing tests for code that is never called I propose to delete it. Dead code was found using [vulture](https://pypi.python.org/pypi/vulture), imports where amended using [pylint](https://pypi.python.org/pypi/pylint).

forms: remove dead code

---

inspirehep/dojson/institutions/fields/bd1xx.py
inspirehep/dojson/utils/geo.py
tests/unit/dojson/test_dojson_institutions.py
tests/unit/dojson/test_dojson_utils_geo.py

Split in 3 commits for clarity.
Closes #1264

dojson: fix two bugs

---

inspirehep/modules/migrator/cli.py
inspirehep/modules/migrator/tasks.py

* Truncates all record related tables and allows cleaning up ES.

migrator: improvements

---

inspirehep/modules/search/query.py
inspirehep/modules/search/query_factory.py

* Searches on different fields based on the index we are searching on.
Co-authored-by: Samuele Kaplun <samuele.kaplun@cern.ch>

search: google like search fields

---

inspirehep/modules/search/bundles.py

search: invenio-search-js upgrade to 0.2.1

---

inspirehep/modules/records/json_ref_loader.py

json_ref: no recursive loop on ref repr

---

docker-compose.yml

Nobody gave docker some dev love :(

docker: working dev setup

---

inspirehep/modules/migrator/cli.py

* Using `inspirehep migrator clean_records` now adds the mappings to the ES
indices when recreating them.

migrator: add mappings to ES when recreating records

---

inspirehep/dojson/utils/__init__.py

dojson: ValueError on split page_artid fix

---

INSTALL.rst
docs/conf.py

* Add some missing steps
* Add centos examples
* Add user admin access grant

docs:Update the install docs

---

inspirehep/modules/workflows/tasks/magpie.py
tests/unit/workflows/test_workflows_tasks_magpie.py

First commit adds unit tests for magpie tasks, while second commit fixes a bug these tests uncovered. A similar bug is present in the BEARD tasks.

tests: unit tests for workflows magpie tasks

---

setup.py

* Upgrade to latest invenio-records-files and invenio-files-rest
packages

global: invenio files packages upgrade

---

inspirehep/dojson/conferences/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd1xx.py
inspirehep/dojson/institutions/fields/bd1xx.py
tests/unit/dojson/test_dojson_institutions.py

Cleared the small nit myself so I can unblock #1323.
Closes #1322

dojson: clear forgotten dedupes

---

setup.py

Hot fix for this Travis failure: https://travis-ci.org/inspirehep/inspire-next/jobs/144952882#L1303.

setup: pin html5lib

---

inspirehep/utils/record.py
tests/unit/utils/test_utils_record.py

Some small touches I wanted to do before merging.
Closes #1335
Gets #1337

utils: return default on IndexError

---

inspirehep/utils/stats.py
tests/unit/utils/test_utils_stats.py

I simplified the API to be just functions rather than static methods in a class.
Closes #1218

utils: add h-index and i10-index utils

---

inspirehep/dojson/common/base.py
inspirehep/dojson/conferences/fields/bd1xx.py
inspirehep/dojson/experiments/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd01x09x.py
inspirehep/dojson/hep/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd20x24x.py
inspirehep/dojson/hep/fields/bd5xx.py
inspirehep/dojson/hep/fields/bd6xx.py
inspirehep/dojson/hep/fields/bd70x75x.py
inspirehep/dojson/hep/fields/bd76x78x.py
inspirehep/dojson/hep/fields/bd90x99x.py
inspirehep/dojson/hep/model.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/institutions/fields/bd1xx.py
inspirehep/dojson/jobs/fields/bd1xx.py
inspirehep/dojson/processors.py
inspirehep/dojson/utils/__init__.py
inspirehep/dojson/utils/geo.py
inspirehep/modules/orcid/schema.py
inspirehep/utils/bibtex.py
inspirehep/utils/helpers.py
inspirehep/utils/pubnote.py
tests/unit/dojson/test_dojson_utils.py
tests/unit/utils/test_utils_helpers.py

dojson: move force_force_list to inspirehep.utils

---

inspirehep/modules/theme/static/scss/format/detailed-record.scss

css: remove unused classes

---

inspirehep/base/converterext/kb/arxiv-to-inspire-categories.kb

* Introduces new physics.data-an mapping to Data Analysis and
Statistics.

config: physics.data-an

---

inspirehep/config.py
tests/integration/conftest.py
tests/integration/test_detailed_records.py
tests/integration/test_orcid.py

config: make records visible without authorization

---

inspirehep/dojson/experiments/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/experiments.json
tests/unit/dojson/test_dojson_experiments.py

tests: unit tests for DoJSON experiments

---

inspirehep/modules/records/jsonschemas/records/hep.json

schemas: remove format on full names

---

inspirehep/dojson/common/base.py
inspirehep/dojson/hep/fields/bd01x09x.py
inspirehep/dojson/hep/fields/bd5xx.py
inspirehep/dojson/hep/model.py
inspirehep/modules/references/processors.py

dojson: fix arbitrary dojson exceptions

---

inspirehep/celery.py
inspirehep/modules/migrator/tasks.py
setup.py

* Refactors migration logic into a single function
* Wraps every step that might fail due to corrupt data in try: except:
blocks
* Adds logging messages that are aggregated by Sentry
Closes #1365

migrator: better error logging

---

inspirehep/modules/migrator/tasks.py

migrator: catch receiver errors

---

inspirehep/modules/theme/jinja2filters.py
inspirehep/modules/theme/static/js/datatables.js
inspirehep/modules/theme/static/scss/base/core.scss
inspirehep/modules/theme/static/scss/format/brief-results.scss
inspirehep/modules/theme/static/scss/format/detailed-record.scss
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Conference_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Experiment_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Institution_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Job_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Journal_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/search/collection_conferences.html
inspirehep/modules/theme/templates/inspirehep_theme/search/collection_experiments.html
inspirehep/modules/theme/templates/inspirehep_theme/search/collection_institutions.html
inspirehep/modules/theme/templates/inspirehep_theme/search/collection_journals.html
inspirehep/modules/theme/templates/inspirehep_theme/search/collection_literature.html
inspirehep/modules/theme/views.py

* Avoids line breaks when displaying facet labels and counts.
(addresses #1368)

theme: facet labels adjustment

---

docker-compose.deps.yml
docker-compose.yml

docker: run gunicorn on web node

---

setup.py

Attempts to fix https://travis-ci.org/inspirehep/inspire-next/jobs/148804909#L1610.

setup: pin invenio-oauthclient

---

inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/authors.json
inspirehep/modules/records/jsonschemas/records/experiments.json

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601589/

schemas: remove enum from ids types

---

inspirehep/modules/records/jsonschemas/records/elements/fields.json
tests/unit/dojson/test_dojson_common_base.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601593/

schemas: remove enum on _scheme

---

inspirehep/dojson/hep/receivers.py
tests/unit/dojson/test_dojson_hep_receivers.py

Salvaged from #1364 since it was growing too much in scope.

dojson: refactor earliest_date

---

inspirehep/modules/records/jsonschemas/records/journals.json

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601537/

schemas: add online to issn medium enum

---

inspirehep/modules/orcid/tasks.py
inspirehep/modules/orcid/utils.py
setup.py
tests/integration/test_orcid.py
tests/unit/orcid/test_orcid_converter.py

* Also updates the orcid module in order to work with the latest
invenio-oauthclient. (addresses #1382)
* Updates the loggers of the orcid module. (addresses #1371 )

setup: bump invenio-oauthclient

---

inspirehep/dojson/experiments/fields/bd1xx.py
inspirehep/modules/records/mappings/records/authors.json
inspirehep/modules/theme/jinja2filters.py
inspirehep/modules/theme/static/js/datatables.js
inspirehep/modules/theme/static/scss/format/detailed-record.scss
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Conference_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Experiment_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Institution_HTML_detailed.tpl
inspirehep/modules/theme/views.py
inspirehep/utils/experiments.py
tests/unit/dojson/test_dojson_experiments.py
tests/unit/theme/test_theme_jinja2filters.py

theme: experiment detailed view

---

inspirehep/config.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/modules/authors/dojson/fields/updateform.py
inspirehep/modules/authors/templates/authors/workflows/authorupdate.html
inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/records/jsonschemas/records/authors.json
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html
tests/unit/authors/test_authors_dojson.py
tests/unit/dojson/test_dojson_hepnames.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601538/

schemas: phd_advisors -> advisors

---

docker-compose.yml

@mihaibivol, that's all we need, right?

docker: add access-logfile to gunicorn

---

inspirehep/modules/records/jsonschemas/records/hep.json
inspirehep/modules/records/receivers.py

records: activity report document type addition

---

inspirehep/utils/record_getter.py

@mihaibivol, whenever you have time to have a look at this...

utils: proper logging in record_getter

---

inspirehep/config.py
inspirehep/dojson/jobs/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/jobs.json
inspirehep/modules/records/mappings/records/authors.json
inspirehep/modules/records/mappings/records/jobs.json
inspirehep/modules/search/config.py
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Job_HTML_detailed.tpl
tests/unit/dojson/test_dojson_jobs.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601632/
* First commit fixes a `scripts/prettifyjson` I missed in a previous PR 😳 
* Second commit implements the solution proposed in https://github.com/inspirehep/inspire/issues/199.
This PR is ready for review.

schemas: continent -> regions

---

inspirehep/modules/records/mappings/records/hep.json

* Updates HEP schema to include uuid field in authors object.

mappings: add not_analyzed to uuid

---

inspirehep/modules/theme/templates/inspirehep_theme/search/collection_conferences.html

theme: upcoming conferences ui fix

---

inspirehep/config.py
inspirehep/modules/records/wrappers.py
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Journal_HTML_detailed.tpl

* Initial journal detailed view.
* Introduces new wrapper JournalsRecord to access parts of a Journal
record.

theme: journals detailed view

---

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html

holdingpen: hide actions if workflow complete

---

inspirehep/dojson/experiments/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd1xx.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/utils/__init__.py
inspirehep/modules/records/jsonschemas/records/authors.json
inspirehep/modules/records/jsonschemas/records/elements/id.json
inspirehep/modules/records/jsonschemas/records/experiments.json
inspirehep/modules/records/jsonschemas/records/hep.json
tests/unit/dojson/test_dojson_experiments.py
tests/unit/dojson/test_dojson_hep.py
tests/unit/dojson/test_dojson_hepnames.py
tests/unit/dojson/test_dojson_utils.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601553/

schemas: organize identifiers

---

inspirehep/dojson/jobs/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/jobs.json
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Job_HTML_detailed.tpl
tests/unit/dojson/test_dojson_jobs.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601633/

schemas: institution -> institutions

---

inspirehep/modules/records/mappings/records/authors.json
inspirehep/modules/records/mappings/records/conferences.json
inspirehep/modules/records/mappings/records/experiments.json
inspirehep/modules/records/mappings/records/journals.json
inspirehep/modules/search/api.py

search: enable _all in secondary collections

---

inspirehep/dojson/jobs/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/jobs.json

As per https://github.com/inspirehep/inspire/issues/199#issuecomment-239185808.

schemas: make australia part of australasia

---

inspirehep/dojson/experiments/fields/bd1xx.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/jobs/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/experiments.json
inspirehep/modules/records/jsonschemas/records/jobs.json
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Experiment_HTML_detailed.tpl
tests/unit/dojson/test_dojson_experiments.py
tests/unit/dojson/test_dojson_hepnames.py
tests/unit/dojson/test_dojson_jobs.py

dojson: add links between collections

---

inspirehep/modules/records/jsonschemas/records/hep.json

jsonschema: remove \u2013 character

---

inspirehep/config.py
inspirehep/dojson/hep/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/hep.json
inspirehep/modules/search/walkers/elasticsearch.py
tests/unit/dojson/test_dojson_hep.py
tests/unit/search/test_search_query.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601536/

dojson: alternative_name -> alternative_names

---

.gitignore

global: add vim swapfiles to gitignore

---

inspirehep/modules/migrator/tasks.py

migrator: smaller chunks for citations in ES

---

inspirehep/modules/records/jsonschemas/records/journals.json

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601671/
Closes https://github.com/inspirehep/inspire/issues/198 (will this work?)

schemas: be liberal on CODENs

---

inspirehep/dojson/hep/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd70x75x.py
inspirehep/dojson/jobs/fields/bd1xx.py
inspirehep/modules/records/jsonschemas/records/hep.json
tests/unit/dojson/test_dojson_hep.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601540/

dojson: email -> emails

---

inspirehep/modules/migrator/tasks.py

migrator: use logger instead of logging

---

.travis.yml
docker-compose.test.yml
tests/integration/workflows/test_arxiv_workflow.py
tests/integration/workflows/test_audit.py

Implements the idea I described in https://github.com/inspirehep/inspire-next/pull/1353#issuecomment-237524229 using the timings from https://github.com/inspirehep/inspire-next/pull/1478.
I believe this a nice time to solve #1399 as well.

travis: speed up the build by splitting it

---

inspirehep/modules/authors/rest/citations.py
inspirehep/modules/authors/rest/publications.py
tests/integration/test_author_api.py

api: restructure schemas of /authors/citations and /authors/publications

---

inspirehep/modules/authors/rest/stats.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/603317/
Reproduction on nightly: http://inspire-nightly.cern.ch/api/authors/982620/stats

api: fix bug in /api/authors/stats

---

inspirehep/modules/authors/bundles.py
inspirehep/modules/authors/static/js/authors/app.js
inspirehep/modules/authors/static/js/authors/author.js
inspirehep/modules/authors/static/js/authors/profile.js
inspirehep/modules/authors/static/js/authors/publications.js
inspirehep/modules/authors/static/js/authors/statistics.js
inspirehep/modules/authors/static/js/authors/templates/collaborators.html
inspirehep/modules/authors/static/js/authors/templates/position.html
inspirehep/modules/authors/static/js/authors/templates/publications.html
inspirehep/modules/authors/static/js/authors/templates/statistics.html
inspirehep/modules/theme/static/js/settings.js
inspirehep/modules/theme/static/scss/authors/profiles.scss
inspirehep/modules/theme/templates/inspirehep_theme/format/record/authors/Author_HTML_detailed.html

authors: make the profiles great again

---

inspirehep/modules/migrator/tasks.py

migrator: faster implementation of count_citations

---

inspirehep/dojson/hep/fields/bd01x09x.py

dojson: more languages

---

inspirehep/modules/migrator/cli.py

migrator: migrating one INSPIRE record

---

inspirehep/config.py
inspirehep/modules/records/mappings/records/hep.json
inspirehep/modules/search/query_factory.py
inspirehep/modules/search/walkers/elasticsearch.py
tests/unit/search/test_search_query.py

I changed my mind on how to structure the commits, so I submitted this myself rather than inflicting another rebase on you, @Panos512 : )
Closes #1436

search: authors exact search

---

inspirehep/config.py
inspirehep/dojson/hep/fields/bd6xx.py
inspirehep/modules/authors/rest/publications.py
inspirehep/modules/authors/rest/stats.py
inspirehep/modules/authors/views/publications.py
inspirehep/modules/records/jsonschemas/records/hep.json
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Holding_Pen_HTML_detailed.tpl
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl
tests/integration/test_author_views.py
tests/unit/dojson/fixtures/test_hep_record.xml
tests/unit/dojson/test_dojson_hep.py

No changes, just a rebase on top of master.
Closes #1469

schemas: merge keyword fields

---

inspirehep/dojson/common/base.py
tests/unit/dojson/test_dojson_hep.py

Just minor changes: the name of the test and some spacing.
Closes #1514

dojson: multiple 970 SPIRES sysnos

---

inspirehep/dojson/hep/fields/bd01x09x.py
tests/unit/dojson/test_dojson_hep.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601552/

dojson: skip invalid DOIs

---

inspirehep/modules/records/jsonschemas/records/elements/id.json

Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
(closes #1531)

schemas: allow dashes in GoogleScholar ids

---

.travis.yml

travis: enable fast_finish

---

inspirehep/modules/workflows/tasks/matching.py

workflow: more robust is_too_old

---

.gitignore
.travis.yml
docker-compose.test.yml
inspirehep/config.py
inspirehep/wsgi_with_coverage.py
setup.py
tests/acceptance/conftest.py
tests/acceptance/test_login.py

tests: coverage of web part

---

inspirehep/modules/hal/__init__.py
inspirehep/modules/hal/config.py
inspirehep/modules/hal/tei.py
inspirehep/modules/hal/templates.py
inspirehep/modules/hal/templates/hal_tei.xml
inspirehep/modules/hal/templates/macros.xml
inspirehep/modules/records/serializers/tei_serializer.py
setup.py
tests/integration/hal/fixtures/test_tei_record.xml
tests/integration/hal/test_tei_exporting.py
tests/unit/hal/test_tei.py

Signed-off-by: Liam Kirsh <liam.kirsh@cern.ch>

WIP tei: first commits

---

inspirehep/modules/records/jsonschemas/records/elements/reference.json
inspirehep/modules/records/jsonschemas/records/hep.json

jsonschema: references

---

inspirehep/dojson/common/base.py
inspirehep/dojson/conferences/fields/bd1xx.py
inspirehep/dojson/experiments/fields/bd1xx.py
inspirehep/dojson/hep/fields/bd01x09x.py
inspirehep/dojson/hep/fields/bd25x28x.py
inspirehep/dojson/hep/fields/bd4xx.py
inspirehep/dojson/hep/fields/bd5xx.py
inspirehep/dojson/hep/fields/bd6xx.py
inspirehep/dojson/hep/fields/bd70x75x.py
inspirehep/dojson/hep/fields/bd76x78x.py
inspirehep/dojson/hep/fields/bd84188x.py
inspirehep/dojson/hepnames/fields/bd1xx.py
inspirehep/dojson/institutions/fields/bd1xx.py
inspirehep/dojson/journals/fields/bd1xx.py

`filter_values` from DoJSON was superseded by `clean_record`

dojson: evict filter_values

---

inspirehep/dojson/hep/fields/bd6xx.py
tests/unit/dojson/test_dojson_hep.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601722/
Closes #1560

dojson: allow multiple experiments on hep records

---

inspirehep/dojson/conferences/fields/bd1xx.py
inspirehep/dojson/conferences/model.py
tests/unit/dojson/test_dojson_conferences.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/603955/
Closes #1553

dojson: fix lone series number

---

inspirehep/config.py
inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/workflows/mappings/holdingpen/authors.json
inspirehep/modules/workflows/templates/inspire_workflows/index.html

* Enables the form to update an author using his records legacy
recid.
* Fixes workflow counts in holdingpen dashboard.
(closes #1534)

workflows: author update

---

tests/acceptance/test_login.py

tests: fixes in acceptance tests

---

inspirehep/modules/migrator/legacy/workflows.py

migrator: workflow dumping fix

---

inspirehep/modules/authors/dojson/fields/updateform.py
inspirehep/modules/migrator/cli.py
inspirehep/modules/migrator/legacy/audit.py
inspirehep/modules/migrator/legacy/workflows.py
inspirehep/modules/migrator/tasks/records.py
inspirehep/modules/migrator/tasks/workflows.py
setup.py
tests/acceptance/conftest.py
tests/integration/conftest.py

Superseeds https://github.com/inspirehep/inspire-next/pull/1226

Workflows migration

---

inspirehep/modules/authors/dojson/fields/updateform.py
inspirehep/modules/authors/forms.py
inspirehep/modules/authors/tasks.py
inspirehep/modules/authors/templates/authors/forms/review_form.html
inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.directives.js
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_decision_authors.html

* Displays missing fields on holdingpen detailed view
(notes, experimens, native name, email address).
* Adds "Review Submission" button on holdingpen detailed view.
* "Review Submission" url now properly works.
* "Review Submission" form now populates with updated values.
closes #1535
closes #1537

workflows/authors: holdingpen fixes

---

inspirehep/dojson/hepnames/fields/bd1xx.py
tests/unit/dojson/test_dojson_hepnames.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/606026 and https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/606034/.

dojson: don't try to correct None

---

inspirehep/dojson/common/base.py
inspirehep/modules/migrator/tasks/records.py
inspirehep/modules/records/jsonschemas/records/authors.json
inspirehep/modules/records/jsonschemas/records/conferences.json
inspirehep/modules/records/jsonschemas/records/experiments.json
inspirehep/modules/records/jsonschemas/records/hep.json
inspirehep/modules/records/jsonschemas/records/institutions.json
inspirehep/modules/records/jsonschemas/records/jobs.json
inspirehep/modules/records/jsonschemas/records/journals.json
inspirehep/modules/records/receivers.py
inspirehep/utils/record.py
tests/integration/test_record.py
tests/unit/dojson/test_dojson_common_base.py

general: support for deleted records 

---

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.controllers.js
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html

* Adds review subsmission button on holdingpen brief results.
* closes #1594.

workflows: review submission button

---

docker-compose.test.yml
docker-compose.yml
inspirehep/config.py

* Removed os.environment.get from config
* Updated docker-compose files

Clean up environment variables and update docker-compose files #1616

---

README.rst

docs: readthedocs.io move

---

docs/howtos.rst
inspirehep/modules/cache/__init__.py
inspirehep/modules/cache/ext.py
inspirehep/modules/cache/proxies.py
inspirehep/modules/workflows/views/callback.py
setup.py

cache: flask-cache addition

---

inspirehep/modules/theme/static/js/settings.js
setup.py

@eamonnmag, I think I need your help in deploying this, because I'm not able to reconstruct all the things that must be run before seeing results in the dashboard.
~~There's also the question that this adds `numpy`, `scipy`, `scikit-learn` to the build, something which is highly undesirable.~~ Actually, it doesn't appear to affect in any way the build times...
Closes #1485

trends: first commits

---

inspirehep/modules/forms/static/js/forms/conferences_typeahead.js

Fix the autocompletion in order to complete the selenium tests

forms: fix the suggestions parsers for conferences

---

inspirehep/modules/forms/static/js/forms/journals_typeahead.js
inspirehep/modules/records/mappings/records/journals.json

I have found this bug during my tests. It is necessary in order to push the new tests.

Fix autocompletion journals literature

---

inspirehep/modules/migrator/legacy/audit.py

* Fixes audit dump to ignore none values.
Signed-off-by: Panos Paparrigopoulos panos.paparrigopoulos@cern.ch

migrator: audit dump fix

---

docs/howtos.rst
inspirehep/modules/cache/ext.py
setup.py

`Flask-Cache` has been sitting unmantained with bugs for a few months.
`Flask-Caching` is a drop-in replacement for it (addresses #1646).

setup: Flask-Cache -> Flask-Caching

---

inspirehep/dojson/hep/fields/bd90x99x.py
inspirehep/modules/references/processors.py
inspirehep/modules/references/view_utils.py
tests/unit/dojson/test_dojson_hep.py
tests/unit/references/test_processors.py

* Adapt ReferenceBuilder to references data model.

references: ReferenceBuilder fix

---

inspirehep/modules/migrator/tasks/records.py
inspirehep/modules/records/receivers.py
inspirehep/utils/record.py
tests/integration/test_record.py

Minor changes (whitespace, import order).
Closes #1620

 general: add support for merged records

---

setup.py

* Workaround until inveniosoftware/invenio-files-rest#130 is fixed.

packaging: pin the version of fs

---

inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_decision_authors.html

* Fixes a bug that didn't allow reviewing author's submissions.
* Accept button of workflow's detailed view now has correct styling.

workflows: fixes author's review submissions

---

inspirehep/modules/theme/templates/inspirehep_theme/header.html
inspirehep/modules/tools/__init__.py
inspirehep/modules/tools/bundles.py
inspirehep/modules/tools/ext.py
inspirehep/modules/tools/static/js/tools/authorlist_init.js
inspirehep/modules/tools/templates/authorlist_form.html
inspirehep/modules/tools/templates/tools.html
inspirehep/modules/tools/utils.py
inspirehep/modules/tools/views.py
setup.py
tests/unit/tools/test_utils.py

* Adds new tool authorlist, to format author strings.
(closes #1628)
Signed-off-by: Henrik Vesterinen <henrik.vesterinen@cern.ch>

tools: new tools directory for cataloging tools

---

requirements.txt
setup.py

Combines b593411f4c11767f7e57821fdd448790ab07de42, 3a15bd35419baa9dbcaaffa398b7b2fd27924cdb, and 062d66a66c7767376c56951a2b1d634c60834deb to fix the build atomically (so that we don't break `git bisect`).

travis: fix build

---

docker-compose.deps.yml
docker-compose.yml
inspirehep/dojson/common/base.py
inspirehep/modules/authors/dojson/fields/updateform.py
inspirehep/modules/authors/forms.py
inspirehep/modules/authors/tasks.py
inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/literaturesuggest/forms.py
inspirehep/modules/migrator/tasks/workflows.py
inspirehep/modules/records/receivers.py
inspirehep/modules/refextract/tasks.py
inspirehep/modules/workflows/mappings/holdingpen/hep.json
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_references.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_subject_areas.html
inspirehep/modules/workflows/tasks/arxiv.py
inspirehep/modules/workflows/tasks/matching.py
inspirehep/modules/workflows/tasks/submission.py
inspirehep/modules/workflows/tasks/upload.py
inspirehep/modules/workflows/workflows/article.py
inspirehep/modules/workflows/workflows/author.py
inspirehep/utils/helpers.py
pytest.ini
requirements.txt
setup.py
tests/unit/records/test_records_receivers.py

Ok, making the test suite pass at each step was just taking too much time. Squashed everything (with a few corrections here and there).
Closes #1341 
Closes #1661

workflows: integrate hepcrawl

---

setup.py

Otherwise https://travis-ci.org/inspirehep/inspire-next/jobs/173476792 happens.

setup: pin elasticsearch-dsl

---

inspirehep/modules/pidstore/utils.py
setup.py

Closes #1711
Closes #1713
Closes #1718

setup: remove invenio-records-rest from apps

---

inspirehep/modules/authors/forms.py

authors: fix validator for author public mail

---

inspirehep/config.py
inspirehep/modules/theme/bundles.py
inspirehep/modules/theme/static/images/labs-flask-darkbg.svg
inspirehep/modules/theme/static/scss/landing_page.scss
inspirehep/modules/theme/templates/inspirehep_theme/header.html
inspirehep/modules/theme/templates/inspirehep_theme/inspire_labs_cover.html
inspirehep/modules/theme/views.py
setup.py

* Allows to switch between the labs.inspirehep.net look and the full site.
(closes #1731)

theme: new INSPIRE_FULL_THEME configuration

---

inspirehep/modules/theme/jinja2filters.py
inspirehep/modules/theme/templates/inspirehep_theme/header.html
tests/unit/theme/test_theme_jinja2filters.py

templates: show cataloger tools to catalogers only

---

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/613718/

theme: literature references API call fix

---

inspirehep/modules/pidstore/providers.py

pidstore: make pid_type an int

---

inspirehep/config.py
inspirehep/modules/records/mappings/records/experiments.json
inspirehep/modules/records/mappings/records/hep.json
inspirehep/modules/records/mappings/records/journals.json
inspirehep/modules/records/receivers.py
tests/unit/records/test_records_receivers.py

records: add experiment suggester receiver

---

inspirehep/modules/tools/templates/authorlist_form.html
inspirehep/modules/tools/utils.py
tests/unit/tools/test_tools_utils.py

tools: make authorlist work better with bad input

---

inspirehep/config.py
inspirehep/modules/search/static/js/search/app.js
inspirehep/modules/search/templates/search/search.html

Pending merge of https://github.com/inspirehep/inspire-next/pull/1255
Pending release of https://github.com/inveniosoftware/invenio-search-js in npm

Facet year range

---

inspirehep/modules/refextract/tasks.py
tests/integration/workflows/test_arxiv_workflow.py
tests/unit/refextract/test_refextract_tasks.py

refextract: fix year type in extract_journal_info

---

inspirehep/modules/theme/views.py

theme: redirect linkedaccounts view

---

inspirehep/modules/workflows/tasks/__init__.py
inspirehep/modules/workflows/tasks/actions.py
inspirehep/modules/workflows/tasks/arxiv.py
inspirehep/modules/workflows/tasks/classifier.py
inspirehep/modules/workflows/tasks/matching.py
inspirehep/modules/workflows/tasks/submission.py
inspirehep/modules/workflows/tasks/upload.py
tests/unit/workflows/test_workflows_tasks_actions.py

tests: unit tests for workflows/tasks/actions

---

inspirehep/config.py
inspirehep/modules/theme/static/scss/inspirehep.scss
inspirehep/modules/theme/static/scss/invenio-record-editor/record-editor.scss
inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html

record-editor: invenio-record-editor template configuration

---

tests/integration/test_record.py

tests: document error raised by get_es_records

---

tests/integration/workflows/test_arxiv_workflow.py

tests: fix imports in workflows tests

---

.travis.yml
docker-compose.test.yml

@david-caro, @kaplun: like we discussed. See if you like it.
Essentially reverts #1373.

travis: merge pep8 and unit suites

---

.travis.yml
docker-compose.test.yml
inspirehep/wsgi_with_coverage.py

travis: add coverage to acceptance suite

---

inspirehep/modules/authors/views/holdingpen.py

authors: native name data model to form conversion fix

---

inspirehep/config.py
inspirehep/modules/records/mappings/records/hep.json
inspirehep/modules/records/receivers.py
tests/unit/records/test_records_receivers.py

records: add abstract source suggester receiver

---

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_references.html
inspirehep/modules/workflows/tasks/submission.py

* Shows references inputted by the user in the Holding Pen detailed view.
(closes #1801)

literaturesuggest: show references in Holding Pen detailed view

---

inspirehep/utils/robotupload.py
tests/unit/utils/test_utils_robotupload.py

utils: fix encoding of robotupload parameter

---

inspirehep/config.py

* Adds new category Data Analysis and Statistics.

config: add new INSPIRE category

---

tests/integration/conftest.py

tests: set celery eager mode in integration tests

---

inspirehep/config.py
inspirehep/modules/records/tasks.py
tests/integration/test_record.py
tests/unit/records/test_records_tasks.py

records: update links for merged records

---

inspirehep/modules/authors/permissions.py
inspirehep/modules/authors/views/holdingpen.py
inspirehep/modules/fixtures/users.py
setup.py
tests/integration/test_holdingpen_permissions.py

permissions: add author view permissions

---

inspirehep/modules/authors/forms.py
inspirehep/modules/authors/tasks.py
inspirehep/modules/literaturesuggest/tasks.py
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_comments.html
tests/unit/authors/test_authors_tasks.py
tests/unit/literaturesuggest/test_literaturesuggest_tasks.py

forms: extra_data cleanup

---

inspirehep/modules/literaturesuggest/dojson/fields/literature.py
inspirehep/modules/literaturesuggest/fields/arxiv_id.py
inspirehep/modules/literaturesuggest/forms.py
inspirehep/modules/literaturesuggest/tasks.py
tests/unit/literaturesuggest/test_literaturesuggest_tasks.py

literaturesuggest: fix xfailed tests

---

inspirehep/modules/records/serializers/impactgraph_serializer.py
inspirehep/utils/record_getter.py
tests/integration/test_record.py
tests/integration/test_serializers.py

records: fix impact graph serializer

---

inspirehep/utils/conferences.py
tests/unit/utils/test_utils_conferences.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/606817/
Closes #1826

utils: fix unicode issues in utils/conferences

---

requirements.txt
setup.py

requirements: use released invenio-classifiers

---

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html

* Allows editing a workflow object using the JSON record editor.

editor: add record editor to Holding Pen entries

---

inspirehep/modules/migrator/tasks/records.py
tests/integration/fixtures/1502655.xml
tests/integration/fixtures/1502656.xml
tests/integration/fixtures/1502656_update.xml
tests/integration/test_migrator.py

Closes #1864
Also adds integration tests for it (closes #1787).

migrator: fix continuous migration

---

inspirehep/modules/workflows/tasks/arxiv.py
inspirehep/utils/helpers.py
tests/integration/workflows/test_arxiv_workflow.py
tests/unit/utils/test_utils_helpers.py

utils: rename download_file_to_record

---

inspirehep/modules/search/bundles.py

search: inspirehep-search-js 0.3.0 version bump

---

inspirehep/config.py
inspirehep/modules/pidstore/utils.py
inspirehep/modules/records/tasks.py
inspirehep/modules/records/utils.py
inspirehep/modules/theme/views.py
tests/unit/records/test_records_utils.py

* Moves get_endpoint_from_schema to get_endpoint_from_record inside
of the new utils module.
* Moves get_index_from_endpoint to a configuration variable
INSPIRE_ENDPOINT_TO_INDEX.

records: add utils module

---

tests/unit/dojson/test_dojson_hep_bd1xx.py

dojson: tests for inspire_roles

---

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_keywords.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_subject_areas.html

holdingpen: change to light color style

---

.gitignore
inspirehep/modules/workflows/models.py
inspirehep/modules/workflows/tasks/actions.py
inspirehep/modules/workflows/tasks/submission.py
inspirehep/modules/workflows/views/callback.py
inspirehep/modules/workflows/workflows/article.py
inspirehep/modules/workflows/workflows/author.py
scripts/recreate_records
setup.py
tests/integration/workflows/test_arxiv_workflow.py

Refactor (and fix) callbacks to support robotupload, continue_workflow (generic), and webcoll.

workflows: fix continue_workflow callback

---

docker-compose.yml

* Hot reloads the gunicorn server when editing Python files to ease development.
* Adds DEBUG and ASSETS_DEBUG configuration.

docker: add dev options to docker-compose

---

inspirehep/modules/workflows/tasks/actions.py
tests/unit/workflows/test_workflows_tasks_actions.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619697/
A leftover of #1918.

workflows: fix add_core task

---

inspirehep/dojson/data/__init__.py
inspirehep/dojson/data/model.py
inspirehep/dojson/data/rules.py
inspirehep/dojson/processors.py
tests/unit/dojson/test_dojson_processors.py

Invokes the `data` model on Data records instead of falling back
to the `hep` model (closes #1960).

dojson: stub data model

---

tests/integration/workflows/test_arxiv_workflow.py

* Adapts tests to new view permissions in invenio-workflows-ui.

tests: workflows login before API request

---

inspirehep/dojson/common/rules.py
tests/unit/dojson/test_dojson_common.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619250/

dojson: fix _fft

---

inspirehep/dojson/hep/rules/bd5xx.py
tests/unit/dojson/test_dojson_hep_bd5xx.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619581/

dojson: fix _desy_bookkeeping

---

inspirehep/modules/workflows/templates/inspire_workflows/index.html

holdingpen: remove empty stats section

---

.gitignore

gitignore: add twistd pid file

---

inspirehep/modules/forms/validators/simple_fields.py

* Port HAL Hidden validator functionality. (closes #1297)

literaturesuggest: validate if id already present in Hal Hidden

---

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.controllers.js
inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.directives.js
inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.services.js
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/batch-actions.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_decision_hep.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/modals/generic_info_modal.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/modals/rejection_reason_modal.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html

* Adds an extra step when rejecting a user suggestion that allows
setting the reason. (closes #1936)

holdingpen: allow setting reject reason on hep workflow

---

inspirehep/config.py
inspirehep/modules/workflows/mappings/holdingpen/hep.json
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/facets.html

holdingpen: add facet on inspire_categories

---

inspirehep/modules/authors/tasks.py
tests/unit/authors/test_authors_tasks.py

authors: handle unicode in new_ticket_context

---

inspirehep/dojson/hep/rules/bd3xx.py
tests/unit/dojson/test_dojson_hep_bd3xx.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619227/

dojson: fix number_of_pages

---

inspirehep/modules/workflows/tasks/submission.py
inspirehep/modules/workflows/workflows/article.py
inspirehep/modules/workflows/workflows/author.py

* Renames send_and_wait_robotupload to send_robotupload.
* Halts workflow only when a callback URL is set. (closes #2008)

workflows: conditional halt in send_and_wait_robotupload

---

inspirehep/bat/pages/holding_panel_author_detail.py
inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_decision_authors.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_experiments.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_positions.html

* Reorders action buttons.
* Moves positions on top.
* Adds missing link to author profile.

holdingpen: author workflow template changes

---

inspirehep/dojson/common/rules.py
inspirehep/dojson/hep/rules/bd5xx.py
tests/unit/dojson/test_dojson_hep_bd5xx.py

dojson: handle defense_date in 500__a

---

inspirehep/modules/authors/dojson/fields/__init__.py
inspirehep/modules/literaturesuggest/fields/__init__.py
inspirehep/modules/migrator/legacy/__init__.py
inspirehep/modules/pidstore/__init__.py
inspirehep/modules/records/mappings/__init__.py
inspirehep/modules/records/serializers/schemas/__init__.py
inspirehep/modules/references/__init__.py
inspirehep/modules/refextract/__init__.py
inspirehep/modules/search/walkers/__init__.py
inspirehep/modules/workflows/mappings/__init__.py
inspirehep/utils/__init__.py

migrator: add missing __init__.py

---

inspirehep/modules/forms/static/js/forms/affiliations_typeahead.js
inspirehep/modules/forms/static/js/forms/authors_typeahead.js
inspirehep/modules/forms/static/js/forms/conferences_typeahead.js
inspirehep/modules/forms/static/js/forms/experiments_typeahead.js
inspirehep/modules/forms/static/js/forms/journals_typeahead.js
inspirehep/modules/records/mappings/records/experiments.json
inspirehep/modules/workflows/tasks/submission.py

forms: autocomplete without regex queries

---

requirements.txt
setup.py

setup: use kaplun's invenio-migrator fork

---

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_decision_hep.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html

workflows: show reject method on hepcrawl workflows

---

inspirehep/modules/literaturesuggest/tasks.py
tests/integration/fixtures/conference_article_expected.json
tests/integration/fixtures/journal_article_expected.json
tests/integration/fixtures/thesis_expected.json

literaturesuggest: add internal_uid to acquisition_source

---

inspirehep/dojson/hep/rules/bd0xx.py
tests/unit/dojson/test_dojson_hep_bd0xx.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619219

dojson: fix material in dois

---

inspirehep/modules/authors/tasks.py
tests/unit/authors/test_authors_tasks.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820689/

authors: handle unicode in update_ticket_context

---

inspirehep/modules/authors/templates/authors/tickets/user_accepted.html

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820738/

authors: fix ticket template import

---

inspirehep/modules/literaturesuggest/tasks.py
tests/unit/literaturesuggest/test_literaturesuggest_tasks.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820778/
Closes #2116

literaturesuggest: handle unicode in new_ticket_context

---

inspirehep/modules/authors/tasks.py
tests/unit/authors/test_authors_tasks.py

authors: add subject to update_ticket_context

---

inspirehep/modules/records/mappings/records/hep.json

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820421/

mappings: add citation_count to hep

---

inspirehep/modules/workflows/tasks/submission.py
tests/unit/workflows/test_workflows_tasks_submission.py

workflows: fix unicode issues in create_ticket

---

inspirehep/modules/authors/tasks.py
tests/unit/authors/test_authors_tasks.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820806/
Addresses https://github.com/inspirehep/inspire-next/issues/2133
Closes https://github.com/inspirehep/inspire-next/issues/2127

authors: handle unicode in curation_ticket_context

---

inspirehep/dojson/hep/rules/bd9xx.py
tests/unit/dojson/test_dojson_hep_bd9xx.py

Closes https://github.com/inspirehep/inspire-next/issues/2176

dojson: fix document_type2marc

---

inspirehep/modules/workflows/search.py
inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.filters.js
inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.module.js
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details.html
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html

Closes #2112 
Closes #2130 
Closes #2166 
Closes #2167
Closes #2177
Closes #2182

holdingpen: various fixes

---

tests/unit/authors/test_authors_tasks.py
tests/unit/conftest.py
tests/unit/helpers/mocks.py
tests/unit/literaturesuggest/test_literaturesuggest_tasks.py
tests/unit/refextract/test_refextract_tasks.py
tests/unit/workflows/test_workflows_tasks_actions.py
tests/unit/workflows/test_workflows_tasks_arxiv.py
tests/unit/workflows/test_workflows_tasks_beard.py
tests/unit/workflows/test_workflows_tasks_magpie.py
tests/unit/workflows/test_workflows_tasks_matching.py
tests/unit/workflows/test_workflows_tasks_submission.py

Implements the refactoring suggested by @jmartinm in https://github.com/inspirehep/inspire-next/pull/2143#discussion_r108917485.

tests: refactor workflow mock objects

---

inspirehep/modules/literaturesuggest/forms.py
tests/unit/literaturesuggest/test_literaturesuggest_form.py

* Capitalized the phd value in the degree_type field. (addresses #2161)

literaturesuggest: capitalized phd field

---

inspirehep/modules/theme/static/scss/base/header.scss
inspirehep/modules/theme/templates/inspirehep_theme/accounts/login.html
inspirehep/modules/theme/templates/inspirehep_theme/header.html

theme: hide collections menu in mobile view

---

inspirehep/bat/pages/create_literature.py
inspirehep/modules/literaturesuggest/forms.py
inspirehep/modules/literaturesuggest/tasks.py
tests/acceptance/test_literature_suggestion_form.py

Closes #2067 
Closes #2068 
Closes #2157

literaturesuggest: various fixes

---

inspirehep/dojson/hep/rules/bd5xx.py
inspirehep/dojson/hepnames/rules.py
tests/unit/dojson/test_dojson_hep_bd5xx.py
tests/unit/dojson/test_dojson_hepnames.py

dojson: capitalize correctly degree_type

---

inspirehep/modules/workflows/tasks/actions.py
inspirehep/modules/workflows/tasks/arxiv.py
inspirehep/modules/workflows/tasks/beard.py
inspirehep/modules/workflows/tasks/classifier.py
inspirehep/modules/workflows/tasks/magpie.py
inspirehep/modules/workflows/tasks/matching.py
inspirehep/modules/workflows/tasks/submission.py
inspirehep/modules/workflows/tasks/upload.py
inspirehep/modules/workflows/utils.py

Closes #1879 
I actually didn't test this locally yet, I just wanted to check that resuscitating this PR was easy (it was).

workflows: add debug logging to tasks

---

setup.py

setup: add web-node extra

---

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl

* Update MathJax CDN link to cdnjs provider

theme:update MathJax CDN links

---

setup.py

Reverts b92ebfd from https://github.com/inspirehep/inspire-next/pull/2183.

setup: remove pin on selenium

---

inspirehep/dojson/common/rules.py
tests/unit/dojson/test_dojson_common.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619220

dojson: fix _private_notes

---

inspirehep/config.py

config: use member ORCID api

---

inspirehep/config.py
inspirehep/modules/workflows/mappings/holdingpen/hep.json
inspirehep/modules/workflows/templates/inspire_workflows/index.html

Closes #2091 
Err, I almost lost this commit while juggling a couple of rebases. Repetition of #2097.

workflows: populate arXiv card with arXiv papers

---

.gitignore
docker-compose.deps.yml
docker-compose.test.yml
docs/Makefile
docs/building_the_docs.rst
docs/conf.py
docs/index.rst
inspirehep/bat/EC.py
inspirehep/dojson/utils/__init__.py
inspirehep/modules/authors/utils.py
inspirehep/modules/forms/form.py
inspirehep/modules/forms/validation_utils.py
inspirehep/modules/records/receivers.py
inspirehep/modules/records/serializers/bibtex_serializer.py
inspirehep/modules/records/serializers/cvformathtml_serializer.py
inspirehep/modules/records/serializers/cvformatlatex_serializer.py
inspirehep/modules/records/serializers/cvformattext_serializer.py
inspirehep/modules/records/serializers/latexeu_serializer.py
inspirehep/modules/records/serializers/latexus_serializer.py
inspirehep/modules/search/api.py
inspirehep/utils/conferences.py
inspirehep/utils/cv_latex.py
inspirehep/utils/date.py
inspirehep/utils/experiments.py
inspirehep/utils/jinja2.py
inspirehep/utils/record.py
setup.py

docs: add the sphinxcontrib.napoleon extension

---

setup.py

See: https://travis-ci.org/inspirehep/inspire-next/jobs/224492807#L1393

setup: pin selenium to 3.3.3

---

inspirehep/dojson/hep/rules/bd9xx.py
inspirehep/modules/references/processors.py
tests/unit/dojson/test_dojson_hep_bd9xx.py
tests/unit/references/test_references_processors.py

references: make builder support 999C5q

---

inspirehep/dojson/hep/rules/bd7xx.py
setup.py
tests/unit/dojson/test_dojson_hep_bd7xx.py

dojson: support hidden publication_info

---

inspirehep/dojson/hep/rules/bd9xx.py
tests/unit/dojson/test_dojson_hep_bd9xx.py

Follow-up of the discussion in https://github.com/inspirehep/inspire-schemas/issues/146.

references: make builder support 999C5k

---

inspirehep/modules/authors/forms.py

authors: use high level categories in research_field

---

inspirehep/config.py
inspirehep/modules/records/mappings/records/institutions.json
inspirehep/modules/records/receivers.py
tests/unit/records/test_records_receivers.py

records: add affiliation suggester

---

.coveragerc
.dockerignore
.editorconfig
.gitignore
.travis.yml
Procfile
docker-compose.deps.yml
docker-compose.test.yml
docker-compose.yml
gunicorn.cfg
pytest.ini
requirements.txt
setup.cfg
setup.py

travis: avoid extra 1000 lines of output

---

inspirehep/config.py
tests/unit/workflows/test_workflows_tasks_matching.py

config: use proper capitalization in arXiv categories

---

docs/tests.rst

docs: document how to debug the acceptance tests

---

inspirehep/bat/pages/holding_panel_literature_list.py
tests/acceptance/conftest.py
tests/acceptance/test_literature_suggestion_form.py

tests: add test of workflow completion

---

inspirehep/modules/migrator/tasks/records.py

This is why I write tests: because I do silly things like this all the time. 🥇

migrator: fix error message for Sentry

---

inspirehep/modules/authors/templates/authors/tickets/curation_needed.html
inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_core.html

Closes #2335 
Here's how tickets look like with this PR:
```
New submission from user@example.org
Curate record here: https://inspirehep.net/record/edit/#state=edit&recid=4328.
Link to pdf: http://example.org/foo.pdf
Record url: http://inspirehep.net/record/4328
User comments:
foo bar baz
References:
foo bar baz
```
and
```
Author request by user@example.org
Curate record here: https://inspirehep.net/record/edit/#state=edit&recid=4328.
Record url: http://inspirehep.net/record/4328
User comments:
foo bar baz
```
@tsgit, @bing13: if you can confirm that this is what your tools expect I can merge and deploy it on Monday.
NB: tests for this will come as part of #2313

global: improve curation ticket layout

---

inspirehep/modules/references/processors.py
tests/unit/dojson/test_dojson_hep_bd9xx.py
tests/unit/references/test_references_processors.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly-1/group/822126/

references: fix _normalize_arxiv

---

.gitignore
inspirehep/bat/pages/top_navigation_page.py
tests/acceptance/conftest.py

tests: login only once in the acceptance suite

---

inspirehep/modules/workflows/utils.py
setup.py
tests/unit/workflows/test_workflows_utils.py

Addresses #2337 
~~Still missing tests~~, but I'd like your feedback, @david-caro @jmartinm @kaplun.

workflows: retry on error when fetching files

---

inspirehep/modules/workflows/tasks/submission.py

workflows: make strip call safe

---

inspirehep/modules/authors/bundles.py
inspirehep/modules/authors/forms.py
inspirehep/modules/authors/static/js/authors/author_form_init.js
inspirehep/modules/authors/static/js/authors/authors_submission_form.js
inspirehep/modules/authors/templates/authors/forms/update_form.html
inspirehep/modules/forms/validators/dynamic_fields.py
setup.py

* New js and a python validator for the author dates input. (Closes #2092)
Co-Authored-By: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>
Co-Authored-By: Javier Martin Montull <javier.martin.montull@cern.ch>

authors: two date validation

---

inspirehep/modules/forms/static/js/forms/experiments_typeahead.js

literaturesuggest: sort experiments autocomplete

---

inspirehep/modules/fixtures/__init__.py
inspirehep/modules/pidstore/fetchers.py
inspirehep/modules/search/config.py
inspirehep/modules/search/parser.py
inspirehep/modules/search/walkers/pypeg_to_ast.py
inspirehep/modules/search/walkers/spires_to_invenio.py
inspirehep/modules/workflows/__init__.py
inspirehep/modules/workflows/actions/__init__.py
inspirehep/modules/workflows/bundles.py
inspirehep/modules/workflows/errors.py
inspirehep/modules/workflows/ext.py
inspirehep/modules/workflows/receivers.py
inspirehep/modules/workflows/search.py
inspirehep/modules/workflows/tasks/arxiv.py
inspirehep/modules/workflows/workflows/__init__.py
tests/unit/helpers/mocks.py
tests/unit/workflows/test_workflows_utils.py

Closes #2360 
Closes #2361 
Testing this is a little more complicated than expected, so I'm going to go forward on it and add some technical debt for later.

workflows: retry arxiv pdf download

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

github: new PR/Issue templates

---

.github/PULL_REQUEST_TEMPLATE.md

github: more stable git log guidelines URL

---

inspirehep/modules/records/mappings/records/journals.json
tests/integration/utils/test_normalizers.py

* Update journals mapping with lowercase analyzer.
* Add `lowercase_journal_titles` field for searching the abbreviated journal
name.
Co-Authored-By: George Lignos <glignos93@gmail.com>
Co-Authored-By: Javier Martin Montull <javier.martin.montull@cern.ch>

utils: normalize_journal_title proper search

---

requirements.txt
setup.py

setup: use released invenio-jsonschemas

---

inspirehep/config.py
inspirehep/modules/workflows/mappings/holdingpen/hep.json
inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/facets.html

holdingpen: sort and filter by coreness

---

setup.py

setup: pin invenio-workflows to the major version

---

inspirehep/modules/workflows/utils.py

workflows: decompress gzipped pdf downloads

---

requirements.txt
setup.py

* Pins invenio-indexer to commit ead1eaa923c3289f08f1c84b404fbb3362764fa3
to allow reindexing of records from database.

setup: pin invenio-indexer

---

inspirehep/dojson/experiments/rules.py
inspirehep/modules/forms/static/js/forms/experiments_typeahead.js
inspirehep/modules/records/mappings/records/experiments.json
inspirehep/modules/records/receivers.py
inspirehep/modules/records/wrappers.py
inspirehep/modules/theme/templates/inspirehep_theme/format/record/Experiment_HTML_detailed.tpl
inspirehep/modules/theme/views.py
setup.py
tests/unit/dojson/test_dojson_experiments.py
tests/unit/dojson/test_dojson_experiments_model.py
tests/unit/records/test_records_receivers.py

Closes https://github.com/inspirehep/inspire-next/issues/2266

global: bump inspire-schemas to version ~32.0

---

docker-compose.test.yml
docker-compose.yml

Follow-up of https://github.com/inspirehep/inspire-next/pull/2426#issuecomment-307922532.

docker: pin rabbitmq and redis

---

inspirehep/config.py
inspirehep/dojson/experiments/rules.py
inspirehep/dojson/hep/rules/bd7xx.py
inspirehep/dojson/institutions/rules.py
inspirehep/dojson/journals/rules.py
inspirehep/modules/records/mappings/records/experiments.json
inspirehep/modules/records/mappings/records/hep.json
inspirehep/modules/records/mappings/records/institutions.json
inspirehep/modules/records/mappings/records/journals.json
setup.py
tests/unit/dojson/test_dojson_experiments.py
tests/unit/dojson/test_dojson_hep_bd7xx.py
tests/unit/dojson/test_dojson_institutions.py
tests/unit/dojson/test_dojson_journals.py

global: bump inspire-schemas to version ~33.0

---

docs/Makefile
requirements-docs.txt

docs: fix napoleon in readthedocs

---

inspirehep/modules/forms/validators/simple_fields.py

Also searches arXiv identifiers and DOIs in the CDS Hidden collection
when looking for duplicates.
Closes #2424

Include CDS and HAL collections in duplicate validators

---

inspirehep/dojson/experiments/rules.py
setup.py
tests/unit/dojson/test_dojson_experiments.py

Closes https://github.com/inspirehep/inspire-next/issues/2428

global: bump inspire-schemas to version ~35.0

---

setup.py

Closes https://github.com/inspirehep/inspire-next/issues/2380

setup: unpin Sphinx
