inspirehep/inspire-next

setup.py
=> setup: unpin docutils

inspirehep/modules/workflows/models.py
Adds indexes to columns which are subject of a foreign key with
on delete cascade.
=> workflows: add indexes for on delete cascade

INSTALL.rst, docs/about.rst, docs/docker.rst, docs/getting_started.rst
=> docs: update getting started

inspirehep/modules/workflows/tasks/refextract.py, tests/unit/workflows/test_workflows_tasks_refextract.py
=> workflows: fix refextract task 

inspirehep/dojson/hep/rules/bd9xx.py, setup.py, tests/unit/dojson/test_dojson_hep_bd9xx.py
Closes https://github.com/inspirehep/inspire-next/issues/2434
Closes https://github.com/inspirehep/inspire-next/issues/2460
Closes https://github.com/inspirehep/inspire-next/issues/2469
=> global: bump inspire-schemas to version ~39.0

inspirehep/modules/migrator/tasks/records.py, inspirehep/modules/records/tasks.py, inspirehep/modules/search/api.py, tests/integration/test_records.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/618692/
Closes #1849
=> records: add task to merge merged records

inspirehep/modules/records/mappings/records/hep.json
Commit b3c7776 forgot to update the mappings correspondingly.
=> records: update mappings for the latest schemas

inspirehep/modules/migrator/tasks/records.py, tests/integration/test_records.py
Renames record_upsert to record_insert_or_replace and indeed
inserts or replaces a record when coming from legacy during
migration.
=> migrator: upsert -> insert_or_replace

.travis.yml
Removes a minor source of flakiness by retrying the creation of assets
in case it fails.
=> travis: retry assets creation

inspirehep/modules/workflows/tasks/refextract.py, setup.py, tests/integration/workflows/test_arxiv_workflow.py
Updates the refextract workflow task to be able to use refextract v0.2.0, bringing many [improvements](https://github.com/inspirehep/refextract/blob/v0.2.0/RELEASE-NOTES.rst).
Closes #1816
=> workflows: update refextract to v0.2.0

inspirehep/modules/migrator/tasks/records.py
* Commit into the database after each record is processed.
=> migrator: continuous migration improvement

inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_references.html
* Adapt template to new author key data model. (closes #2490)
=> holdingpen: reference template fix

inspirehep/modules/search/bundles.py
* Ensures that on development, bundle will get recreated everytime a
file changes on inspirehep-search-js, to allow for faster development.
=> search: add depends parameter to bundle

inspirehep/modules/arxiv/ext.py, inspirehep/modules/arxiv/utils/__init__.py, inspirehep/modules/arxiv/utils/xmlhelpers.py, setup.py
~~Expected to fail, as this depends on https://github.com/inspirehep/inspire-next/pull/2504.~~
Closes https://github.com/inspirehep/inspire-next/issues/2207
=> global: remove dependency on invenio-utils

inspirehep/modules/authors/receivers.py
* Protects against beard malfunctionments by backing off in case
it's not possible to parse the JSON returned results (typically
this is simptom of network error).
(Closes #2503)
=> authors: backoff on beard

Procfile, inspirehep/config.py, inspirehep/modules/refextract/tasks.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py
Adds a celery beat task to run periodically and build the journal-kb file.
Related issue: https://github.com/inspirehep/inspire-next/issues/2495
=> WIP refextract: Improve normalized extracted references

inspirehep/modules/workflows/tasks/matching.py
Protect legacy matching with the backoff decorator.
(Closes #2481)
=> matching: backoff when legacy is down

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss, inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.filters.js, inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/holdingpen.module.js, inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/results.html
* Color codes the number of filtered core keywords in Holding Pen
results. (closes #2326)
* Shows all core keywords.
=> holdingpen: show all keywords

inspirehep/modules/refextract/__init__.py, setup.py
Explicitly advertize celery tasks in corresponding entry points so that they are all correctly registered for Celery.
=> setup: advertize celery tasks in entry_points

inspirehep/modules/workflows/static/js/inspire_workflows_ui/holdingpen/app.js
* Adds inspirehep-search-js dependency to correctly find pagination
template.
=> holdingpen: fix pagination template

requirements.txt, setup.py
* Uses @jmartinm's invenio-logging patch which should allow logging
into Sentry also errors in invenio-workflows's Celery tasks.
(addresses #1371)
=> setup: use @jmartinm's invenio-logging patch

docs/docker.rst
* Corrects several typos as reported by @fschwenn.
=> docs: typos

inspirehep/modules/workflows/tasks/submission.py, inspirehep/utils/ext.py, inspirehep/utils/proxies.py, inspirehep/utils/tickets.py, setup.py, tests/unit/conftest.py, tests/unit/helpers/mocks.py, tests/unit/utils/test_utils_tickets.py, tests/unit/workflows/test_workflows_tasks_submission.py
* Implements Rt module (fixes #2418)
=> utils: implement rt module

inspirehep/utils/tickets.py
Closes https://sentry.cern.ch/inspire-sentry/inspire-labs/group/824604/
=> tickets: relogin if needed

inspirehep/modules/authors/receivers.py, inspirehep/modules/authors/utils.py, setup.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/authors/test_authors_receivers.py
* Uses native beard instance in order to compute author phonetic
blocks, thus avoiding relying on sometimes flaky external service
for a very small functionality.
(addresses #1282)
=> authors: phonetic_blocks via native beard

requirements.txt, setup.py
(see inveniosoftware/invenio-oauthclient#131)
* Forces latest commit by @jmartinm in
inveniosoftware/invenio-oauthclient, in order to have persistent
ORCID sessions.
=> setup: persistent ORCID session

tests/integration/workflows/conftest.py, tests/integration/workflows/helpers/calls.py, tests/integration/workflows/helpers/mocks.py, tests/integration/workflows/helpers/utils.py, tests/integration/workflows/test_arxiv_workflow.py
Use `conftest.py` for the reusable fixtures and add a `helpers`
module with all the functions that are reusable.
Trying to add more features to the callbacks module in the workflows
found out really hard to add new tests for it.
=> Refactor workflows test

inspirehep/modules/workflows/templates/inspire_workflows/index.html
* Removes Alpha Experiment card.
* Fixes dashboard column display (closes #2536)
=> holdingpen: dashboard changes

requirements.txt
=> setup: force in invenio-logging for sentry

inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/tasks/submission.py, tests/unit/workflows/test_workflows_tasks_arxiv.py, tests/unit/workflows/test_workflows_tasks_submission.py
* Properly passes arguments in obj.log.error, so that it's possible
to aggregate exceptions in Sentry.
Co-authored-by: Antonio Ammirate <antonio.ammirate@cern.ch>
=> workflows: better sentry logging

inspirehep/config.py
* This variable allows to distinguish internal from external URLs
in doJSON.
=> config: add LEGACY_BASE_URL variable

inspirehep/bat/pages/holding_panel_literature_detail.py
This makes the literature details check more robust, and thus, the
whole acceptance tests more robust too.
=> tests.acceptance: use more stable EC.TryClick

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/test_bibtex_exporting.py, tests/unit/authors/test_authors_views.py, tests/unit/search/test_search_query.py, tests/unit/utils/test_utils_cv_latex.py, tests/unit/utils/test_utils_cv_latex_html_text.py, tests/unit/utils/test_utils_date.py, tests/unit/workflows/test_workflows_tasks_submission.py
=> workflows: preserve references

inspirehep/modules/editor/views.py, tests/integration/editor/test_editor_views.py
Closes https://github.com/inspirehep/inspire-next/pull/2560
=> tests: add tests for the editor's RT API

inspirehep/modules/forms/static/js/forms/experiments_typeahead.js
=> literaturesuggest: expand experiment autocomplete

docs/operations.rst
Adds some info on how to start debugging workflows that were started
by a harvest.
=> docs: add some hints about how to debug crawls

inspirehep/utils/ext.py, scripts/clean_assets, scripts/clear_pycache, scripts/prettify_json, scripts/prettify_licenses, scripts/recreate_records, tests/integration/workflows/conftest.py, tests/integration/workflows/helpers/calls.py, tests/integration/workflows/test_arxiv_workflow.py
=> scripts: various fixes

inspirehep/bat/pages/create_literature.py, inspirehep/config.py, inspirehep/modules/forms/static/js/forms/books_typeahead.js, inspirehep/modules/forms/static/scss/forms/form.scss, inspirehep/modules/forms/validators/simple_fields.py, inspirehep/modules/literaturesuggest/forms.py, inspirehep/modules/literaturesuggest/normalizers.py, inspirehep/modules/literaturesuggest/static/js/literaturesuggest/data_sources/data_source.js, inspirehep/modules/literaturesuggest/static/js/literaturesuggest/data_sources/doi.js, inspirehep/modules/literaturesuggest/static/js/literaturesuggest/literature_submission_form.js, inspirehep/modules/literaturesuggest/static/js/literaturesuggest/mapper.js, inspirehep/modules/literaturesuggest/static/js/literaturesuggest/task_manager.js, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/literaturesuggest/templates/literaturesuggest/forms/suggest_book_parent.html, inspirehep/modules/literaturesuggest/views.py, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/receivers.py, tests/acceptance/test_literature_suggestion_form.py, tests/integration/literaturesuggest/test_literaturesuggest_normalizers.py, tests/unit/literaturesuggest/test_literaturesuggest_tasks.py
=> literaturesuggest: add book and chapter submission

inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html
* Load styles from node_modules folder to make sure all relative imports
present in the bundle css are correctly resolved.
=> editor: css style fix

inspirehep/modules/forms/validators/simple_fields.py
=> forms: update deprecated flask.ext import

tests/integration/conftest.py
=> tests: minor fixes to integration tests

inspirehep/modules/literaturesuggest/templates/literaturesuggest/forms/suggest.html, inspirehep/modules/theme/templates/inspirehep_theme/inspire_labs_cover.html
=> templates: advertize book addition forms

inspirehep/config.py
=> config: remove real MAGPIE_API_URL

requirements.txt, setup.py
Every time we add a line to `requirements.txt` we contract some debt.
=> setup: upstream workflow

inspirehep/modules/workflows/tasks/submission.py, inspirehep/utils/tickets.py, setup.py
=> setup: remove retrying in favor of backoff

setup.py
=> setup: remove unneeded dependencies

inspirehep/utils/helpers.py, tests/unit/utils/test_utils_helpers.py
=> utils: remove download_file util

inspirehep/modules/workflows/workflows/article.py
Supposedly gonna fix https://sentry.cern.ch/inspire-sentry/inspire-labs/group/824875/
=> workflows: call close_ticket if is submission

setup.py
=> setup: pin invenio-accounts

services.yml
=> docker: use sane locale vars

.gitignore, inspirehep/bat/pages/top_navigation_page.py, requirements.txt, setup.py, tests/acceptance/conftest.py
Closes https://github.com/inspirehep/inspire-next/issues/2605
=> setup: unpin invenio-accounts

inspirehep/modules/api/utils.py, inspirehep/modules/authors/rest/stats.py, inspirehep/modules/authors/views/holdingpen.py, inspirehep/modules/forms/validators/simple_fields.py, inspirehep/modules/hal/utils.py, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/migrator/tasks/records.py, inspirehep/modules/records/receivers.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/beard.py, inspirehep/modules/workflows/tasks/magpie.py, inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/tasks/refextract.py, inspirehep/utils/bibtex.py, inspirehep/utils/record.py, setup.py, tests/integration/test_records.py, tests/unit/utils/test_utils_record.py
=> global: get get_value from inspire-utils

tests/unit/forms/test_forms_validation_utils.py
=> tests: add missing tests for validation utils

tests/integration/test_refextract_tasks.py
=> tests: add test for create_journal_kb_file

requirements.txt, setup.py
=> setup: upstream invenio-logging

tests/integration/arxiv/fixtures/1305.0014.xml, tests/integration/arxiv/fixtures/1305.0014v1.xml, tests/integration/arxiv/fixtures/1305.9999.xml, tests/integration/arxiv/fixtures/is-malformed.xml, tests/integration/arxiv/test_arxiv_views.py
I have written a series of integration tests for all the possible xml response messages that the 'arxiv' module might have to deal with.
Previously, this module was not tested at all. This is not good practice.
Following TDD mantra prior to refactoring of the 'arxiv' module, i.e. reimplementing it with blueprints.
=> tests: add integration tests for the arxiv module

tests/integration/crossref/fixtures/10.1086_305772.json, tests/integration/crossref/fixtures/does-not-exist, tests/integration/crossref/test_crossref_views.py
Preparation for https://github.com/inspirehep/inspire-next/issues/2257.
=> tests: add integration tests for the crossref views

inspirehep/config.py, inspirehep/modules/authors/forms.py, inspirehep/modules/authors/views.py, inspirehep/modules/literaturesuggest/forms.py, inspirehep/modules/records/receivers.py, inspirehep/modules/theme/jinja2filters.py, inspirehep/utils/date.py, tests/unit/records/test_records_receivers.py, tests/unit/theme/test_theme_jinja2filters.py, tests/unit/utils/test_utils_conferences.py, tests/unit/utils/test_utils_date.py
=> theme: simplify the format_date filter 

inspirehep/modules/workflows/tasks/actions.py
=> workflows: add a nice name to the halt step

inspirehep/modules/fixtures/users.py, tests/integration/arxiv/test_arxiv_views.py, tests/integration/crossref/test_crossref_views.py, tests/integration/editor/test_editor_views.py, tests/integration/test_holdingpen_permissions.py, tests/integration/test_permissions.py
This suggests that we need to refactor these test fixtures in a single place.
=> global: encrypt_password -> hash_password

inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
It was actually doing nothing, as the schema had changed in the
meantime, and its job is better handled by the schema anyway.
=> records: remove references_validator

inspirehep/modules/workflows/views.py
* Since legacy can send a big amount of record ids, this change
avoids doing a db query per recid (which makes the gunicorn worker
timeout).
=> workflows: avoid multiple db queries on callback

inspirehep/modules/hal/config.py
=> hal: fix math domain mapping

setup.py
=> setproctitle

inspirehep/modules/crossref/__init__.py, inspirehep/modules/crossref/config.py, inspirehep/modules/crossref/core.py, inspirehep/modules/crossref/views.py, inspirehep/wsgi_with_coverage.py, setup.py
=> crossref: refactor module

inspirehep/modules/arxiv/__init__.py, inspirehep/modules/arxiv/config.py, inspirehep/modules/arxiv/core.py, inspirehep/modules/arxiv/views.py, inspirehep/wsgi_with_coverage.py, setup.py
=> arxiv: refactor module

inspirehep/modules/literaturesuggest/normalizers.py, tests/integration/literaturesuggest/test_literaturesuggest_normalizers.py
Previously the query would have matched only if the record had a
single `document_type`, and was using two LATERAL JOINs instead
of one (closes #2693).
Closes #2693
=> literaturesuggest: fix check_book_existence

inspirehep/modules/arxiv/ext.py, inspirehep/modules/crossref/ext.py, inspirehep/modules/migrator/ext.py, setup.py
Yet another edition of "minor fixes I did on the train".
=> global: fix some extensions

inspirehep/modules/records/mappings/records/authors.json, inspirehep/modules/records/mappings/records/conferences.json, inspirehep/modules/records/mappings/records/experiments.json, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/mappings/records/institutions.json, inspirehep/modules/records/mappings/records/jobs.json, inspirehep/modules/records/mappings/records/journals.json, inspirehep/modules/records/permissions.py, tests/integration/conftest.py, tests/integration/test_permissions.py
* Permissions when accessing records will now take into account
the view-restricted-collection action in roles.
* Adds back lowercase_analyzer for _collections field in ES mappings,
which is needed for correct filtering of records.
* Adds extra permission tests.
=> records: role based permissions

inspirehep/modules/records/mappings/records/hep.json
* Adds extra fields and analyzers used for matching of records.
=> records: matching-related hep mappings

inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/tasks.py
=> migrator: remigrate all support

inspirehep/modules/migrator/tasks.py
=> migrator: remigrate records fix

inspirehep/config.py
Note that this commit requires to recreate the `collection` table in
production, otherwise the records in the LArSoft special collection
would be assigned to a no longer existing collection.
Because of this I'm not going to merge it now, as deployments are
still blocked, and it wouldn't make sense to pile up more manual ops.
CC: @david-caro @kaplun @jmartinm
=> config: use the right capitalization for LArSoft

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl
=> theme: fix keywords panel

inspirehep/modules/theme/views.py, inspirehep/utils/citations.py
Closes https://github.com/inspirehep/inspire-next/issues/2676.
=> utils: refactor pointless Citation class

inspirehep/modules/theme/views.py, inspirehep/utils/references.py
Closes https://github.com/inspirehep/inspire-next/issues/2677.
=> utils: refactor pointless Reference class

setup.py
Otherwise https://travis-ci.org/inspirehep/inspire-next/jobs/275252305#L1067 happens.
=> setup: pin node-semver

inspirehep/modules/theme/static/js/settings.js, setup.py
=> theme: temporarily remove invenio-trends

setup.py
* Fixes superlance dependency in the worker-node.
* Cleans extra_require definitions.
Co-authored-by: David Caro <david@dcaro.es>
=> setup: fix superlance dependency

setup.py
=> harvesting: upgraded hepcrawl to latest

tests/acceptance/conftest.py, tests/integration/conftest.py, tests/integration/workflows/conftest.py, tests/unit/conftest.py
=> tests: improve all conftests

setup.py
When inveniosoftware/invenio-oaiharvester#42 use upstream version.
=> setup: pin fixed invenio-oaiharvester

inspirehep/modules/fixtures/__init__.py, inspirehep/modules/fixtures/ext.py, inspirehep/modules/forms/__init__.py, inspirehep/modules/forms/ext.py, inspirehep/modules/literaturesuggest/__init__.py, inspirehep/modules/literaturesuggest/ext.py, inspirehep/modules/tools/__init__.py, inspirehep/modules/tools/ext.py, setup.py
=> global: refactor most extensions

docs/conf.py, docs/index.rst, inspirehep/modules/hal/utils.py
=> global: fix warnings when building the docs

inspirehep/modules/authors/forms.py, inspirehep/modules/records/receivers.py, pytest.ini, tests/integration/workflows/conftest.py, tests/integration/workflows/helpers/calls.py, tests/unit/editor/test_editor_views.py, tests/unit/records/test_records_json_ref_loader.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Fixes the PyFlakes errors about indentation.
=> global: fix E121, E123, E126, and E128

tests/acceptance/conftest.py, tests/integration/conftest.py
=> tests: clarify that only tasks need local imports

setup.py
=> setup: upgrade inspire-crawler

inspirehep/modules/theme/static/scss/format/detailed-record.scss, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Conference_HTML_detailed.tpl
Fixed the detailed conference template to correctly display the address, series, short description, and website of the conference 
(partly) fixes #2736
=> themes: fix the detailed conference template

inspirehep/modules/forms/static/js/forms/conferences_typeahead.js, inspirehep/modules/records/mappings/records/conferences.json, tests/acceptance/literature/test_literature_new_form.py
=> literaturesuggest: conference autocomplete fix

inspirehep/modules/migrator/cli.py
* Adds new report_errors CLI to pipe into a .csv file all record IDs
and the corresponding error.
* Improves populate CLI option parsing by using flags where they are
due.
=> migrator: new report_errors CLI

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Conference_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Institution_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Job_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/search/collection_map.html
=> Add maps api key

inspirehep/modules/hal/__init__.py, inspirehep/modules/hal/config.py, inspirehep/modules/hal/core/sword.py, inspirehep/modules/hal/core/tei.py, inspirehep/modules/hal/ext.py, inspirehep/modules/hal/utils.py
=> hal: improve docstrings

README.rst, setup.py
In particular removes all mentions of the overlay concept, as it's no
longer true that INSPIRE is an overlay of Invenio (closes #2253).
Closes #2253.
=> docs: improve the README

requirements.txt, setup.py
Addresses https://github.com/inspirehep/inspire-next/issues/2250.
=> setup: remove postgresql extra

setup.py
Addresses https://github.com/inspirehep/inspire-next/issues/2250.
=> setup: make tests_require more uniform

docker-compose.deps.yml, setup.py
Addresses https://github.com/inspirehep/inspire-next/issues/2250.
=> setup: make extras_require more uniform

inspirehep/version.py, setup.py
Closes https://github.com/inspirehep/inspire-next/issues/2250.
=> setup: refactor entire file

setup.py
I don't remember, or have have an explanation why this was failing. Let's watch it burn!
=> setup: unpin elasticsearch-dsl

inspirehep/modules/editor/views.py, tests/integration/editor/test_editor_views.py
* Adds views for getting revisions and reverting.
=> editor: record revisions api

inspirehep/modules/theme/static/scss/format/brief-results.scss
fix facets ui for mozilla browser
In combination with PR [#42](https://github.com/inspirehep/inspirehep-search-js/pull/42) in inspirehep-search-js this PR fixes #2806
=> theme: fix facets ui for mozilla browser

inspirehep/config.py
=> config: enable access cache

inspirehep/modules/records/mappings/records/authors.json, inspirehep/modules/records/mappings/records/conferences.json, inspirehep/modules/records/mappings/records/experiments.json, inspirehep/modules/records/mappings/records/hep.json, inspirehep/modules/records/mappings/records/institutions.json, inspirehep/modules/records/mappings/records/jobs.json, inspirehep/modules/records/mappings/records/journals.json
Resurrection of https://github.com/inspirehep/inspire-next/pull/2039, since https://github.com/inspirehep/inspire-dojson/pull/107 has happened.
=> mappings: use date format wherever possible

inspirehep/modules/records/mappings/records/hep.json
Closes https://github.com/inspirehep/inspire-next/issues/2848.
=> mappings: analyze arXiv ids and DOIs as lowercase

inspirehep/modules/records/json_ref_loader.py, tests/integration/records/test_records_json_ref_loader.py
New load_resolved_schema function that allows loading a given
schema with all $ref resolved.
=> records: add load_resolved_schema

inspirehep/modules/workflows/ext.py, inspirehep/modules/workflows/mappings/holdingpen/hep.json, inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/workflows/article.py, requirements.txt, setup.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_tasks_matching.py
Closes https://github.com/inspirehep/inspire-next/issues/2527.
=> workflows: integrate inspire-matcher

setup.py
=> setup: bump inspire-query-parser to version ~1.0

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
=> figures: Append the figure extension in figure `key`

setup.py
=> setup: pin SQLAlchemy

setup.py
Hepcrawl was upgraded to the latest schemas.
=> setup: pin to next version of hepcrawl

setup.py
* Upgrades Raven dependency in order to use Central Sentry service.
=> setup: upgrade Raven

inspirehep/modules/migrator/cli.py
=> migrator: improved reporterrors

inspirehep/modules/records/wrappers.py, inspirehep/modules/theme/jinja2filters.py, inspirehep/modules/theme/static/scss/search/collection.scss, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Experiment_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Journal_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/search/form/controls.html, tests/unit/records/test_records_wrappers.py, tests/unit/theme/test_theme_jinja2filters.py
=> Integrate ui changes

setup.py
Periodical sync between schemas and hepcrawl.
=> setup: bump version of hepcrawl to match schemas

services.yml
=> docker: add usable workdir for scrapy

inspirehep/modules/records/api.py, inspirehep/modules/records/utils.py, inspirehep/modules/workflows/tasks/upload.py, tests/integration/editor/test_editor_views.py, tests/integration/test_records.py
~This PR is just a POC about something we discussed in #2623, it
started as quick patch but looks complete :/, will push to that one
if we agree to use this in it's tead.~
~Opened a PR just to see if it passes the travis tests.~
This has become the main PR now.
=> record: add documents/figures handling methods

inspirehep/modules/search/bundles.py
=> search: use latest version of invenio search

inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html
=> editor: remove redundant assets and scripts

inspirehep/modules/forms/validators/simple_fields.py, inspirehep/modules/workflows/tasks/matching.py, setup.py
See: https://github.com/inspirehep/inspire-matcher/pull/29.
=> global: adapt to the new inspire-matcher API

inspirehep/modules/records/api.py, inspirehep/modules/workflows/tasks/upload.py, tests/integration/test_records.py
* That way you can merge more than one single record, and still get
the files from all the merged ones.
=> documents: allow passing a list of source record

inspirehep/alembic/cb9f81e8251c_add_record_metadata_indices.py, inspirehep/modules/literaturesuggest/normalizers.py, tests/integration/conftest.py, tests/integration/test_alembic.py
=> literaturesuggest: make use of JSONB in normalizers

inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html
* Adds title to record editor HTML page. (closes #2960)
=> theme: record editor page title change

inspirehep/modules/workflows/workflows/author.py
When starting a user update workflow, a curation ticket is created, but the user is not notified. This leads to many support tickets from users wondering if anything has happened.
Note that, as this adds a step to the author workflow, it requires some action (hopefully only for author updates, not new authors).
Users should receive feedback for their actions.
=> workflows: send email to user for author update

docs/alembic.rst, docs/developers_guide.rst
=> docs: Create docs for alembic

inspirehep/modules/forms/static/js/forms/books_typeahead.js, inspirehep/modules/literaturesuggest/static/js/literaturesuggest/literature_submission_form.js
=> literaturesubmit: fixes typeahead issue with value reappearing

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
Addresses https://github.com/inspirehep/inspire-next/issues/2643
https://github.com/inspirehep/inspirehep-search-js/pull/50
=> holdingpen scss: Reject button new scss class

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl
=> theme: fix template for records without authors

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl
=> theme: fix kek links macro

inspirehep/modules/theme/static/js/feedback/templates/modal.mustache, inspirehep/modules/theme/static/scss/feedback/modal.scss
=> theme: change the style of modals

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
Following updates were made:
1. The text color of 'Dashboard' link in the header is changed to white for more visibility
2. The checkbox in the table header and the rest of the checkboxes in the body were not properly aligned earlier
3. The background color of the search input box has been changed to make it more visible. Also, it's right alignment is corrected
4. The buttons and text under 'Action and Status' is left aligned
5. The labels in the facets were floating to the right earlier. This has been corrected
Final result now
=> theme: update holdingpen ui

tests/unit/records/test_records_receivers.py
=> tests: refactor receivers unit tests

setup.py
This works around the current issue on pytest:
https://github.com/davehunt/pytest-metadata/issues/5
To be unpinned once fixed.
=> setup: pin pytest to 3.2.5

inspirehep/modules/search/bundles.py
=> search: bump invenio-search-js to 1.4.0

setup.py
The issue mentioned in 293c7e8 has been fixed, so we can unpin.
=> setup: unpin pytest

inspirehep/modules/theme/static/scss/format/brief-results.scss
Reset link added to facets
fixes #1827
=> theme: style the reset link in facets

inspirehep/modules/tools/utils.py, tests/unit/tools/test_tools_utils.py
Closes https://github.com/inspirehep/inspire-next/issues/2964.
=> tools: fix bug in authorlist

tests/integration/test_search_views.py
=> tests.integration: adapt to new invenio-search

.gitignore, inspirehep/config.py, inspirehep/modules/editor/views.py, tests/integration/conftest.py, tests/integration/editor/test_editor_views.py
=> editor: add file upload view

inspirehep/modules/search/templates/search/search.html, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl
=> search: fix latex in lit search and detailed templates

inspirehep/modules/authors/views.py, inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/tasks.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/author.py, setup.py, tests/integration/test_records.py, tests/integration/workflows/helpers/calls.py, tests/unit/workflows/test_workflows_tasks_submission.py
=> global: bump inspire-dojson to version ~57.0

inspirehep/modules/workflows/tasks/matching.py, tests/unit/workflows/test_workflows_tasks_matching.py
=> workflows: allow rerunning the 'matches' steps

inspirehep/modules/workflows/tasks/matching.py
=> workflows: don't fail on empty holdingpen matches

inspirehep/config.py, inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/marcxml.py, tests/integration/records/test_records_serializers_marcxml.py
=> records: add MARCXML serializer

setup.py
=> setup: bump hepcrawl to ~5.0

inspirehep/modules/theme/views.py
=> Reraise if exception has no code

inspirehep/modules/workflows/tasks/arxiv.py
=> plot_extract: check if a file exists before deleting from ``_files``

inspirehep/modules/records/api.py
=> records: always open files in binary mode

inspirehep/modules/records/tasks.py, tests/integration/test_records.py
Closes #2912.
Merging records now works in the opposite direction. All the records having ``deleted_records`` are retrieved from ES. Then, all the records referred in that field are loaded and merged into the enriched record.
=> tasks: merge records based on `deleted_records`

inspirehep/modules/records/mappings/records/hep.json, setup.py
Added `raw` field to `external_system_identifiers.value` .
https://github.com/inspirehep/inspire-query-parser/issues/65
https://github.com/inspirehep/inspire-query-parser/pull/70
It is needed for the inspire_query_parser to support `irn`(term) queries.
=> mappings: add raw field to ext_sys_ids.value

inspirehep/modules/theme/views.py, tests/unit/theme/test_theme_views.py
=> theme: fix unicode error in postfeedback

inspirehep/modules/records/wrappers.py, inspirehep/modules/theme/static/scss/format/detailed-record.scss, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl, tests/unit/records/test_records_wrappers.py
Closes https://github.com/inspirehep/inspire-next/pull/3026, closes https://github.com/inspirehep/inspire-next/pull/3026, and as a consequence closes https://github.com/inspirehep/inspire-next/issues/3053.
=> theme: various fixes

inspirehep/modules/migrator/tasks.py
Using Python's module logger actually logs any errors that the migrator
might have (e.g. validation errors). These also show up in the terminal
compared to the task logger of Celery.
When running `inspirehep migrator one --recid= 1367322` it failed silently for this record with this error
```
ERROR:inspirehep.modules.migrator.tasks:Migrator Validator Error: properties.references.items.properties.reference.properties.urls.items.properties.value.format, Value: u'www.physics.ohio-state.edu/\u223cmathur', Record: 1367322
```
With this PR, I can see the error in the terminal where I was running the command: 
```
Migrating record 1367322 from INSPIRE legacy
------------------------------------------------------------------------------- …
```
=> migrator: use python module logger

docker-compose.yml
=> docker: fix wrong queue name in compose

inspirehep/modules/workflows/tasks/upload.py
=> workflows: fix updated record retrieval

inspirehep/modules/workflows/views.py
When getting an update for a record, we will not need to wait for
webcol, thus we don't have to store the relation workflow_id-recid
anywhere.
Signed-off-by: Antonio Cesarano <acesarano2607@gmail.com>
=> workflows: don't create pending entry on updates

inspirehep/config.py, inspirehep/modules/forms/validators/simple_fields.py
=> forms: add configurable url for duplicate validator

INSTALL.rst, setup.py
=> docs: improve installation notes for MacOS

inspirehep/modules/records/api.py, tests/integration/test_records.py
=> inspire_record: clean data before creating a record

inspirehep/modules/migrator/tasks.py
=> migrate_and_insert_record: handle undefined recid

inspirehep/config.py
=> set the default sorting order as descending

docs/harvesting.rst, setup.py
=> setup: bump hepcrawl to 9

docker-compose.yml
This is not really used yet in the tests, only if you want to try
harvesting locally.
=> docker: adapt to new harvest configs

inspirehep/modules/cache/__init__.py, inspirehep/modules/cache/providers/__init__.py, inspirehep/modules/cache/providers/lock.py, inspirehep/modules/cache/proxies.py, tests/integration/cache/test_lock_cache.py
* Adds the ``cache`` module with a ``lock_cache`` proxy for
easy access to the lock cache.
=> global: addition of the ``cache`` module

inspirehep/modules/workflows/tasks/actions.py, tests/unit/workflows/test_workflows_tasks_actions.py
Fixes the bug that will be explained in https://github.com/inspirehep/inspire-next/pull/2753#discussion_r164050594.
=> workflows: fix fix_submission_number

inspirehep/modules/records/wrappers.py
Use a list comprehension instead of ``map`` and ``filter``.
=> records: improve a little the coding style

inspirehep/modules/editor/bundles.py, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Conference_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Experiment_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Institution_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/Job_HTML_detailed.tpl, inspirehep/modules/theme/templates/inspirehep_theme/format/record/authors/Author_HTML_detailed.html
Closes #3132
Shouldn't be merged before a new release of `record-editor`
=> theme: update record-editor links

inspirehep/modules/migrator/tasks.py, tests/integration/migrator/test_migrator_tasks.py
=> migrator: also store records on DoJSON exception

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
The color of the text input in the search box is made darker
The text input in the search box of holding pen was not quite legible
=> theme: make the input text of search box darker

docker-compose.test.yml
=> docker: remove unneeded dependencies

inspirehep/modules/migrator/tasks.py, inspirehep/modules/tools/authorlist.py, inspirehep/modules/workflows/tasks/matching.py, setup.cfg, tests/integration/test_records.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_workflow_actions.py, tests/integration/workflows/test_workflows_manual_merge.py, tests/unit/tools/test_tools_authorlist.py, tests/unit/workflows/test_workflows_tasks_matching.py
This allows running flake8 with the project settings out of pytest.
=> setup: add flake8 conf for editor/cli

docs/dev_flow.rst, docs/docker.rst
Fixed Documentation
Changed a couple of documents of the documentation that had spelling mistakes or doubled sentences.
Easier to read and allows me to practice with git and github
=> docs: minor improvements to docker and dev guide

inspirehep/modules/orcid/converter.py
Just removed the comment because @szymonlopaciuk has taken care of this problem in his bibtex PR
=> remove the TODO comment from OrcidConeverter

inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py
=> workflows: add validation at the beginning

inspirehep/modules/records/mappings/records/hep.json
* Adds filter for case insensitive in ``report_number``.
=> mappings: addition of report number filters

inspirehep/modules/orcid/__init__.py, inspirehep/modules/orcid/utils.py, tests/integration/orcid/test_orcid_utils.py
=> orcid: push a record to ORCID

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_refextract.py, tests/unit/workflows/test_workflows_tasks_submission.py
* references are extracted from `raw_refs` if there are `references` in the record metadata.
* references are not removed before shipping the record to legacy.
=> workflows: improve reference handling

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py
=> workflows: show useful message on validation error

inspirehep/modules/workflows/tasks/actions.py, tests/unit/workflows/test_workflows_tasks_actions.py
=> workflows: don't auto-reject auto-approved workflows

inspirehep/modules/hal/core/tei.py, inspirehep/modules/hal/templates/hal/art.xml, inspirehep/modules/hal/templates/hal/comm.xml, inspirehep/modules/hal/templates/hal/preprint.xml
Resubmitting https://github.com/jacquerie/inspire-next/commit/2625e191ec9ece4f9e170ad07ce54ec907c21f35 from https://github.com/inspirehep/inspire-next/issues/2629#issuecomment-364265687 so that it can be part of the next push.
=> hal: also send the subtitle

.gitignore
Because this drove me mad all day.
=> git: ignore items created by scrapy runs

inspirehep/modules/search/api.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/53/
=> search: remove annoying exception

inspirehep/modules/workflows/workflows/article.py
=> workflows: fix of rt duplication

inspirehep/modules/forms/validation_utils.py, tests/unit/forms/test_forms_validation_utils.py
=> orcid: fix ``MemberAPI`` search

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
See: inspirehep/inspirehep-search-js/pull/68
=> workflows: add bottom margin to resolve errors btn

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss, inspirehep/modules/workflows/search.py
Style the UI for possible matches added in inspirehep-search-js (PR [#65](https://github.com/inspirehep/inspirehep-search-js/pull/65))
On search results page (holdingpen)
On the detailed record view:
Success message:
=> theme: add style to the possible matches UI

requirements.txt
=> setup: fix ``invenio-indexer`` requirement

inspirehep/modules/orcid/tasks.py, tests/integration/orcid/test_orcid_import_legacy_tokens.py
Signed-off-by: Szymon Łopaciuk <szymon.lopaciuk@cern.ch>
=> orcid: bugfix: don't confuse client_id with ORCID

inspirehep/config.py, inspirehep/modules/records/receivers.py, tests/integration/records/test_records_receivers.py
Signed-off-by: Szymon Łopaciuk <szymon.lopaciuk@cern.ch>
=> orcid: add a feature flag for ORCID push

inspirehep/modules/orcid/utils.py, inspirehep/modules/records/receivers.py, setup.py, tests/integration/orcid/test_orcid_utils.py
Also looks for ORCIDs to push a paper to in the author records that have claimed the paper.
Depends on #3224.
Fixes https://its.cern.ch/jira/browse/INSPIR-250.
=> orcid: also push to orcid in author record

requirements.txt, setup.py
=> setup: bump ``invenio-indexer`` version

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss, inspirehep/modules/workflows/templates/inspire_workflows/index.html
* Uses feature flag not to display on prod
* Reorders cards
* Recolors cards
* Fixes previous search query
=> holdingpen: add publisher harvests card back

inspirehep/modules/orcid/utils.py
=> orcid: fix ORCID login INSPIR-243

inspirehep/modules/workflows/search.py
=> holdingpen: add crawl_errors to search results

tests/integration/migrator/test_migrator_tasks.py
* I realised that the previous tests were not working, as the default senting for ORCID push feature was 'False'
* also use properly `assert_not_called` on `attempt_push` instead of manually throwing an assertion error
=> receivers: tests fix: migration orcid push disable

inspirehep/modules/records/receivers.py, tests/integration/workflows/test_workflows_tasks_upload.py
Closes https://github.com/inspirehep/inspire-next/pull/3252.
=> records: don't push to ORCiD without recid

inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py
*Fix to save a reharvest if its now a valid article
for our system
=> workflow fix for preventing rejecting reharvests

inspirehep/config.py, inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
https://its.cern.ch/jira/browse/INSPIR-237
=> workflow: retry arxiv download from non-export url INSPIR-237

setup.py
=> setup: put pytest-vcr in the right place

inspirehep/modules/tools/templates/authorlist_form.html
=> add clear button to authorlist page

inspirehep/modules/orcid/utils.py
This allows the database to use an index on the `(json -> ids)`, which
it doesn't do if the join on the PIDStore happens in the same query.
=> orcid: split get_literature_recids_for_orcid query

inspirehep/modules/orcid/tasks.py, tests/integration/orcid/test_orcid_import_legacy_tokens.py
https://its.cern.ch/jira/browse/INSPIR-296
=> orcid: plug get_literature_recids_for_orcid

setup.py
=> setup: remove pin on invenio-oauthclient

INSTALL.rst, inspirehep/modules/migrator/cli.py, scripts/recreate_records
QoL fixes after https://github.com/inspirehep/inspire-next/pull/3286.
=> scripts: use migrate, not migrator

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/tasks/refextract.py, inspirehep/utils/record.py, tests/unit/utils/test_utils_record.py, tests/unit/workflows/test_workflows_tasks_actions.py
=> workflows: protect plot extraction with a timeout

tests/integration/workflows/test_arxiv_workflow.py
=> workflows: fix typo at wf test

inspirehep/modules/orcid/utils.py, tests/integration/helpers/factories/__init__.py, tests/integration/helpers/factories/db/__init__.py, tests/integration/helpers/factories/db/base.py, tests/integration/helpers/factories/db/invenio_accounts.py, tests/integration/helpers/factories/db/invenio_oauthclient.py, tests/integration/orcid/test_orcid_utils.py
https://its.cern.ch/jira/browse/INSPIR-427
https://its.cern.ch/jira/browse/INSPIR-334
=> tests: test factories for User and related models INSPIR-427

inspirehep/modules/orcid/tasks.py, tests/integration/orcid/test_orcid_import_legacy_tokens.py
=> orcid: fix orcid_push call

inspirehep/modules/workflows/templates/inspire_workflows/index.html
*Fixes all harvests query to introduce workflows that dont
have the 'is-update' key.
=> holdingpen: fix all harvests query

inspirehep/config.py, inspirehep/modules/orcid/api.py, inspirehep/modules/orcid/tasks.py, inspirehep/modules/orcid/utils.py, tests/unit/orcid/test_orcid_utils.py
- change logging format to match that of celery (incl. worker process name, logger name [i.e. module path] instead of just module name
- log the reason of retry on the orcid_push task
- log cache miss for storing hashes & put-codes in Redis
- log duration of re-cacheing, thanks to new function timing decorator util
[This is effectively a follow-up of #3340.]
=> orcid: add more logging for troubleshooting and stats

inspirehep/config.py, inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss, inspirehep/modules/workflows/search.py, inspirehep/modules/workflows/tasks/matching.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_tasks_matching.py
Search results
Search results view when more than 1 records match
Detailed View
=> add more fields for the possible matches results

inspirehep/config.py
=> holdingpen: add filter for decision type

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
=> theme: add style to pub_info for possible matches detailed page

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
=> add style for public_notes in possible matches

inspirehep/config.py
=> holdingpen: show most recent results for queries

inspirehep/modules/workflows/tasks/merging.py
* Fixes an issue with workflows that contained documents and figures.
=> workflows: fix of merge workflows with documents

requirements.txt, setup.py
=> setup: temp fix for flower

setup.py
https://its.cern.ch/jira/browse/INSPIR-616
=> 616 requirements: pin Flask to 0.12.2 because 0.12.3 breaks

setup.py
Jira: https://its.cern.ch/jira/browse/INSPIR-623
=> 616 setup: unpin Flask

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_workflows_tasks_upload.py, tests/unit/workflows/test_workflows_tasks_submission.py
=> workflows: add feature flag action

inspirehep/modules/workflows/tasks/actions.py, tests/unit/workflows/test_workflows_tasks_actions.py
Hotfix for the duplicated refs issue in prod
=> Dedupe references hotfix

inspirehep/modules/workflows/templates/inspire_workflows/index.html
=> rename publisher and arxiv updates card in hp

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_workflows_tasks_upload.py, tests/unit/workflows/test_workflows_tasks_submission.py
It has some common code boilerplate commonly needed to start a
workflow.
=> workflows: fix workflow type check

inspirehep/modules/workflows/tasks/upload.py, inspirehep/modules/workflows/utils/__init__.py, tests/integration/workflows/test_arxiv_merge.py
=> merger: handle and test source-less updates

inspirehep/modules/records/mappings/records/hep.json
Following the decision by @StellaCh in chat (https://inspirehep.zulipchat.com/#narrow/stream/122209-reviews/subject/inspire-next.20.2F.20PR.20.233128.20search.3A.20hep-titles.20improvements) let's merge the mapping changes now and add a Jira task to add tests for them later.
Closes https://github.com/inspirehep/inspire-next/pull/3128.
=> mappings: improve title search

inspirehep/config.py, inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/serializers/schemas/json.py, inspirehep/modules/search/templates/search/search.html, tests/unit/records/test_records_serializers_json_literature.py
=> serializers: addition of ``ui`` serializer

docker-compose.yml
Remove the proxy, and dependencies on it from the docker-compose.yml file, as it's just needed in the test compose.
=> docker-compose.yml: don't proxy

tests/e2e/test_arxiv_harvest.py
=> e2e: add external system calls assertions

inspirehep/config.py
=> config: consolidate usage of dicts and rest endpoints

inspirehep/modules/disambiguation/core/ml/__init__.py, inspirehep/modules/disambiguation/core/ml/models.py, setup.py, tests/unit/disambiguation/test_disambiguation_core_ml_models.py
Integrates https://github.com/inspirehep/beard/blob/87b37a3028825b5199616b195663fee526c26be3/examples/applications/author-disambiguation/ethnicity.py.
=> disambiguation: add ethnicity estimator

inspirehep/config.py, inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/schemas/json.py, inspirehep/modules/theme/views.py, inspirehep/utils/references.py, tests/integration/helpers/factories/db/invenio_pidstore.py, tests/integration/records/fixtures/29177.json, tests/integration/records/test_records_utils.py, tests/unit/records/serializers/test_schemas_json.py
* Addition of ``references`` endpoint for literature.
=> global: addition of ``references`` endpoint for literature

inspirehep/modules/records/checkers.py, inspirehep/modules/records/cli.py, inspirehep/modules/records/ext.py, setup.py, tests/integration/records/test_cli.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
=> records: add functionality check unlinked references

inspirehep/modules/records/api.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/utils/__init__.py, tests/integration/records/test_records_api.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_utils.py
=> workflows: addition of copy local files

inspirehep/modules/workflows/config.py, setup.py, tests/integration/workflows/test_workflows_tasks_refextract.py
=> workflows: don't ref-match hidden and deleted recs

inspirehep/modules/records/checkers.py, tests/integration/records/test_cli.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
=> records: link doi and arxiv eprint of unlinked literature

docs/operations.rst, inspirehep/modules/workflows/mappings/holdingpen/hep.json
This disables the default behaviour of the dynamic mapping creation, which can cause conflicts when two records with conflicting types, e.g. in extra_data, are indexed. Instead, this will only enable indexing on fields specified explicitly and will ignore the rest.
Also fixed a small mistake in docs related to the remapping.
| Test | Outcome (local) | Outcome (QA)
|---|---|---|
|new core arxiv harvest | OK (appears in inspire)| :arrow_left::ok: |
|new publisher harvest | OK (appears in inspire)| :arrow_left::ok: |
|update from arxiv | OK (updated in inspire)| :arrow_left::ok: |
|update from DESY | OK (updated in inspire)| :arrow_left::ok: |
|workflow errors when matched against WF in ERROR | OK (workflow in ERROR)| :arrow_left::ok: |
|article submission form blocks if submission WF has it …
=> 907 workflows: make HP hep mapping non-dynamic

inspirehep/modules/workflows/views.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_edit_article.py
=> edit_article: at the end redirect to referrer or root

inspirehep/testlib/api/holdingpen.py, tests/e2e/scenarios/harvest_core_article_goes_in/ArxivService/core_article_update.yaml, tests/e2e/test_arxiv_harvest.py
=> Add a new e2e test for a core harvest update

inspirehep/testlib/api/base_resource.py, inspirehep/testlib/api/holdingpen.py, inspirehep/testlib/api/literature.py, setup.py, tests/e2e/test_arxiv_harvest.py
As it includes the python requests version, better ignore it.
=> fix current test issues so we can merge

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/edit_article.py, tests/integration/workflows/test_edit_article.py
=> edit_workflow: cleanup the pending workflows entries

inspirehep/testlib/api/base_resource.py, tests/e2e/test_arxiv_harvest.py
Addresses the comments that got overlooked at #3520
=> e2e: fix small nits

inspirehep/modules/workflows/search.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/edit_article.py, inspirehep/testlib/api/base_resource.py, inspirehep/testlib/api/holdingpen.py, inspirehep/testlib/api/literature.py, scripts/modify_record.py, setup.py, tests/e2e/scenarios/harvest_core_article_goes_in/ArxivService/core_article_update.yaml, tests/e2e/test_arxiv_harvest.py, tests/integration/workflows/test_edit_article.py
=> release: v0.11.3

requirements.txt
=> setup: addition of ``dictdiff`` fork

inspirehep/modules/hal/bulk_push.py, inspirehep/modules/hal/cli.py, inspirehep/modules/hal/tasks.py
=> 249 HAL: wrap the hal push in a task

requirements.txt, setup.py
=> setup: addition of flower from pypi

setup.py
=> hal: register tasks on setup

.gitignore, inspirehep/modules/records/serializers/schemas/common/__init__.py, inspirehep/modules/records/serializers/schemas/common/isbn.py, inspirehep/modules/records/serializers/schemas/common/thesis_info.py, inspirehep/modules/records/serializers/schemas/json.py, tests/unit/records/serializers/common/test_isbn.py, tests/unit/records/serializers/common/test_thesis_info.py
* Adds marshmallow serializer for record metadata (hides unnecessary
fields)
* Adds serialiser for isbns and thesis_info
=> serializers: add initial record serializers

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss
=> set display of decision buttons container as inline

inspirehep/modules/records/serializers/schemas/common/conference_info_item.py, inspirehep/modules/records/serializers/schemas/json.py, inspirehep/modules/records/wrappers.py, tests/integration/records/serializers/test_schemas_json.py
=> serializers: add conference_info

inspirehep/modules/authors/views.py
Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>
=> authors: fill source_data for author updates

inspirehep/modules/authors/views.py
- fill source data in the author update form
- fix the restart current step button
=> Release v0.11.8

inspirehep/modules/records/serializers/schemas/common/__init__.py, inspirehep/modules/records/serializers/schemas/common/reference_item.py, inspirehep/modules/records/serializers/schemas/json.py, tests/integration/records/serializers/test_schemas_json.py, tests/unit/records/serializers/common/test_reference_item.py, tests/unit/records/serializers/test_schemas_json.py
=> serializers: fix issue with label in references

inspirehep/config.py
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/agg-metadata.html
=> config: addition of ``meta`` in ``aggs``

inspirehep/modules/records/receivers.py, tests/unit/records/test_records_receivers.py
=> receivers: populate experiment_suggest

inspirehep/config.py, inspirehep/modules/authors/static/js/authors/templates/publications.html, inspirehep/modules/theme/templates/inspirehep_theme/citations.html, inspirehep/modules/theme/templates/inspirehep_theme/references.html, tests/integration/test_detailed_records.py, tests/integration/test_permissions.py
=> global: rename UI ``/literature`` to ``/old-literature``

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/utils/__init__.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/author.py, tests/e2e/test_submissions.py, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_actions.py
=> INSPIR-1056 workflows: don't repeat ticket creation

inspirehep/modules/records/receivers.py
=> citation_count: fix indexing receiver

inspirehep/modules/records/api.py, inspirehep/modules/records/serializers/__init__.py, inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/serializers/schemas/json/__init__.py, inspirehep/modules/records/serializers/schemas/json/literature/__init__.py, inspirehep/modules/records/serializers/schemas/json/literature/common/citation_item.py, inspirehep/modules/records/views.py, inspirehep/modules/theme/views.py, inspirehep/utils/citations.py, setup.py, tests/integration/records/test_records_views.py, tests/unit/records/serializers/literature/common/test_citation_item.py
=> records: addition of citations REST

docs/harvesting.rst
Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>
=> docs: update harvesting doc

inspirehep/modules/theme/templates/inspirehep_theme/format/record/Publication_info.tpl
This will not be needed once we have the proper blueprints (see #3614)
but for now it's a quick fix.
=> citations: dummy fix to be able to show citations

inspirehep/modules/authors/forms.py
* anchor the regexp to avoid trailing junk
* exclude INSPIRE-00000000
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
fixes https://github.com/inspirehep/inspire-next/issues/3608
=> forms: stricter INSPIRE-Id verification

inspirehep/modules/migrator/cli.py, inspirehep/modules/migrator/tasks.py, scripts/recreate_records, tests/integration/conftest.py
Removed old citation count
Also removed migrator task for counting citations
Closes INSPIR-1150
=> Removed old citation count

inspirehep/modules/records/serializers/schemas/json/literature/__init__.py, inspirehep/modules/records/serializers/schemas/json/literature/common/doi.py, tests/unit/records/serializers/literature/common/test_doi.py
Signed off-by: Dinika Saxena <dinika.saxena@cern.ch>
User-Story: [INSPIR-1154](https://its.cern.ch/jira/browse/INSPIR-1154)
=> records: remove duplicate doi values

inspirehep/modules/search/search_factory.py, tests/integration/test_search_views.py
=> Specify which fields should be returned from ES for LiteratureSearch

tests/integration/records/test_records_views.py
=> records: ignore order in citations tests

inspirehep/modules/theme/views.py
* Passes json serilized user role names for the current user to the
opener tab (inspirehep-ui)
=> pass user roles with login_success

scripts/recreate_records
Add alembic to recreate_records script so it would be able to create index for citations.
=> "Recreate record" script fix

inspirehep/modules/records/api.py, inspirehep/modules/records/receivers.py, inspirehep/modules/records/serializers/json_literature.py, inspirehep/modules/records/serializers/schemas/json/literature/common/conference_info_item.py, inspirehep/modules/workflows/tasks/merging.py, scripts/modify_record.py, tests/unit/records/test_records_receivers.py
=> records: add 'earliest_date' to literarure detail api

docker-compose.yml, inspirehep/modules/records/cli.py, inspirehep/modules/records/receivers.py, tests/integration/records/test_records_receivers.py, tests/integration/records/test_records_views.py, tests/integration/workflows/test_edit_article.py
added a check to see if a record has deleted flag true before indexing it to es. If it is deleted, then the index is deleted from es as well
added integration tests
=> Remove deleted records from search

inspirehep/config.py
For now, it only includes fields we need on author submission form.
=> suggestors: specify fiels to include in _source

inspirehep/config.py
Removed the best match sorting option
=> Remove sorting by best match

inspirehep/modules/forms/validators/simple_fields.py, setup.py
Changed the link for the submission form from labs to legacy
=> Submission form link to labs

inspirehep/modules/records/api.py, inspirehep/modules/records/exceptions.py, inspirehep/modules/records/receivers.py, inspirehep/modules/records/utils.py, inspirehep/utils/record.py, tests/integration/records/test_records_api.py, tests/integration/records/test_records_receivers.py
Fixed issue where not all records were properly re-indexed because of wrong data passed
=> INSPIR-1299 Fix 0 citations bug in search on some records 

scripts/workflows/resolve_missmatch_version_with_legacy.py
=> scripts: resolve missmatch versions

inspirehep/modules/authors/views.py, tests/integration/authors/test_authors_views.py
=> authors: change of redirect url

inspirehep/modules/records/serializers/schemas/json/literature/common/citation_item.py, tests/unit/records/serializers/literature/common/test_citation_item.py
UI now needs to display collaboration for each citation
=> serializers: add collaborations to citation_item

inspirehep/modules/submissions/serializers/schemas/author.py, tests/unit/submissions/serializers/test_authors.py
=> submissions: addition of ``orcid``

inspirehep/config.py
=> config: addition of ``_source`` in authors suggest

inspirehep/modules/records/serializers/schemas/json/literature/common/reference_item.py, tests/integration/records/serializers/literature/test_schemas_json.py, tests/unit/records/serializers/literature/common/test_reference_item.py, tests/unit/records/serializers/literature/test_schemas_json.py
User Story: [INSPIR-1204](https://its.cern.ch/jira/browse/INSPIR-1204)
=> serializers: add misc, url, doi and arxiv eprint to reference item

inspirehep/modules/search/bundles.py
=> search: bump of inspirehep-search-js

inspirehep/modules/submissions/serializers/schemas/author.py, tests/unit/submissions/serializers/test_authors.py
=> submissions: rename ``native_names`` to ``native_name``

inspirehep/config.py, inspirehep/modules/records/facets.py, tests/integration/test_search_views.py, tests/unit/records/test_records_facets.py
=> config: addition of number of authors facet

inspirehep/config.py
For it uses default invenio serializers.
=> authors: add basic ui serializers to config

inspirehep/modules/records/api.py, inspirehep/modules/records/receivers.py, inspirehep/modules/records/tasks.py, inspirehep/utils/record_getter.py, tests/integration/conftest.py, tests/integration/records/test_records_api.py, tests/integration/records/test_records_receivers.py, tests/integration/utils/test_record_getter.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_workflows_tasks_actions.py, tests/integration/workflows/test_workflows_tasks_upload.py
=> citation_count: index new citations records - INSPIR-1127

inspirehep/modules/records/receivers.py, tests/integration/records/test_records_receivers.py
Fixes the issues 251776 on Sentry.
https://sentry.inspirehep.net/inspire-sentry/inspire-qa/issues/251776/
=> citation_count: fix UUID serialization for indexing task

inspirehep/modules/submissions/serializers/schemas/author.py, inspirehep/modules/submissions/views.py, tests/unit/submissions/serializers/test_authors.py
=> serializers: fix unicode names

inspirehep/modules/submissions/views.py, tests/integration/submissions/test_submissions_views.py
=> submissions: restrict the api to login users

inspirehep/config.py, tests/integration/test_search_views.py
Related issue: https://its.cern.ch/jira/browse/INSPIR-1468
=> author_count: use properly elasticsearch range INSPIR-1468

setup.py
=> setup: bump urllib3 to <1.24

Procfile, docker-compose.yml
=> docker-compose: remove unused celery queue

inspirehep/config.py, inspirehep/modules/search/facets.py, inspirehep/modules/search/search_factory.py, inspirehep/modules/search/utils.py, tests/integration/search/test_search_facets.py, tests/integration/search/test_search_utils.py, tests/integration/search/test_search_views.py
=> records: addition of parameterized facets

inspirehep/config.py, inspirehep/modules/records/facets.py, inspirehep/modules/search/facets.py, tests/integration/search/test_search_views.py, tests/unit/records/test_records_facets.py
=> facets: added must match query to terms_filter facets

inspirehep/modules/workflows/tasks/arxiv.py, setup.cfg, tests/unit/workflows/test_workflows_tasks_arxiv.py
Caught request exception in arxiv pdf download and threw them as DownloadError. Added backoff for IO error.
INSPIR-1478
=> retry for arxiv PDF download

tests/integration/search/test_search_views.py
=> Added tests for ea bai queries

inspirehep/modules/records/errors.py, inspirehep/modules/records/tasks.py, inspirehep/modules/records/utils.py, tests/integration/records/test_records_receivers.py
=> tasks: handle new record not yet in DB when indexing citations

inspirehep/modules/records/utils.py, tests/unit/records/test_records_utils.py, tests/unit/theme/test_theme_views.py
=> receivers: extract UMR number for affiliation suggester

inspirehep/modules/records/tasks.py
to be sure what is really happening inside this task.
=> Adding more logs to 'index_modified_citations_from_record' 

inspirehep/modules/records/cli.py
Fixed parameters for CLI record checks
=> Added paralelization to checks

inspirehep/modules/editor/api.py, tests/integration/editor/fixtures/es_response.json, tests/integration/editor/test_editor_api.py
=> editor: match references when extract references from url or text

inspirehep/alembic/53e8594bc789_fix_the_production_db.py
ee6e0ad6cceb0572e46af570a53e7e78a444aee4
=> Remove comment left behind after removing the commented code in ee6e0ad6cceb0572e46af570a53e7e78a444aee4

inspirehep/modules/orcid/tasks.py
In order to make it compatible with @time_execution
=> 1586 monitoring: bind import_legacy_orcid_tokens

inspirehep/modules/search/api.py
=> search: add query-parser on institutions and conferences 

tests/e2e/test_arxiv_harvest.py
=> e2e: disable tests

inspirehep/modules/records/utils.py, tests/unit/records/test_records_utils.py
In case bai doesn't exist, replace it with 'BAI'
=> Check if bai exists during enhancement for facet_author_name

inspirehep/modules/records/serializers/schemas/json/authors/__init__.py, inspirehep/modules/records/serializers/schemas/json/authors/common/__init__.py, inspirehep/modules/records/serializers/schemas/json/authors/common/position.py, tests/unit/records/serializers/authors/common/test_position.py, tests/unit/records/serializers/authors/test_authors_schema_json.py
That returns `display_date` rather than `start_date` and `end_date`.
=> serializers: add author position schema

inspirehep/modules/records/mappings/v5/records/hep.json, tests/integration/search/test_search_views.py
=> Added exact search for affiliations

inspirehep/config.py, inspirehep/modules/records/receivers.py
* Fixes book title autocomplete
* Adds source to conference and book_title
=> suggesters: fix and specify `_source` for lit form

inspirehep/modules/records/mappings/v5/records/hep.json, inspirehep/modules/search/api.py, tests/integration/search/test_search_views.py
Added include_in_all option to mapping in literature. Added tests to check if it behaves properly
=> Added include_in_all option to mapping in literature.

inspirehep/modules/records/serializers/schemas/latex/__init__.py, inspirehep/modules/records/serializers/templates/latex_template.tex, tests/integration/records/test_records_serializers_latex.py, tests/unit/records/serializers/literature/test_schemas_latex.py
Signed-off-by: vbalbp <vbalbp@gmail.com>
=> serializers: fix templating bugs

inspirehep/modules/records/serializers/schemas/json/literature/common/accelerator_experiment.py, tests/unit/records/serializers/literature/common/test_accelerator_experiment.py
=> serializers: fix unicode encoding for accelerator experiments

inspirehep/modules/records/cli.py, tests/integration/records/test_cli.py
=> cli: add find_arxiv_duplicates command INSPIR-1835

inspirehep/utils/references.py, tests/unit/workflows/test_workflows_tasks_refextract.py
=> Dedup urls in references

inspirehep/modules/submissions/serializers/schemas/author.py, tests/unit/submissions/serializers/test_authors.py
=> Add bai to author submission serializer

inspirehep/config.py
=> Added sort by best match

inspirehep/config.py, inspirehep/utils/tickets.py, tests/integration/editor/test_editor_api.py
=> Added caching for rt queues and users

inspirehep/config.py, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/records/serializers/schemas/json/authors/__init__.py, inspirehep/modules/records/serializers/schemas/json/literature/common/collaboration.py, inspirehep/modules/records/serializers/schemas/json/literature/common/collaboration_with_suffix.py, inspirehep/modules/records/tasks.py, tests/e2e/test_arxiv_harvest.py, tests/integration/orcid/test_orcid_putcode_getter.py, tests/unit/workflows/test_workflows_tasks_matching.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
=> config: remove default source in config

inspirehep/modules/records/serializers/config.py, inspirehep/modules/records/serializers/fields_export.py, tests/unit/records/test_records_serializers_fields_export.py
=> records: better bibtex collaboration INSPIR-1773

inspirehep/modules/search/search_factory.py, tests/unit/search/test_search_queries.py
* Search response returns authors' roles
=> literature: add author role for search

setup.py
=> setup: pin munkres~=1.0.12

inspirehep/modules/workflows/tasks/author.py, inspirehep/modules/workflows/views.py, inspirehep/modules/workflows/workflows/author.py, tests/integration/workflows/test_views.py, tests/unit/workflows/test_workflows_tasks_author.py
INSPIR-1902
Added start author workflow endpoint
Moved the tasks from submission module to workflow module
=> Added author submission endpoint

inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_workflows_tasks_upload.py
=> workflow: avoid duplicate records when workflow fails

inspirehep/modules/theme/templates/inspirehep_theme/header.html, setup.py
=> setup: pin Twisted < 19.0.0

inspirehep/modules/workflows/views.py, tests/integration/workflows/test_views.py
That create a workflow for a literature submission.
=> workflows: add literature sub wf endpoint

inspirehep/config.py, inspirehep/modules/fixtures/cli.py, inspirehep/modules/fixtures/users.py, inspirehep/modules/workflows/views.py, setup.py, tests/integration/conftest.py, tests/integration/search/test_search_facets.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_views.py
INSPIR-1992
Added invenio oauth2 server
Added authentication to workflow author submission endpoint
Added fixture to create authentication token for local development
=> Added invenio oauth2 server

.travis.yml, Dockerfile, deploy-docker-image.sh
* Creates new docker imagine to have all necessary things to be able to
run inspire-next as a service (required by inspirehep).
* Pushes docker image to dockerhub when something is merged to master
=> create and push docker image to dockerhub

.travis.yml
* "Attempts" to fix travis deployment "Script failed with status 127"
issue
* Conditions deployment to run only for integration job
=> fix travis deployment script

inspirehep/__init__.py, inspirehep/version.py
=> version: read version from git

inspirehep/modules/theme/templates/inspirehep_theme/login_success.html
In order to inform user to try logging incase of redirection error
(INSPIR-2072)
=> change loging_sucess message

inspirehep/modules/migrator/tasks.py, setup.cfg, tests/integration/migrator/fixtures/deleted_record.xml, tests/integration/migrator/test_migrator_tasks.py
=> migration: do not index deleted records

inspirehep/modules/workflows/views.py, tests/integration/workflows/test_views.py
=> Add authentication to the start literature submission endpoint

Dockerfile, inspirehep/config.py, scripts/setup_inspire_next
This commit is part of the User Story INSPIR-2098.
=> docker: improve Dockerfile and configs

inspirehep/modules/theme/views.py
* login_success page will check if user is Anonymous user,
and will retry if it is. After 5 retries go back to login page.
INSPIR-2355
=> authentication: fix AnonymousUser' object has no attribute 'email'

scripts/workflows/purge_holdingpen.py
=> scripts: add script to purge holdingpen

.gitignore, tests/integration/records/test_records_json_ref_loader.py
=> loader: fix broken test with latest inspire-schemas

inspirehep/modules/workflows/tasks/upload.py
=> edit_article: add ``head_uuid``

docker-compose.test.yml, inspirehep/utils/tickets.py
Same as inspirehep/inspire-next#266.
=> utils: allow overriding RT queues for testing

Dockerfile
=> docker: add ``kstart`` package

inspirehep/utils/normalizers.py, inspirehep/wsgi_with_coverage.py, scripts/workflows/purge_holdingpen.py, setup.cfg, setup.py, tests/integration/conftest.py, tests/integration/helpers/utils.py, tests/integration/records/test_records_receivers.py, tests/integration/records/test_records_views.py, tests/integration/search/test_search_views.py, tests/integration/tasks/test_matching.py, tests/integration/test_records.py, tests/integration/workflows/conftest.py, tests/integration/workflows/test_arxiv_workflow.py, tests/integration_async/conftest.py, tests/integration_async/test_workflows.py, tests/ui/conftest.py
This cannot be merged before this PRs 
~https://github.com/inveniosoftware/invenio-search/pull/183~ (merged)
and
~https://github.com/inspirehep/inspire-schemas/pull/373~ (merged)
=> invenio-modules: Update code to be compatible with invenio-search 1.21

inspirehep/modules/workflows/errors.py, inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_workflows_tasks_upload.py
* Retries when inspirehep returns bad gateway error possibly due to
network issues.
=> workflows: retry while managing record via hep

.travis.yml, deploy-docker-image.sh
=> setup: deploy on QA webhook

setup.py
=> setup: update to the latest invenio-logging

setup.py
=> setup: pin invenio-logging < 1.2

inspirehep/modules/workflows/tasks/arxiv.py, inspirehep/modules/workflows/workflows/article.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
=> workflows: remove derive categories

setup.py
* Update sqlalchemy-continuum to version which is also used in inspirehep
* Update celery to be comaptible with hepcrawl
* INSPIR-2751
=> setup: Update sqlalchemy-continuum

inspirehep/celery.py
* INSPIR-2795
This PR doesn't provide any test since our test environment doesn't support it, even using the `integration_async` test suite.
I have performed some manual tests, together with @pazembrz, here are the steps:
1. Connect to the worker container and check celery processes
* `docker-compose -f docker-compose.yml exec worker bash`
* `watch ps aux` this shows 4 celery processes.
2. Connect to the web container and run a task that raises `InvalidRequestError`
* `docker-compose -f docker-compose.yml exec web inspirehep shell`
* define a `shared_task` whose body has `raise InvalidRequestError()`
* run the task with `.apply_async()`
3. Observe how in the worker container one of the celery process is killed and a new one is spawned.
Signed-off-by: Antonio Cesarano …
=> celery: kill worker process on OperationalError

inspirehep/modules/editor/bundles.py
* In order to trigger deployment
=> record-editor: bumps version

inspirehep/modules/workflows/cli.py, setup.py, tests/integration/workflows/test_workflows_cli.py
=> cli: add restart wf by error message command

inspirehep/modules/workflows/tasks/upload.py, setup.py, tests/integration/workflows/test_workflows_tasks_upload.py
=> workflows: retry on connection error on record creation on hep

requirements.txt, setup.py
=> setup: bump invenio-oauth2server to v1.0.4

setup.py
=> setup: pin cookiecutter

inspirehep/modules/workflows/workflows/article.py
=> article: move store_root after send_to_legacy step

inspirehep/modules/editor/bundles.py
=> setup: bump record-editor

inspirehep/modules/refextract/config.py, inspirehep/modules/refextract/matcher.py, tests/integration/refextract/test_refextract_matcher.py
=> matcher: lower priority for texkey in reference matcher

inspirehep/config.py
=> config: update search_type for workflows

poetry.lock, pyproject.toml
lock elasticsearch client to 7.1.x
INSPIR-3044
=> celery:update celery to 4.4

inspirehep/modules/workflows/search.py
=> holdingpen: Show more than 10k in boxes total number

inspirehep/modules/workflows/views.py
submission_url should be filled before extra_data will be moved to sourcE_data
=> workflows: quick fix formdata_url

inspirehep/utils/references.py, poetry.lock, pyproject.toml
* INSPIR-3190
No tests, as I don't want to touch workflow tests and the feature is already tested in inspire-schemas and inspire-dojson.
=> refextract: handle additional pubnotes

poetry.lock, pyproject.toml
=> poetry: update plotextractor to v0.3.3

inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_core.html, inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_jlab.html
=> RT templates: update urls to editor

poetry.lock
=> poetry: update inspire-dojson to v63.0.10

inspirehep/modules/workflows/views.py
=> RT: submission approval ticket link to labs

inspirehep/modules/editor/api.py, tests/integration/editor/test_editor_api.py
=> views: move revision endpoints to hep

setup.py, tests/integration/conftest.py, tests/integration/workflows/conftest.py, tests/integration_async/conftest.py
=> setup: remove mappings to records

inspirehep/modules/workflows/cli.py, tests/integration/workflows/test_workflows_cli.py
Ref. inspirehep/inspirehep#1071
=> workflows: Add delete edit article cli

inspirehep/config.py, inspirehep/modules/authors/templates/authors/tickets/curation_needed.html, inspirehep/modules/literaturesuggest/tasks.py, inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_core.html, inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_jlab.html, inspirehep/modules/workflows/tasks/author.py, tests/unit/literaturesuggest/test_literaturesuggest_tasks.py
ref inspirehep/inspirehep#1116
=> RT: update legacy url

inspirehep/modules/workflows/views.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py
=> workflows: disable wait_for_webcoll for articles

poetry.lock, pyproject.toml
Also use celery from official branch
ref: inspirehep/inspire-json-merger#81
=> poetry: update inspire-json-merger

inspirehep/modules/workflows/tasks/merging.py
Ref inspirehep/inspirehep#1109
=> workflows: add conflicts_metadata

poetry.lock
ref: inspirehep/inspirehep#1154 inspirehep/inspirehep#1155
=> poetry: update inspire-json-merger to 11.0.6

inspirehep/utils/latex.py, poetry.lock, pyproject.toml, tests/unit/utils/test_utils_latex.py
* ref inspirehep/inspirehep#1273
=> utils: improve LateX decoding

inspirehep/config.py, inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
* ref:  inspirehep/inspirehep#1291
=> matcher: replace match_references with call to hep

poetry.lock, pyproject.toml
Ref: inspirehep/inspirehep#1212
=> setup: bump hepcrawl

inspirehep/modules/workflows/workflows/author.py
Ref: inspirehep/inspirehep#1346
=> author workflow: remove legacy dependencies

inspirehep/modules/editor/views.py
=> editor: add endpoint to get workflow and schema

poetry.lock, pyproject.toml
Ref: inspirehep/inspirehep#1447
=> setup: bump hepcrawl to 13.0.16

inspirehep/modules/workflows/workflows/author.py
* Fix sending author record in correct mode to legacy when updating.
=> Fix on author update

poetry.lock, pyproject.toml
Ref: inspirehep/inspirehep#1465
=> setup: bump hepcrawl 13.0.21

INSTALL.rst, Procfile, docker-compose.test.yml, docker-compose.yml, docs/postgresql.rst, inspirehep/config.py, services.yml
* Updates the documentation and how to get started with `next`.
* Cleans up the Procfile.
=> docker: change postgresql password to be the same with hep

inspirehep/modules/workflows/tasks/merging.py, inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/templates/workflows/tickets/conflicts-ticket-template.html, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_merge.py
=> workflows: create ticket when there is a conflict on wf

inspirehep/modules/authors/templates/authors/tickets/curator_update.html, inspirehep/modules/workflows/tasks/author.py, inspirehep/modules/workflows/workflows/author.py, inspirehep/utils/url.py, tests/integration/workflows/helpers/workflow_utils.py, tests/integration/workflows/test_authors_workflow.py, tests/unit/authors/test_authors_tasks.py, tests/unit/workflows/test_workflows_tasks_author.py
=> workflows: in author wf send record to legacy as an update instead to legacy holdingpen

poetry.lock
=> bump inspire-json-merger

inspirehep/modules/editor/api.py, tests/integration/editor/test_editor_api.py, tests/integration/records/test_cli.py
Ref: https://github.com/inspirehep/inspirehep/issues/1474
=> validation: a new endpoint is added for workflow validation

inspirehep/modules/editor/api.py, tests/integration/editor/test_editor_api.py
Ref: https://github.com/inspirehep/inspirehep/issues/1474
=> validation: endpoint changed to POST.

.github/actions/load-image-from-cache/action.yml, .github/workflows/backend-tests-on-docker.yml, .travis.yml, docker-compose.test.yml, services.yml
You can check this github workflow on my private repo https://github.com/pazembrz/inspire-next/actions/runs/482773838
=> ops: Introduce github-workflows and update docker-compose.tests

poetry.lock, pyproject.toml
* ref inspirehep/inspirehep#1649.
=> poetry: update inspire-dojson to v63.1.0

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_article_workflow.py, tests/unit/workflows/test_workflows_actions.py
=> workflows: add Fermilab collection when proper report_number exists in record

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
=> workflow: Normalize journal_title in references

inspirehep/modules/workflows/config.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/utils/grobid_authors_parser.py, tests/unit/conftest.py, tests/unit/workflows/fixtures/grobid_no_authors_doc.xml, tests/unit/workflows/test_workflows_actions.py, tests/unit/workflows/test_workflows_utils.py
* Ignore authors without surname
* Replace authors in metadata if there are no authors originally and there are authors extracted from grobid
#1782
=> workflow: fix and improve grobid authors extraction

poetry.lock, pyproject.toml
* ref inspirehep/inspirehep#1754.
=> poetry: update hepcrawl to v13.0.29

poetry.lock
* ref inspirehep/inspirehep#1814.
=> poetry: update json-merger to v0.7.4

poetry.lock
* ref inspirehep/inspirehep#1832.
=> poetry: update inspire-dojson to v63.1.2

inspirehep/modules/records/mappings/v7/records/experiments.json, inspirehep/modules/workflows/errors.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, poetry.lock, tests/integration/workflows/fixtures/experiment_with_collaboration.json, tests/integration/workflows/fixtures/experiment_with_collaboration_and_subgroups.json, tests/integration/workflows/fixtures/experiment_without_collaboration.json, tests/integration/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_actions.py
Requires https://github.com/inspirehep/inspirehep/pull/1820 and reindexing
inspirehep/inspirehep#1689
=> workflows: add collaborations normalization step

inspirehep/modules/workflows/tasks/classifier.py, inspirehep/modules/workflows/tasks/submission.py, tests/integration/workflows/test_article_workflow.py, tests/unit/workflows/test_workflows_tasks_classifier.py, tests/unit/workflows/test_workflows_tasks_submission.py
=> workflows: put classifier keywords into core records

inspirehep/modules/workflows/tasks/actions.py, poetry.lock, pyproject.toml, tests/integration/workflows/test_arxiv_workflow.py, tests/unit/workflows/test_workflows_actions.py
ref: inspirehep/inspirehep#1816
=> extract authors from pdf: improve grobid name handling

poetry.lock
* related to inspirehep/inspirehep#1677 and inspirehep/inspirehep#1345
=> poetry: bump inspire-dojson & inspire-json-merger

inspirehep/config.py, inspirehep/modules/workflows/mappings/v7/holdingpen/hep.json, tests/integration/workflows/test_views.py
ref: inspirehep/inspirehep#1865
=> holdingpen: search improvements

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/fixtures/experiment_with_ambiguous_collaboration_1.json, tests/integration/workflows/fixtures/experiment_with_ambiguous_collaboration_2.json, tests/integration/workflows/test_workflows_tasks_actions.py
ref: inspirehep/inspirehep#1862
=> collaboration linking: don't link when match is ambiguous

inspirehep/config.py, inspirehep/modules/workflows/mappings/v7/holdingpen/hep.json, tests/integration/workflows/test_views.py
ref: inspirehep/inspirehep#1865
=> holdingpen: journal facet improvement

inspirehep/modules/workflows/mappings/v7/holdingpen/hep.json
ref: inspirehep/inspirehep#1865
=> journal facet: fix filtering

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, setup.cfg, tests/integration/workflows/fixtures/institution_1126070.json, tests/integration/workflows/fixtures/institution_902725.json, tests/integration/workflows/fixtures/institution_903335.json, tests/integration/workflows/fixtures/literature_1836272.json, tests/integration/workflows/fixtures/literature_1862822.json, tests/integration/workflows/fixtures/literature_1863053.json, tests/integration/workflows/test_workflows_tasks_actions.py
ref:inspirehep/inspirehep#1866
=> workflows: affiliation disambiguation

Dockerfile, Dockerfile.dev
* Ref inspirehep/inspirehep#1849.
=> poetry: update to v1.1.6

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/fixtures/institution_902725.json, tests/integration/workflows/fixtures/institution_903335.json, tests/integration/workflows/test_workflows_tasks_actions.py
ref: inspirehep/inspirehp#1866
=> affiliation linking: assign institution ref when not present

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/fixtures/literature_1459277.json, tests/integration/workflows/test_workflows_tasks_actions.py
* fixes logging
* fixes doubled affiliations causing record validation errors
* fixes issue with nested list in affiliation list
=> affiliation linking: fix minor bugs

.github/workflows/backend-tests-on-docker.yml, inspirehep/modules/workflows/errors.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/views.py, inspirehep/modules/workflows/workflows/__init__.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/core_selection.py, setup.py, tests/integration/helpers/utils.py, tests/integration/workflows/conftest.py, tests/integration/workflows/fixtures/hep_record_no_core.json, tests/integration/workflows/test_arxiv_merge.py, tests/integration/workflows/test_views.py, tests/integration/workflows/test_workflow_core_selection.py, tests/integration/workflows/test_workflows_tasks_actions.py
=> workflows: Add core_selection workflow

poetry.lock
* update poetry.lock to be compatible with poetry v 1.1.6
=> bump hepcrawl

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/fixtures/literature_1800446.json, tests/integration/workflows/test_workflows_tasks_actions.py
ref: #inspirehep/inspirehep#1942
=> affiliation linking: don't add not valid keys to affiliation

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/fixtures/literature_1800446.json, tests/integration/workflows/test_workflows_tasks_actions.py
ref: inspirehep/inspirehep#1930
=> affiliation linking: don't assign affiliations when ambiguous

inspirehep/modules/workflows/workflows/article.py
ref:inspirehep/inspirehep#1959
=> workflows: check if france in fulltext only for arxiv

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
Ref: https://github.com/inspirehep/inspirehep/issues/1969
=> workflows: fix `Collaborations key is not a list`

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
Ref: https://github.com/inspirehep/inspirehep/issues/1969
=> workflows: fix logging when no collaborations

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/fixtures/literature_1800446.json, tests/integration/workflows/test_workflows_tasks_actions.py
ref: #inspirehep/inspirehep#1930
=> workflows: improve affiliation linking for ambiguous matches

inspirehep/modules/workflows/utils/__init__.py
Ref: https://github.com/inspirehep/inspirehep/issues/1979
=> workflows: remove `_files` before sending record to hep

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
ref:inspirehep/inspirehep#1930
=> affiliation linking: fix bug in selection for ambiguous affs

inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_workflows_tasks_upload.py
ref: inspirehep/inspirehep#1987
=> workflows: move store recid in extra_data to send_to_legacy

inspirehep/modules/workflows/workflows/article.py
=> workflows: add institution linking

inspirehep/modules/workflows/tasks/refextract.py, tests/unit/workflows/test_workflows_tasks_refextract.py
ref: inspirehep/inspirehep#2016
=> workflows: fix extract_references_from_raw_ref when source missing

inspirehep/modules/workflows/tasks/upload.py, tests/integration/workflows/test_workflows_tasks_upload.py
=> inspire-next: record url not displayed in holdingpen

inspirehep/modules/editor/api.py, tests/integration/editor/test_editor_api.py, tests/integration/records/test_cli.py
=> editor: fix hardcoded validation

inspirehep/modules/records/api.py, setup.cfg, tests/integration/records/test_records_api.py, tests/integration_async/test_workflows.py
ref:inspirehep/inspirehep#2059
=> records: document url should be escaped

pyproject.toml, scripts/setup_inspire_next, setup.py
ref: inspirehep/inspirehep#2050
=> setup: improve local setup script

inspirehep/modules/workflows/workflows/core_selection.py
ref: inspirehep/inspirehep#1975
=> workflows: change queue for tickets in core selection workflow

inspirehep/modules/authors/templates/authors/tickets/curation_needed.html, inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_core.html, inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_jlab.html
=> Remove legacy links from RT templates

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/fixtures/jou_record_refereed.json, tests/integration/workflows/fixtures/jou_record_refereed_and_proceedings.json, tests/integration/workflows/test_workflows_tasks_actions.py
ref: inspirehep/inspirehep#2273
=> workflows: automatically assign categories to journals

inspirehep/modules/workflows/mappings/v7/holdingpen/hep.json
ref: inspirehep/inspirehep#2285
=> workflow: update mapping with new fields

poetry.lock, pyproject.toml
Ref: https://github.com/inspirehep/inspirehep/issues/2270
=> hepcrawl: update version 13.0.44

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
ref: inspirehep/inspirehep#2282
=> workflows: don't assign inspire categories from references

poetry.lock
* ref:inspirehep/inspirehep#2328
=> bump inspire-matcher

inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py
ref: inspirehep/inspirehep#1730
=> don't stop processing workflows from other source when matched

inspirehep/modules/workflows/tasks/actions.py, tests/unit/workflows/test_workflows_tasks_actions.py
ref: inspirehep/inspirehep#2378
=> workflows: don't autoreject when journal_covergae is full

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Ref: https://github.com/inspirehep/inspirehep/issues/2455
=> remove from object doc or fig if empty

inspirehep/modules/refextract/tasks.py, tests/integration/refextract/test_refextract_tasks.py
ref:#inspirehep/inspirehep#2399
=> refextract: don't query deleted jounrals for journal dict

inspirehep/modules/workflows/mappings/v7/holdingpen/hep.json, tests/integration/workflows/test_views.py
ref: https://github.com/cern-sis/issues-inspire/issues/30
=> search in private notes in holdingpen

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
Ref: https://github.com/cern-sis/issues-inspire/issues/28
=> don't overwrite inspire_categories if non-empty

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Ref: https://github.com/cern-sis/issues-inspire/issues/50
=> Remove None from institutions affiliations

inspirehep/modules/workflows/tasks/refextract.py
ref: cern-sis/issues-inspire#51
=> refextract: handle extract journal info exception

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Ref: https://github.com/cern-sis/issues-inspire/issues/61
=> inspireid value is empty

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
Ref: https://github.com/cern-sis/issues-inspire/issues/95
=> fix remove none valued rors

poetry.lock
closes https://github.com/cern-sis/issues-inspire/issues/83
=> deps: bump plotextractor to 0.3.15

poetry.lock
ref: https://github.com/cern-sis/issues-inspire/issues/65
=> poetry update heprcawl - mathml title bug fix

inspirehep/modules/workflows/tasks/matching.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_arxiv_workflow.py, tests/integration/workflows/test_matching.py
ref: cern-sis/issues-inspire#101
=> don't stop wfs with different source when hp match

inspirehep/modules/workflows/tasks/actions.py, tests/integration/workflows/test_workflows_tasks_actions.py
ref: cern-sis/issues-inspire#108
=> workflows: move rejected wfs to hidden collections based on report number

inspirehep/modules/workflows/tasks/classifier.py, tests/unit/workflows/test_workflows_tasks_classifier.py
ref: cern-sis/issues-inspire#123
=> classifier: update scoring for non-core

inspirehep/config.py, tests/integration/workflows/test_workflow_core_selection.py
=> quantum-ph: move to non-core

inspirehep/modules/workflows/workflows/article.py
ref: cern-sis/issues-inspire#208
=> restart workflows matched with stopped one

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
ref: cern-sis/issues-inspire#236
=> author xml: add name suffix to the author full_name

inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss, inspirehep/modules/workflows/templates/inspire_workflows/details.html
* ref: cern-sis/issues-inspire#280
=> ui: add api button

inspirehep/modules/workflows/tasks/submission.py, tests/integration/workflows/test_workflow_tasks_submission.py
* Ref: cern-sis/issues-inspire#344
=> workflows: fix reply_ticket

inspirehep/modules/workflows/tasks/refextract.py, tests/integration/workflows/test_workflows_tasks_actions.py
ref: cern-sis/issues-inspire#351
=> fix refextract

inspirehep/modules/workflows/tasks/manual_merging.py
Fixes https://github.com/inspirehep/inspire-next/commit/f308e5c374876d6306f1f46bec7969be0e07946e
=> workflows: fix merge roots

inspirehep/modules/workflows/utils/__init__.py
ref: https://github.com/cern-sis/issues-inspire/issues/412
=> documents: check for pdf in key

inspirehep/modules/workflows/tasks/submission.py, inspirehep/modules/workflows/workflows/article.py, inspirehep/modules/workflows/workflows/author.py, tests/integration/workflows/test_workflow_tasks_submission.py
ref: https://github.com/cern-sis/issues-inspire/issues/415
=> snow: adjust workflows to new snow endpoints

poetry.lock
* ref https://github.com/cern-sis/issues-inspire/issues/441
=> setup: bump inspire-json-merger

inspirehep/config.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_article_workflow.py, tests/unit/workflows/test_workflows_actions.py
ref: https://github.com/cern-sis/issues-inspire/issues/463
=> workflows: add uk curation step

Dockerfile, Dockerfile.dev, poetry.lock, pyproject.toml, tests/unit/utils/test_idutils.py
* WARNING: it uses inspire-idutils to support python 2.7.
* ref: https://github.com/cern-sis/issues-inspire/issues/465
=> setup: bump inspire-schemas

poetry.lock, pyproject.toml
ref: https://github.com/cern-sis/issues-inspire/issues/485
ref: https://github.com/inspirehep/inspire-json-merger/pull/117
=> inspire-json-merger: bump to 11.0.35

inspirehep/config.py, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_article_workflow.py, tests/unit/workflows/test_workflows_actions.py
ref: https://github.com/cern-sis/issues-inspire/issues/559
=> workflows: add german curation step

poetry.lock
ref: https://github.com/cern-sis/issues-inspire/issues/777
=> bump: inspire-schemas

README.rst, inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py, inspirehep/utils/references.py, tests/unit/workflows/test_workflows_tasks_actions.py, tests/unit/workflows/test_workflows_tasks_refextract.py
* ref: cern-sis/issues-inspire/issues/814
=> refextract: use service for raw_references

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/tasks/refextract.py
* ref: cern-sis/issues-inspire/issues/849
=> refextract: timeout not being triggered

poetry.lock, pyproject.toml
* ref: cern-sis/issues-inspire/issues/858
=> bump plotextractor: use new version

inspirehep/modules/workflows/tasks/arxiv.py, tests/unit/workflows/test_workflows_tasks_arxiv.py
* ref: cern-sis/issues-inspire/issues/850
=> plotextract: skip on cache error

inspirehep/modules/workflows/tasks/actions.py, inspirehep/modules/workflows/workflows/article.py, tests/integration/workflows/test_article_workflow.py
* ref: cern-sis/issues-inspire/issues/851
=> workflows: add custom queue for CDS

inspirehep/modules/workflows/tasks/arxiv.py, poetry.lock, pyproject.toml, requirements.poetry.txt, tests/unit/workflows/test_workflows_tasks_arxiv.py
cern-sis/issues-inspire/issues/627
=> plotextractor: bump version

inspirehep/modules/records/serializers/fields_export.py, poetry.lock, pyproject.toml
* ref https://github.com/cern-sis/issues-inspire/issues/902
=> isbn: catch correctly the exception

inspirehep/modules/workflows/workflows/article.py
* ref https://github.com/cern-sis/issues-inspire/issues/911
=> cds: fix curation tickets

inspirehep/modules/workflows/tasks/arxiv.py
* ref:  cern-sis/issues-inspire#460
=> workflows: fix author xml ids
